In [1]:
!pip install -q pandas requests beautifulsoup4 lxml openpyxl ddgs

In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from ddgs import DDGS
import re
import time
from urllib.parse import urljoin, urlparse

In [3]:
columns = [
    "State",
    "Region",
    "Country",
    "Name",
    "Website",
    "Email",
    "Contact Number",
    "Coverage State",
    "Coverage Type",
    "Services Rendered",
    "Target Customers",
    "Source",
    "Source URL"
]

health_df = pd.DataFrame(columns=columns)

health_df

Empty DataFrame
Columns: [State, Region, Country, Name, Website, Email, Contact Number, Coverage State, Coverage Type, Services Rendered, Target Customers, Source, Source URL]
Index: []

In [4]:
companies = [
    ("England", "Bupa", "https://www.bupa.co.uk/"),
    ("England", "AXA Health", "https://www.axahealth.co.uk/"),
    ("England", "Aviva", "https://www.aviva.co.uk/"),
    ("England", "WPA", "https://www.wpa.org.uk/"),
    ("England", "VitalityHealth", "https://www.vitality.co.uk/"),
    ("England", "The Exeter", "https://www.the-exeter.com/"),
    ("England", "Benenden Health", "https://www.benenden.co.uk/"),
    ("England", "Freedom Health Insurance", "https://www.freedomhealthinsurance.co.uk/"),
    ("England", "National Friendly", "https://www.nationalfriendly.co.uk/"),
    ("England", "Saga Health Insurance", "https://www.saga.co.uk/health-insurance"),
    ("England", "Cigna Healthcare", "https://www.cigna.co.uk/"),
    ("England", "Simplyhealth", "https://www.simplyhealth.co.uk/"),
    ("England", "General & Medical", "https://www.gminsure.com/"),
    ("England", "CS Healthcare", "https://www.cshealthcare.co.uk/")
]

In [5]:
health_df = pd.DataFrame([
    {
        "State": state,
        "Region": "N/A",
        "Country": "United Kingdom",
        "Name": name,
        "Website": website,
        "Email": "N/A",
        "Contact Number": "N/A",
        "Coverage State": "N/A",
        "Coverage Type": "N/A",
        "Services Rendered": "N/A",
        "Target Customers": "N/A",
        "Source": "Official Company Website",
        "Source URL": website
    }
    for state, name, website in companies
])

health_df

,State,Region,Country,Name,Website,Email,Contact Number,Coverage State,Coverage Type,Services Rendered,Target Customers,Source,Source URL
0,England,N/A,United Kingdom,Bupa,https://www.bupa.co.uk/,N/A,N/A,N/A,N/A,N/A,N/A,Official Company Website,https://www.bupa.co.uk/
1,England,N/A,United Kingdom,AXA Health,https://www.axahealth.co.uk/,N/A,N/A,N/A,N/A,N/A,N/A,Official Company Website,https://www.axahealth.co.uk/
2,England,N/A,United Kingdom,Aviva,https://www.aviva.co.uk/,N/A,N/A,N/A,N/A,N/A,N/A,Official Company Website,https://www.aviva.co.uk/
3,England,N/A,United Kingdom,WPA,https://www.wpa.org.uk/,N/A,N/A,N/A,N/A,N/A,N/A,Official Company Website,https://www.wpa.org.uk/
4,England,N/A,United Kingdom,VitalityHealth,https://www.vitality.co.uk/,N/A,N/A,N/A,N/A,N/A,N/A,Official Company Website,https://www.vitality.co.uk/
5,England,N/A,United Kingdom,The Exeter,https://www.the-exeter.com/,N/A,N/A,N/A,N/A,N/A,N/A,Official Company Website,https://www.the-exeter.com/
6,England,N/A,United Kingdom,Benenden Health,https://www.benenden.co.uk/,N/A,N/A,N/A,N/A,N/A,N/A,Official Company Website,https://www.benenden.co.uk/
7,England,N/A,United Kingdom,Freedom Health Insurance,https://www.freedomhealthinsurance.co.uk/,N/A,N/A,N/A,N/A,N/A,N/A,Official Company Website,https://www.freedomhealthinsurance.co.uk/
8,England,N/A,United Kingdom,National Friendly,https://www.nationalfriendly.co.uk/,N/A,N/A,N/A,N/A,N/A,N/A,Official Company Website,https://www.nationalfriendly.co.uk/
9,England,N/A,United Kingdom,Saga Health Insurance,https://www.saga.co.uk/health-insurance,N/A,N/A,N/A,N/A,N/A,N/A,Official Company Website,https://www.saga.co.uk/health-insurance
10,England,N/A,United Kingdom,Cigna Healthcare,https://www.cigna.co.uk/,N/A,N/A,N/A,N/A,N/A,N/A,Official Company Website,https://www.cigna.co.uk/
11,England,N/A,United Kingdom,Simplyhealth,https://www.simplyhealth.co.uk/,N/A,N/A,N/A,N/A,N/A,N/A,Official Company Website,https://www.simplyhealth.co.uk/
12,England,N/A,United Kingdom,General & Medical,https://www.gminsure.com/,N/A,N/A,N/A,N/A,N/A,N/A,Official Company Website,https://www.gminsure.com/
13,England,N/A,United Kingdom,CS Healthcare,https://www.cshealthcare.co.uk/,N/A,N/A,N/A,N/A,N/A,N/A,Official Company Website,https://www.cshealthcare.co.uk/

In [6]:
def scrape_website(url):
    try:
        response = requests.get(
            url,
            headers={
                "User-Agent": "Mozilla/5.0"
            },
            timeout=15
        )

        if response.status_code != 200:
            return None

        return BeautifulSoup(response.text, "lxml")

    except:
        return None

In [7]:
def find_phones(soup):
    if soup is None:
        return []

    text = soup.get_text(" ", strip=True)

    phones = re.findall(
        r'(?:\+44\s?\(?0?\)?\s?|0)(?:\d[\s\-]?){9,12}',
        text
    )

    cleaned = []

    for phone in phones:
        phone = re.sub(r'\s+', ' ', phone).strip()

        if phone not in cleaned:
            cleaned.append(phone)

    return cleaned

In [9]:
def find_emails(soup):
    if soup is None:
        return []

    text = soup.get_text(" ", strip=True)

    emails = re.findall(
        r'[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}',
        text
    )

    return list(dict.fromkeys(emails))

In [10]:
for i, row in health_df.iterrows():

    print("Processing:", row["Name"])

    soup = scrape_website(row["Website"])

    emails = find_emails(soup)
    phones = find_phones(soup)

    if emails:
        health_df.at[i, "Email"] = emails[0]

    if phones:
        health_df.at[i, "Contact Number"] = phones[0]

    time.sleep(1)

Processing: Bupa
Processing: AXA Health
Processing: Aviva
Processing: WPA
Processing: VitalityHealth
Processing: The Exeter
Processing: Benenden Health
Processing: Freedom Health Insurance
Processing: National Friendly
Processing: Saga Health Insurance
Processing: Cigna Healthcare
Processing: Simplyhealth
Processing: General & Medical
Processing: CS Healthcare

In [11]:
health_df[
    [
        "Name",
        "Website",
        "Email",
        "Contact Number"
    ]
]

,Name,Website,Email,Contact Number
0,Bupa,https://www.bupa.co.uk/,N/A,N/A
1,AXA Health,https://www.axahealth.co.uk/,N/A,0800 169 7593
2,Aviva,https://www.aviva.co.uk/,N/A,N/A
3,WPA,https://www.wpa.org.uk/,N/A,N/A
4,VitalityHealth,https://www.vitality.co.uk/,N/A,N/A
5,The Exeter,https://www.the-exeter.com/,enquiries@the-exeter.com,0300 123 3201
6,Benenden Health,https://www.benenden.co.uk/,N/A,N/A
7,Freedom Health Insurance,https://www.freedomhealthinsurance.co.uk/,N/A,01202 756 350
8,National Friendly,https://www.nationalfriendly.co.uk/,N/A,N/A
9,Saga Health Insurance,https://www.saga.co.uk/health-insurance,N/A,0808 239 3479
10,Cigna Healthcare,https://www.cigna.co.uk/,N/A,N/A
11,Simplyhealth,https://www.simplyhealth.co.uk/,N/A,N/A
12,General & Medical,https://www.gminsure.com/,info@gminsure.com,N/A
13,CS Healthcare,https://www.cshealthcare.co.uk/,N/A,N/A

In [12]:
england_df = health_df.copy()
print("England records:", len(england_df))

England records: 14

In [13]:
from ddgs import DDGS
import time

def search_company(company, query):
    try:
        results = list(
            DDGS().text(
                f'"{company}" {query} official UK',
                max_results=5
            )
        )
        return results
    except Exception as e:
        print(f"Search failed for {company}: {e}")
        return []

contact_results = {}

for company in england_df["Name"]:
    print("Searching:", company)

    results = search_company(company, "contact phone email")
    contact_results[company] = results

    time.sleep(1)

print("Done.")

Searching: Bupa
Searching: AXA Health
Searching: Aviva
Searching: WPA
Searching: VitalityHealth
Searching: The Exeter
Searching: Benenden Health
Searching: Freedom Health Insurance
Searching: National Friendly
Searching: Saga Health Insurance
Searching: Cigna Healthcare
Searching: Simplyhealth
Searching: General & Medical
Searching: CS Healthcare
Done.

In [14]:
for company, results in contact_results.items():
    print("\n==============================")
    print(company)
    
    for r in results[:3]:
        print("TITLE:", r.get("title"))
        print("URL:", r.get("href"))
        print("DESCRIPTION:", r.get("body"))

==============================
Bupa
TITLE: Contact us | Ways to get in touch with Bupa UK
URL: https://www.bupa.co.uk/contact-us.php
DESCRIPTION: Discover contact information for Bupa UK for both existing and new customers. For phone numbers and app information, visit our contact web page.
TITLE: Contact Us | Small Business Healthcare | Bupa UK
URL: https://www.bupa.co.uk/business/small-business-healthcare/small-business-contact-us
DESCRIPTION: Whether you're looking for healthcare for your small business or have existing cover with Bupa, you can talk to us by phone, email or requesting a callback.
TITLE: Bupa UK - Company Profile & Staff Directory | ContactOut
URL: https://contactout.com/company/Bupa-UK-11275
DESCRIPTION: Bupa UK is a Wellness and Fitness Services company located in London, England, United Kingdom with 1,350 employees. Access Bupa UK's email format and staff directory for direct contact details.

==============================
AXA Health
TITLE: Contact us | AXA UK | AXA UK home page
URL: https://www.axa.co.uk/contact-us/
DESCRIPTION: Log in to manage your health insurance policy Make a claim on your AXA Health Insurance policy.Renew your policy online. Avoid wait times on the phone. Save on admin fees for certain policy changes.
TITLE: AXA UK Contact 2026: How to Reach AXA, Claims, Online...
URL: https://selectra.co.uk/insurance/providers/axa/contact
DESCRIPTION: How to contact AXA UK in 2026: AXA routes by product with no single switchboard, so the right number for car, home, travel or health cover is on your policy documents. MyAXA, official contact pages, head office and complaints.
TITLE: How to Call AXA Health from Abroad (No Roaming)
URL: https://callshake.com/guides/call-axa-healthcare-from-abroad/
DESCRIPTION: AXA Health phone numbers (UK).Disclaimer: AXA Health phone numbers and availability vary by membership type and plan. If you can’t reach the right department using a general number, use the official Contact Us page to route to the correct claims/support option for your plan.

==============================
Aviva
TITLE: Insurance, Savings, Investments, Retirement and Health - Aviva
URL: https://www.aviva.co.uk/
DESCRIPTION: Let the UK’s biggest insurance firm quote you, now.We're proposing to transfer insurance business from U K Insurance Limited (UKIL) to Aviva Insurance Limited (AIL) on 31 December 2026. Find out more. Defaqto 5 Star car, home and travel insurance.
TITLE: Aviva Contact 2026: How to Reach Aviva, Online Help & Complaints
URL: https://selectra.co.uk/insurance/providers/aviva/contact
DESCRIPTION: The official Aviva contact pages: aviva.co.uk/help-and-support/contact-us lists the current phone number and opening hours for each product
TITLE: Aviva Adviser: Contact us - Aviva
URL: https://connect.avivab2b.co.uk/adviser/contact-us/
DESCRIPTION: Here you can access the contact details of our Aviva adviser support teams. Including contact details for new and existing business.

==============================
WPA
TITLE: Arnie Shelley - Healthcare Practice Partner | WPA
URL: https://www.wpa.org.uk/arnieshelley?link=arnieshelley
DESCRIPTION: Email icon. arnie.shelley@wpa-hcp.org.uk.To find out more and discuss the range of health insurance options available to you or your business, please contact me. 07863108481. arnie.shelley@wpa-hcp.org.uk. Arrange a meeting.
TITLE: Wpa, Taunton
URL: https://taunton.cylex-uk.co.uk/company/wpa-19159773.html
DESCRIPTION: Check Wpa in Taunton, No 475557 At Rivergate House, Blackbrook Park on Cylex and find 01803 855..., contact info, opening hours. Events. Official Data. Menu. Special offer.
TITLE: Rubilen Amit vs Savannah Easton | TV Table Round 2 | Oneida WPA...
URL: https://www.youtube.com/watch?v=2TxkNEPtRiw
DESCRIPTION: The second annual Oneida WPA Women's 8 Ball World Championship is here! Top WPBA players are invited to compete for a world title and over $160k in prize money! Quick facts • Venue: Oneida Casino, Green Bay WI • Tables: Olhausen 9‑foot • Format:...

==============================
VitalityHealth
TITLE: Vitality Health and Life Insurance - Wikipedia
URL: https://en.wikipedia.org/wiki/Vitality_Health_and_Life_Insurance
DESCRIPTION: Vitality Health Limited is a United Kingdom-based company offering private health insurance and life insurance to the UK market. It is the UK's third-largest health insurer, behind Bupa and Axa, with 1.9 million members as of February 2025.
TITLE: VitalityHealth Corporate head office | headquarters | Phone
URL: https://corporate-office-headquarters.co.uk/vitalityhealth/
DESCRIPTION: VitalityHealth Corporate Office Headquarters. Head Office Address : 3 More London Riverside, London SE1 2AQ, England, UK. Phone Number : 03456023437. Email : customerdirectsupport@vitality.co.uk.
TITLE: VitalityHealth | Morehealth Limited
URL: https://www.more-health.co.uk/provider/vitalityhealth/
DESCRIPTION: Contact Us. VitalityHealth. VitalityHealth is a UK based health insurer with over 1 million customers. It is owned by its parent company DiscoveryHoldings; a global insurance organisation covering over 5 million people worldwide.

==============================
The Exeter
TITLE: Member | Contact us | The Exeter
URL: https://the-exeter.com/contact-us/member/
DESCRIPTION: Have a question or need to make changes? For existing health insurance, income protection and life insurance enquiries: Email us member@the-exeter.com Call us 0300 123 3201 Open Monday to Friday, 8am - 6pm
TITLE: Corporate governance | About us | The Exeter
URL: https://www.the-exeter.com/about-us/corporate-governance/
DESCRIPTION: Write to us: The Exeter, Lakeside House Emperor Way, Exeter, EX1 3FD Call us: 0300 123 3201 Email us:
TITLE: The exeter - Email Address & Phone Number - Lusha
URL: https://www.lusha.com/business/cee5949c49b8f1af/
DESCRIPTION: Reach decision-makers at The Exeter. Find their phone numbers & email addresses. It's free. - Lusha

==============================
Benenden Health
TITLE: Benenden Health Overview, Address & Contact
URL: https://prospeo.io/c/benenden-health
DESCRIPTION: Benenden Health uses 2 email formats. The most common is {first name}.{last name} (e.g., john.doe@benenden.co.uk), used 85% of the time.
TITLE: Contact us | Benenden Health
URL: https://www.benenden.co.uk/contact-us/?enq=member+area
DESCRIPTION: Find contact details, including emails and phone numbers, for various services and areas of Benenden Health.
TITLE: Benenden Health - Company Profile & Staff Directory | ContactOut
URL: https://contactout.com/company/benenden-health-6278575
DESCRIPTION: Benenden Health is a Hospitals and Health Care company located in Holgate Business Park, Holgate Park Drive, York, Yorkshire YO26 4GG, GB with 346 employees. Access Benenden Health's email format and staff directory for direct contact details.

==============================
Freedom Health Insurance
TITLE: Contact Us - Freedom Health Insurance
URL: https://www.freedomhealthinsurance.co.uk/contact-us
DESCRIPTION: Freedom Health Insurance and Freedom Health are trading names of Freedom Healthnet Ltd © 2023. Freedom Healthnet Limited is authorised and regulated by the Financial Conduct Authority with the registration number 312282. Company registered address: Freedom Healthnet Ltd, County Gates House, 300 Poole Road, Poole, BH12 1AZ. Company registration number: 04815524. The guidance contained within the website is subject to the UK regulatory regime and is therefore primarily targeted at customers in the UK.
TITLE: COVID-19 Information | Freedom Health Insurance
URL: https://www.freedomhealthinsurance.co.uk/support/covid-19
DESCRIPTION: Phone: 0800 999 2013* Email: [email protected] If you think you, or a family member, may have COVID-19, please follow the Government’s advice at NHS.UK · The COVID-19 outbreak is being managed centrally by the UK Government and, at present, all diagnostics and treatment are being carried out by the NHS/Public Health England. Testing and screening are therefore not covered under your health insurance policy unless these are pre-requirements of any approved claims.
TITLE: Freedom Health Insurance Email Formats & Email Address Examples | LeadIQ
URL: https://leadiq.com/c/freedom-health-insurance/5a1d9f322300005c008facf1/email-format
DESCRIPTION: Freedom Health Insurance's email format typically follows the pattern of F.Last@freedomhealthinsurance.co.uk; this email format is used 60% of the time. Other contacts within LeadIQ's database had email formats such as First@freedomhealthin...

==============================
National Friendly
TITLE: Compare National Friendly VS Simply Health + Free Quote
URL: https://goingprivateuk.co.uk/national-friendly-vs-simply-health/
DESCRIPTION: Get Your Free Health Insurance Quote National Friendly vs Simplyhealth: Which Is Better in 2025 for Everyday Health Costs? Trying to cut the cost of “everyday” health — dental, optical, physio — while still getting fast access to scans and surgery if...
TITLE: National friendly match with Portugal and Egypt - YouTube
URL: https://www.youtube.com/watch?v=B_NzICqDOf4
DESCRIPTION: The best of mehran rahnama 2020_21 Player of iran’s national handball team Sephan club.
TITLE: Ryan Kenny Email & Phone Number | Hargreaves Lansdown...
URL: https://rocketreach.co/ryan-kenny-email_77870327
DESCRIPTION: Ryan Kenny, based in Bristol, GB, is currently a Marketing Lead at Hargreaves Lansdown. Ryan Kenny brings experience from previous roles at Hargreaves Lansdown, National Friendly and DAS UK Group.

==============================
Saga Health Insurance
TITLE: Contact us | Health insurance
URL: https://www.saga.co.uk/contact-us/insurance/health-insurance
DESCRIPTION: Find all the contact information you need for Saga Health Insurance. Contact us for quotes, claims and customer support.Subscribe to the award-winning Saga Magazine. A celebration of life, experience, and the joy of living, delivered direct to your door.
TITLE: Over 50s Health Insurance | Private Medical Insurance
URL: https://www.saga.co.uk/health-insurance
DESCRIPTION: Saga offers comprehensive health insurance for over 50s, which includes the following: Choice of hospitals.Saga GP service. Speak to a doctor with unlimited access to telephone or video GP appointments 24/7, 365 days a year. Choice of health plans.
TITLE: Saga health insurance review
URL: https://www.azmoney.co.uk/insurance/health-insurance/companies/saga
DESCRIPTION: Contact phone*.Saga Health Insurance offers four different health plans, with each one covering hospital in-patient, day-patient treatment, and care. The four plans offered are: Saga HealthPlan Support.

==============================
Cigna Healthcare
TITLE: Privacy Policy | Data Protection & Compliance | Cigna Healthcare
URL: https://www.cignahealthbenefits.com/en/privacy
DESCRIPTION: Understand Cigna Global’s privacy policy. Learn how we collect, process, and protect personal data, including legal basis, rights, and cross-border transfer details.
TITLE: Privacy Statement & Information Use | Cigna Global
URL: https://www.cignaglobal.com/privacy-statement
DESCRIPTION: Business contacts if you are the Cigna Healthcare contact at your company.General information such as your first and last name, title, address, email address, telephone numbers, date of birth, gender, and relationship to the policyholder (where you are not the policyholder).
TITLE: Cigna Healthcare Email Format
URL: https://scalelist.com/cigna-healthcare-email-format/
DESCRIPTION: You can reach Cigna Healthcare’s investor relations department through the contact section on their official website or directly via the investor relations email listed in their latest SEC filings. Find verified emails and phone numbers for professionals like those at.

==============================
Simplyhealth
TITLE: Contact Us | Simplyhealth Health & Dental Plans to cover you
URL: https://www.simplyhealth.co.uk/contact-us
DESCRIPTION: If you don’t yet have a plan with Simplyhealth you can join online. If you would like to find out more about how our plans can help you manage your everyday health, please contact us by web chat, email or complete the form by clicking the button below.
TITLE: Contact Us Online | Simplyhealth
URL: https://www.simplyhealth.co.uk/contact-us/personal/online-form
DESCRIPTION: Please note: your email address and phone number will be added to your account so we can use them to communicate with you about your plans in the future.
TITLE: Contact Us
URL: https://www.simplyhealth.co.uk/content/dam/simplyhealth/forms/existing-customers-contact-form/existing-customers-contact-form-prod.html
DESCRIPTION: We're here to help, just fill in our form with a full description of your query and we'll get back to you by email in working hours. We can help you stay covered. We'd love to have a chat with you to see what we can offer. We're waiting for your call on 0370 908 3304. We're here Monday to Friday 9am - 6pm but not bank holidays. Or if you'd like to cancel your plan we'll take care of it. Fill in our contact us from here and tell us why you want to cancel your plan today.

==============================
General & Medical
TITLE: Contact General & Medical Healthcare | Ways To Get In Touch With Us
URL: https://www.generalandmedical.com/contact-us/
DESCRIPTION: Call us, Freephone 0800 970 9442 for more information or to purchase your Health Insurance policy - Our friendly Customer Service team are ready to assist you.
TITLE: Contact Us | General & Medical Solutions
URL: https://www.generalandmedicalsolutions.com/contact-general-medical-solutions
DESCRIPTION: ProAmica is now General & Medical Solutions! Call Us (UK): 0800 084 2589 Rest of World: +44 (0)1733 362880 08:45 to 17:15 UK Time (Mon-Fri)
TITLE: Help and Support at General and Medical
URL: https://www.generalandmedical.com/help/
DESCRIPTION: Help and Support. Frequently Asked Questions, Secure Login, Jargon Buster, Medical Glossary.

==============================
CS Healthcare
TITLE: Contact Information & Details | CS Healthcare
URL: https://www.cshealthcare.co.uk/contact-us/
DESCRIPTION: September 28, 2017 - Get in Contact with the right team for your enquiry. Phone numbers and email addresses of all our teams at CS Healthcare available online.
TITLE: CS Healthcare - Crunchbase Company Profile & Funding
URL: https://www.crunchbase.com/organization/cs-healthcare
DESCRIPTION: www.cshealthcare.co.uk · Health Care · Health Insurance · Hospital · Medical · Legal Name · Civil Service Healthcare Society Limited · Operating Status · Active · Company Type · For Profit · Phone Number · 44-800-917-4325 · Contact Email · info@cshealthcare.co.uk ...
TITLE: CS Healthcare Company Overview, Contact Details & Competitors | LeadIQ
URL: https://leadiq.com/c/cs-healthcare/5a1d99252300005e0087cb31
DESCRIPTION: You can contact CS Healthcare's main corporate office by phone at · +44-20-8410-****. For more prospecting data, LeadIQ has access to up-to-date and accurate contact information within our platform. Find, capture, and sync contact data to your CRM and sales tools in one click. CS Healthcare is a publicly traded company; the company's stock symbol is NCSAA. CS Healthcare's official website is cshealthcare.co.uk and has social profiles on LinkedIn.

In [15]:
contact_updates = {
    "Bupa": {
        "Contact Number": "0345 609 0111",
        "Source URL": "https://www.bupa.co.uk/contact-us.php"
    },

    "AXA Health": {
        "Contact Number": "0800 027 1384",
        "Source URL": "https://www.axahealth.co.uk/health-insurance/contact-us/"
    },

    "Aviva": {
        "Contact Number": "N/A",
        "Source URL": "https://www.aviva.co.uk/help-and-support/contact-us/"
    },

    "WPA": {
        "Contact Number": "N/A",
        "Source URL": "https://www.wpa.org.uk/"
    },

    "VitalityHealth": {
        "Contact Number": "N/A",
        "Source URL": "https://www.vitality.co.uk/"
    },

    "The Exeter": {
        "Email": "member@the-exeter.com",
        "Contact Number": "0300 123 3201",
        "Source URL": "https://the-exeter.com/contact-us/member/"
    },

    "Benenden Health": {
        "Contact Number": "N/A",
        "Source URL": "https://www.benenden.co.uk/contact-us/"
    },

    "Freedom Health Insurance": {
        "Contact Number": "0800 999 2013",
        "Source URL": "https://www.freedomhealthinsurance.co.uk/contact-us"
    },

    "National Friendly": {
        "Contact Number": "N/A",
        "Source URL": "https://www.nationalfriendly.co.uk/"
    },

    "Saga Health Insurance": {
        "Contact Number": "N/A",
        "Source URL": "https://www.saga.co.uk/contact-us/insurance/health-insurance"
    },

    "Cigna Healthcare": {
        "Contact Number": "N/A",
        "Source URL": "https://www.cigna.co.uk/"
    },

    "Simplyhealth": {
        "Contact Number": "0370 908 3304",
        "Source URL": "https://www.simplyhealth.co.uk/contact-us"
    },

    "General & Medical": {
        "Contact Number": "0800 970 9442",
        "Source URL": "https://www.generalandmedical.com/contact-us/"
    },

    "CS Healthcare": {
        "Contact Number": "N/A",
        "Source URL": "https://www.cshealthcare.co.uk/contact-us/"
    }
}

In [16]:
for company, info in contact_updates.items():
    idx = england_df.index[england_df["Name"] == company]

    for column, value in info.items():
        england_df.loc[idx, column] = value

england_df[["Name", "Website", "Email", "Contact Number", "Source URL"]]

,Name,Website,Email,Contact Number,Source URL
0,Bupa,https://www.bupa.co.uk/,N/A,0345 609 0111,https://www.bupa.co.uk/contact-us.php
1,AXA Health,https://www.axahealth.co.uk/,N/A,0800 027 1384,https://www.axahealth.co.uk/health-insurance/c...
2,Aviva,https://www.aviva.co.uk/,N/A,N/A,https://www.aviva.co.uk/help-and-support/conta...
3,WPA,https://www.wpa.org.uk/,N/A,N/A,https://www.wpa.org.uk/
4,VitalityHealth,https://www.vitality.co.uk/,N/A,N/A,https://www.vitality.co.uk/
5,The Exeter,https://www.the-exeter.com/,member@the-exeter.com,0300 123 3201,https://the-exeter.com/contact-us/member/
6,Benenden Health,https://www.benenden.co.uk/,N/A,N/A,https://www.benenden.co.uk/contact-us/
7,Freedom Health Insurance,https://www.freedomhealthinsurance.co.uk/,N/A,0800 999 2013,https://www.freedomhealthinsurance.co.uk/conta...
8,National Friendly,https://www.nationalfriendly.co.uk/,N/A,N/A,https://www.nationalfriendly.co.uk/
9,Saga Health Insurance,https://www.saga.co.uk/health-insurance,N/A,N/A,https://www.saga.co.uk/contact-us/insurance/he...
10,Cigna Healthcare,https://www.cigna.co.uk/,N/A,N/A,https://www.cigna.co.uk/
11,Simplyhealth,https://www.simplyhealth.co.uk/,N/A,0370 908 3304,https://www.simplyhealth.co.uk/contact-us
12,General & Medical,https://www.gminsure.com/,info@gminsure.com,0800 970 9442,https://www.generalandmedical.com/contact-us/
13,CS Healthcare,https://www.cshealthcare.co.uk/,N/A,N/A,https://www.cshealthcare.co.uk/contact-us/

In [17]:
print(england_df[[
    "Name",
    "Coverage State",
    "Coverage Type",
    "Services Rendered",
    "Target Customers"
]].to_string(index=False))

                    Name Coverage State Coverage Type Services Rendered Target Customers
                    Bupa            N/A           N/A               N/A              N/A
              AXA Health            N/A           N/A               N/A              N/A
                   Aviva            N/A           N/A               N/A              N/A
                     WPA            N/A           N/A               N/A              N/A
          VitalityHealth            N/A           N/A               N/A              N/A
              The Exeter            N/A           N/A               N/A              N/A
         Benenden Health            N/A           N/A               N/A              N/A
Freedom Health Insurance            N/A           N/A               N/A              N/A
       National Friendly            N/A           N/A               N/A              N/A
   Saga Health Insurance            N/A           N/A               N/A              N/A
        Cigna Healthcare            N/A           N/A               N/A              N/A
            Simplyhealth            N/A           N/A               N/A              N/A
       General & Medical            N/A           N/A               N/A              N/A
           CS Healthcare            N/A           N/A               N/A              N/A

In [18]:
coverage_updates = {

    "Bupa": {
        "Coverage State": "United Kingdom",
        "Coverage Type": "Private Medical Insurance",
        "Services Rendered": "Private healthcare, health insurance, specialist treatment, hospital care, health assessments and wellbeing services",
        "Target Customers": "Individuals, families, employers and businesses"
    },

    "AXA Health": {
        "Coverage State": "United Kingdom",
        "Coverage Type": "Private Medical Insurance",
        "Services Rendered": "Private healthcare, hospital treatment, specialist consultations, diagnostic tests, mental health support and health assessments",
        "Target Customers": "Individuals, couples, families, self-employed people, small businesses and large corporates"
    },

    "Aviva": {
        "Coverage State": "United Kingdom",
        "Coverage Type": "Private Medical Insurance",
        "Services Rendered": "Private treatment, hospital care, specialist consultations, diagnostic tests, cancer treatment, mental health treatment and GP video consultations",
        "Target Customers": "Individuals, families, employees and businesses"
    },

    "WPA": {
        "Coverage State": "United Kingdom",
        "Coverage Type": "Private Medical Insurance / Health Cash Plans",
        "Services Rendered": "Private hospital treatment, consultations, diagnostic tests, health cash plans, dental plans and employee health services",
        "Target Customers": "Individuals, families, self-employed people and businesses"
    },

    "VitalityHealth": {
        "Coverage State": "United Kingdom",
        "Coverage Type": "Private Medical Insurance",
        "Services Rendered": "Private hospital treatment, GP services, diagnostic tests, specialist care, cancer care, mental health support, physiotherapy and wellbeing rewards",
        "Target Customers": "Individuals, families, self-employed people and businesses"
    },

    "The Exeter": {
        "Coverage State": "United Kingdom",
        "Coverage Type": "Private Medical Insurance",
        "Services Rendered": "Private medical treatment, specialist consultations, hospital care, diagnostics and healthcare support",
        "Target Customers": "Individuals, families and businesses"
    },

    "Benenden Health": {
        "Coverage State": "United Kingdom",
        "Coverage Type": "Healthcare Membership",
        "Services Rendered": "24/7 GP helpline, mental health support, diagnostic consultations and tests, surgical treatment, hospital access and health and wellbeing services",
        "Target Customers": "UK residents, individuals, families and members"
    },

    "Freedom Health Insurance": {
        "Coverage State": "United Kingdom",
        "Coverage Type": "Private Medical Insurance",
        "Services Rendered": "Private medical treatment, hospital care, specialist consultations, diagnostic services and healthcare support",
        "Target Customers": "Individuals, families, expatriates and businesses"
    },

    "National Friendly": {
        "Coverage State": "United Kingdom",
        "Coverage Type": "Private Medical Insurance",
        "Services Rendered": "Private healthcare, medical consultations, diagnostic services and treatment",
        "Target Customers": "Individuals and families"
    },

    "Saga Health Insurance": {
        "Coverage State": "United Kingdom",
        "Coverage Type": "Private Medical Insurance",
        "Services Rendered": "Private hospital treatment, inpatient and day-patient treatment, outpatient consultations, tests, scans, physiotherapy, cancer support and 24/7 GP services",
        "Target Customers": "People aged 50 and over"
    },

    "Cigna Healthcare": {
        "Coverage State": "United Kingdom and international",
        "Coverage Type": "International Private Medical Insurance",
        "Services Rendered": "International medical insurance, inpatient and day-patient care, hospital treatment, specialist care, outpatient care, dental options, telehealth and global healthcare support",
        "Target Customers": "Individuals, families, international students, workers, retirees, globally mobile employees and organisations"
    },

    "Simplyhealth": {
        "Coverage State": "United Kingdom",
        "Coverage Type": "Health Cash Plan / Health Insurance",
        "Services Rendered": "Dental care, optical care, physiotherapy, chiropractic care, podiatry, diagnostic consultations and scans, prescriptions and everyday healthcare costs",
        "Target Customers": "Individuals, families, employees and businesses"
    },

    "General & Medical": {
        "Coverage State": "United Kingdom",
        "Coverage Type": "Private Medical Insurance",
        "Services Rendered": "Private medical treatment, hospital care, specialist consultations, diagnostics and healthcare support",
        "Target Customers": "Individuals, families and businesses"
    },

    "CS Healthcare": {
        "Coverage State": "United Kingdom",
        "Coverage Type": "Private Healthcare / Health Insurance",
        "Services Rendered": "Private healthcare, consultations, diagnostic services, hospital treatment and healthcare support",
        "Target Customers": "Civil servants, public-sector employees, their families and eligible members"
    }
}

In [19]:
for company, info in coverage_updates.items():
    idx = england_df.index[england_df["Name"] == company]

    for column, value in info.items():
        england_df.loc[idx, column] = value

print("England enrichment complete.")

England enrichment complete.

In [20]:
england_df[
    [
        "Name",
        "Coverage State",
        "Coverage Type",
        "Services Rendered",
        "Target Customers"
    ]
]

,Name,Coverage State,Coverage Type,Services Rendered,Target Customers
0,Bupa,United Kingdom,Private Medical Insurance,"Private healthcare, health insurance, speciali...","Individuals, families, employers and businesses"
1,AXA Health,United Kingdom,Private Medical Insurance,"Private healthcare, hospital treatment, specia...","Individuals, couples, families, self-employed ..."
2,Aviva,United Kingdom,Private Medical Insurance,"Private treatment, hospital care, specialist c...","Individuals, families, employees and businesses"
3,WPA,United Kingdom,Private Medical Insurance / Health Cash Plans,"Private hospital treatment, consultations, dia...","Individuals, families, self-employed people an..."
4,VitalityHealth,United Kingdom,Private Medical Insurance,"Private hospital treatment, GP services, diagn...","Individuals, families, self-employed people an..."
5,The Exeter,United Kingdom,Private Medical Insurance,"Private medical treatment, specialist consulta...","Individuals, families and businesses"
6,Benenden Health,United Kingdom,Healthcare Membership,"24/7 GP helpline, mental health support, diagn...","UK residents, individuals, families and members"
7,Freedom Health Insurance,United Kingdom,Private Medical Insurance,"Private medical treatment, hospital care, spec...","Individuals, families, expatriates and businesses"
8,National Friendly,United Kingdom,Private Medical Insurance,"Private healthcare, medical consultations, dia...",Individuals and families
9,Saga Health Insurance,United Kingdom,Private Medical Insurance,"Private hospital treatment, inpatient and day-...",People aged 50 and over
10,Cigna Healthcare,United Kingdom and international,International Private Medical Insurance,"International medical insurance, inpatient and...","Individuals, families, international students,..."
11,Simplyhealth,United Kingdom,Health Cash Plan / Health Insurance,"Dental care, optical care, physiotherapy, chir...","Individuals, families, employees and businesses"
12,General & Medical,United Kingdom,Private Medical Insurance,"Private medical treatment, hospital care, spec...","Individuals, families and businesses"
13,CS Healthcare,United Kingdom,Private Healthcare / Health Insurance,"Private healthcare, consultations, diagnostic ...","Civil servants, public-sector employees, their..."

In [24]:
england_df[
    [
        "Name",
        "State",
        "Website",
        "Email",
        "Contact Number",
        "Coverage Type",
        "Coverage State",
        "Services Rendered",
        "Target Customers",
        "Source URL"
    ]
]

,Name,State,Website,Email,Contact Number,Coverage Type,Coverage State,Services Rendered,Target Customers,Source URL
0,Bupa,England,https://www.bupa.co.uk/,N/A,0345 609 0111,Private Medical Insurance,United Kingdom,"Private healthcare, health insurance, speciali...","Individuals, families, employers and businesses",https://www.bupa.co.uk/contact-us.php
1,AXA Health,England,https://www.axahealth.co.uk/,N/A,0800 027 1384,Private Medical Insurance,United Kingdom,"Private healthcare, hospital treatment, specia...","Individuals, couples, families, self-employed ...",https://www.axahealth.co.uk/health-insurance/c...
2,Aviva,England,https://www.aviva.co.uk/,N/A,N/A,Private Medical Insurance,United Kingdom,"Private treatment, hospital care, specialist c...","Individuals, families, employees and businesses",https://www.aviva.co.uk/help-and-support/conta...
3,WPA,England,https://www.wpa.org.uk/,N/A,N/A,Private Medical Insurance / Health Cash Plans,United Kingdom,"Private hospital treatment, consultations, dia...","Individuals, families, self-employed people an...",https://www.wpa.org.uk/
4,VitalityHealth,England,https://www.vitality.co.uk/,N/A,N/A,Private Medical Insurance,United Kingdom,"Private hospital treatment, GP services, diagn...","Individuals, families, self-employed people an...",https://www.vitality.co.uk/
5,The Exeter,England,https://www.the-exeter.com/,member@the-exeter.com,0300 123 3201,Private Medical Insurance,United Kingdom,"Private medical treatment, specialist consulta...","Individuals, families and businesses",https://the-exeter.com/contact-us/member/
6,Benenden Health,England,https://www.benenden.co.uk/,N/A,N/A,Healthcare Membership,United Kingdom,"24/7 GP helpline, mental health support, diagn...","UK residents, individuals, families and members",https://www.benenden.co.uk/contact-us/
7,Freedom Health Insurance,England,https://www.freedomhealthinsurance.co.uk/,N/A,0800 999 2013,Private Medical Insurance,United Kingdom,"Private medical treatment, hospital care, spec...","Individuals, families, expatriates and businesses",https://www.freedomhealthinsurance.co.uk/conta...
8,National Friendly,England,https://www.nationalfriendly.co.uk/,N/A,N/A,Private Medical Insurance,United Kingdom,"Private healthcare, medical consultations, dia...",Individuals and families,https://www.nationalfriendly.co.uk/
9,Saga Health Insurance,England,https://www.saga.co.uk/health-insurance,N/A,N/A,Private Medical Insurance,United Kingdom,"Private hospital treatment, inpatient and day-...",People aged 50 and over,https://www.saga.co.uk/contact-us/insurance/he...
10,Cigna Healthcare,England,https://www.cigna.co.uk/,N/A,N/A,International Private Medical Insurance,United Kingdom and international,"International medical insurance, inpatient and...","Individuals, families, international students,...",https://www.cigna.co.uk/
11,Simplyhealth,England,https://www.simplyhealth.co.uk/,N/A,0370 908 3304,Health Cash Plan / Health Insurance,United Kingdom,"Dental care, optical care, physiotherapy, chir...","Individuals, families, employees and businesses",https://www.simplyhealth.co.uk/contact-us
12,General & Medical,England,https://www.gminsure.com/,info@gminsure.com,0800 970 9442,Private Medical Insurance,United Kingdom,"Private medical treatment, hospital care, spec...","Individuals, families and businesses",https://www.generalandmedical.com/contact-us/
13,CS Healthcare,England,https://www.cshealthcare.co.uk/,N/A,N/A,Private Healthcare / Health Insurance,United Kingdom,"Private healthcare, consultations, diagnostic ...","Civil servants, public-sector employees, their...",https://www.cshealthcare.co.uk/contact-us/

In [25]:
wales_df = england_df.copy()

In [26]:
%whos

Variable           Type          Data/Info
------------------------------------------
BeautifulSoup      type          <class 'bs4.BeautifulSoup'>
DDGS               _ProxyMeta    <class 'ddgs._DDGSProxy'>
column             str           Target Customers
columns            list          n=13
companies          list          n=14
company            str           CS Healthcare
contact_results    dict          n=14
contact_updates    dict          n=14
coverage_updates   dict          n=14
emails             list          n=0
england_df         DataFrame     Shape: (14, 13)
find_emails        function      <function find_emails at 0x0000020B80216020>
find_phones        function      <function find_phones at 0x0000020BFA9C6B60>
health_df          DataFrame     Shape: (14, 13)
i                  int           13
idx                Index         Index([13], dtype='int64')
info               dict          n=4
pd                 module        <module 'pandas' from 'C:<...>es\\pandas\\__init__.py'>
phones             list          n=0
r                  dict          n=3
re                 module        <module 're' from 'C:\\Us<...>3\\Lib\\re\\__init__.py'>
requests           module        <module 'requests' from '<...>\\requests\\__init__.py'>
results            list          n=5
row                Series        Shape: (13,)
scrape_website     function      <function scrape_website at 0x0000020BFA9C68E0>
search_company     function      <function search_company at 0x0000020B80217F60>
soup               NoneType      None
time               module        <module 'time' (built-in)>
urljoin            function      <function urljoin at 0x0000020BF8FF2CA0>
urlparse           function      <function urlparse at 0x0000020BF8FF1F80>
value              str           Civil servants, public-se<...>lies and eligible members
wales_df           DataFrame     Shape: (14, 13)

In [27]:
wales_df

,State,Region,Country,Name,Website,Email,Contact Number,Coverage State,Coverage Type,Services Rendered,Target Customers,Source,Source URL
0,England,N/A,United Kingdom,Bupa,https://www.bupa.co.uk/,N/A,0345 609 0111,United Kingdom,Private Medical Insurance,"Private healthcare, health insurance, speciali...","Individuals, families, employers and businesses",Official Company Website,https://www.bupa.co.uk/contact-us.php
1,England,N/A,United Kingdom,AXA Health,https://www.axahealth.co.uk/,N/A,0800 027 1384,United Kingdom,Private Medical Insurance,"Private healthcare, hospital treatment, specia...","Individuals, couples, families, self-employed ...",Official Company Website,https://www.axahealth.co.uk/health-insurance/c...
2,England,N/A,United Kingdom,Aviva,https://www.aviva.co.uk/,N/A,N/A,United Kingdom,Private Medical Insurance,"Private treatment, hospital care, specialist c...","Individuals, families, employees and businesses",Official Company Website,https://www.aviva.co.uk/help-and-support/conta...
3,England,N/A,United Kingdom,WPA,https://www.wpa.org.uk/,N/A,N/A,United Kingdom,Private Medical Insurance / Health Cash Plans,"Private hospital treatment, consultations, dia...","Individuals, families, self-employed people an...",Official Company Website,https://www.wpa.org.uk/
4,England,N/A,United Kingdom,VitalityHealth,https://www.vitality.co.uk/,N/A,N/A,United Kingdom,Private Medical Insurance,"Private hospital treatment, GP services, diagn...","Individuals, families, self-employed people an...",Official Company Website,https://www.vitality.co.uk/
5,England,N/A,United Kingdom,The Exeter,https://www.the-exeter.com/,member@the-exeter.com,0300 123 3201,United Kingdom,Private Medical Insurance,"Private medical treatment, specialist consulta...","Individuals, families and businesses",Official Company Website,https://the-exeter.com/contact-us/member/
6,England,N/A,United Kingdom,Benenden Health,https://www.benenden.co.uk/,N/A,N/A,United Kingdom,Healthcare Membership,"24/7 GP helpline, mental health support, diagn...","UK residents, individuals, families and members",Official Company Website,https://www.benenden.co.uk/contact-us/
7,England,N/A,United Kingdom,Freedom Health Insurance,https://www.freedomhealthinsurance.co.uk/,N/A,0800 999 2013,United Kingdom,Private Medical Insurance,"Private medical treatment, hospital care, spec...","Individuals, families, expatriates and businesses",Official Company Website,https://www.freedomhealthinsurance.co.uk/conta...
8,England,N/A,United Kingdom,National Friendly,https://www.nationalfriendly.co.uk/,N/A,N/A,United Kingdom,Private Medical Insurance,"Private healthcare, medical consultations, dia...",Individuals and families,Official Company Website,https://www.nationalfriendly.co.uk/
9,England,N/A,United Kingdom,Saga Health Insurance,https://www.saga.co.uk/health-insurance,N/A,N/A,United Kingdom,Private Medical Insurance,"Private hospital treatment, inpatient and day-...",People aged 50 and over,Official Company Website,https://www.saga.co.uk/contact-us/insurance/he...
10,England,N/A,United Kingdom,Cigna Healthcare,https://www.cigna.co.uk/,N/A,N/A,United Kingdom and international,International Private Medical Insurance,"International medical insurance, inpatient and...","Individuals, families, international students,...",Official Company Website,https://www.cigna.co.uk/
11,England,N/A,United Kingdom,Simplyhealth,https://www.simplyhealth.co.uk/,N/A,0370 908 3304,United Kingdom,Health Cash Plan / Health Insurance,"Dental care, optical care, physiotherapy, chir...","Individuals, families, employees and businesses",Official Company Website,https://www.simplyhealth.co.uk/contact-us
12,England,N/A,United Kingdom,General & Medical,https://www.gminsure.com/,info@gminsure.com,0800 970 9442,United Kingdom,Private Medical Insurance,"Private medical treatment, hospital care, spec...","Individuals, families and businesses",Official Company Website,https://www.generalandmedical.com/contact-us/
13,England,N/A,United Kingdom,CS Healthcare,https://www.cshealthcare.co.uk/,N/A,N/A,United Kingdom,Private Healthcare / Health Insurance,"Private healthcare, consultations, diagnostic ...","Civil servants, public-sector employees, their...",Official Company Website,https://www.cshealthcare.co.uk/contact-us/

In [28]:
wales_df = pd.DataFrame(columns=england_df.columns)

In [29]:
wales_df

Empty DataFrame
Columns: [State, Region, Country, Name, Website, Email, Contact Number, Coverage State, Coverage Type, Services Rendered, Target Customers, Source, Source URL]
Index: []

In [30]:
wales_companies = [
    ["Aneurin Bevan University Health Board"],
    ["Betsi Cadwaladr University Health Board"],
    ["Cardiff and Vale University Health Board"],
    ["Cwm Taf Morgannwg University Health Board"],
    ["Hywel Dda University Health Board"],
    ["Powys Teaching Health Board"],
    ["Swansea Bay University Health Board"],
    ["Public Health Wales NHS Trust"],
    ["Velindre University NHS Trust"],
    ["Welsh Ambulance Services University NHS Trust"],
    ["Health Education and Improvement Wales"],
    ["Digital Health and Care Wales"]
]

wales_df = pd.DataFrame(wales_companies, columns=["Name"])

wales_df["State"] = "Wales"
wales_df["Region"] = "N/A"
wales_df["Country"] = "United Kingdom"

wales_df

,Name,State,Region,Country
0,Aneurin Bevan University Health Board,Wales,N/A,United Kingdom
1,Betsi Cadwaladr University Health Board,Wales,N/A,United Kingdom
2,Cardiff and Vale University Health Board,Wales,N/A,United Kingdom
3,Cwm Taf Morgannwg University Health Board,Wales,N/A,United Kingdom
4,Hywel Dda University Health Board,Wales,N/A,United Kingdom
5,Powys Teaching Health Board,Wales,N/A,United Kingdom
6,Swansea Bay University Health Board,Wales,N/A,United Kingdom
7,Public Health Wales NHS Trust,Wales,N/A,United Kingdom
8,Velindre University NHS Trust,Wales,N/A,United Kingdom
9,Welsh Ambulance Services University NHS Trust,Wales,N/A,United Kingdom
10,Health Education and Improvement Wales,Wales,N/A,United Kingdom
11,Digital Health and Care Wales,Wales,N/A,United Kingdom

In [31]:
wales_df["Website"] = "N/A"
wales_df["Email"] = "N/A"
wales_df["Contact Number"] = "N/A"
wales_df["Coverage Type"] = "N/A"
wales_df["Coverage State"] = "N/A"
wales_df["Services Rendered"] = "N/A"
wales_df["Target Customers"] = "N/A"
wales_df["Source"] = "Official Organisation Website"
wales_df["Source URL"] = "N/A"

wales_df

,Name,State,Region,Country,Website,Email,Contact Number,Coverage Type,Coverage State,Services Rendered,Target Customers,Source,Source URL
0,Aneurin Bevan University Health Board,Wales,N/A,United Kingdom,N/A,N/A,N/A,N/A,N/A,N/A,N/A,Official Organisation Website,N/A
1,Betsi Cadwaladr University Health Board,Wales,N/A,United Kingdom,N/A,N/A,N/A,N/A,N/A,N/A,N/A,Official Organisation Website,N/A
2,Cardiff and Vale University Health Board,Wales,N/A,United Kingdom,N/A,N/A,N/A,N/A,N/A,N/A,N/A,Official Organisation Website,N/A
3,Cwm Taf Morgannwg University Health Board,Wales,N/A,United Kingdom,N/A,N/A,N/A,N/A,N/A,N/A,N/A,Official Organisation Website,N/A
4,Hywel Dda University Health Board,Wales,N/A,United Kingdom,N/A,N/A,N/A,N/A,N/A,N/A,N/A,Official Organisation Website,N/A
5,Powys Teaching Health Board,Wales,N/A,United Kingdom,N/A,N/A,N/A,N/A,N/A,N/A,N/A,Official Organisation Website,N/A
6,Swansea Bay University Health Board,Wales,N/A,United Kingdom,N/A,N/A,N/A,N/A,N/A,N/A,N/A,Official Organisation Website,N/A
7,Public Health Wales NHS Trust,Wales,N/A,United Kingdom,N/A,N/A,N/A,N/A,N/A,N/A,N/A,Official Organisation Website,N/A
8,Velindre University NHS Trust,Wales,N/A,United Kingdom,N/A,N/A,N/A,N/A,N/A,N/A,N/A,Official Organisation Website,N/A
9,Welsh Ambulance Services University NHS Trust,Wales,N/A,United Kingdom,N/A,N/A,N/A,N/A,N/A,N/A,N/A,Official Organisation Website,N/A
10,Health Education and Improvement Wales,Wales,N/A,United Kingdom,N/A,N/A,N/A,N/A,N/A,N/A,N/A,Official Organisation Website,N/A
11,Digital Health and Care Wales,Wales,N/A,United Kingdom,N/A,N/A,N/A,N/A,N/A,N/A,N/A,Official Organisation Website,N/A

In [32]:
wales_df.columns

Index(['Name', 'State', 'Region', 'Country', 'Website', 'Email',
       'Contact Number', 'Coverage Type', 'Coverage State',
       'Services Rendered', 'Target Customers', 'Source', 'Source URL'],
      dtype='object')

In [33]:
wales_websites = {
    "Aneurin Bevan University Health Board": "https://abuhb.nhs.wales/",
    "Betsi Cadwaladr University Health Board": "https://bcuhb.nhs.wales/",
    "Cardiff and Vale University Health Board": "https://cavuhb.nhs.wales/",
    "Cwm Taf Morgannwg University Health Board": "https://ctmuhb.nhs.wales/",
    "Hywel Dda University Health Board": "https://hduhb.nhs.wales/",
    "Powys Teaching Health Board": "https://pthb.nhs.wales/",
    "Swansea Bay University Health Board": "https://sbuhb.nhs.wales/",
    "Public Health Wales NHS Trust": "https://phw.nhs.wales/",
    "Velindre University NHS Trust": "https://velindre.nhs.wales/",
    "Welsh Ambulance Services University NHS Trust": "https://ambulance.nhs.wales/",
    "Health Education and Improvement Wales": "https://heiw.nhs.wales/",
    "Digital Health and Care Wales": "https://dhcw.nhs.wales/"
}

wales_df["Website"] = wales_df["Name"].map(wales_websites)

wales_df[["Name", "Website"]]

,Name,Website
0,Aneurin Bevan University Health Board,https://abuhb.nhs.wales/
1,Betsi Cadwaladr University Health Board,https://bcuhb.nhs.wales/
2,Cardiff and Vale University Health Board,https://cavuhb.nhs.wales/
3,Cwm Taf Morgannwg University Health Board,https://ctmuhb.nhs.wales/
4,Hywel Dda University Health Board,https://hduhb.nhs.wales/
5,Powys Teaching Health Board,https://pthb.nhs.wales/
6,Swansea Bay University Health Board,https://sbuhb.nhs.wales/
7,Public Health Wales NHS Trust,https://phw.nhs.wales/
8,Velindre University NHS Trust,https://velindre.nhs.wales/
9,Welsh Ambulance Services University NHS Trust,https://ambulance.nhs.wales/
10,Health Education and Improvement Wales,https://heiw.nhs.wales/
11,Digital Health and Care Wales,https://dhcw.nhs.wales/

In [35]:
wales_df["Website"] = wales_df["Name"].map(wales_websites)

In [36]:
wales_contacts = {
    "Aneurin Bevan University Health Board": {
        "Email": "abb.engagement@wales.nhs.uk",
        "Contact Number": "01633 431890",
        "Source URL": "https://abuhb.nhs.wales/about-us/engagement/community-engagement/contact-us/"
    },

    "Betsi Cadwaladr University Health Board": {
        "Email": "N/A",
        "Contact Number": "N/A",
        "Source URL": "https://bcuhb.nhs.wales/contact-us/"
    },

    "Cardiff and Vale University Health Board": {
        "Email": "Cav.Concerns@wales.nhs.uk",
        "Contact Number": "029 2183 6318",
        "Source URL": "https://cavuhb.nhs.wales/contact-us/"
    },

    "Cwm Taf Morgannwg University Health Board": {
        "Email": "N/A",
        "Contact Number": "N/A",
        "Source URL": "https://ctmuhb.nhs.wales/contact-us/"
    },

    "Hywel Dda University Health Board": {
        "Email": "corporate.correspondence.hdd@wales.nhs.uk",
        "Contact Number": "01267 235151",
        "Source URL": "https://hduhb.nhs.wales/about-us/your-health-board/board-members/our-board-members/contact-board-members/"
    },

    "Powys Teaching Health Board": {
        "Email": "N/A",
        "Contact Number": "01874 442071",
        "Source URL": "https://pthb.nhs.wales/use-of-site/freedom-of-information/"
    },

    "Swansea Bay University Health Board": {
        "Email": "FOIA.Requests@wales.nhs.uk",
        "Contact Number": "01639 683344",
        "Source URL": "https://sbuhb.nhs.wales/about-us/contact-us/"
    },

    "Public Health Wales NHS Trust": {
        "Email": "N/A",
        "Contact Number": "029 2022 7744",
        "Source URL": "https://phw.nhs.wales/contact-us/"
    },

    "Velindre University NHS Trust": {
        "Email": "N/A",
        "Contact Number": "N/A",
        "Source URL": "https://velindre.nhs.wales/contact-us/"
    },

    "Welsh Ambulance Services University NHS Trust": {
        "Email": "PECI.team@wales.nhs.uk",
        "Contact Number": "0300 723 9207",
        "Source URL": "https://ambulance.nhs.wales/contact-us/"
    },

    "Health Education and Improvement Wales": {
        "Email": "N/A",
        "Contact Number": "N/A",
        "Source URL": "https://heiw.nhs.wales/contact-us/"
    },

    "Digital Health and Care Wales": {
        "Email": "DHCW-Comms@wales.nhs.uk",
        "Contact Number": "02920 500500",
        "Source URL": "https://dhcw.nhs.wales/contact-us/"
    }
}

In [37]:
for company, info in wales_contacts.items():
    idx = wales_df.index[wales_df["Name"] == company]

    if len(idx) > 0:
        wales_df.loc[idx, "Email"] = info["Email"]
        wales_df.loc[idx, "Contact Number"] = info["Contact Number"]
        wales_df.loc[idx, "Source URL"] = info["Source URL"]

wales_df[["Name", "Email", "Contact Number", "Source URL"]]

,Name,Email,Contact Number,Source URL
0,Aneurin Bevan University Health Board,abb.engagement@wales.nhs.uk,01633 431890,https://abuhb.nhs.wales/about-us/engagement/co...
1,Betsi Cadwaladr University Health Board,N/A,N/A,https://bcuhb.nhs.wales/contact-us/
2,Cardiff and Vale University Health Board,Cav.Concerns@wales.nhs.uk,029 2183 6318,https://cavuhb.nhs.wales/contact-us/
3,Cwm Taf Morgannwg University Health Board,N/A,N/A,https://ctmuhb.nhs.wales/contact-us/
4,Hywel Dda University Health Board,corporate.correspondence.hdd@wales.nhs.uk,01267 235151,https://hduhb.nhs.wales/about-us/your-health-b...
5,Powys Teaching Health Board,N/A,01874 442071,https://pthb.nhs.wales/use-of-site/freedom-of-...
6,Swansea Bay University Health Board,FOIA.Requests@wales.nhs.uk,01639 683344,https://sbuhb.nhs.wales/about-us/contact-us/
7,Public Health Wales NHS Trust,N/A,029 2022 7744,https://phw.nhs.wales/contact-us/
8,Velindre University NHS Trust,N/A,N/A,https://velindre.nhs.wales/contact-us/
9,Welsh Ambulance Services University NHS Trust,PECI.team@wales.nhs.uk,0300 723 9207,https://ambulance.nhs.wales/contact-us/
10,Health Education and Improvement Wales,N/A,N/A,https://heiw.nhs.wales/contact-us/
11,Digital Health and Care Wales,DHCW-Comms@wales.nhs.uk,02920 500500,https://dhcw.nhs.wales/contact-us/

In [38]:
wales_df[["Name", "Email", "Contact Number"]]

,Name,Email,Contact Number
0,Aneurin Bevan University Health Board,abb.engagement@wales.nhs.uk,01633 431890
1,Betsi Cadwaladr University Health Board,N/A,N/A
2,Cardiff and Vale University Health Board,Cav.Concerns@wales.nhs.uk,029 2183 6318
3,Cwm Taf Morgannwg University Health Board,N/A,N/A
4,Hywel Dda University Health Board,corporate.correspondence.hdd@wales.nhs.uk,01267 235151
5,Powys Teaching Health Board,N/A,01874 442071
6,Swansea Bay University Health Board,FOIA.Requests@wales.nhs.uk,01639 683344
7,Public Health Wales NHS Trust,N/A,029 2022 7744
8,Velindre University NHS Trust,N/A,N/A
9,Welsh Ambulance Services University NHS Trust,PECI.team@wales.nhs.uk,0300 723 9207
10,Health Education and Improvement Wales,N/A,N/A
11,Digital Health and Care Wales,DHCW-Comms@wales.nhs.uk,02920 500500

In [39]:
coverage_types = {
    "Aneurin Bevan University Health Board": "NHS Health Services",
    "Betsi Cadwaladr University Health Board": "NHS Health Services",
    "Cardiff and Vale University Health Board": "NHS Health Services",
    "Cwm Taf Morgannwg University Health Board": "NHS Health Services",
    "Hywel Dda University Health Board": "NHS Health Services",
    "Powys Teaching Health Board": "NHS Health Services",
    "Swansea Bay University Health Board": "NHS Health Services",
    
    "Public Health Wales NHS Trust": "Public Health Services",
    
    "Velindre University NHS Trust": "Specialist NHS Healthcare",
    
    "Welsh Ambulance Services University NHS Trust": "Emergency and Non-Emergency Ambulance Services",
    
    "Health Education and Improvement Wales": "NHS Workforce Education and Training",
    
    "Digital Health and Care Wales": "Digital Health and Data Services"
}

wales_df["Coverage Type"] = wales_df["Name"].map(coverage_types)

wales_df[["Name", "Coverage Type"]]

,Name,Coverage Type
0,Aneurin Bevan University Health Board,NHS Health Services
1,Betsi Cadwaladr University Health Board,NHS Health Services
2,Cardiff and Vale University Health Board,NHS Health Services
3,Cwm Taf Morgannwg University Health Board,NHS Health Services
4,Hywel Dda University Health Board,NHS Health Services
5,Powys Teaching Health Board,NHS Health Services
6,Swansea Bay University Health Board,NHS Health Services
7,Public Health Wales NHS Trust,Public Health Services
8,Velindre University NHS Trust,Specialist NHS Healthcare
9,Welsh Ambulance Services University NHS Trust,Emergency and Non-Emergency Ambulance Services
10,Health Education and Improvement Wales,NHS Workforce Education and Training
11,Digital Health and Care Wales,Digital Health and Data Services

In [40]:
coverage_state = {
    "Aneurin Bevan University Health Board": "Local – Southeast Wales",
    "Betsi Cadwaladr University Health Board": "Local – North Wales",
    "Cardiff and Vale University Health Board": "Local – Cardiff and Vale of Glamorgan",
    "Cwm Taf Morgannwg University Health Board": "Local – Cwm Taf Morgannwg",
    "Hywel Dda University Health Board": "Local – West Wales",
    "Powys Teaching Health Board": "Local – Powys",
    "Swansea Bay University Health Board": "Local – Swansea Bay",
    "Public Health Wales NHS Trust": "National – Wales",
    "Velindre University NHS Trust": "National – Wales",
    "Welsh Ambulance Services University NHS Trust": "National – Wales",
    "Health Education and Improvement Wales": "National – Wales",
    "Digital Health and Care Wales": "National – Wales"
}

wales_df["Coverage State"] = wales_df["Name"].map(coverage_state)

wales_df[["Name", "Coverage State"]]

,Name,Coverage State
0,Aneurin Bevan University Health Board,Local – Southeast Wales
1,Betsi Cadwaladr University Health Board,Local – North Wales
2,Cardiff and Vale University Health Board,Local – Cardiff and Vale of Glamorgan
3,Cwm Taf Morgannwg University Health Board,Local – Cwm Taf Morgannwg
4,Hywel Dda University Health Board,Local – West Wales
5,Powys Teaching Health Board,Local – Powys
6,Swansea Bay University Health Board,Local – Swansea Bay
7,Public Health Wales NHS Trust,National – Wales
8,Velindre University NHS Trust,National – Wales
9,Welsh Ambulance Services University NHS Trust,National – Wales
10,Health Education and Improvement Wales,National – Wales
11,Digital Health and Care Wales,National – Wales

In [41]:
services_rendered = {
    "Aneurin Bevan University Health Board":
        "Primary care, hospital care, community health services, mental health services, specialist healthcare and public health services",

    "Betsi Cadwaladr University Health Board":
        "Primary care, hospital care, community health services, mental health services, specialist healthcare and emergency care",

    "Cardiff and Vale University Health Board":
        "Primary care, hospital care, community health services, mental health services, specialist healthcare and emergency care",

    "Cwm Taf Morgannwg University Health Board":
        "Primary care, hospital care, community health services, mental health services, specialist healthcare and emergency care",

    "Hywel Dda University Health Board":
        "Primary care, hospital care, community health services, mental health services, cancer care, diagnostics, physiotherapy and specialist healthcare",

    "Powys Teaching Health Board":
        "Primary care, community hospitals, community health services, mental health services, therapy services and specialist care through commissioned services",

    "Swansea Bay University Health Board":
        "Hospital care, primary care, community health services, mental health and learning disability services, specialist healthcare and emergency care",

    "Public Health Wales NHS Trust":
        "Screening programmes, immunisations and vaccines, health data and surveillance, STI testing, disease control, workplace health and public health programmes",

    "Velindre University NHS Trust":
        "Specialist cancer treatment, radiotherapy, systemic anti-cancer treatments, specialist palliative care, cancer research and Welsh Blood Service",

    "Welsh Ambulance Services University NHS Trust":
        "Emergency ambulance services, non-emergency patient transport, emergency medical services and NHS 111 Wales",

    "Health Education and Improvement Wales":
        "Workforce education, training, professional development, workforce planning and development for NHS Wales",

    "Digital Health and Care Wales":
        "National digital health systems, digital and data services, electronic health records, digital infrastructure, cyber security and digital transformation"
}

wales_df["Services Rendered"] = wales_df["Name"].map(services_rendered)

wales_df[["Name", "Services Rendered"]]

,Name,Services Rendered
0,Aneurin Bevan University Health Board,"Primary care, hospital care, community health ..."
1,Betsi Cadwaladr University Health Board,"Primary care, hospital care, community health ..."
2,Cardiff and Vale University Health Board,"Primary care, hospital care, community health ..."
3,Cwm Taf Morgannwg University Health Board,"Primary care, hospital care, community health ..."
4,Hywel Dda University Health Board,"Primary care, hospital care, community health ..."
5,Powys Teaching Health Board,"Primary care, community hospitals, community h..."
6,Swansea Bay University Health Board,"Hospital care, primary care, community health ..."
7,Public Health Wales NHS Trust,"Screening programmes, immunisations and vaccin..."
8,Velindre University NHS Trust,"Specialist cancer treatment, radiotherapy, sys..."
9,Welsh Ambulance Services University NHS Trust,"Emergency ambulance services, non-emergency pa..."
10,Health Education and Improvement Wales,"Workforce education, training, professional de..."
11,Digital Health and Care Wales,"National digital health systems, digital and d..."

In [42]:
target_customers = {
    "Aneurin Bevan University Health Board": "Residents of Blaenau Gwent, Caerphilly, Monmouthshire, Newport and Torfaen",
    "Betsi Cadwaladr University Health Board": "Residents of North Wales",
    "Cardiff and Vale University Health Board": "Residents of Cardiff and the Vale of Glamorgan",
    "Cwm Taf Morgannwg University Health Board": "Residents of Bridgend, Merthyr Tydfil and Rhondda Cynon Taf",
    "Hywel Dda University Health Board": "Residents of Carmarthenshire, Ceredigion, Pembrokeshire and parts of South Powys",
    "Powys Teaching Health Board": "Residents of Powys",
    "Swansea Bay University Health Board": "Residents of Neath Port Talbot and Swansea",
    "Public Health Wales NHS Trust": "People across Wales, including individuals, communities and public-sector organisations",
    "Velindre University NHS Trust": "Patients across Wales requiring specialist cancer and related services",
    "Welsh Ambulance Services University NHS Trust": "People across Wales requiring emergency or non-emergency ambulance services",
    "Health Education and Improvement Wales": "Healthcare professionals, healthcare students and the NHS workforce in Wales",
    "Digital Health and Care Wales": "NHS Wales organisations, healthcare professionals and the people who use NHS Wales services"
}

wales_df["Target Customers"] = wales_df["Name"].map(target_customers)

wales_df[["Name", "Target Customers"]]

,Name,Target Customers
0,Aneurin Bevan University Health Board,"Residents of Blaenau Gwent, Caerphilly, Monmou..."
1,Betsi Cadwaladr University Health Board,Residents of North Wales
2,Cardiff and Vale University Health Board,Residents of Cardiff and the Vale of Glamorgan
3,Cwm Taf Morgannwg University Health Board,"Residents of Bridgend, Merthyr Tydfil and Rhon..."
4,Hywel Dda University Health Board,"Residents of Carmarthenshire, Ceredigion, Pemb..."
5,Powys Teaching Health Board,Residents of Powys
6,Swansea Bay University Health Board,Residents of Neath Port Talbot and Swansea
7,Public Health Wales NHS Trust,"People across Wales, including individuals, co..."
8,Velindre University NHS Trust,Patients across Wales requiring specialist can...
9,Welsh Ambulance Services University NHS Trust,People across Wales requiring emergency or non...
10,Health Education and Improvement Wales,"Healthcare professionals, healthcare students ..."
11,Digital Health and Care Wales,"NHS Wales organisations, healthcare profession..."

In [43]:
print(england_df.columns.tolist())
print(wales_df.columns.tolist())

['State', 'Region', 'Country', 'Name', 'Website', 'Email', 'Contact Number', 'Coverage State', 'Coverage Type', 'Services Rendered', 'Target Customers', 'Source', 'Source URL']
['Name', 'State', 'Region', 'Country', 'Website', 'Email', 'Contact Number', 'Coverage Type', 'Coverage State', 'Services Rendered', 'Target Customers', 'Source', 'Source URL']

In [44]:
england_wales_df = pd.concat(
    [england_df, wales_df],
    ignore_index=True
)

In [45]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 100)
pd.set_option("display.max_rows", None)

display(england_wales_df)

,State,Region,Country,Name,Website,Email,Contact Number,Coverage State,Coverage Type,Services Rendered,Target Customers,Source,Source URL
0,England,N/A,United Kingdom,Bupa,https://www.bupa.co.uk/,N/A,0345 609 0111,United Kingdom,Private Medical Insurance,"Private healthcare, health insurance, specialist treatment, hospital care, health assessments an...","Individuals, families, employers and businesses",Official Company Website,https://www.bupa.co.uk/contact-us.php
1,England,N/A,United Kingdom,AXA Health,https://www.axahealth.co.uk/,N/A,0800 027 1384,United Kingdom,Private Medical Insurance,"Private healthcare, hospital treatment, specialist consultations, diagnostic tests, mental healt...","Individuals, couples, families, self-employed people, small businesses and large corporates",Official Company Website,https://www.axahealth.co.uk/health-insurance/contact-us/
2,England,N/A,United Kingdom,Aviva,https://www.aviva.co.uk/,N/A,N/A,United Kingdom,Private Medical Insurance,"Private treatment, hospital care, specialist consultations, diagnostic tests, cancer treatment, ...","Individuals, families, employees and businesses",Official Company Website,https://www.aviva.co.uk/help-and-support/contact-us/
3,England,N/A,United Kingdom,WPA,https://www.wpa.org.uk/,N/A,N/A,United Kingdom,Private Medical Insurance / Health Cash Plans,"Private hospital treatment, consultations, diagnostic tests, health cash plans, dental plans and...","Individuals, families, self-employed people and businesses",Official Company Website,https://www.wpa.org.uk/
4,England,N/A,United Kingdom,VitalityHealth,https://www.vitality.co.uk/,N/A,N/A,United Kingdom,Private Medical Insurance,"Private hospital treatment, GP services, diagnostic tests, specialist care, cancer care, mental ...","Individuals, families, self-employed people and businesses",Official Company Website,https://www.vitality.co.uk/
5,England,N/A,United Kingdom,The Exeter,https://www.the-exeter.com/,member@the-exeter.com,0300 123 3201,United Kingdom,Private Medical Insurance,"Private medical treatment, specialist consultations, hospital care, diagnostics and healthcare s...","Individuals, families and businesses",Official Company Website,https://the-exeter.com/contact-us/member/
6,England,N/A,United Kingdom,Benenden Health,https://www.benenden.co.uk/,N/A,N/A,United Kingdom,Healthcare Membership,"24/7 GP helpline, mental health support, diagnostic consultations and tests, surgical treatment,...","UK residents, individuals, families and members",Official Company Website,https://www.benenden.co.uk/contact-us/
7,England,N/A,United Kingdom,Freedom Health Insurance,https://www.freedomhealthinsurance.co.uk/,N/A,0800 999 2013,United Kingdom,Private Medical Insurance,"Private medical treatment, hospital care, specialist consultations, diagnostic services and heal...","Individuals, families, expatriates and businesses",Official Company Website,https://www.freedomhealthinsurance.co.uk/contact-us
8,England,N/A,United Kingdom,National Friendly,https://www.nationalfriendly.co.uk/,N/A,N/A,United Kingdom,Private Medical Insurance,"Private healthcare, medical consultations, diagnostic services and treatment",Individuals and families,Official Company Website,https://www.nationalfriendly.co.uk/
9,England,N/A,United Kingdom,Saga Health Insurance,https://www.saga.co.uk/health-insurance,N/A,N/A,United Kingdom,Private Medical Insurance,"Private hospital treatment, inpatient and day-patient treatment, outpatient consultations, tests...",People aged 50 and over,Official Company Website,https://www.saga.co.uk/contact-us/insurance/health-insurance
10,England,N/A,United Kingdom,Cigna Healthcare,https://www.cigna.co.uk/,N/A,N/A,United Kingdom and international,International Private Medical Insurance,"International medical insurance, inpatient and day-patient care, hospital treatment, specialist ...","Individuals, families, international students, workers, retirees, globally mobile employees and ...",Official Company Website,https://www.cigna.co.uk/
11,England,N/A,United Kingdom,Simplyhealth,https://www.simplyhealth.co.uk/,N/A,0370 908 3304,United Kingdom,Health Cash Plan / Health Insurance,"Dental care, optical care, physiotherapy, chiropractic care, podiatry, diagnostic consultations ...","Individuals, families, employees and businesses",Official Company Website,https://www.simplyhealth.co.uk/contact-us
12,England,N/A,United Kingdom,General & Medical,https://www.gminsure.com/,info@gminsure.com,0800 970 9442,United Kingdom,Private Medical Insurance,"Private medical treatment, hospital care, specialist consultations, diagnostics and healthcare s...","Individuals, families and businesses",Official Company Website,https://www.generalandmedical.com/contact-us/
13,England,N/A,United Kingdom,CS Healthcare,https://www.cshealthcare.co.uk/,N/A,N/A,United Kingdom,Private Healthcare / Health Insurance,"Private healthcare, consultations, diagnostic services, hospital treatment and healthcare support","Civil servants, public-sector employees, their families and eligible members",Official Company Website,https://www.cshealthcare.co.uk/contact-us/
14,Wales,N/A,United Kingdom,Aneurin Bevan University Health Board,https://abuhb.nhs.wales/,abb.engagement@wales.nhs.uk,01633 431890,Local – Southeast Wales,NHS Health Services,"Primary care, hospital care, community health services, mental health services, specialist healt...","Residents of Blaenau Gwent, Caerphilly, Monmouthshire, Newport and Torfaen",Official Organisation Website,https://abuhb.nhs.wales/about-us/engagement/community-engagement/contact-us/
15,Wales,N/A,United Kingdom,Betsi Cadwaladr University Health Board,https://bcuhb.nhs.wales/,N/A,N/A,Local – North Wales,NHS Health Services,"Primary care, hospital care, community health services, mental health services, specialist healt...",Residents of North Wales,Official Organisation Website,https://bcuhb.nhs.wales/contact-us/
16,Wales,N/A,United Kingdom,Cardiff and Vale University Health Board,https://cavuhb.nhs.wales/,Cav.Concerns@wales.nhs.uk,029 2183 6318,Local – Cardiff and Vale of Glamorgan,NHS Health Services,"Primary care, hospital care, community health services, mental health services, specialist healt...",Residents of Cardiff and the Vale of Glamorgan,Official Organisation Website,https://cavuhb.nhs.wales/contact-us/
17,Wales,N/A,United Kingdom,Cwm Taf Morgannwg University Health Board,https://ctmuhb.nhs.wales/,N/A,N/A,Local – Cwm Taf Morgannwg,NHS Health Services,"Primary care, hospital care, community health services, mental health services, specialist healt...","Residents of Bridgend, Merthyr Tydfil and Rhondda Cynon Taf",Official Organisation Website,https://ctmuhb.nhs.wales/contact-us/
18,Wales,N/A,United Kingdom,Hywel Dda University Health Board,https://hduhb.nhs.wales/,corporate.correspondence.hdd@wales.nhs.uk,01267 235151,Local – West Wales,NHS Health Services,"Primary care, hospital care, community health services, mental health services, cancer care, dia...","Residents of Carmarthenshire, Ceredigion, Pembrokeshire and parts of South Powys",Official Organisation Website,https://hduhb.nhs.wales/about-us/your-health-board/board-members/our-board-members/contact-board...
19,Wales,N/A,United Kingdom,Powys Teaching Health Board,https://pthb.nhs.wales/,N/A,01874 442071,Local – Powys,NHS Health Services,"Primary care, community hospitals, community health services, mental health services, therapy se...",Residents of Powys,Official Organisation Website,https://pthb.nhs.wales/use-of-site/freedom-of-information/
20,Wales,N/A,United Kingdom,Swansea Bay University Health Board,https://sbuhb.nhs.wales/,FOIA.Requests@wales.nhs.uk,01639 683344,Local – Swansea Bay,NHS Health Services,"Hospital care, primary care, community health services, mental health and learning disability se...",Residents of Neath Port Talbot and Swansea,Official Organisation Website,https://sbuhb.nhs.wales/about-us/contact-us/
21,Wales,N/A,United Kingdom,Public Health Wales NHS Trust,https://phw.nhs.wales/,N/A,029 2022 7744,National – Wales,Public Health Services,"Screening programmes, immunisations and vaccines, health data and surveillance, STI testing, dis...","People across Wales, including individuals, communities and public-sector organisations",Official Organisation Website,https://phw.nhs.wales/contact-us/
22,Wales,N/A,United Kingdom,Velindre University NHS Trust,https://velindre.nhs.wales/,N/A,N/A,National – Wales,Specialist NHS Healthcare,"Specialist cancer treatment, radiotherapy, systemic anti-cancer treatments, specialist palliativ...",Patients across Wales requiring specialist cancer and related services,Official Organisation Website,https://velindre.nhs.wales/contact-us/
23,Wales,N/A,United Kingdom,Welsh Ambulance Services University NHS Trust,https://ambulance.nhs.wales/,PECI.team@wales.nhs.uk,0300 723 9207,National – Wales,Emergency and Non-Emergency Ambulance Services,"Emergency ambulance services, non-emergency patient transport, emergency medical services and NH...",People across Wales requiring emergency or non-emergency ambulance services,Official Organisation Website,https://ambulance.nhs.wales/contact-us/
24,Wales,N/A,United Kingdom,Health Education and Improvement Wales,https://heiw.nhs.wales/,N/A,N/A,National – Wales,NHS Workforce Education and Training,"Workforce education, training, professional development, workforce planning and development for ...","Healthcare professionals, healthcare students and the NHS workforce in Wales",Official Organisation Website,https://heiw.nhs.wales/contact-us/
25,Wales,N/A,United Kingdom,Digital Health and Care Wales,https://dhcw.nhs.wales/,DHCW-Comms@wales.nhs.uk,02920 500500,National – Wales,Digital Health and Data Services,"National digital health systems, digital and data services, electronic health records, digital i...","NHS Wales organisations, healthcare professionals and the people who use NHS Wales services",Official Organisation Website,https://dhcw.nhs.wales/contact-us/

In [46]:
print("Total organisations:", len(england_wales_df))
print("\nBy State:")
print(england_wales_df["State"].value_counts())

Total organisations: 26

By State:
State
England    14
Wales      12
Name: count, dtype: int64

In [47]:
display(england_wales_df)

,State,Region,Country,Name,Website,Email,Contact Number,Coverage State,Coverage Type,Services Rendered,Target Customers,Source,Source URL
0,England,N/A,United Kingdom,Bupa,https://www.bupa.co.uk/,N/A,0345 609 0111,United Kingdom,Private Medical Insurance,"Private healthcare, health insurance, specialist treatment, hospital care, health assessments an...","Individuals, families, employers and businesses",Official Company Website,https://www.bupa.co.uk/contact-us.php
1,England,N/A,United Kingdom,AXA Health,https://www.axahealth.co.uk/,N/A,0800 027 1384,United Kingdom,Private Medical Insurance,"Private healthcare, hospital treatment, specialist consultations, diagnostic tests, mental healt...","Individuals, couples, families, self-employed people, small businesses and large corporates",Official Company Website,https://www.axahealth.co.uk/health-insurance/contact-us/
2,England,N/A,United Kingdom,Aviva,https://www.aviva.co.uk/,N/A,N/A,United Kingdom,Private Medical Insurance,"Private treatment, hospital care, specialist consultations, diagnostic tests, cancer treatment, ...","Individuals, families, employees and businesses",Official Company Website,https://www.aviva.co.uk/help-and-support/contact-us/
3,England,N/A,United Kingdom,WPA,https://www.wpa.org.uk/,N/A,N/A,United Kingdom,Private Medical Insurance / Health Cash Plans,"Private hospital treatment, consultations, diagnostic tests, health cash plans, dental plans and...","Individuals, families, self-employed people and businesses",Official Company Website,https://www.wpa.org.uk/
4,England,N/A,United Kingdom,VitalityHealth,https://www.vitality.co.uk/,N/A,N/A,United Kingdom,Private Medical Insurance,"Private hospital treatment, GP services, diagnostic tests, specialist care, cancer care, mental ...","Individuals, families, self-employed people and businesses",Official Company Website,https://www.vitality.co.uk/
5,England,N/A,United Kingdom,The Exeter,https://www.the-exeter.com/,member@the-exeter.com,0300 123 3201,United Kingdom,Private Medical Insurance,"Private medical treatment, specialist consultations, hospital care, diagnostics and healthcare s...","Individuals, families and businesses",Official Company Website,https://the-exeter.com/contact-us/member/
6,England,N/A,United Kingdom,Benenden Health,https://www.benenden.co.uk/,N/A,N/A,United Kingdom,Healthcare Membership,"24/7 GP helpline, mental health support, diagnostic consultations and tests, surgical treatment,...","UK residents, individuals, families and members",Official Company Website,https://www.benenden.co.uk/contact-us/
7,England,N/A,United Kingdom,Freedom Health Insurance,https://www.freedomhealthinsurance.co.uk/,N/A,0800 999 2013,United Kingdom,Private Medical Insurance,"Private medical treatment, hospital care, specialist consultations, diagnostic services and heal...","Individuals, families, expatriates and businesses",Official Company Website,https://www.freedomhealthinsurance.co.uk/contact-us
8,England,N/A,United Kingdom,National Friendly,https://www.nationalfriendly.co.uk/,N/A,N/A,United Kingdom,Private Medical Insurance,"Private healthcare, medical consultations, diagnostic services and treatment",Individuals and families,Official Company Website,https://www.nationalfriendly.co.uk/
9,England,N/A,United Kingdom,Saga Health Insurance,https://www.saga.co.uk/health-insurance,N/A,N/A,United Kingdom,Private Medical Insurance,"Private hospital treatment, inpatient and day-patient treatment, outpatient consultations, tests...",People aged 50 and over,Official Company Website,https://www.saga.co.uk/contact-us/insurance/health-insurance
10,England,N/A,United Kingdom,Cigna Healthcare,https://www.cigna.co.uk/,N/A,N/A,United Kingdom and international,International Private Medical Insurance,"International medical insurance, inpatient and day-patient care, hospital treatment, specialist ...","Individuals, families, international students, workers, retirees, globally mobile employees and ...",Official Company Website,https://www.cigna.co.uk/
11,England,N/A,United Kingdom,Simplyhealth,https://www.simplyhealth.co.uk/,N/A,0370 908 3304,United Kingdom,Health Cash Plan / Health Insurance,"Dental care, optical care, physiotherapy, chiropractic care, podiatry, diagnostic consultations ...","Individuals, families, employees and businesses",Official Company Website,https://www.simplyhealth.co.uk/contact-us
12,England,N/A,United Kingdom,General & Medical,https://www.gminsure.com/,info@gminsure.com,0800 970 9442,United Kingdom,Private Medical Insurance,"Private medical treatment, hospital care, specialist consultations, diagnostics and healthcare s...","Individuals, families and businesses",Official Company Website,https://www.generalandmedical.com/contact-us/
13,England,N/A,United Kingdom,CS Healthcare,https://www.cshealthcare.co.uk/,N/A,N/A,United Kingdom,Private Healthcare / Health Insurance,"Private healthcare, consultations, diagnostic services, hospital treatment and healthcare support","Civil servants, public-sector employees, their families and eligible members",Official Company Website,https://www.cshealthcare.co.uk/contact-us/
14,Wales,N/A,United Kingdom,Aneurin Bevan University Health Board,https://abuhb.nhs.wales/,abb.engagement@wales.nhs.uk,01633 431890,Local – Southeast Wales,NHS Health Services,"Primary care, hospital care, community health services, mental health services, specialist healt...","Residents of Blaenau Gwent, Caerphilly, Monmouthshire, Newport and Torfaen",Official Organisation Website,https://abuhb.nhs.wales/about-us/engagement/community-engagement/contact-us/
15,Wales,N/A,United Kingdom,Betsi Cadwaladr University Health Board,https://bcuhb.nhs.wales/,N/A,N/A,Local – North Wales,NHS Health Services,"Primary care, hospital care, community health services, mental health services, specialist healt...",Residents of North Wales,Official Organisation Website,https://bcuhb.nhs.wales/contact-us/
16,Wales,N/A,United Kingdom,Cardiff and Vale University Health Board,https://cavuhb.nhs.wales/,Cav.Concerns@wales.nhs.uk,029 2183 6318,Local – Cardiff and Vale of Glamorgan,NHS Health Services,"Primary care, hospital care, community health services, mental health services, specialist healt...",Residents of Cardiff and the Vale of Glamorgan,Official Organisation Website,https://cavuhb.nhs.wales/contact-us/
17,Wales,N/A,United Kingdom,Cwm Taf Morgannwg University Health Board,https://ctmuhb.nhs.wales/,N/A,N/A,Local – Cwm Taf Morgannwg,NHS Health Services,"Primary care, hospital care, community health services, mental health services, specialist healt...","Residents of Bridgend, Merthyr Tydfil and Rhondda Cynon Taf",Official Organisation Website,https://ctmuhb.nhs.wales/contact-us/
18,Wales,N/A,United Kingdom,Hywel Dda University Health Board,https://hduhb.nhs.wales/,corporate.correspondence.hdd@wales.nhs.uk,01267 235151,Local – West Wales,NHS Health Services,"Primary care, hospital care, community health services, mental health services, cancer care, dia...","Residents of Carmarthenshire, Ceredigion, Pembrokeshire and parts of South Powys",Official Organisation Website,https://hduhb.nhs.wales/about-us/your-health-board/board-members/our-board-members/contact-board...
19,Wales,N/A,United Kingdom,Powys Teaching Health Board,https://pthb.nhs.wales/,N/A,01874 442071,Local – Powys,NHS Health Services,"Primary care, community hospitals, community health services, mental health services, therapy se...",Residents of Powys,Official Organisation Website,https://pthb.nhs.wales/use-of-site/freedom-of-information/
20,Wales,N/A,United Kingdom,Swansea Bay University Health Board,https://sbuhb.nhs.wales/,FOIA.Requests@wales.nhs.uk,01639 683344,Local – Swansea Bay,NHS Health Services,"Hospital care, primary care, community health services, mental health and learning disability se...",Residents of Neath Port Talbot and Swansea,Official Organisation Website,https://sbuhb.nhs.wales/about-us/contact-us/
21,Wales,N/A,United Kingdom,Public Health Wales NHS Trust,https://phw.nhs.wales/,N/A,029 2022 7744,National – Wales,Public Health Services,"Screening programmes, immunisations and vaccines, health data and surveillance, STI testing, dis...","People across Wales, including individuals, communities and public-sector organisations",Official Organisation Website,https://phw.nhs.wales/contact-us/
22,Wales,N/A,United Kingdom,Velindre University NHS Trust,https://velindre.nhs.wales/,N/A,N/A,National – Wales,Specialist NHS Healthcare,"Specialist cancer treatment, radiotherapy, systemic anti-cancer treatments, specialist palliativ...",Patients across Wales requiring specialist cancer and related services,Official Organisation Website,https://velindre.nhs.wales/contact-us/
23,Wales,N/A,United Kingdom,Welsh Ambulance Services University NHS Trust,https://ambulance.nhs.wales/,PECI.team@wales.nhs.uk,0300 723 9207,National – Wales,Emergency and Non-Emergency Ambulance Services,"Emergency ambulance services, non-emergency patient transport, emergency medical services and NH...",People across Wales requiring emergency or non-emergency ambulance services,Official Organisation Website,https://ambulance.nhs.wales/contact-us/
24,Wales,N/A,United Kingdom,Health Education and Improvement Wales,https://heiw.nhs.wales/,N/A,N/A,National – Wales,NHS Workforce Education and Training,"Workforce education, training, professional development, workforce planning and development for ...","Healthcare professionals, healthcare students and the NHS workforce in Wales",Official Organisation Website,https://heiw.nhs.wales/contact-us/
25,Wales,N/A,United Kingdom,Digital Health and Care Wales,https://dhcw.nhs.wales/,DHCW-Comms@wales.nhs.uk,02920 500500,National – Wales,Digital Health and Data Services,"National digital health systems, digital and data services, electronic health records, digital i...","NHS Wales organisations, healthcare professionals and the people who use NHS Wales services",Official Organisation Website,https://dhcw.nhs.wales/contact-us/

In [48]:
england_wales_df.to_excel(
    "England_Wales_Healthcare_Organisations.xlsx",
    index=False
)

print("Saved successfully!")

Saved successfully!

In [49]:
england_wales_df.shape

(26, 13)

In [50]:
nigeria_df = pd.DataFrame(columns=[
    "State",
    "Region",
    "Country",
    "Name",
    "Website",
    "Email",
    "Contact Number",
    "Coverage State",
    "Coverage Type",
    "Services Rendered",
    "Target Customers",
    "Source",
    "Source URL"
])

nigeria_df

Empty DataFrame
Columns: [State, Region, Country, Name, Website, Email, Contact Number, Coverage State, Coverage Type, Services Rendered, Target Customers, Source, Source URL]
Index: []

In [52]:
import requests
import pandas as pd
from io import StringIO

nhia_url = "https://www.nhia.gov.ng/hmo/"

response = requests.get(nhia_url, verify=False, timeout=30)

print(response.status_code)

tables = pd.read_html(StringIO(response.text))

print("Number of tables found:", len(tables))

for i, table in enumerate(tables):
    print("Table", i, table.shape)
    display(table.head())

C:\Users\user\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.nhia.gov.ng'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

200
Number of tables found: 1
Table 0 (94, 7)

,S/NO.,HMO,HMO ID,WEBSITES,Address,Email,Call Center Numbers
0,1,A&M HEALTHCARE TRUST LIMITED,102,Click here,"Plot U Bekaji Road, Opposite Bekaji Jumma'at Mosque, Jimeta, Yola, Adamawa State",info@amhmo.com,"08033646497, 09162788582, 08024143666"
1,2,AIICO MULTISHIELD NIGERIA LIMITED,6,Click here,"322, IKORODU ROAD, ANTHONY",info@aiicomultishield.com loshunniyi@aiicomultishield.com,O7026744353 O8056744353
2,3,ALLEANZA HEALTH MANAGEMENT LIMITED,111,Click here,"? 83B, Basheer Shittu Avenue, Magodo Estate, Phase 2, Shangisha, Lagos",info@alleanzahealth.com,O7036592835
3,4,ALLY HEALTHCARE LIMITED,119,NaN,"Suit C4 Plot 1196 Ndjamena Crescent, Wuse II, Abuja",allyhealthcarelimited@gmail.com,O8148808171
4,5,AMAN HEALTH MAINTENANCE ORGANIZATIONS,121,Click here,"? 1, M. M. Alkali Street, Off 442 Crescent, Citec Vilas Gwarinpa, Abuja",info@amanhmo.com,O8100588906

In [53]:
nigeria_hmo = tables[0].copy()

nigeria_hmo

,S/NO.,HMO,HMO ID,WEBSITES,Address,Email,Call Center Numbers
0,1,A&M HEALTHCARE TRUST LIMITED,102,Click here,"Plot U Bekaji Road, Opposite Bekaji Jumma'at Mosque, Jimeta, Yola, Adamawa State",info@amhmo.com,"08033646497, 09162788582, 08024143666"
1,2,AIICO MULTISHIELD NIGERIA LIMITED,6,Click here,"322, IKORODU ROAD, ANTHONY",info@aiicomultishield.com loshunniyi@aiicomultishield.com,O7026744353 O8056744353
2,3,ALLEANZA HEALTH MANAGEMENT LIMITED,111,Click here,"? 83B, Basheer Shittu Avenue, Magodo Estate, Phase 2, Shangisha, Lagos",info@alleanzahealth.com,O7036592835
3,4,ALLY HEALTHCARE LIMITED,119,NaN,"Suit C4 Plot 1196 Ndjamena Crescent, Wuse II, Abuja",allyhealthcarelimited@gmail.com,O8148808171
4,5,AMAN HEALTH MAINTENANCE ORGANIZATIONS,121,Click here,"? 1, M. M. Alkali Street, Off 442 Crescent, Citec Vilas Gwarinpa, Abuja",info@amanhmo.com,O8100588906
5,6,ANCHOR HMO INTERNATIONAL COMPANY LIMITED,76,Click here,GOLDCREST MALL BUILDING,info@anchorhmo.com,"O8031230306, O7058890062, O7080601192"
6,7,ASHMED INTEGRATED HEALTH SERVICES LTD.,89,Click here,"RE 013 ZUNGERU CLOSE BY BIMA ROAD NITEL QUARTERS, KADUNA",info@ashmedintegratedhealthservices.com,O7036035182
7,8,AVON HEALTHCARE LIMITED,63,Click here,"22B, GLOVER ROAD",info@avonhealthcare.com,"O8102659972, O7002779800"
8,9,AXA MANSARD HEALTH LIMITED,59,Click here,"177, IKORODU ROAD, ONIPANU, LAGOS",healthcare@axamansard.com,O700AXAMANSARD
9,10,BASTION HEALTH LIMITED,97,Click here,"UBN HOUSE NO 1 ADEOLA ODEKU STREET, VICTORIA ISLAND, LAGOS, ETI OSA, LAGOS, Nigeria",Naomiduku@bastionhmo.com,0802BASTIONHMO 08002278466
10,11,BONITAS HEALTH MAINTENANCE LIMITED,120,NaN,"No. 7 Birabi Street, GRA phase 1, Port Harcourt, Rivers State",info@bonitashmo.org,O9164113000
11,12,CENTURY MEDICAID SERVICES LIMITED,99,Click here,"36 OKOROJI STREET, D/LINE, PORT HARCOURT, PORT HARCOURT CITY LGA, RIVERS STATE, Nigeria","info@centurymedicaid.org, centurymedicaid@yahoo.com","08090235044, 09087000193, 09087000192"
12,13,CLEARLINE INTERNATIONAL LIMITED,3,Click here,"290, IKORODU ROAD, ANTHONY, LAGOS",info@clearlinehmo.net clearline_int@yahoo.com,"O8076490111, O8076490101, O14482520"
13,14,DEFENCE HEALTH MAINTENANCE LIMITED,22,Click here,"2 HAMINA CLOSE, ABUJA",info@dhmlnigeria.com,"O7037921025, 08069305886"
14,15,Delog Medical Services Ltd. (HMO),117,Click here,"? 369, Borno Way, Alagomeji, Yaba, Lagos",info@delogmedicalhmo.com,O8128300972
15,16,DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO,115,Click here,"2nd Floor, 34/36, Association Avenue, Ilupeju, Lagos",info@doheec.com,"O9069431050, O9078945165"
16,17,DOT HMO Ltd.,100,Click here,"MJS House, 366 Murtala Mohammed Way (Opposite Polaris Bank), Yaba, Lagos",support@dot.aihelp@dot.ai,07000368466 (calls) 08170369507 (WhatsApp Only)
17,18,FOUNTAIN HEALTHCARE LIMITED,94,Click here,"ALL SEASON PLACE, NO 74 ISHERI- OGUNNUSI ROAD, OJUDU-OMOLE, IKEJA LAGOS",info@fountainhealthcareng.com,"O700FOUNTAIN, O8077705100, O8077705200"
18,19,GNI HEALTHCARE LTD,60,Click here,"28, AFOLABI AINA STREET, OFF AWOLOWO WAY, IKEJA LAGOS",gnihealthcare@greatnigeriaplc.com,"08057752870, 08163290105 O7043051516, O7046251142"
19,20,GORAH HEALTHCARE LTD.,112,Click here,"? 322A, Ikorodu Road, Ikeja, Lagos",info@gorahhmo.com,"O8132783427, O7031870956"
20,21,GREENBAY HEALTHCARE SERVICES LIMITED,43,Click here,"9, ODUNUGA STREET, OFF OPEBI LINK ROAD,",info@greenbayhmo.com,O70047336229
21,22,GREENFIELD HEALTH MANAGEMENT LTD,78,Click here,"PLOT 14, MARKET GARDEN POCKET LAYOUT, BY ISIADINSO CLOSE, G",info@greenfieldhmo.com hodaccounts@greenfieldhmo.com ezealaelizabeth@greenfieldhmo.com,"O9091910003, O9091909993"
22,23,GROOMING HEALTH MANAGEMENT LIMITED,108,Click here,"No. 3, Tina Chris Street, Ejigbo, Lagos State",info@groominghm.com,"O7080631850, O9087966270"
23,24,HALLMARK HEALTH SERVICES LIMITED,96,Click here,"264 Ikorodu Road, Obanikoro, Lagos, Somolu Local Government Area, Lagos, Nigeria",info@hallmarkhmo.com,"08170920155, 09087792936, 08090918940"
24,25,HEALTH ASSUR LIMITED,87,Click here,"NO.1 RAMAT CRESCENT OGUDU GRA, KOSOFE, LAGOS.",info@healthassur.com,"01-3422321, 08026547348, 0700 HEALTH ASSUR (07004325427787)"
25,26,Health Partners Limited,35,Click here,NaN,hmo@healthpartnersng.org,"O8077140844, O8077140855, O8077140688"
26,27,HEALTHCARE INTERNATIONAL LIMITED,4,Click here,"308A, MURITALA MOHAMMED WAY, YABA",info@healthcare-ng.com,"O8052099069 (Abuja) O8052099099 (Lagos) O14489820, O8052099094"
27,28,HEALTHSPRING HMO,122,Click here,"? 1, Julius Nyerere Crescent, Asokoro, Abuja",info@healthspringhmo.com,"07047000591, 07047000590"
28,29,HYGEIA HMO LIMITED,1,Click here,"2ND FLOOR, BANK OF INDUSTRY BUILDING, 21/22 MARINA","hycare@hygeiahmo.com, nhisdesk@hygeiahmo.com","O70049434266, O14488300"
29,30,Infinite X2 Health Maintenance Services,113,Click here,"No. 13, Lafia Road, Adjacent Kaduna Golf Course, Kaduna State","Infinitex2health@gmail.com, info@infinitex2health.net",O7066026262
30,31,INTEGRATED HEALTHCARE,14,Click here,"19, JOS STREET, AREA 3 GARKI-ABUJA",info@integratedhealthcareltd.com,"O8051322662, O8146120236, O8097236759, O9020008294 SMS (and WhatsApp only: 08063206121) Lagos: 0..."
31,32,INTERNATIONAL HEALTH MGT. SERVICES,11,Click here,"IGI HOUSE, 3 GWAMI ST, WUSE ZONE 4,",info@ihmsnigeria.com,"O8085861299, O7041446622, O7004467466"
32,33,IVES MEDICARE,69,Click here,"4 MOJIDI STREET, OFF TOYIN STREET",info@ivesmedicare.com,"O8032639058, O9085187582, O8092165592"
33,34,KENNEDIA HMO LIMITED,109,Click here,"14B, Kingsley Emu Street, Lagos, Off Chris Onanuga, Lekki Phase 1",info@kennediahmo.com,"070030306060, 017002018, 09120351385"
34,35,LEADWAY HEALTH LIMITED,90,Click here,"121/123, FUNSHO WILLIAMS AVENUE, IPONRI, SURULERE, LAGOS.",healthcare@leadway.com,"O12801051, O8139862271"
35,36,LIFE WORTH MEDICARE LTD,79,Click here,"13A, BISHOP COKER ROUND ABOUT, ILUPEJU, LAGOS",info@lifeworthhmo.com,O8091111760
36,37,LIFESAVER HEALTHCARE LIMITED,118,NaN,"20B, Olutoye Crescent, Afra Estate, Off Adeniyi Jones Avenue, Ikeja, Lagos State",mb@lifesaverhealthcarehmo.com,O9123973551
37,38,MAAYOIT HEALTH CARE LIMITED,98,Click here,"MHL BUILDING OPPOSITE GSS, OLD JEBBA ROAD, ILORIN, KWARA STATE, P.O. BOX 5504, ILORIN, KWARA STA...",info@mayooithealth.org,"08058026841, 08174627100"
38,39,MARINA MEDICAL SERVICES HMO LIMITED,48,Click here,"24, MONTGOMERY ROAD, YABA-LAGOS.",info@marinamedicalhmo.ng,"O8144814021, O8182318170,O8022598259"
39,40,MARKFEMA NIGERIA LTD.,29,Click here,"4A GURARA STREET, IBRAHIM ABACHA ESTATE",info@markfema.com,"O8077456035, O8034935832"
40,41,MASSLIFE HEALTHCARE LIMITED,103,Click here,"I. T. F. House (4th Floor), No. 6, Adetokunbo Ademola Crescent, Wuse 2, Abuja",info@masslifehealthcare.com,"234(0)92918962, 234(0)9039887632"
41,42,MB & O HEALTHCARE SERVICES LIMITED,110,Click here,"30, Bassie Ogamba Street, Off Adeniran Ogunsanya Street, Surulere, Lagos",info@mbandohmo.com,O8139952126
42,43,MEDEXIA LIMITED,44,Click here,"221, IKORODU ROAD, ILUPEJU LAGOS.",okuribido@medexia.com,"O8134224609, O9051991430, O14537588"
43,44,MEDICARE ALLIANCE LIMITED,71,Click here,"SUITE 9-13, 2ND FLOOR, ADAMU FURA HOUSE",domahealthcare@gmail.com,O7065645662 O8063545370
44,45,MEDIPLAN HEALTHCARE LIMITED,5,Click here,"CAPITAL BUILDING, 332, IKORODU ROAD, IDI-IROKO BUS STOP, MAR",mediplan@mediplanhealthcare.com,"08159093838, 07084068760, 01-4485390, 07066401413, 09036058822"
45,46,METROHEALTH HMO LIMITED,77,Click here,"26, CATHOLIC MISSION STREET","info@metrohealthhmo.com, nogbodu@metrohealthhmo.com","O8090235478, O1-6310038"
46,47,NEM HEALTH LIMITED,116,Click here,"New House, 199 Ikorodu Road, Obanikoro, Lagos",info@nem-health.com,O20-13300150
47,48,NNPC-HMO LIMITED,86,Click here,NNPC PENSION FUND COMPLEX,nnpchmo@nnpcgroup.com,"08022200180 08097777689 08058866690 08036950614 O9-460-85500, O803-695-0614, O809-777-7689"
48,49,NONSUCH MEDICARE LIMITED,51,Click here,"PLOT 1, ABIMBOLA ESTATE LAFIA HOSPITAL COMPLEX, APATA-IBADAN",nonsuchmedicare@gmail.com,"O8078392043, O8078391607, O8097541194"
49,50,NOOR HEALTH LTD.,114,NaN,"? 168, Awolowo Road, Ikoyi, Lagos State. ? 170, Gbagada Express Way, Lagos State",info@noorhealth.ng,O9048485050
50,51,NOVO HEALTH AFRICA LIMITED,74,Click here,"PLOT 10A AKIOGUN ROAD, ONIRU LEKKI LAGOS STATE",info@novohealthafrica.org,"O9092139552, O7037602736, O9082914217"
51,52,OCEANIC HEALTH MANAGEMENT LIMITED,39,Click here,"PLOT 226, AWOLOWO ROAD IKOYI, LAGOS / NEXIM HOUSE CBD, ABUJA",hmo@oceanichealthng.com,"O16330300, O12806399,O8085897999"
52,53,PERAMARE HEALTH MANAGEMENT COMPANY LIMITED,105,Click here,"Hall 1, 6th Floor, Tsukunde House, Opposite World Trade Centre, CBD, Abuja",hmo@peramare.ng,O9128007005
53,54,PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED,88,Click here,"70B LANRE AWOLOKUN STREET, GBAGADA PHASE 2 GBAGADA KOSOFE, LAGOS.",info@philipshmo.net,016339122-3
54,55,POLICE HEALTH MAINTENANCE LIMITED,73,Click here,"517, SYLVESTER UGOR CRESCENT,",info@phlnigeria.com,"O8132529114, O8174210057, O90552293969"
55,56,PRECIOUS HEALTHCARE LIMITED,36,Click here,"8 LUNGI STREET, OFF CAIRO STREET WUSE 2,",info@precioushmo.com,O8067456841
56,57,PREPAID MEDICARE SERVICES LTD.,30,Click here,9A GANGES STREET OFF ALVAN IKOKU WAY,hr@prepaidmedicareng.com,"O8085927262, O8091116207, O8035777338, O8076688032"
57,58,PRINCETON HEALTH,17,Click here,"26 MOGAJI ARE ROAD, OPPOSITE VITAS BAKERY, RING ROAD",info@princetonhmo.net,"O8151205555, O81859555555, O9060005654, O9060005674, O7064489783"
58,59,PROHEALTH HMO LTD,57,Click here,"BASSAN PLAZA, BLOCK D, FIRST FLOOR, PLOT 759 INDEPENDENCE AV",info@prohealthhmo.com,O70776432584
59,60,REDCARE HEALTH SERVICES LIMITED,65,Click here,"22 COKER ROAD, OPPOSITE MAMACASS",info@redcarehmo.com,"012772020, 07700REDCARE"
60,61,REGENIX HEALTH CARE SERVICE LIMITED,64,Click here,"KIENI PLAZA, KLM 13MELFORD OKILO ROAD",info@regenixhealthcare.com admin@regenixhealthcare.com regehmoservices@gmail.com,"08148220185, 08029377719"
61,62,RELIANCE HMO LIMITED,92,Click here,"32 LANRE AWOLOKUN STREET GBAGADA PHASE 2, KOSOFE, LAGOS",hello@reliancehmo.com,"O70073542623, O17001580"
62,63,RODING HEALTHCARE LTD.,93,Click here,"NO. 4 MAKOLO ROAD, ADEKUNLE YABA, LAGOS","rodinghealthcare@gmail.com, info@rodingheatlhcareltd.com",O70 CALL RODING (O7002255763464)
63,64,RONSBERGER NIGERIA LTD.,10,Click here,"1, MAMBOLO STREET, WUSE ZONE 2, ABUJA.",info@ronsbergerhmo.org,"O8021811800 , O92902975, O8103247680, O92903430"
64,65,ROTHAUGE HEALTHCARE LIMITED,101,Click here,"16, BABATUNDE STREET, OFF OGUNLANA DRIVE, SURULERE, SURULERE LGA, LAGOS, Nigeria","info@rothaugehealth.com, directors@rothaugehealth.com","07060910825, 09080000134, 08159996670"
65,66,ROYAL HEALTH MAINTENANCE SERVICES LTD.,26,Click here,PLOT 271 IKENEGBU LAYOUT (FLORIDA BOOKSHOP BUILDING) OWERRI,royalhealthmaintenanceservices@yahoo.com,O8037956689
66,67,SALUS TRUST GTE,54,Click here,"7 FORCE ROAD, LAGOS ISLAND.",salustrustgte@yahoo.com,"O8052272587, O1-3428992"
67,68,SERAPH HMO LIMITED,107,Click here,"Kilometer 7, Gboko Road, Makurdi, Benue State",seraphnigltd@yahoo.com,O8061136674
68,69,SKYDA HEALTH LIMITED,104,Click here,"8A, Panama Street, off IBB Way Maitama, Abuja",skydahealthng@gmail.com,08037013715
69,70,SONGHAI HEALTH TRUST,13,Click here,"TSUKUNDA HOUSE SUITE B11, AND B12, PLOT 1446, CONSTITUTION A",info@songhaihealthtrust.com,O7000303030
70,71,SPRINGTIDE HEALTHCARE SERVICES LTD.,106,Click here,"Iriebe Street, D''line Port Harcourt, Rivers State",info@sprintidehmo.com,O8183099999
71,72,STERLING HEALTH MANAGED CARE SERVICES LIMITED,34,Click here,"VALLEY VIEW PLAZA, 99 OPEBI ROAD",info@sterlinghealth-mcs.com,"O7009110911, O7014184367"
72,73,SUNU HEALTH NIGERIA LIMITED,16,Click here,NO. 16 OBOKUN ST. ILUPEJU,"nigeria.health@sunu-group.com , info@mhshmo.com","070010008000, 08003425647"
73,74,SYNERGY WELLCARE MEDICAID LIMITED,91,Click here,"NO. 13 PRECISION SCHOOL ROAD, ODANI ELELENWO, PORT HARCOURT, OBIAKPO RIVERS STATE.","synergywellcare@gmail.com, info@synergywellcare.com","O8099992825, O8098862873, O9081777726,O9081888837"
74,75,TOTAL HEALTH TRUST LIMITED,2,Click here,"2, MARCONI ROAD, PALMGROOVE ESTATE, ILUPEJU",thtabuja@totalhealthtrust.com,O7080687600 O14482105
75,76,ULTIMATE HEALTH MANAGEMENT SERVICES LTD,61,Click here,"TSUKUNDA HOUSE, 4TH FLOOR, RIGHT WING, PLOT 1446.CONSTITUTIO",info@ultimatehealthhmo.com,"O70085846283, O8179948153"
76,77,UNITED COMPREHENSIVE HEALTH MANAGERS LTD.,23,Click here,PLOT C-1 RUMUOGBA RESIDENTIAL ESTATE,info@uchm.net unichm2013@gmail.com,"O8158393328, O7033683712"
77,78,UNITED HEALTHCARE INTERNATIONAL LIMITED,7,Click here,"UHI HOUSE, 7 JABA CLOSE OFF DUNUKOFIA ST, OPPOSITE FCDA MINI",info@unitedhealthcare-ng.com contact@unitedhealthcare_ng.com,O7088485894 O8164582835 O94611600
78,79,VENUS MEDICARE LTD,21,Click here,"PLOT 472, CADASTRAL ZONE A8, FORMER CHICKEN HOUSE. OPP. ASCO",info@venusmedicare.com,"O70033330000, O7046090877, O7046090878"
79,80,VERITAS HEALTHCARE LIMITED,24,Click here,"3RD FLOOR, UNITY KAPITAL BUILDING, PLOT 497, ABOGO LARGEMA S",info@vhcl.com.ng,07067880493 08137895669 08137967923 08082560543
80,81,WELL HEALTH NETWORK LIMITED,67,Click here,"15 IBUSA AVENUE, INDEPENDENT LAYOUT",info@wellhealthnetwork.com,O8086250004
81,82,WELLNESS HEALTH MANAGEMENT SERVICES LIMITED,41,Click here,"9, JOGUNOLA STREET, GBAGADA PHASE II, GBAGADA,",callcenter@wellnesshmo.com info@wellnesshmo.com,"O70093556377, O8098726196, O8184742564"
82,83,ZUMA HEALTH TRUST,28,Click here,"PLOT 856, OLU AWOTESU STREET, OFF IDRISS IBRAHIM CRESCENT, (",zumahmo28@gmail.com,"O7062236824, O9055958534, 08094872221,"
83,84,Healthnomics HMO PLC,123,Click here,"MDCAN National Secretariat, Stephen Keshi Street, Off 69 Road, 6th Avenue, Gwarinpa Estate, Abuja",info@healthnomicshmoplc.org,"07033112298, 08020703947"
84,85,HYSSOP Health International Limited (HMO),124,Click here,"217, Jakpa Road, By Okuisoko, Effurun, Warri, Delta State",info@hyssophmo.com,O8038630662
85,86,Hopewell Healthcare Management Ltd,125,Click here,"Suite A5, 1st Floor, Ocean Center, No. 3, Happiness Blessing Street, Opposite FCT Library, Gudu,...",hdimka@hopewellhealthcare.ng,O8066951910
86,87,Crown Jewel HMO Ltd.,126,NaN,"No, 17, Ahmadu Bello Way, Garki, Abuja",info@crownjewelhmo.com,+2348065598104
87,88,Smathealth Medicare Limited,127,Click here,"Smathealth Medicare Limited 12B, Ogunmodede Street, By Ikeja Medical Cebtre, Allen Avenue, Ikeja...",info@smarthealth.com,"08032343023, 08087651504"
88,89,Health Assur Limited,128,Click here,"1, Ramat Crescent, Ogudu GRA, Kosofe, Lagos State",info@healthassur.com,08035541657
89,90,Quest Medicare Limited,129,Click here,"Quest Building, 8, Oladimeji Alo Street, Lekki Phase 1, Lagos",emannuel.omoloye@questhmo.com,"07033581816, 08180004972"
90,91,Life Action Plus Ltd.,130,Click here,"st Floor, Nigeria Law Publications House, Jobi Fele Way, Centrasl Business District, Alausa, Ike...",info@lifeactionplus.com,07055023555
91,92,Zenor Healthcare Ltd.,131,NaN,"86, Ajayi Road, Off Aboaba Street, Ogba, Lagos",zenorhealthcare@gmail.com,08164638041
92,93,Aspire HMO Limited,132,Click here,"3, lover Road, Ikoyi, Lagos State",info@aspirehmo.com,07071495437
93,94,Mitera Health Limited,133,Click here,"Plot 8/10, Hortico Way, Off Command Road, Ikeja, Lagos",gbeminiyi.onabanjo@miterahealth.com,08033273747

In [54]:
nigeria_hmo.columns = [
    "S/NO.",
    "Name",
    "HMO ID",
    "Website",
    "Address",
    "Email",
    "Contact Number"
]

nigeria_hmo.head()

,S/NO.,Name,HMO ID,Website,Address,Email,Contact Number
0,1,A&M HEALTHCARE TRUST LIMITED,102,Click here,"Plot U Bekaji Road, Opposite Bekaji Jumma'at Mosque, Jimeta, Yola, Adamawa State",info@amhmo.com,"08033646497, 09162788582, 08024143666"
1,2,AIICO MULTISHIELD NIGERIA LIMITED,6,Click here,"322, IKORODU ROAD, ANTHONY",info@aiicomultishield.com loshunniyi@aiicomultishield.com,O7026744353 O8056744353
2,3,ALLEANZA HEALTH MANAGEMENT LIMITED,111,Click here,"? 83B, Basheer Shittu Avenue, Magodo Estate, Phase 2, Shangisha, Lagos",info@alleanzahealth.com,O7036592835
3,4,ALLY HEALTHCARE LIMITED,119,NaN,"Suit C4 Plot 1196 Ndjamena Crescent, Wuse II, Abuja",allyhealthcarelimited@gmail.com,O8148808171
4,5,AMAN HEALTH MAINTENANCE ORGANIZATIONS,121,Click here,"? 1, M. M. Alkali Street, Off 442 Crescent, Citec Vilas Gwarinpa, Abuja",info@amanhmo.com,O8100588906

In [55]:
nigeria_hmo["Country"] = "Nigeria"
nigeria_hmo["Source"] = "NHIA"
nigeria_hmo["Source URL"] = nhia_url

In [56]:
nigeria_hmo["State"] = "N/A"
nigeria_hmo["Region"] = "N/A"
nigeria_hmo["Coverage State"] = "N/A"
nigeria_hmo["Coverage Type"] = "N/A"
nigeria_hmo["Services Rendered"] = "N/A"
nigeria_hmo["Target Customers"] = "N/A"

In [57]:
import requests
from bs4 import BeautifulSoup

response = requests.get(nhia_url, verify=False, timeout=30)

soup = BeautifulSoup(response.text, "html.parser")

links = []

for a in soup.find_all("a"):
    text = a.get_text(strip=True)
    href = a.get("href")

    if text.lower() == "click here" and href:
        links.append(href)

print("Number of website links found:", len(links))

C:\Users\user\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.nhia.gov.ng'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Number of website links found: 88

In [58]:
links[:10]

['https://amhmo.com/',
 'https://www.aiicomultishield.com/',
 'https://alleanzahealth.com/individual-plans/',
 'https://amanhmo.com/home',
 'https://anchorhmo.com/',
 'https://ashmedintegratedhealthservices.com/',
 'https://www.avonhealthcare.com/',
 'https://www.axamansard.com/health/plans/',
 'https://bastionhmo.com/',
 'https://www.centurymedicaid.org/']

In [59]:
nigeria_hmo["Website"] = "N/A"

website_indices = nigeria_hmo.index[:len(links)]

nigeria_hmo.loc[website_indices, "Website"] = links

nigeria_hmo[["Name", "Website"]]

,Name,Website
0,A&M HEALTHCARE TRUST LIMITED,https://amhmo.com/
1,AIICO MULTISHIELD NIGERIA LIMITED,https://www.aiicomultishield.com/
2,ALLEANZA HEALTH MANAGEMENT LIMITED,https://alleanzahealth.com/individual-plans/
3,ALLY HEALTHCARE LIMITED,https://amanhmo.com/home
4,AMAN HEALTH MAINTENANCE ORGANIZATIONS,https://anchorhmo.com/
5,ANCHOR HMO INTERNATIONAL COMPANY LIMITED,https://ashmedintegratedhealthservices.com/
6,ASHMED INTEGRATED HEALTH SERVICES LTD.,https://www.avonhealthcare.com/
7,AVON HEALTHCARE LIMITED,https://www.axamansard.com/health/plans/
8,AXA MANSARD HEALTH LIMITED,https://bastionhmo.com/
9,BASTION HEALTH LIMITED,https://www.centurymedicaid.org/
10,BONITAS HEALTH MAINTENANCE LIMITED,https://clearlinehmo.com/
11,CENTURY MEDICAID SERVICES LIMITED,https://www.dhmlnigeria.com
12,CLEARLINE INTERNATIONAL LIMITED,https://delogmedicalhmo.com/
13,DEFENCE HEALTH MAINTENANCE LIMITED,https://doheec.com/
14,Delog Medical Services Ltd. (HMO),https://hmo.dot.ai/
15,DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO,https://fountainhealthcareng.com/office/
16,DOT HMO Ltd.,http://gnihealthcare.com/
17,FOUNTAIN HEALTHCARE LIMITED,https://gorahhmo.com/
18,GNI HEALTHCARE LTD,https://greenbayhmo.com/
19,GORAH HEALTHCARE LTD.,https://www.greenfieldhmo.com/
20,GREENBAY HEALTHCARE SERVICES LIMITED,http://www.groominghm.com/
21,GREENFIELD HEALTH MANAGEMENT LTD,https://hallmarkhmo.com/
22,GROOMING HEALTH MANAGEMENT LIMITED,https://www.healthassur.com/
23,HALLMARK HEALTH SERVICES LIMITED,https://healthpartnersng.org/
24,HEALTH ASSUR LIMITED,https://www.hcihealthcare.ng/
25,Health Partners Limited,https://healthspringhmo.com/
26,HEALTHCARE INTERNATIONAL LIMITED,https://hygeiahmo.com/
27,HEALTHSPRING HMO,"http://Infinitex2health@gmail.com,%20info@infinitex2health.net"
28,HYGEIA HMO LIMITED,https://integratedhealthcareltd.com/
29,Infinite X2 Health Maintenance Services,https://ihmsnigeria.com/
30,INTEGRATED HEALTHCARE,https://www.ivesmedicare.com/
31,INTERNATIONAL HEALTH MGT. SERVICES,https://kennediahmo.com/
32,IVES MEDICARE,https://leadwayhealth.com/
33,KENNEDIA HMO LIMITED,https://lifeworthhmo.com/
34,LEADWAY HEALTH LIMITED,https://maayoithealth.org/
35,LIFE WORTH MEDICARE LTD,https://marinamedicalhmo.ng/
36,LIFESAVER HEALTHCARE LIMITED,https://markfema.com/
37,MAAYOIT HEALTH CARE LIMITED,https://masslife.com.ng/
38,MARINA MEDICAL SERVICES HMO LIMITED,https://mbandohmo.com/
39,MARKFEMA NIGERIA LTD.,https://medexia.com/
40,MASSLIFE HEALTHCARE LIMITED,https://www.farepharm.com/hmo/143
41,MB & O HEALTHCARE SERVICES LIMITED,https://mediplanhealthcare.com/
42,MEDEXIA LIMITED,https://www.metrohealthhmo.com/
43,MEDICARE ALLIANCE LIMITED,https://nem-health.com/
44,MEDIPLAN HEALTHCARE LIMITED,https://nnpcgroup.com/contact
45,METROHEALTH HMO LIMITED,https://www.nonsuchhmo.com/
46,NEM HEALTH LIMITED,https://www.novohealthafrica.org/
47,NNPC-HMO LIMITED,https://www.oceanichealth.com/
48,NONSUCH MEDICARE LIMITED,https://peramarehmo.ng/
49,NOOR HEALTH LTD.,https://phillipshmo.net/
50,NOVO HEALTH AFRICA LIMITED,https://www.phmlnigeria.com/
51,OCEANIC HEALTH MANAGEMENT LIMITED,https://precioushmo.com/
52,PERAMARE HEALTH MANAGEMENT COMPANY LIMITED,https://prepaidmedicareng.com/
53,PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED,http://info@princetonhmo.net
54,POLICE HEALTH MAINTENANCE LIMITED,https://prohealthhmo.com/
55,PRECIOUS HEALTHCARE LIMITED,https://redcarehmo.com/contact-us/
56,PREPAID MEDICARE SERVICES LTD.,https://regenixhealthcare.com/
57,PRINCETON HEALTH,https://getreliancehealth.com/nigeria/
58,PROHEALTH HMO LTD,https://fountainhealthcareng.com/office/
59,REDCARE HEALTH SERVICES LIMITED,https://ronsbergerhmo.com/
60,REGENIX HEALTH CARE SERVICE LIMITED,https://rothaugehealth.com/
61,RELIANCE HMO LIMITED,http://www.royalhealthms.com/
62,RODING HEALTHCARE LTD.,https://salustrustng.com/
63,RONSBERGER NIGERIA LTD.,https://seraphhmo.com/
64,ROTHAUGE HEALTHCARE LIMITED,https://www.skydalink.com/
65,ROYAL HEALTH MAINTENANCE SERVICES LTD.,https://www.songhaihealthtrust.com/
66,SALUS TRUST GTE,https://springtidehmo.com/
67,SERAPH HMO LIMITED,http://www.sterlinghealthmcs.com/
68,SKYDA HEALTH LIMITED,http://nigeria.health@sunugroup.com.
69,SONGHAI HEALTH TRUST,https://synergywellcare.com/
70,SPRINGTIDE HEALTHCARE SERVICES LTD.,https://www.libertyhealth.net/nigeria/en/
71,STERLING HEALTH MANAGED CARE SERVICES LIMITED,https://ultimatehealthhmo.com/
72,SUNU HEALTH NIGERIA LIMITED,https://www.uchm.net/
73,SYNERGY WELLCARE MEDICAID LIMITED,https://unitedhealthcare-ng.com/
74,TOTAL HEALTH TRUST LIMITED,https://www.venusmedicare.com/
75,ULTIMATE HEALTH MANAGEMENT SERVICES LTD,https://veritashealthcareltd.com/
76,UNITED COMPREHENSIVE HEALTH MANAGERS LTD.,https://wellhealthnetwork.com/
77,UNITED HEALTHCARE INTERNATIONAL LIMITED,https://www.wellnesshealthcare.com.ng/
78,VENUS MEDICARE LTD,https://zumahealthtrust.ng/
79,VERITAS HEALTHCARE LIMITED,http://www.healthnomicshmoplc.org
80,WELL HEALTH NETWORK LIMITED,http://www.hyssophmo.com
81,WELLNESS HEALTH MANAGEMENT SERVICES LIMITED,http://www.hopewellhealthcare.ng
82,ZUMA HEALTH TRUST,http://www.smarthealth.com
83,Healthnomics HMO PLC,http://www.healthassur.com%20
84,HYSSOP Health International Limited (HMO),http://www.questhmo.com
85,Hopewell Healthcare Management Ltd,http://www.lifeactionplus.com
86,Crown Jewel HMO Ltd.,http://www.aspirehmo.com
87,Smathealth Medicare Limited,http://www.miterahealth.com
88,Health Assur Limited,N/A
89,Quest Medicare Limited,N/A
90,Life Action Plus Ltd.,N/A
91,Zenor Healthcare Ltd.,N/A
92,Aspire HMO Limited,N/A
93,Mitera Health Limited,N/A

In [60]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

response = requests.get(nhia_url, verify=False, timeout=30)
soup = BeautifulSoup(response.text, "html.parser")

rows = []

table = soup.find("table")

for tr in table.find_all("tr"):
    cells = tr.find_all(["td", "th"])

    if len(cells) >= 7:
        hmo_name = cells[1].get_text(" ", strip=True)

        link = cells[3].find("a")
        
        if link and link.get("href"):
            website = link.get("href")
        else:
            website = "N/A"

        rows.append([hmo_name, website])

website_df = pd.DataFrame(rows, columns=["Name", "Website"])

website_df

C:\Users\user\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.nhia.gov.ng'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

,Name,Website
0,HMO,N/A
1,A&M HEALTHCARE TRUST LIMITED,https://amhmo.com/
2,AIICO MULTISHIELD NIGERIA LIMITED,https://www.aiicomultishield.com/
3,ALLEANZA HEALTH MANAGEMENT LIMITED,https://alleanzahealth.com/individual-plans/
4,ALLY HEALTHCARE LIMITED,N/A
5,AMAN HEALTH MAINTENANCE ORGANIZATIONS,https://amanhmo.com/home
6,ANCHOR HMO INTERNATIONAL COMPANY LIMITED,https://anchorhmo.com/
7,ASHMED INTEGRATED HEALTH SERVICES LTD.,https://ashmedintegratedhealthservices.com/
8,AVON HEALTHCARE LIMITED,https://www.avonhealthcare.com/
9,AXA MANSARD HEALTH LIMITED,https://www.axamansard.com/health/plans/
10,BASTION HEALTH LIMITED,https://bastionhmo.com/
11,BONITAS HEALTH MAINTENANCE LIMITED,N/A
12,CENTURY MEDICAID SERVICES LIMITED,https://www.centurymedicaid.org/
13,CLEARLINE INTERNATIONAL LIMITED,https://clearlinehmo.com/
14,DEFENCE HEALTH MAINTENANCE LIMITED,https://www.dhmlnigeria.com
15,Delog Medical Services Ltd. (HMO),https://delogmedicalhmo.com/
16,DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO,https://doheec.com/
17,DOT HMO Ltd.,https://hmo.dot.ai/
18,FOUNTAIN HEALTHCARE LIMITED,https://fountainhealthcareng.com/office/
19,GNI HEALTHCARE LTD,http://gnihealthcare.com/
20,GORAH HEALTHCARE LTD.,https://gorahhmo.com/
21,GREENBAY HEALTHCARE SERVICES LIMITED,https://greenbayhmo.com/
22,GREENFIELD HEALTH MANAGEMENT LTD,https://www.greenfieldhmo.com/
23,GROOMING HEALTH MANAGEMENT LIMITED,http://www.groominghm.com/
24,HALLMARK HEALTH SERVICES LIMITED,https://hallmarkhmo.com/
25,HEALTH ASSUR LIMITED,https://www.healthassur.com/
26,Health Partners Limited,https://healthpartnersng.org/
27,HEALTHCARE INTERNATIONAL LIMITED,https://www.hcihealthcare.ng/
28,HEALTHSPRING HMO,https://healthspringhmo.com/
29,HYGEIA HMO LIMITED,https://hygeiahmo.com/
30,Infinite X2 Health Maintenance Services,"http://Infinitex2health@gmail.com,%20info@infinitex2health.net"
31,INTEGRATED HEALTHCARE,https://integratedhealthcareltd.com/
32,INTERNATIONAL HEALTH MGT. SERVICES,https://ihmsnigeria.com/
33,IVES MEDICARE,https://www.ivesmedicare.com/
34,KENNEDIA HMO LIMITED,https://kennediahmo.com/
35,LEADWAY HEALTH LIMITED,https://leadwayhealth.com/
36,LIFE WORTH MEDICARE LTD,https://lifeworthhmo.com/
37,LIFESAVER HEALTHCARE LIMITED,N/A
38,MAAYOIT HEALTH CARE LIMITED,https://maayoithealth.org/
39,MARINA MEDICAL SERVICES HMO LIMITED,https://marinamedicalhmo.ng/
40,MARKFEMA NIGERIA LTD.,https://markfema.com/
41,MASSLIFE HEALTHCARE LIMITED,https://masslife.com.ng/
42,MB & O HEALTHCARE SERVICES LIMITED,https://mbandohmo.com/
43,MEDEXIA LIMITED,https://medexia.com/
44,MEDICARE ALLIANCE LIMITED,https://www.farepharm.com/hmo/143
45,MEDIPLAN HEALTHCARE LIMITED,https://mediplanhealthcare.com/
46,METROHEALTH HMO LIMITED,https://www.metrohealthhmo.com/
47,NEM HEALTH LIMITED,https://nem-health.com/
48,NNPC-HMO LIMITED,https://nnpcgroup.com/contact
49,NONSUCH MEDICARE LIMITED,https://www.nonsuchhmo.com/
50,NOOR HEALTH LTD.,N/A
51,NOVO HEALTH AFRICA LIMITED,https://www.novohealthafrica.org/
52,OCEANIC HEALTH MANAGEMENT LIMITED,https://www.oceanichealth.com/
53,PERAMARE HEALTH MANAGEMENT COMPANY LIMITED,https://peramarehmo.ng/
54,PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED,https://phillipshmo.net/
55,POLICE HEALTH MAINTENANCE LIMITED,https://www.phmlnigeria.com/
56,PRECIOUS HEALTHCARE LIMITED,https://precioushmo.com/
57,PREPAID MEDICARE SERVICES LTD.,https://prepaidmedicareng.com/
58,PRINCETON HEALTH,http://info@princetonhmo.net
59,PROHEALTH HMO LTD,https://prohealthhmo.com/
60,REDCARE HEALTH SERVICES LIMITED,https://redcarehmo.com/contact-us/
61,REGENIX HEALTH CARE SERVICE LIMITED,https://regenixhealthcare.com/
62,RELIANCE HMO LIMITED,https://getreliancehealth.com/nigeria/
63,RODING HEALTHCARE LTD.,https://fountainhealthcareng.com/office/
64,RONSBERGER NIGERIA LTD.,https://ronsbergerhmo.com/
65,ROTHAUGE HEALTHCARE LIMITED,https://rothaugehealth.com/
66,ROYAL HEALTH MAINTENANCE SERVICES LTD.,http://www.royalhealthms.com/
67,SALUS TRUST GTE,https://salustrustng.com/
68,SERAPH HMO LIMITED,https://seraphhmo.com/
69,SKYDA HEALTH LIMITED,https://www.skydalink.com/
70,SONGHAI HEALTH TRUST,https://www.songhaihealthtrust.com/
71,SPRINGTIDE HEALTHCARE SERVICES LTD.,https://springtidehmo.com/
72,STERLING HEALTH MANAGED CARE SERVICES LIMITED,http://www.sterlinghealthmcs.com/
73,SUNU HEALTH NIGERIA LIMITED,http://nigeria.health@sunugroup.com.
74,SYNERGY WELLCARE MEDICAID LIMITED,https://synergywellcare.com/
75,TOTAL HEALTH TRUST LIMITED,https://www.libertyhealth.net/nigeria/en/
76,ULTIMATE HEALTH MANAGEMENT SERVICES LTD,https://ultimatehealthhmo.com/
77,UNITED COMPREHENSIVE HEALTH MANAGERS LTD.,https://www.uchm.net/
78,UNITED HEALTHCARE INTERNATIONAL LIMITED,https://unitedhealthcare-ng.com/
79,VENUS MEDICARE LTD,https://www.venusmedicare.com/
80,VERITAS HEALTHCARE LIMITED,https://veritashealthcareltd.com/
81,WELL HEALTH NETWORK LIMITED,https://wellhealthnetwork.com/
82,WELLNESS HEALTH MANAGEMENT SERVICES LIMITED,https://www.wellnesshealthcare.com.ng/
83,ZUMA HEALTH TRUST,https://zumahealthtrust.ng/
84,Healthnomics HMO PLC,http://www.healthnomicshmoplc.org
85,HYSSOP Health International Limited (HMO),http://www.hyssophmo.com
86,Hopewell Healthcare Management Ltd,http://www.hopewellhealthcare.ng
87,Crown Jewel HMO Ltd.,N/A
88,Smathealth Medicare Limited,http://www.smarthealth.com
89,Health Assur Limited,http://www.healthassur.com%20
90,Quest Medicare Limited,http://www.questhmo.com
91,Life Action Plus Ltd.,http://www.lifeactionplus.com
92,Zenor Healthcare Ltd.,N/A
93,Aspire HMO Limited,http://www.aspirehmo.com
94,Mitera Health Limited,http://www.miterahealth.com

In [61]:
print("Number of HMOs:", len(website_df))
print("Websites found:", (website_df["Website"] != "N/A").sum())

display(website_df.head(15))

Number of HMOs: 95
Websites found: 88

,Name,Website
0,HMO,N/A
1,A&M HEALTHCARE TRUST LIMITED,https://amhmo.com/
2,AIICO MULTISHIELD NIGERIA LIMITED,https://www.aiicomultishield.com/
3,ALLEANZA HEALTH MANAGEMENT LIMITED,https://alleanzahealth.com/individual-plans/
4,ALLY HEALTHCARE LIMITED,N/A
5,AMAN HEALTH MAINTENANCE ORGANIZATIONS,https://amanhmo.com/home
6,ANCHOR HMO INTERNATIONAL COMPANY LIMITED,https://anchorhmo.com/
7,ASHMED INTEGRATED HEALTH SERVICES LTD.,https://ashmedintegratedhealthservices.com/
8,AVON HEALTHCARE LIMITED,https://www.avonhealthcare.com/
9,AXA MANSARD HEALTH LIMITED,https://www.axamansard.com/health/plans/
10,BASTION HEALTH LIMITED,https://bastionhmo.com/
11,BONITAS HEALTH MAINTENANCE LIMITED,N/A
12,CENTURY MEDICAID SERVICES LIMITED,https://www.centurymedicaid.org/
13,CLEARLINE INTERNATIONAL LIMITED,https://clearlinehmo.com/
14,DEFENCE HEALTH MAINTENANCE LIMITED,https://www.dhmlnigeria.com

In [62]:
website_df = website_df[website_df["Name"] != "HMO"].reset_index(drop=True)

print("Number of HMOs:", len(website_df))
print("Websites found:", (website_df["Website"] != "N/A").sum())

display(website_df)

Number of HMOs: 94
Websites found: 88

,Name,Website
0,A&M HEALTHCARE TRUST LIMITED,https://amhmo.com/
1,AIICO MULTISHIELD NIGERIA LIMITED,https://www.aiicomultishield.com/
2,ALLEANZA HEALTH MANAGEMENT LIMITED,https://alleanzahealth.com/individual-plans/
3,ALLY HEALTHCARE LIMITED,N/A
4,AMAN HEALTH MAINTENANCE ORGANIZATIONS,https://amanhmo.com/home
5,ANCHOR HMO INTERNATIONAL COMPANY LIMITED,https://anchorhmo.com/
6,ASHMED INTEGRATED HEALTH SERVICES LTD.,https://ashmedintegratedhealthservices.com/
7,AVON HEALTHCARE LIMITED,https://www.avonhealthcare.com/
8,AXA MANSARD HEALTH LIMITED,https://www.axamansard.com/health/plans/
9,BASTION HEALTH LIMITED,https://bastionhmo.com/
10,BONITAS HEALTH MAINTENANCE LIMITED,N/A
11,CENTURY MEDICAID SERVICES LIMITED,https://www.centurymedicaid.org/
12,CLEARLINE INTERNATIONAL LIMITED,https://clearlinehmo.com/
13,DEFENCE HEALTH MAINTENANCE LIMITED,https://www.dhmlnigeria.com
14,Delog Medical Services Ltd. (HMO),https://delogmedicalhmo.com/
15,DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO,https://doheec.com/
16,DOT HMO Ltd.,https://hmo.dot.ai/
17,FOUNTAIN HEALTHCARE LIMITED,https://fountainhealthcareng.com/office/
18,GNI HEALTHCARE LTD,http://gnihealthcare.com/
19,GORAH HEALTHCARE LTD.,https://gorahhmo.com/
20,GREENBAY HEALTHCARE SERVICES LIMITED,https://greenbayhmo.com/
21,GREENFIELD HEALTH MANAGEMENT LTD,https://www.greenfieldhmo.com/
22,GROOMING HEALTH MANAGEMENT LIMITED,http://www.groominghm.com/
23,HALLMARK HEALTH SERVICES LIMITED,https://hallmarkhmo.com/
24,HEALTH ASSUR LIMITED,https://www.healthassur.com/
25,Health Partners Limited,https://healthpartnersng.org/
26,HEALTHCARE INTERNATIONAL LIMITED,https://www.hcihealthcare.ng/
27,HEALTHSPRING HMO,https://healthspringhmo.com/
28,HYGEIA HMO LIMITED,https://hygeiahmo.com/
29,Infinite X2 Health Maintenance Services,"http://Infinitex2health@gmail.com,%20info@infinitex2health.net"
30,INTEGRATED HEALTHCARE,https://integratedhealthcareltd.com/
31,INTERNATIONAL HEALTH MGT. SERVICES,https://ihmsnigeria.com/
32,IVES MEDICARE,https://www.ivesmedicare.com/
33,KENNEDIA HMO LIMITED,https://kennediahmo.com/
34,LEADWAY HEALTH LIMITED,https://leadwayhealth.com/
35,LIFE WORTH MEDICARE LTD,https://lifeworthhmo.com/
36,LIFESAVER HEALTHCARE LIMITED,N/A
37,MAAYOIT HEALTH CARE LIMITED,https://maayoithealth.org/
38,MARINA MEDICAL SERVICES HMO LIMITED,https://marinamedicalhmo.ng/
39,MARKFEMA NIGERIA LTD.,https://markfema.com/
40,MASSLIFE HEALTHCARE LIMITED,https://masslife.com.ng/
41,MB & O HEALTHCARE SERVICES LIMITED,https://mbandohmo.com/
42,MEDEXIA LIMITED,https://medexia.com/
43,MEDICARE ALLIANCE LIMITED,https://www.farepharm.com/hmo/143
44,MEDIPLAN HEALTHCARE LIMITED,https://mediplanhealthcare.com/
45,METROHEALTH HMO LIMITED,https://www.metrohealthhmo.com/
46,NEM HEALTH LIMITED,https://nem-health.com/
47,NNPC-HMO LIMITED,https://nnpcgroup.com/contact
48,NONSUCH MEDICARE LIMITED,https://www.nonsuchhmo.com/
49,NOOR HEALTH LTD.,N/A
50,NOVO HEALTH AFRICA LIMITED,https://www.novohealthafrica.org/
51,OCEANIC HEALTH MANAGEMENT LIMITED,https://www.oceanichealth.com/
52,PERAMARE HEALTH MANAGEMENT COMPANY LIMITED,https://peramarehmo.ng/
53,PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED,https://phillipshmo.net/
54,POLICE HEALTH MAINTENANCE LIMITED,https://www.phmlnigeria.com/
55,PRECIOUS HEALTHCARE LIMITED,https://precioushmo.com/
56,PREPAID MEDICARE SERVICES LTD.,https://prepaidmedicareng.com/
57,PRINCETON HEALTH,http://info@princetonhmo.net
58,PROHEALTH HMO LTD,https://prohealthhmo.com/
59,REDCARE HEALTH SERVICES LIMITED,https://redcarehmo.com/contact-us/
60,REGENIX HEALTH CARE SERVICE LIMITED,https://regenixhealthcare.com/
61,RELIANCE HMO LIMITED,https://getreliancehealth.com/nigeria/
62,RODING HEALTHCARE LTD.,https://fountainhealthcareng.com/office/
63,RONSBERGER NIGERIA LTD.,https://ronsbergerhmo.com/
64,ROTHAUGE HEALTHCARE LIMITED,https://rothaugehealth.com/
65,ROYAL HEALTH MAINTENANCE SERVICES LTD.,http://www.royalhealthms.com/
66,SALUS TRUST GTE,https://salustrustng.com/
67,SERAPH HMO LIMITED,https://seraphhmo.com/
68,SKYDA HEALTH LIMITED,https://www.skydalink.com/
69,SONGHAI HEALTH TRUST,https://www.songhaihealthtrust.com/
70,SPRINGTIDE HEALTHCARE SERVICES LTD.,https://springtidehmo.com/
71,STERLING HEALTH MANAGED CARE SERVICES LIMITED,http://www.sterlinghealthmcs.com/
72,SUNU HEALTH NIGERIA LIMITED,http://nigeria.health@sunugroup.com.
73,SYNERGY WELLCARE MEDICAID LIMITED,https://synergywellcare.com/
74,TOTAL HEALTH TRUST LIMITED,https://www.libertyhealth.net/nigeria/en/
75,ULTIMATE HEALTH MANAGEMENT SERVICES LTD,https://ultimatehealthhmo.com/
76,UNITED COMPREHENSIVE HEALTH MANAGERS LTD.,https://www.uchm.net/
77,UNITED HEALTHCARE INTERNATIONAL LIMITED,https://unitedhealthcare-ng.com/
78,VENUS MEDICARE LTD,https://www.venusmedicare.com/
79,VERITAS HEALTHCARE LIMITED,https://veritashealthcareltd.com/
80,WELL HEALTH NETWORK LIMITED,https://wellhealthnetwork.com/
81,WELLNESS HEALTH MANAGEMENT SERVICES LIMITED,https://www.wellnesshealthcare.com.ng/
82,ZUMA HEALTH TRUST,https://zumahealthtrust.ng/
83,Healthnomics HMO PLC,http://www.healthnomicshmoplc.org
84,HYSSOP Health International Limited (HMO),http://www.hyssophmo.com
85,Hopewell Healthcare Management Ltd,http://www.hopewellhealthcare.ng
86,Crown Jewel HMO Ltd.,N/A
87,Smathealth Medicare Limited,http://www.smarthealth.com
88,Health Assur Limited,http://www.healthassur.com%20
89,Quest Medicare Limited,http://www.questhmo.com
90,Life Action Plus Ltd.,http://www.lifeactionplus.com
91,Zenor Healthcare Ltd.,N/A
92,Aspire HMO Limited,http://www.aspirehmo.com
93,Mitera Health Limited,http://www.miterahealth.com

In [63]:
# Check the number of HMOs
print("Number of HMOs:", len(nigeria_hmo))

# Check for duplicate names
print("Duplicate names:", nigeria_hmo["Name"].duplicated().sum())

# Show the full list
pd.set_option("display.max_rows", None)
pd.set_option("display.max_colwidth", None)

nigeria_hmo[["Name", "Website"]]

Number of HMOs: 94
Duplicate names: 0

,Name,Website
0,A&M HEALTHCARE TRUST LIMITED,https://amhmo.com/
1,AIICO MULTISHIELD NIGERIA LIMITED,https://www.aiicomultishield.com/
2,ALLEANZA HEALTH MANAGEMENT LIMITED,https://alleanzahealth.com/individual-plans/
3,ALLY HEALTHCARE LIMITED,https://amanhmo.com/home
4,AMAN HEALTH MAINTENANCE ORGANIZATIONS,https://anchorhmo.com/
5,ANCHOR HMO INTERNATIONAL COMPANY LIMITED,https://ashmedintegratedhealthservices.com/
6,ASHMED INTEGRATED HEALTH SERVICES LTD.,https://www.avonhealthcare.com/
7,AVON HEALTHCARE LIMITED,https://www.axamansard.com/health/plans/
8,AXA MANSARD HEALTH LIMITED,https://bastionhmo.com/
9,BASTION HEALTH LIMITED,https://www.centurymedicaid.org/
10,BONITAS HEALTH MAINTENANCE LIMITED,https://clearlinehmo.com/
11,CENTURY MEDICAID SERVICES LIMITED,https://www.dhmlnigeria.com
12,CLEARLINE INTERNATIONAL LIMITED,https://delogmedicalhmo.com/
13,DEFENCE HEALTH MAINTENANCE LIMITED,https://doheec.com/
14,Delog Medical Services Ltd. (HMO),https://hmo.dot.ai/
15,DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO,https://fountainhealthcareng.com/office/
16,DOT HMO Ltd.,http://gnihealthcare.com/
17,FOUNTAIN HEALTHCARE LIMITED,https://gorahhmo.com/
18,GNI HEALTHCARE LTD,https://greenbayhmo.com/
19,GORAH HEALTHCARE LTD.,https://www.greenfieldhmo.com/
20,GREENBAY HEALTHCARE SERVICES LIMITED,http://www.groominghm.com/
21,GREENFIELD HEALTH MANAGEMENT LTD,https://hallmarkhmo.com/
22,GROOMING HEALTH MANAGEMENT LIMITED,https://www.healthassur.com/
23,HALLMARK HEALTH SERVICES LIMITED,https://healthpartnersng.org/
24,HEALTH ASSUR LIMITED,https://www.hcihealthcare.ng/
25,Health Partners Limited,https://healthspringhmo.com/
26,HEALTHCARE INTERNATIONAL LIMITED,https://hygeiahmo.com/
27,HEALTHSPRING HMO,"http://Infinitex2health@gmail.com,%20info@infinitex2health.net"
28,HYGEIA HMO LIMITED,https://integratedhealthcareltd.com/
29,Infinite X2 Health Maintenance Services,https://ihmsnigeria.com/
30,INTEGRATED HEALTHCARE,https://www.ivesmedicare.com/
31,INTERNATIONAL HEALTH MGT. SERVICES,https://kennediahmo.com/
32,IVES MEDICARE,https://leadwayhealth.com/
33,KENNEDIA HMO LIMITED,https://lifeworthhmo.com/
34,LEADWAY HEALTH LIMITED,https://maayoithealth.org/
35,LIFE WORTH MEDICARE LTD,https://marinamedicalhmo.ng/
36,LIFESAVER HEALTHCARE LIMITED,https://markfema.com/
37,MAAYOIT HEALTH CARE LIMITED,https://masslife.com.ng/
38,MARINA MEDICAL SERVICES HMO LIMITED,https://mbandohmo.com/
39,MARKFEMA NIGERIA LTD.,https://medexia.com/
40,MASSLIFE HEALTHCARE LIMITED,https://www.farepharm.com/hmo/143
41,MB & O HEALTHCARE SERVICES LIMITED,https://mediplanhealthcare.com/
42,MEDEXIA LIMITED,https://www.metrohealthhmo.com/
43,MEDICARE ALLIANCE LIMITED,https://nem-health.com/
44,MEDIPLAN HEALTHCARE LIMITED,https://nnpcgroup.com/contact
45,METROHEALTH HMO LIMITED,https://www.nonsuchhmo.com/
46,NEM HEALTH LIMITED,https://www.novohealthafrica.org/
47,NNPC-HMO LIMITED,https://www.oceanichealth.com/
48,NONSUCH MEDICARE LIMITED,https://peramarehmo.ng/
49,NOOR HEALTH LTD.,https://phillipshmo.net/
50,NOVO HEALTH AFRICA LIMITED,https://www.phmlnigeria.com/
51,OCEANIC HEALTH MANAGEMENT LIMITED,https://precioushmo.com/
52,PERAMARE HEALTH MANAGEMENT COMPANY LIMITED,https://prepaidmedicareng.com/
53,PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED,http://info@princetonhmo.net
54,POLICE HEALTH MAINTENANCE LIMITED,https://prohealthhmo.com/
55,PRECIOUS HEALTHCARE LIMITED,https://redcarehmo.com/contact-us/
56,PREPAID MEDICARE SERVICES LTD.,https://regenixhealthcare.com/
57,PRINCETON HEALTH,https://getreliancehealth.com/nigeria/
58,PROHEALTH HMO LTD,https://fountainhealthcareng.com/office/
59,REDCARE HEALTH SERVICES LIMITED,https://ronsbergerhmo.com/
60,REGENIX HEALTH CARE SERVICE LIMITED,https://rothaugehealth.com/
61,RELIANCE HMO LIMITED,http://www.royalhealthms.com/
62,RODING HEALTHCARE LTD.,https://salustrustng.com/
63,RONSBERGER NIGERIA LTD.,https://seraphhmo.com/
64,ROTHAUGE HEALTHCARE LIMITED,https://www.skydalink.com/
65,ROYAL HEALTH MAINTENANCE SERVICES LTD.,https://www.songhaihealthtrust.com/
66,SALUS TRUST GTE,https://springtidehmo.com/
67,SERAPH HMO LIMITED,http://www.sterlinghealthmcs.com/
68,SKYDA HEALTH LIMITED,http://nigeria.health@sunugroup.com.
69,SONGHAI HEALTH TRUST,https://synergywellcare.com/
70,SPRINGTIDE HEALTHCARE SERVICES LTD.,https://www.libertyhealth.net/nigeria/en/
71,STERLING HEALTH MANAGED CARE SERVICES LIMITED,https://ultimatehealthhmo.com/
72,SUNU HEALTH NIGERIA LIMITED,https://www.uchm.net/
73,SYNERGY WELLCARE MEDICAID LIMITED,https://unitedhealthcare-ng.com/
74,TOTAL HEALTH TRUST LIMITED,https://www.venusmedicare.com/
75,ULTIMATE HEALTH MANAGEMENT SERVICES LTD,https://veritashealthcareltd.com/
76,UNITED COMPREHENSIVE HEALTH MANAGERS LTD.,https://wellhealthnetwork.com/
77,UNITED HEALTHCARE INTERNATIONAL LIMITED,https://www.wellnesshealthcare.com.ng/
78,VENUS MEDICARE LTD,https://zumahealthtrust.ng/
79,VERITAS HEALTHCARE LIMITED,http://www.healthnomicshmoplc.org
80,WELL HEALTH NETWORK LIMITED,http://www.hyssophmo.com
81,WELLNESS HEALTH MANAGEMENT SERVICES LIMITED,http://www.hopewellhealthcare.ng
82,ZUMA HEALTH TRUST,http://www.smarthealth.com
83,Healthnomics HMO PLC,http://www.healthassur.com%20
84,HYSSOP Health International Limited (HMO),http://www.questhmo.com
85,Hopewell Healthcare Management Ltd,http://www.lifeactionplus.com
86,Crown Jewel HMO Ltd.,http://www.aspirehmo.com
87,Smathealth Medicare Limited,http://www.miterahealth.com
88,Health Assur Limited,N/A
89,Quest Medicare Limited,N/A
90,Life Action Plus Ltd.,N/A
91,Zenor Healthcare Ltd.,N/A
92,Aspire HMO Limited,N/A
93,Mitera Health Limited,N/A

In [64]:
nigeria_hmo[nigeria_hmo["Website"].str.contains(
    "Infinitex2|princeton|fountainhealthcareng|farepharm|nnpcgroup|libertyhealth|sunugroup",
    case=False,
    na=False
)][["Name", "Website"]]

,Name,Website
15,DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO,https://fountainhealthcareng.com/office/
27,HEALTHSPRING HMO,"http://Infinitex2health@gmail.com,%20info@infinitex2health.net"
40,MASSLIFE HEALTHCARE LIMITED,https://www.farepharm.com/hmo/143
44,MEDIPLAN HEALTHCARE LIMITED,https://nnpcgroup.com/contact
53,PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED,http://info@princetonhmo.net
58,PROHEALTH HMO LTD,https://fountainhealthcareng.com/office/
68,SKYDA HEALTH LIMITED,http://nigeria.health@sunugroup.com.
70,SPRINGTIDE HEALTHCARE SERVICES LTD.,https://www.libertyhealth.net/nigeria/en/

In [65]:
website_corrections = {
    "HEALTHSPRING HMO": "https://healthspringhmo.com/",
    "MASSLIFE HEALTHCARE LIMITED": "https://masslife.com.ng/",
    "MEDIPLAN HEALTHCARE LIMITED": "https://mediplanhealthcare.com/",
    "PROHEALTH HMO LTD": "https://www.prohealthhmo.com/"
}

for company, website in website_corrections.items():
    nigeria_hmo.loc[
        nigeria_hmo["Name"] == company, "Website"
    ] = website

nigeria_hmo[nigeria_hmo["Name"].isin(website_corrections.keys())][
    ["Name", "Website"]
]

                           Name                          Website
27             HEALTHSPRING HMO     https://healthspringhmo.com/
40  MASSLIFE HEALTHCARE LIMITED         https://masslife.com.ng/
44  MEDIPLAN HEALTHCARE LIMITED  https://mediplanhealthcare.com/
58            PROHEALTH HMO LTD    https://www.prohealthhmo.com/

In [66]:
website_corrections = {
    "HEALTHSPRING HMO": "https://healthspringhmo.com/",
    "MASSLIFE HEALTHCARE LIMITED": "https://masslife.com.ng/",
    "MEDIPLAN HEALTHCARE LIMITED": "https://mediplanhealthcare.com/",
    "PROHEALTH HMO LTD": "https://www.prohealthhmo.com/",
    "PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED": "https://phillipshmo.net/",
    "SKYDA HEALTH LIMITED": "https://skydalink.com/",
    "SPRINGTIDE HEALTHCARE SERVICES LTD.": "https://springtidehmo.com/"
}

for company, website in website_corrections.items():
    nigeria_hmo.loc[
        nigeria_hmo["Name"] == company, "Website"
    ] = website
    
nigeria_hmo.loc[
    nigeria_hmo["Name"] == "DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO",
    "Website"
] = "N/A"

nigeria_hmo[nigeria_hmo["Name"].isin(
    list(website_corrections.keys()) +
    ["DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO"]
)][["Name", "Website"]]

,Name,Website
15,DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO,N/A
27,HEALTHSPRING HMO,https://healthspringhmo.com/
40,MASSLIFE HEALTHCARE LIMITED,https://masslife.com.ng/
44,MEDIPLAN HEALTHCARE LIMITED,https://mediplanhealthcare.com/
53,PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED,https://phillipshmo.net/
58,PROHEALTH HMO LTD,https://www.prohealthhmo.com/
68,SKYDA HEALTH LIMITED,https://skydalink.com/
70,SPRINGTIDE HEALTHCARE SERVICES LTD.,https://springtidehmo.com/

In [67]:
nigeria_hmo.columns

Index(['S/NO.', 'Name', 'HMO ID', 'Website', 'Address', 'Email',
       'Contact Number', 'Country', 'Source', 'Source URL', 'State', 'Region',
       'Coverage State', 'Coverage Type', 'Services Rendered',
       'Target Customers'],
      dtype='object')

In [68]:
nigeria_hmo.head()

,S/NO.,Name,HMO ID,Website,Address,Email,Contact Number,Country,Source,Source URL,State,Region,Coverage State,Coverage Type,Services Rendered,Target Customers
0,1,A&M HEALTHCARE TRUST LIMITED,102,https://amhmo.com/,"Plot U Bekaji Road, Opposite Bekaji Jumma'at Mosque, Jimeta, Yola, Adamawa State",info@amhmo.com,"08033646497, 09162788582, 08024143666",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,N/A,N/A,N/A,N/A,N/A,N/A
1,2,AIICO MULTISHIELD NIGERIA LIMITED,6,https://www.aiicomultishield.com/,"322, IKORODU ROAD, ANTHONY",info@aiicomultishield.com loshunniyi@aiicomultishield.com,O7026744353 O8056744353,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,N/A,N/A,N/A,N/A,N/A,N/A
2,3,ALLEANZA HEALTH MANAGEMENT LIMITED,111,https://alleanzahealth.com/individual-plans/,"? 83B, Basheer Shittu Avenue, Magodo Estate, Phase 2, Shangisha, Lagos",info@alleanzahealth.com,O7036592835,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,N/A,N/A,N/A,N/A,N/A,N/A
3,4,ALLY HEALTHCARE LIMITED,119,https://amanhmo.com/home,"Suit C4 Plot 1196 Ndjamena Crescent, Wuse II, Abuja",allyhealthcarelimited@gmail.com,O8148808171,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,N/A,N/A,N/A,N/A,N/A,N/A
4,5,AMAN HEALTH MAINTENANCE ORGANIZATIONS,121,https://anchorhmo.com/,"? 1, M. M. Alkali Street, Off 442 Crescent, Citec Vilas Gwarinpa, Abuja",info@amanhmo.com,O8100588906,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,N/A,N/A,N/A,N/A,N/A,N/A

In [69]:
nigeria_hmo["Contact Number"] = (
    nigeria_hmo["Contact Number"]
    .astype(str)
    .str.replace("O", "0", regex=False)
)

In [70]:
nigeria_hmo[["Name", "Email", "Contact Number"]].head(10)

,Name,Email,Contact Number
0,A&M HEALTHCARE TRUST LIMITED,info@amhmo.com,"08033646497, 09162788582, 08024143666"
1,AIICO MULTISHIELD NIGERIA LIMITED,info@aiicomultishield.com loshunniyi@aiicomultishield.com,07026744353 08056744353
2,ALLEANZA HEALTH MANAGEMENT LIMITED,info@alleanzahealth.com,07036592835
3,ALLY HEALTHCARE LIMITED,allyhealthcarelimited@gmail.com,08148808171
4,AMAN HEALTH MAINTENANCE ORGANIZATIONS,info@amanhmo.com,08100588906
5,ANCHOR HMO INTERNATIONAL COMPANY LIMITED,info@anchorhmo.com,"08031230306, 07058890062, 07080601192"
6,ASHMED INTEGRATED HEALTH SERVICES LTD.,info@ashmedintegratedhealthservices.com,07036035182
7,AVON HEALTHCARE LIMITED,info@avonhealthcare.com,"08102659972, 07002779800"
8,AXA MANSARD HEALTH LIMITED,healthcare@axamansard.com,0700AXAMANSARD
9,BASTION HEALTH LIMITED,Naomiduku@bastionhmo.com,0802BASTI0NHM0 08002278466

In [71]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_colwidth", None)

nigeria_hmo[["Name", "Address"]]

,Name,Address
0,A&M HEALTHCARE TRUST LIMITED,"Plot U Bekaji Road, Opposite Bekaji Jumma'at Mosque, Jimeta, Yola, Adamawa State"
1,AIICO MULTISHIELD NIGERIA LIMITED,"322, IKORODU ROAD, ANTHONY"
2,ALLEANZA HEALTH MANAGEMENT LIMITED,"? 83B, Basheer Shittu Avenue, Magodo Estate, Phase 2, Shangisha, Lagos"
3,ALLY HEALTHCARE LIMITED,"Suit C4 Plot 1196 Ndjamena Crescent, Wuse II, Abuja"
4,AMAN HEALTH MAINTENANCE ORGANIZATIONS,"? 1, M. M. Alkali Street, Off 442 Crescent, Citec Vilas Gwarinpa, Abuja"
5,ANCHOR HMO INTERNATIONAL COMPANY LIMITED,GOLDCREST MALL BUILDING
6,ASHMED INTEGRATED HEALTH SERVICES LTD.,"RE 013 ZUNGERU CLOSE BY BIMA ROAD NITEL QUARTERS, KADUNA"
7,AVON HEALTHCARE LIMITED,"22B, GLOVER ROAD"
8,AXA MANSARD HEALTH LIMITED,"177, IKORODU ROAD, ONIPANU, LAGOS"
9,BASTION HEALTH LIMITED,"UBN HOUSE NO 1 ADEOLA ODEKU STREET, VICTORIA ISLAND, LAGOS, ETI OSA, LAGOS, Nigeria"
10,BONITAS HEALTH MAINTENANCE LIMITED,"No. 7 Birabi Street, GRA phase 1, Port Harcourt, Rivers State"
11,CENTURY MEDICAID SERVICES LIMITED,"36 OKOROJI STREET, D/LINE, PORT HARCOURT, PORT HARCOURT CITY LGA, RIVERS STATE, Nigeria"
12,CLEARLINE INTERNATIONAL LIMITED,"290, IKORODU ROAD, ANTHONY, LAGOS"
13,DEFENCE HEALTH MAINTENANCE LIMITED,"2 HAMINA CLOSE, ABUJA"
14,Delog Medical Services Ltd. (HMO),"? 369, Borno Way, Alagomeji, Yaba, Lagos"
15,DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO,"2nd Floor, 34/36, Association Avenue, Ilupeju, Lagos"
16,DOT HMO Ltd.,"MJS House, 366 Murtala Mohammed Way (Opposite Polaris Bank), Yaba, Lagos"
17,FOUNTAIN HEALTHCARE LIMITED,"ALL SEASON PLACE, NO 74 ISHERI- OGUNNUSI ROAD, OJUDU-OMOLE, IKEJA LAGOS"
18,GNI HEALTHCARE LTD,"28, AFOLABI AINA STREET, OFF AWOLOWO WAY, IKEJA LAGOS"
19,GORAH HEALTHCARE LTD.,"? 322A, Ikorodu Road, Ikeja, Lagos"
20,GREENBAY HEALTHCARE SERVICES LIMITED,"9, ODUNUGA STREET, OFF OPEBI LINK ROAD,"
21,GREENFIELD HEALTH MANAGEMENT LTD,"PLOT 14, MARKET GARDEN POCKET LAYOUT, BY ISIADINSO CLOSE, G"
22,GROOMING HEALTH MANAGEMENT LIMITED,"No. 3, Tina Chris Street, Ejigbo, Lagos State"
23,HALLMARK HEALTH SERVICES LIMITED,"264 Ikorodu Road, Obanikoro, Lagos, Somolu Local Government Area, Lagos, Nigeria"
24,HEALTH ASSUR LIMITED,"NO.1 RAMAT CRESCENT OGUDU GRA, KOSOFE, LAGOS."
25,Health Partners Limited,NaN
26,HEALTHCARE INTERNATIONAL LIMITED,"308A, MURITALA MOHAMMED WAY, YABA"
27,HEALTHSPRING HMO,"? 1, Julius Nyerere Crescent, Asokoro, Abuja"
28,HYGEIA HMO LIMITED,"2ND FLOOR, BANK OF INDUSTRY BUILDING, 21/22 MARINA"
29,Infinite X2 Health Maintenance Services,"No. 13, Lafia Road, Adjacent Kaduna Golf Course, Kaduna State"
30,INTEGRATED HEALTHCARE,"19, JOS STREET, AREA 3 GARKI-ABUJA"
31,INTERNATIONAL HEALTH MGT. SERVICES,"IGI HOUSE, 3 GWAMI ST, WUSE ZONE 4,"
32,IVES MEDICARE,"4 MOJIDI STREET, OFF TOYIN STREET"
33,KENNEDIA HMO LIMITED,"14B, Kingsley Emu Street, Lagos, Off Chris Onanuga, Lekki Phase 1"
34,LEADWAY HEALTH LIMITED,"121/123, FUNSHO WILLIAMS AVENUE, IPONRI, SURULERE, LAGOS."
35,LIFE WORTH MEDICARE LTD,"13A, BISHOP COKER ROUND ABOUT, ILUPEJU, LAGOS"
36,LIFESAVER HEALTHCARE LIMITED,"20B, Olutoye Crescent, Afra Estate, Off Adeniyi Jones Avenue, Ikeja, Lagos State"
37,MAAYOIT HEALTH CARE LIMITED,"MHL BUILDING OPPOSITE GSS, OLD JEBBA ROAD, ILORIN, KWARA STATE, P.O. BOX 5504, ILORIN, KWARA STATE, ILORIN, ILORIN WEST, KWARA, Nigeria"
38,MARINA MEDICAL SERVICES HMO LIMITED,"24, MONTGOMERY ROAD, YABA-LAGOS."
39,MARKFEMA NIGERIA LTD.,"4A GURARA STREET, IBRAHIM ABACHA ESTATE"
40,MASSLIFE HEALTHCARE LIMITED,"I. T. F. House (4th Floor), No. 6, Adetokunbo Ademola Crescent, Wuse 2, Abuja"
41,MB & O HEALTHCARE SERVICES LIMITED,"30, Bassie Ogamba Street, Off Adeniran Ogunsanya Street, Surulere, Lagos"
42,MEDEXIA LIMITED,"221, IKORODU ROAD, ILUPEJU LAGOS."
43,MEDICARE ALLIANCE LIMITED,"SUITE 9-13, 2ND FLOOR, ADAMU FURA HOUSE"
44,MEDIPLAN HEALTHCARE LIMITED,"CAPITAL BUILDING, 332, IKORODU ROAD, IDI-IROKO BUS STOP, MAR"
45,METROHEALTH HMO LIMITED,"26, CATHOLIC MISSION STREET"
46,NEM HEALTH LIMITED,"New House, 199 Ikorodu Road, Obanikoro, Lagos"
47,NNPC-HMO LIMITED,NNPC PENSION FUND COMPLEX
48,NONSUCH MEDICARE LIMITED,"PLOT 1, ABIMBOLA ESTATE LAFIA HOSPITAL COMPLEX, APATA-IBADAN"
49,NOOR HEALTH LTD.,"? 168, Awolowo Road, Ikoyi, Lagos State. ? 170, Gbagada Express Way, Lagos State"
50,NOVO HEALTH AFRICA LIMITED,"PLOT 10A AKIOGUN ROAD, ONIRU LEKKI LAGOS STATE"
51,OCEANIC HEALTH MANAGEMENT LIMITED,"PLOT 226, AWOLOWO ROAD IKOYI, LAGOS / NEXIM HOUSE CBD, ABUJA"
52,PERAMARE HEALTH MANAGEMENT COMPANY LIMITED,"Hall 1, 6th Floor, Tsukunde House, Opposite World Trade Centre, CBD, Abuja"
53,PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED,"70B LANRE AWOLOKUN STREET, GBAGADA PHASE 2 GBAGADA KOSOFE, LAGOS."
54,POLICE HEALTH MAINTENANCE LIMITED,"517, SYLVESTER UGOR CRESCENT,"
55,PRECIOUS HEALTHCARE LIMITED,"8 LUNGI STREET, OFF CAIRO STREET WUSE 2,"
56,PREPAID MEDICARE SERVICES LTD.,9A GANGES STREET OFF ALVAN IKOKU WAY
57,PRINCETON HEALTH,"26 MOGAJI ARE ROAD, OPPOSITE VITAS BAKERY, RING ROAD"
58,PROHEALTH HMO LTD,"BASSAN PLAZA, BLOCK D, FIRST FLOOR, PLOT 759 INDEPENDENCE AV"
59,REDCARE HEALTH SERVICES LIMITED,"22 COKER ROAD, OPPOSITE MAMACASS"
60,REGENIX HEALTH CARE SERVICE LIMITED,"KIENI PLAZA, KLM 13MELFORD OKILO ROAD"
61,RELIANCE HMO LIMITED,"32 LANRE AWOLOKUN STREET GBAGADA PHASE 2, KOSOFE, LAGOS"
62,RODING HEALTHCARE LTD.,"NO. 4 MAKOLO ROAD, ADEKUNLE YABA, LAGOS"
63,RONSBERGER NIGERIA LTD.,"1, MAMBOLO STREET, WUSE ZONE 2, ABUJA."
64,ROTHAUGE HEALTHCARE LIMITED,"16, BABATUNDE STREET, OFF OGUNLANA DRIVE, SURULERE, SURULERE LGA, LAGOS, Nigeria"
65,ROYAL HEALTH MAINTENANCE SERVICES LTD.,PLOT 271 IKENEGBU LAYOUT (FLORIDA BOOKSHOP BUILDING) OWERRI
66,SALUS TRUST GTE,"7 FORCE ROAD, LAGOS ISLAND."
67,SERAPH HMO LIMITED,"Kilometer 7, Gboko Road, Makurdi, Benue State"
68,SKYDA HEALTH LIMITED,"8A, Panama Street, off IBB Way Maitama, Abuja"
69,SONGHAI HEALTH TRUST,"TSUKUNDA HOUSE SUITE B11, AND B12, PLOT 1446, CONSTITUTION A"
70,SPRINGTIDE HEALTHCARE SERVICES LTD.,"Iriebe Street, D''line Port Harcourt, Rivers State"
71,STERLING HEALTH MANAGED CARE SERVICES LIMITED,"VALLEY VIEW PLAZA, 99 OPEBI ROAD"
72,SUNU HEALTH NIGERIA LIMITED,NO. 16 OBOKUN ST. ILUPEJU
73,SYNERGY WELLCARE MEDICAID LIMITED,"NO. 13 PRECISION SCHOOL ROAD, ODANI ELELENWO, PORT HARCOURT, OBIAKPO RIVERS STATE."
74,TOTAL HEALTH TRUST LIMITED,"2, MARCONI ROAD, PALMGROOVE ESTATE, ILUPEJU"
75,ULTIMATE HEALTH MANAGEMENT SERVICES LTD,"TSUKUNDA HOUSE, 4TH FLOOR, RIGHT WING, PLOT 1446.CONSTITUTIO"
76,UNITED COMPREHENSIVE HEALTH MANAGERS LTD.,PLOT C-1 RUMUOGBA RESIDENTIAL ESTATE
77,UNITED HEALTHCARE INTERNATIONAL LIMITED,"UHI HOUSE, 7 JABA CLOSE OFF DUNUKOFIA ST, OPPOSITE FCDA MINI"
78,VENUS MEDICARE LTD,"PLOT 472, CADASTRAL ZONE A8, FORMER CHICKEN HOUSE. OPP. ASCO"
79,VERITAS HEALTHCARE LIMITED,"3RD FLOOR, UNITY KAPITAL BUILDING, PLOT 497, ABOGO LARGEMA S"
80,WELL HEALTH NETWORK LIMITED,"15 IBUSA AVENUE, INDEPENDENT LAYOUT"
81,WELLNESS HEALTH MANAGEMENT SERVICES LIMITED,"9, JOGUNOLA STREET, GBAGADA PHASE II, GBAGADA,"
82,ZUMA HEALTH TRUST,"PLOT 856, OLU AWOTESU STREET, OFF IDRISS IBRAHIM CRESCENT, ("
83,Healthnomics HMO PLC,"MDCAN National Secretariat, Stephen Keshi Street, Off 69 Road, 6th Avenue, Gwarinpa Estate, Abuja"
84,HYSSOP Health International Limited (HMO),"217, Jakpa Road, By Okuisoko, Effurun, Warri, Delta State"
85,Hopewell Healthcare Management Ltd,"Suite A5, 1st Floor, Ocean Center, No. 3, Happiness Blessing Street, Opposite FCT Library, Gudu, Abuja"
86,Crown Jewel HMO Ltd.,"No, 17, Ahmadu Bello Way, Garki, Abuja"
87,Smathealth Medicare Limited,"Smathealth Medicare Limited 12B, Ogunmodede Street, By Ikeja Medical Cebtre, Allen Avenue, Ikeja, Lagos State"
88,Health Assur Limited,"1, Ramat Crescent, Ogudu GRA, Kosofe, Lagos State"
89,Quest Medicare Limited,"Quest Building, 8, Oladimeji Alo Street, Lekki Phase 1, Lagos"
90,Life Action Plus Ltd.,"st Floor, Nigeria Law Publications House, Jobi Fele Way, Centrasl Business District, Alausa, Ikeja, Lagos State"
91,Zenor Healthcare Ltd.,"86, Ajayi Road, Off Aboaba Street, Ogba, Lagos"
92,Aspire HMO Limited,"3, lover Road, Ikoyi, Lagos State"
93,Mitera Health Limited,"Plot 8/10, Hortico Way, Off Command Road, Ikeja, Lagos"

In [72]:
state_mapping = {
    "A&M HEALTHCARE TRUST LIMITED": "Adamawa",
    "AIICO MULTISHIELD NIGERIA LIMITED": "Lagos",
    "ALLEANZA HEALTH MANAGEMENT LIMITED": "Lagos",
    "ALLY HEALTHCARE LIMITED": "FCT",
    "AMAN HEALTH MAINTENANCE ORGANIZATIONS": "FCT",
    "ANCHOR HMO INTERNATIONAL COMPANY LIMITED": "N/A",
    "ASHMED INTEGRATED HEALTH SERVICES LTD.": "Kaduna",
    "AVON HEALTHCARE LIMITED": "Lagos",
    "AXA MANSARD HEALTH LIMITED": "Lagos",
    "BASTION HEALTH LIMITED": "Lagos",
    "BONITAS HEALTH MAINTENANCE LIMITED": "Rivers",
    "CENTURY MEDICAID SERVICES LIMITED": "Rivers",
    "CLEARLINE INTERNATIONAL LIMITED": "Lagos",
    "DEFENCE HEALTH MAINTENANCE LIMITED": "FCT",
    "Delog Medical Services Ltd. (HMO)": "Lagos",
    "DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO": "Lagos",
    "DOT HMO Ltd.": "Lagos",
    "FOUNTAIN HEALTHCARE LIMITED": "Lagos",
    "GNI HEALTHCARE LTD": "Lagos",
    "GORAH HEALTHCARE LTD.": "Lagos",
    "GREENBAY HEALTHCARE SERVICES LIMITED": "Lagos",
    "GREENFIELD HEALTH MANAGEMENT LTD": "N/A",
    "GROOMING HEALTH MANAGEMENT LIMITED": "Lagos",
    "HALLMARK HEALTH SERVICES LIMITED": "Lagos",
    "HEALTH ASSUR LIMITED": "Lagos",
    "Health Partners Limited": "N/A",
    "HEALTHCARE INTERNATIONAL LIMITED": "Lagos",
    "HEALTHSPRING HMO": "FCT",
    "HYGEIA HMO LIMITED": "Lagos",
    "Infinite X2 Health Maintenance Services": "Kaduna",
    "INTEGRATED HEALTHCARE": "FCT",
    "INTERNATIONAL HEALTH MGT. SERVICES": "FCT",
    "IVES MEDICARE": "Lagos",
    "KENNEDIA HMO LIMITED": "Lagos",
    "LEADWAY HEALTH LIMITED": "Lagos",
    "LIFE WORTH MEDICARE LTD": "Lagos",
    "LIFESAVER HEALTHCARE LIMITED": "Lagos",
    "MAAYOIT HEALTH CARE LIMITED": "Kwara",
    "MARINA MEDICAL SERVICES HMO LIMITED": "Lagos",
    "MARKFEMA NIGERIA LTD.": "FCT",
    "MASSLIFE HEALTHCARE LIMITED": "FCT",
    "MB & O HEALTHCARE SERVICES LIMITED": "Lagos",
    "MEDEXIA LIMITED": "Lagos",
    "MEDICARE ALLIANCE LIMITED": "FCT",
    "MEDIPLAN HEALTHCARE LIMITED": "Lagos",
    "METROHEALTH HMO LIMITED": "Lagos",
    "NEM HEALTH LIMITED": "Lagos",
    "NNPC-HMO LIMITED": "N/A",
    "NONSUCH MEDICARE LIMITED": "Oyo",
    "NOOR HEALTH LTD.": "Lagos",
    "NOVO HEALTH AFRICA LIMITED": "Lagos",
    "OCEANIC HEALTH MANAGEMENT LIMITED": "Lagos / FCT",
    "PERAMARE HEALTH MANAGEMENT COMPANY LIMITED": "FCT",
    "PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED": "Lagos",
    "POLICE HEALTH MAINTENANCE LIMITED": "FCT",
    "PRECIOUS HEALTHCARE LIMITED": "FCT",
    "PREPAID MEDICARE SERVICES LTD.": "FCT",
    "PRINCETON HEALTH": "Oyo",
    "PROHEALTH HMO LTD": "FCT",
    "REDCARE HEALTH SERVICES LIMITED": "N/A",
    "REGENIX HEALTH CARE SERVICE LIMITED": "Rivers",
    "RELIANCE HMO LIMITED": "Lagos",
    "RODING HEALTHCARE LTD.": "Lagos",
    "RONSBERGER NIGERIA LTD.": "FCT",
    "ROTHAUGE HEALTHCARE LIMITED": "Lagos",
    "ROYAL HEALTH MAINTENANCE SERVICES LTD.": "Imo",
    "SALUS TRUST GTE": "Lagos",
    "SERAPH HMO LIMITED": "Benue",
    "SKYDA HEALTH LIMITED": "FCT",
    "SONGHAI HEALTH TRUST": "FCT",
    "SPRINGTIDE HEALTHCARE SERVICES LTD.": "Rivers",
    "STERLING HEALTH MANAGED CARE SERVICES LIMITED": "Lagos",
    "SUNU HEALTH NIGERIA LIMITED": "Lagos",
    "SYNERGY WELLCARE MEDICAID LIMITED": "Rivers",
    "TOTAL HEALTH TRUST LIMITED": "Lagos",
    "ULTIMATE HEALTH MANAGEMENT SERVICES LTD": "FCT",
    "UNITED COMPREHENSIVE HEALTH MANAGERS LTD.": "Rivers",
    "UNITED HEALTHCARE INTERNATIONAL LIMITED": "FCT",
    "VENUS MEDICARE LTD": "FCT",
    "VERITAS HEALTHCARE LIMITED": "FCT",
    "WELL HEALTH NETWORK LIMITED": "Enugu",
    "WELLNESS HEALTH MANAGEMENT SERVICES LIMITED": "Lagos",
    "ZUMA HEALTH TRUST": "FCT",
    "Healthnomics HMO PLC": "FCT",
    "HYSSOP Health International Limited (HMO)": "Delta",
    "Hopewell Healthcare Management Ltd": "FCT",
    "Crown Jewel HMO Ltd.": "FCT",
    "Smathealth Medicare Limited": "Lagos",
    "Health Assur Limited": "Lagos",
    "Quest Medicare Limited": "Lagos",
    "Life Action Plus Ltd.": "Lagos",
    "Zenor Healthcare Ltd.": "Lagos",
    "Aspire HMO Limited": "Lagos",
    "Mitera Health Limited": "Lagos"
}

nigeria_hmo["State"] = nigeria_hmo["Name"].map(state_mapping)

nigeria_hmo[["Name", "Address", "State"]]

,Name,Address,State
0,A&M HEALTHCARE TRUST LIMITED,"Plot U Bekaji Road, Opposite Bekaji Jumma'at Mosque, Jimeta, Yola, Adamawa State",Adamawa
1,AIICO MULTISHIELD NIGERIA LIMITED,"322, IKORODU ROAD, ANTHONY",Lagos
2,ALLEANZA HEALTH MANAGEMENT LIMITED,"? 83B, Basheer Shittu Avenue, Magodo Estate, Phase 2, Shangisha, Lagos",Lagos
3,ALLY HEALTHCARE LIMITED,"Suit C4 Plot 1196 Ndjamena Crescent, Wuse II, Abuja",FCT
4,AMAN HEALTH MAINTENANCE ORGANIZATIONS,"? 1, M. M. Alkali Street, Off 442 Crescent, Citec Vilas Gwarinpa, Abuja",FCT
5,ANCHOR HMO INTERNATIONAL COMPANY LIMITED,GOLDCREST MALL BUILDING,N/A
6,ASHMED INTEGRATED HEALTH SERVICES LTD.,"RE 013 ZUNGERU CLOSE BY BIMA ROAD NITEL QUARTERS, KADUNA",Kaduna
7,AVON HEALTHCARE LIMITED,"22B, GLOVER ROAD",Lagos
8,AXA MANSARD HEALTH LIMITED,"177, IKORODU ROAD, ONIPANU, LAGOS",Lagos
9,BASTION HEALTH LIMITED,"UBN HOUSE NO 1 ADEOLA ODEKU STREET, VICTORIA ISLAND, LAGOS, ETI OSA, LAGOS, Nigeria",Lagos
10,BONITAS HEALTH MAINTENANCE LIMITED,"No. 7 Birabi Street, GRA phase 1, Port Harcourt, Rivers State",Rivers
11,CENTURY MEDICAID SERVICES LIMITED,"36 OKOROJI STREET, D/LINE, PORT HARCOURT, PORT HARCOURT CITY LGA, RIVERS STATE, Nigeria",Rivers
12,CLEARLINE INTERNATIONAL LIMITED,"290, IKORODU ROAD, ANTHONY, LAGOS",Lagos
13,DEFENCE HEALTH MAINTENANCE LIMITED,"2 HAMINA CLOSE, ABUJA",FCT
14,Delog Medical Services Ltd. (HMO),"? 369, Borno Way, Alagomeji, Yaba, Lagos",Lagos
15,DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO,"2nd Floor, 34/36, Association Avenue, Ilupeju, Lagos",Lagos
16,DOT HMO Ltd.,"MJS House, 366 Murtala Mohammed Way (Opposite Polaris Bank), Yaba, Lagos",Lagos
17,FOUNTAIN HEALTHCARE LIMITED,"ALL SEASON PLACE, NO 74 ISHERI- OGUNNUSI ROAD, OJUDU-OMOLE, IKEJA LAGOS",Lagos
18,GNI HEALTHCARE LTD,"28, AFOLABI AINA STREET, OFF AWOLOWO WAY, IKEJA LAGOS",Lagos
19,GORAH HEALTHCARE LTD.,"? 322A, Ikorodu Road, Ikeja, Lagos",Lagos
20,GREENBAY HEALTHCARE SERVICES LIMITED,"9, ODUNUGA STREET, OFF OPEBI LINK ROAD,",Lagos
21,GREENFIELD HEALTH MANAGEMENT LTD,"PLOT 14, MARKET GARDEN POCKET LAYOUT, BY ISIADINSO CLOSE, G",N/A
22,GROOMING HEALTH MANAGEMENT LIMITED,"No. 3, Tina Chris Street, Ejigbo, Lagos State",Lagos
23,HALLMARK HEALTH SERVICES LIMITED,"264 Ikorodu Road, Obanikoro, Lagos, Somolu Local Government Area, Lagos, Nigeria",Lagos
24,HEALTH ASSUR LIMITED,"NO.1 RAMAT CRESCENT OGUDU GRA, KOSOFE, LAGOS.",Lagos
25,Health Partners Limited,NaN,N/A
26,HEALTHCARE INTERNATIONAL LIMITED,"308A, MURITALA MOHAMMED WAY, YABA",Lagos
27,HEALTHSPRING HMO,"? 1, Julius Nyerere Crescent, Asokoro, Abuja",FCT
28,HYGEIA HMO LIMITED,"2ND FLOOR, BANK OF INDUSTRY BUILDING, 21/22 MARINA",Lagos
29,Infinite X2 Health Maintenance Services,"No. 13, Lafia Road, Adjacent Kaduna Golf Course, Kaduna State",Kaduna
30,INTEGRATED HEALTHCARE,"19, JOS STREET, AREA 3 GARKI-ABUJA",FCT
31,INTERNATIONAL HEALTH MGT. SERVICES,"IGI HOUSE, 3 GWAMI ST, WUSE ZONE 4,",FCT
32,IVES MEDICARE,"4 MOJIDI STREET, OFF TOYIN STREET",Lagos
33,KENNEDIA HMO LIMITED,"14B, Kingsley Emu Street, Lagos, Off Chris Onanuga, Lekki Phase 1",Lagos
34,LEADWAY HEALTH LIMITED,"121/123, FUNSHO WILLIAMS AVENUE, IPONRI, SURULERE, LAGOS.",Lagos
35,LIFE WORTH MEDICARE LTD,"13A, BISHOP COKER ROUND ABOUT, ILUPEJU, LAGOS",Lagos
36,LIFESAVER HEALTHCARE LIMITED,"20B, Olutoye Crescent, Afra Estate, Off Adeniyi Jones Avenue, Ikeja, Lagos State",Lagos
37,MAAYOIT HEALTH CARE LIMITED,"MHL BUILDING OPPOSITE GSS, OLD JEBBA ROAD, ILORIN, KWARA STATE, P.O. BOX 5504, ILORIN, KWARA STATE, ILORIN, ILORIN WEST, KWARA, Nigeria",Kwara
38,MARINA MEDICAL SERVICES HMO LIMITED,"24, MONTGOMERY ROAD, YABA-LAGOS.",Lagos
39,MARKFEMA NIGERIA LTD.,"4A GURARA STREET, IBRAHIM ABACHA ESTATE",FCT
40,MASSLIFE HEALTHCARE LIMITED,"I. T. F. House (4th Floor), No. 6, Adetokunbo Ademola Crescent, Wuse 2, Abuja",FCT
41,MB & O HEALTHCARE SERVICES LIMITED,"30, Bassie Ogamba Street, Off Adeniran Ogunsanya Street, Surulere, Lagos",Lagos
42,MEDEXIA LIMITED,"221, IKORODU ROAD, ILUPEJU LAGOS.",Lagos
43,MEDICARE ALLIANCE LIMITED,"SUITE 9-13, 2ND FLOOR, ADAMU FURA HOUSE",FCT
44,MEDIPLAN HEALTHCARE LIMITED,"CAPITAL BUILDING, 332, IKORODU ROAD, IDI-IROKO BUS STOP, MAR",Lagos
45,METROHEALTH HMO LIMITED,"26, CATHOLIC MISSION STREET",Lagos
46,NEM HEALTH LIMITED,"New House, 199 Ikorodu Road, Obanikoro, Lagos",Lagos
47,NNPC-HMO LIMITED,NNPC PENSION FUND COMPLEX,N/A
48,NONSUCH MEDICARE LIMITED,"PLOT 1, ABIMBOLA ESTATE LAFIA HOSPITAL COMPLEX, APATA-IBADAN",Oyo
49,NOOR HEALTH LTD.,"? 168, Awolowo Road, Ikoyi, Lagos State. ? 170, Gbagada Express Way, Lagos State",Lagos
50,NOVO HEALTH AFRICA LIMITED,"PLOT 10A AKIOGUN ROAD, ONIRU LEKKI LAGOS STATE",Lagos
51,OCEANIC HEALTH MANAGEMENT LIMITED,"PLOT 226, AWOLOWO ROAD IKOYI, LAGOS / NEXIM HOUSE CBD, ABUJA",Lagos / FCT
52,PERAMARE HEALTH MANAGEMENT COMPANY LIMITED,"Hall 1, 6th Floor, Tsukunde House, Opposite World Trade Centre, CBD, Abuja",FCT
53,PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED,"70B LANRE AWOLOKUN STREET, GBAGADA PHASE 2 GBAGADA KOSOFE, LAGOS.",Lagos
54,POLICE HEALTH MAINTENANCE LIMITED,"517, SYLVESTER UGOR CRESCENT,",FCT
55,PRECIOUS HEALTHCARE LIMITED,"8 LUNGI STREET, OFF CAIRO STREET WUSE 2,",FCT
56,PREPAID MEDICARE SERVICES LTD.,9A GANGES STREET OFF ALVAN IKOKU WAY,FCT
57,PRINCETON HEALTH,"26 MOGAJI ARE ROAD, OPPOSITE VITAS BAKERY, RING ROAD",Oyo
58,PROHEALTH HMO LTD,"BASSAN PLAZA, BLOCK D, FIRST FLOOR, PLOT 759 INDEPENDENCE AV",FCT
59,REDCARE HEALTH SERVICES LIMITED,"22 COKER ROAD, OPPOSITE MAMACASS",N/A
60,REGENIX HEALTH CARE SERVICE LIMITED,"KIENI PLAZA, KLM 13MELFORD OKILO ROAD",Rivers
61,RELIANCE HMO LIMITED,"32 LANRE AWOLOKUN STREET GBAGADA PHASE 2, KOSOFE, LAGOS",Lagos
62,RODING HEALTHCARE LTD.,"NO. 4 MAKOLO ROAD, ADEKUNLE YABA, LAGOS",Lagos
63,RONSBERGER NIGERIA LTD.,"1, MAMBOLO STREET, WUSE ZONE 2, ABUJA.",FCT
64,ROTHAUGE HEALTHCARE LIMITED,"16, BABATUNDE STREET, OFF OGUNLANA DRIVE, SURULERE, SURULERE LGA, LAGOS, Nigeria",Lagos
65,ROYAL HEALTH MAINTENANCE SERVICES LTD.,PLOT 271 IKENEGBU LAYOUT (FLORIDA BOOKSHOP BUILDING) OWERRI,Imo
66,SALUS TRUST GTE,"7 FORCE ROAD, LAGOS ISLAND.",Lagos
67,SERAPH HMO LIMITED,"Kilometer 7, Gboko Road, Makurdi, Benue State",Benue
68,SKYDA HEALTH LIMITED,"8A, Panama Street, off IBB Way Maitama, Abuja",FCT
69,SONGHAI HEALTH TRUST,"TSUKUNDA HOUSE SUITE B11, AND B12, PLOT 1446, CONSTITUTION A",FCT
70,SPRINGTIDE HEALTHCARE SERVICES LTD.,"Iriebe Street, D''line Port Harcourt, Rivers State",Rivers
71,STERLING HEALTH MANAGED CARE SERVICES LIMITED,"VALLEY VIEW PLAZA, 99 OPEBI ROAD",Lagos
72,SUNU HEALTH NIGERIA LIMITED,NO. 16 OBOKUN ST. ILUPEJU,Lagos
73,SYNERGY WELLCARE MEDICAID LIMITED,"NO. 13 PRECISION SCHOOL ROAD, ODANI ELELENWO, PORT HARCOURT, OBIAKPO RIVERS STATE.",Rivers
74,TOTAL HEALTH TRUST LIMITED,"2, MARCONI ROAD, PALMGROOVE ESTATE, ILUPEJU",Lagos
75,ULTIMATE HEALTH MANAGEMENT SERVICES LTD,"TSUKUNDA HOUSE, 4TH FLOOR, RIGHT WING, PLOT 1446.CONSTITUTIO",FCT
76,UNITED COMPREHENSIVE HEALTH MANAGERS LTD.,PLOT C-1 RUMUOGBA RESIDENTIAL ESTATE,Rivers
77,UNITED HEALTHCARE INTERNATIONAL LIMITED,"UHI HOUSE, 7 JABA CLOSE OFF DUNUKOFIA ST, OPPOSITE FCDA MINI",FCT
78,VENUS MEDICARE LTD,"PLOT 472, CADASTRAL ZONE A8, FORMER CHICKEN HOUSE. OPP. ASCO",FCT
79,VERITAS HEALTHCARE LIMITED,"3RD FLOOR, UNITY KAPITAL BUILDING, PLOT 497, ABOGO LARGEMA S",FCT
80,WELL HEALTH NETWORK LIMITED,"15 IBUSA AVENUE, INDEPENDENT LAYOUT",Enugu
81,WELLNESS HEALTH MANAGEMENT SERVICES LIMITED,"9, JOGUNOLA STREET, GBAGADA PHASE II, GBAGADA,",Lagos
82,ZUMA HEALTH TRUST,"PLOT 856, OLU AWOTESU STREET, OFF IDRISS IBRAHIM CRESCENT, (",FCT
83,Healthnomics HMO PLC,"MDCAN National Secretariat, Stephen Keshi Street, Off 69 Road, 6th Avenue, Gwarinpa Estate, Abuja",FCT
84,HYSSOP Health International Limited (HMO),"217, Jakpa Road, By Okuisoko, Effurun, Warri, Delta State",Delta
85,Hopewell Healthcare Management Ltd,"Suite A5, 1st Floor, Ocean Center, No. 3, Happiness Blessing Street, Opposite FCT Library, Gudu, Abuja",FCT
86,Crown Jewel HMO Ltd.,"No, 17, Ahmadu Bello Way, Garki, Abuja",FCT
87,Smathealth Medicare Limited,"Smathealth Medicare Limited 12B, Ogunmodede Street, By Ikeja Medical Cebtre, Allen Avenue, Ikeja, Lagos State",Lagos
88,Health Assur Limited,"1, Ramat Crescent, Ogudu GRA, Kosofe, Lagos State",Lagos
89,Quest Medicare Limited,"Quest Building, 8, Oladimeji Alo Street, Lekki Phase 1, Lagos",Lagos
90,Life Action Plus Ltd.,"st Floor, Nigeria Law Publications House, Jobi Fele Way, Centrasl Business District, Alausa, Ikeja, Lagos State",Lagos
91,Zenor Healthcare Ltd.,"86, Ajayi Road, Off Aboaba Street, Ogba, Lagos",Lagos
92,Aspire HMO Limited,"3, lover Road, Ikoyi, Lagos State",Lagos
93,Mitera Health Limited,"Plot 8/10, Hortico Way, Off Command Road, Ikeja, Lagos",Lagos

In [73]:
region_map = {
    # North Central
    "Benue": "North Central",
    "Kogi": "North Central",
    "Kwara": "North Central",
    "Nasarawa": "North Central",
    "Niger": "North Central",
    "Plateau": "North Central",
    "FCT": "North Central",

    # North East
    "Adamawa": "North East",
    "Bauchi": "North East",
    "Borno": "North East",
    "Gombe": "North East",
    "Taraba": "North East",
    "Yobe": "North East",

    # North West
    "Jigawa": "North West",
    "Kaduna": "North West",
    "Kano": "North West",
    "Katsina": "North West",
    "Kebbi": "North West",
    "Sokoto": "North West",
    "Zamfara": "North West",

    # South West
    "Ekiti": "South West",
    "Lagos": "South West",
    "Ogun": "South West",
    "Ondo": "South West",
    "Osun": "South West",
    "Oyo": "South West",

    # South East
    "Abia": "South East",
    "Anambra": "South East",
    "Ebonyi": "South East",
    "Enugu": "South East",
    "Imo": "South East",

    # South South
    "Akwa Ibom": "South South",
    "Bayelsa": "South South",
    "Cross River": "South South",
    "Delta": "South South",
    "Edo": "South South",
    "Rivers": "South South"
}

nigeria_hmo["Region"] = nigeria_hmo["State"].map(region_map)

nigeria_hmo[["Name", "State", "Region"]]

                                             Name        State         Region
0                    A&M HEALTHCARE TRUST LIMITED      Adamawa     North East
1               AIICO MULTISHIELD NIGERIA LIMITED        Lagos     South West
2              ALLEANZA HEALTH MANAGEMENT LIMITED        Lagos     South West
3                         ALLY HEALTHCARE LIMITED          FCT  North Central
4           AMAN HEALTH MAINTENANCE ORGANIZATIONS          FCT  North Central
5        ANCHOR HMO INTERNATIONAL COMPANY LIMITED          N/A            NaN
6          ASHMED INTEGRATED HEALTH SERVICES LTD.       Kaduna     North West
7                         AVON HEALTHCARE LIMITED        Lagos     South West
8                      AXA MANSARD HEALTH LIMITED        Lagos     South West
9                          BASTION HEALTH LIMITED        Lagos     South West
10             BONITAS HEALTH MAINTENANCE LIMITED       Rivers    South South
11              CENTURY MEDICAID SERVICES LIMITED       Rivers    South South
12                CLEARLINE INTERNATIONAL LIMITED        Lagos     South West
13             DEFENCE HEALTH MAINTENANCE LIMITED          FCT  North Central
14              Delog Medical Services Ltd. (HMO)        Lagos     South West
15    DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO        Lagos     South West
16                                   DOT HMO Ltd.        Lagos     South West
17                    FOUNTAIN HEALTHCARE LIMITED        Lagos     South West
18                             GNI HEALTHCARE LTD        Lagos     South West
19                          GORAH HEALTHCARE LTD.        Lagos     South West
20           GREENBAY HEALTHCARE SERVICES LIMITED        Lagos     South West
21               GREENFIELD HEALTH MANAGEMENT LTD          N/A            NaN
22             GROOMING HEALTH MANAGEMENT LIMITED        Lagos     South West
23               HALLMARK HEALTH SERVICES LIMITED        Lagos     South West
24                           HEALTH ASSUR LIMITED        Lagos     South West
25                        Health Partners Limited          N/A            NaN
26               HEALTHCARE INTERNATIONAL LIMITED        Lagos     South West
27                               HEALTHSPRING HMO          FCT  North Central
28                             HYGEIA HMO LIMITED        Lagos     South West
29        Infinite X2 Health Maintenance Services       Kaduna     North West
30                          INTEGRATED HEALTHCARE          FCT  North Central
31             INTERNATIONAL HEALTH MGT. SERVICES          FCT  North Central
32                                  IVES MEDICARE        Lagos     South West
33                           KENNEDIA HMO LIMITED        Lagos     South West
34                         LEADWAY HEALTH LIMITED        Lagos     South West
35                        LIFE WORTH MEDICARE LTD        Lagos     South West
36                   LIFESAVER HEALTHCARE LIMITED        Lagos     South West
37                    MAAYOIT HEALTH CARE LIMITED        Kwara  North Central
38            MARINA MEDICAL SERVICES HMO LIMITED        Lagos     South West
39                          MARKFEMA NIGERIA LTD.          FCT  North Central
40                    MASSLIFE HEALTHCARE LIMITED          FCT  North Central
41             MB & O HEALTHCARE SERVICES LIMITED        Lagos     South West
42                                MEDEXIA LIMITED        Lagos     South West
43                      MEDICARE ALLIANCE LIMITED          FCT  North Central
44                    MEDIPLAN HEALTHCARE LIMITED        Lagos     South West
45                        METROHEALTH HMO LIMITED        Lagos     South West
46                             NEM HEALTH LIMITED        Lagos     South West
47                               NNPC-HMO LIMITED          N/A            NaN
48                       NONSUCH MEDICARE LIMITED          Oyo     South West
49                               NOOR HEALTH LTD.        Lagos     South West
50                     NOVO HEALTH AFRICA LIMITED        Lagos     South West
51              OCEANIC HEALTH MANAGEMENT LIMITED  Lagos / FCT            NaN
52     PERAMARE HEALTH MANAGEMENT COMPANY LIMITED          FCT  North Central
53    PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED        Lagos     South West
54              POLICE HEALTH MAINTENANCE LIMITED          FCT  North Central
55                    PRECIOUS HEALTHCARE LIMITED          FCT  North Central
56                 PREPAID MEDICARE SERVICES LTD.          FCT  North Central
57                               PRINCETON HEALTH          Oyo     South West
58                              PROHEALTH HMO LTD          FCT  North Central
59                REDCARE HEALTH SERVICES LIMITED          N/A            NaN
60            REGENIX HEALTH CARE SERVICE LIMITED       Rivers    South South
61                           RELIANCE HMO LIMITED        Lagos     South West
62                         RODING HEALTHCARE LTD.        Lagos     South West
63                        RONSBERGER NIGERIA LTD.          FCT  North Central
64                    ROTHAUGE HEALTHCARE LIMITED        Lagos     South West
65         ROYAL HEALTH MAINTENANCE SERVICES LTD.          Imo     South East
66                                SALUS TRUST GTE        Lagos     South West
67                             SERAPH HMO LIMITED        Benue  North Central
68                           SKYDA HEALTH LIMITED          FCT  North Central
69                           SONGHAI HEALTH TRUST          FCT  North Central
70            SPRINGTIDE HEALTHCARE SERVICES LTD.       Rivers    South South
71  STERLING HEALTH MANAGED CARE SERVICES LIMITED        Lagos     South West
72                    SUNU HEALTH NIGERIA LIMITED        Lagos     South West
73              SYNERGY WELLCARE MEDICAID LIMITED       Rivers    South South
74                     TOTAL HEALTH TRUST LIMITED        Lagos     South West
75        ULTIMATE HEALTH MANAGEMENT SERVICES LTD          FCT  North Central
76      UNITED COMPREHENSIVE HEALTH MANAGERS LTD.       Rivers    South South
77        UNITED HEALTHCARE INTERNATIONAL LIMITED          FCT  North Central
78                             VENUS MEDICARE LTD          FCT  North Central
79                     VERITAS HEALTHCARE LIMITED          FCT  North Central
80                    WELL HEALTH NETWORK LIMITED        Enugu     South East
81    WELLNESS HEALTH MANAGEMENT SERVICES LIMITED        Lagos     South West
82                              ZUMA HEALTH TRUST          FCT  North Central
83                           Healthnomics HMO PLC          FCT  North Central
84      HYSSOP Health International Limited (HMO)        Delta    South South
85             Hopewell Healthcare Management Ltd          FCT  North Central
86                           Crown Jewel HMO Ltd.          FCT  North Central
87                    Smathealth Medicare Limited        Lagos     South West
88                           Health Assur Limited        Lagos     South West
89                         Quest Medicare Limited        Lagos     South West
90                          Life Action Plus Ltd.        Lagos     South West
91                          Zenor Healthcare Ltd.        Lagos     South West
92                             Aspire HMO Limited        Lagos     South West
93                          Mitera Health Limited        Lagos     South West

In [74]:
nigeria_hmo["Region"] = nigeria_hmo["Region"].fillna("N/A")

In [75]:
nigeria_hmo[["Name", "State", "Region"]]

                                             Name        State         Region
0                    A&M HEALTHCARE TRUST LIMITED      Adamawa     North East
1               AIICO MULTISHIELD NIGERIA LIMITED        Lagos     South West
2              ALLEANZA HEALTH MANAGEMENT LIMITED        Lagos     South West
3                         ALLY HEALTHCARE LIMITED          FCT  North Central
4           AMAN HEALTH MAINTENANCE ORGANIZATIONS          FCT  North Central
5        ANCHOR HMO INTERNATIONAL COMPANY LIMITED          N/A            N/A
6          ASHMED INTEGRATED HEALTH SERVICES LTD.       Kaduna     North West
7                         AVON HEALTHCARE LIMITED        Lagos     South West
8                      AXA MANSARD HEALTH LIMITED        Lagos     South West
9                          BASTION HEALTH LIMITED        Lagos     South West
10             BONITAS HEALTH MAINTENANCE LIMITED       Rivers    South South
11              CENTURY MEDICAID SERVICES LIMITED       Rivers    South South
12                CLEARLINE INTERNATIONAL LIMITED        Lagos     South West
13             DEFENCE HEALTH MAINTENANCE LIMITED          FCT  North Central
14              Delog Medical Services Ltd. (HMO)        Lagos     South West
15    DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO        Lagos     South West
16                                   DOT HMO Ltd.        Lagos     South West
17                    FOUNTAIN HEALTHCARE LIMITED        Lagos     South West
18                             GNI HEALTHCARE LTD        Lagos     South West
19                          GORAH HEALTHCARE LTD.        Lagos     South West
20           GREENBAY HEALTHCARE SERVICES LIMITED        Lagos     South West
21               GREENFIELD HEALTH MANAGEMENT LTD          N/A            N/A
22             GROOMING HEALTH MANAGEMENT LIMITED        Lagos     South West
23               HALLMARK HEALTH SERVICES LIMITED        Lagos     South West
24                           HEALTH ASSUR LIMITED        Lagos     South West
25                        Health Partners Limited          N/A            N/A
26               HEALTHCARE INTERNATIONAL LIMITED        Lagos     South West
27                               HEALTHSPRING HMO          FCT  North Central
28                             HYGEIA HMO LIMITED        Lagos     South West
29        Infinite X2 Health Maintenance Services       Kaduna     North West
30                          INTEGRATED HEALTHCARE          FCT  North Central
31             INTERNATIONAL HEALTH MGT. SERVICES          FCT  North Central
32                                  IVES MEDICARE        Lagos     South West
33                           KENNEDIA HMO LIMITED        Lagos     South West
34                         LEADWAY HEALTH LIMITED        Lagos     South West
35                        LIFE WORTH MEDICARE LTD        Lagos     South West
36                   LIFESAVER HEALTHCARE LIMITED        Lagos     South West
37                    MAAYOIT HEALTH CARE LIMITED        Kwara  North Central
38            MARINA MEDICAL SERVICES HMO LIMITED        Lagos     South West
39                          MARKFEMA NIGERIA LTD.          FCT  North Central
40                    MASSLIFE HEALTHCARE LIMITED          FCT  North Central
41             MB & O HEALTHCARE SERVICES LIMITED        Lagos     South West
42                                MEDEXIA LIMITED        Lagos     South West
43                      MEDICARE ALLIANCE LIMITED          FCT  North Central
44                    MEDIPLAN HEALTHCARE LIMITED        Lagos     South West
45                        METROHEALTH HMO LIMITED        Lagos     South West
46                             NEM HEALTH LIMITED        Lagos     South West
47                               NNPC-HMO LIMITED          N/A            N/A
48                       NONSUCH MEDICARE LIMITED          Oyo     South West
49                               NOOR HEALTH LTD.        Lagos     South West
50                     NOVO HEALTH AFRICA LIMITED        Lagos     South West
51              OCEANIC HEALTH MANAGEMENT LIMITED  Lagos / FCT            N/A
52     PERAMARE HEALTH MANAGEMENT COMPANY LIMITED          FCT  North Central
53    PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED        Lagos     South West
54              POLICE HEALTH MAINTENANCE LIMITED          FCT  North Central
55                    PRECIOUS HEALTHCARE LIMITED          FCT  North Central
56                 PREPAID MEDICARE SERVICES LTD.          FCT  North Central
57                               PRINCETON HEALTH          Oyo     South West
58                              PROHEALTH HMO LTD          FCT  North Central
59                REDCARE HEALTH SERVICES LIMITED          N/A            N/A
60            REGENIX HEALTH CARE SERVICE LIMITED       Rivers    South South
61                           RELIANCE HMO LIMITED        Lagos     South West
62                         RODING HEALTHCARE LTD.        Lagos     South West
63                        RONSBERGER NIGERIA LTD.          FCT  North Central
64                    ROTHAUGE HEALTHCARE LIMITED        Lagos     South West
65         ROYAL HEALTH MAINTENANCE SERVICES LTD.          Imo     South East
66                                SALUS TRUST GTE        Lagos     South West
67                             SERAPH HMO LIMITED        Benue  North Central
68                           SKYDA HEALTH LIMITED          FCT  North Central
69                           SONGHAI HEALTH TRUST          FCT  North Central
70            SPRINGTIDE HEALTHCARE SERVICES LTD.       Rivers    South South
71  STERLING HEALTH MANAGED CARE SERVICES LIMITED        Lagos     South West
72                    SUNU HEALTH NIGERIA LIMITED        Lagos     South West
73              SYNERGY WELLCARE MEDICAID LIMITED       Rivers    South South
74                     TOTAL HEALTH TRUST LIMITED        Lagos     South West
75        ULTIMATE HEALTH MANAGEMENT SERVICES LTD          FCT  North Central
76      UNITED COMPREHENSIVE HEALTH MANAGERS LTD.       Rivers    South South
77        UNITED HEALTHCARE INTERNATIONAL LIMITED          FCT  North Central
78                             VENUS MEDICARE LTD          FCT  North Central
79                     VERITAS HEALTHCARE LIMITED          FCT  North Central
80                    WELL HEALTH NETWORK LIMITED        Enugu     South East
81    WELLNESS HEALTH MANAGEMENT SERVICES LIMITED        Lagos     South West
82                              ZUMA HEALTH TRUST          FCT  North Central
83                           Healthnomics HMO PLC          FCT  North Central
84      HYSSOP Health International Limited (HMO)        Delta    South South
85             Hopewell Healthcare Management Ltd          FCT  North Central
86                           Crown Jewel HMO Ltd.          FCT  North Central
87                    Smathealth Medicare Limited        Lagos     South West
88                           Health Assur Limited        Lagos     South West
89                         Quest Medicare Limited        Lagos     South West
90                          Life Action Plus Ltd.        Lagos     South West
91                          Zenor Healthcare Ltd.        Lagos     South West
92                             Aspire HMO Limited        Lagos     South West
93                          Mitera Health Limited        Lagos     South West

In [76]:
nigeria_hmo["Coverage State"] = "N/A"

In [77]:
nationwide_hmos = [
    "HEALTHSPRING HMO",
    "HYGEIA HMO LIMITED",
    "INTERNATIONAL HEALTH MGT. SERVICES"
]

nigeria_hmo.loc[
    nigeria_hmo["Name"].isin(nationwide_hmos),
    "Coverage State"
] = "Nationwide – Nigeria"

In [78]:
nigeria_hmo[["Name", "State", "Region", "Coverage State"]]

,Name,State,Region,Coverage State
0,A&M HEALTHCARE TRUST LIMITED,Adamawa,North East,N/A
1,AIICO MULTISHIELD NIGERIA LIMITED,Lagos,South West,N/A
2,ALLEANZA HEALTH MANAGEMENT LIMITED,Lagos,South West,N/A
3,ALLY HEALTHCARE LIMITED,FCT,North Central,N/A
4,AMAN HEALTH MAINTENANCE ORGANIZATIONS,FCT,North Central,N/A
5,ANCHOR HMO INTERNATIONAL COMPANY LIMITED,N/A,N/A,N/A
6,ASHMED INTEGRATED HEALTH SERVICES LTD.,Kaduna,North West,N/A
7,AVON HEALTHCARE LIMITED,Lagos,South West,N/A
8,AXA MANSARD HEALTH LIMITED,Lagos,South West,N/A
9,BASTION HEALTH LIMITED,Lagos,South West,N/A
10,BONITAS HEALTH MAINTENANCE LIMITED,Rivers,South South,N/A
11,CENTURY MEDICAID SERVICES LIMITED,Rivers,South South,N/A
12,CLEARLINE INTERNATIONAL LIMITED,Lagos,South West,N/A
13,DEFENCE HEALTH MAINTENANCE LIMITED,FCT,North Central,N/A
14,Delog Medical Services Ltd. (HMO),Lagos,South West,N/A
15,DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO,Lagos,South West,N/A
16,DOT HMO Ltd.,Lagos,South West,N/A
17,FOUNTAIN HEALTHCARE LIMITED,Lagos,South West,N/A
18,GNI HEALTHCARE LTD,Lagos,South West,N/A
19,GORAH HEALTHCARE LTD.,Lagos,South West,N/A
20,GREENBAY HEALTHCARE SERVICES LIMITED,Lagos,South West,N/A
21,GREENFIELD HEALTH MANAGEMENT LTD,N/A,N/A,N/A
22,GROOMING HEALTH MANAGEMENT LIMITED,Lagos,South West,N/A
23,HALLMARK HEALTH SERVICES LIMITED,Lagos,South West,N/A
24,HEALTH ASSUR LIMITED,Lagos,South West,N/A
25,Health Partners Limited,N/A,N/A,N/A
26,HEALTHCARE INTERNATIONAL LIMITED,Lagos,South West,N/A
27,HEALTHSPRING HMO,FCT,North Central,Nationwide – Nigeria
28,HYGEIA HMO LIMITED,Lagos,South West,Nationwide – Nigeria
29,Infinite X2 Health Maintenance Services,Kaduna,North West,N/A
30,INTEGRATED HEALTHCARE,FCT,North Central,N/A
31,INTERNATIONAL HEALTH MGT. SERVICES,FCT,North Central,Nationwide – Nigeria
32,IVES MEDICARE,Lagos,South West,N/A
33,KENNEDIA HMO LIMITED,Lagos,South West,N/A
34,LEADWAY HEALTH LIMITED,Lagos,South West,N/A
35,LIFE WORTH MEDICARE LTD,Lagos,South West,N/A
36,LIFESAVER HEALTHCARE LIMITED,Lagos,South West,N/A
37,MAAYOIT HEALTH CARE LIMITED,Kwara,North Central,N/A
38,MARINA MEDICAL SERVICES HMO LIMITED,Lagos,South West,N/A
39,MARKFEMA NIGERIA LTD.,FCT,North Central,N/A
40,MASSLIFE HEALTHCARE LIMITED,FCT,North Central,N/A
41,MB & O HEALTHCARE SERVICES LIMITED,Lagos,South West,N/A
42,MEDEXIA LIMITED,Lagos,South West,N/A
43,MEDICARE ALLIANCE LIMITED,FCT,North Central,N/A
44,MEDIPLAN HEALTHCARE LIMITED,Lagos,South West,N/A
45,METROHEALTH HMO LIMITED,Lagos,South West,N/A
46,NEM HEALTH LIMITED,Lagos,South West,N/A
47,NNPC-HMO LIMITED,N/A,N/A,N/A
48,NONSUCH MEDICARE LIMITED,Oyo,South West,N/A
49,NOOR HEALTH LTD.,Lagos,South West,N/A
50,NOVO HEALTH AFRICA LIMITED,Lagos,South West,N/A
51,OCEANIC HEALTH MANAGEMENT LIMITED,Lagos / FCT,N/A,N/A
52,PERAMARE HEALTH MANAGEMENT COMPANY LIMITED,FCT,North Central,N/A
53,PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED,Lagos,South West,N/A
54,POLICE HEALTH MAINTENANCE LIMITED,FCT,North Central,N/A
55,PRECIOUS HEALTHCARE LIMITED,FCT,North Central,N/A
56,PREPAID MEDICARE SERVICES LTD.,FCT,North Central,N/A
57,PRINCETON HEALTH,Oyo,South West,N/A
58,PROHEALTH HMO LTD,FCT,North Central,N/A
59,REDCARE HEALTH SERVICES LIMITED,N/A,N/A,N/A
60,REGENIX HEALTH CARE SERVICE LIMITED,Rivers,South South,N/A
61,RELIANCE HMO LIMITED,Lagos,South West,N/A
62,RODING HEALTHCARE LTD.,Lagos,South West,N/A
63,RONSBERGER NIGERIA LTD.,FCT,North Central,N/A
64,ROTHAUGE HEALTHCARE LIMITED,Lagos,South West,N/A
65,ROYAL HEALTH MAINTENANCE SERVICES LTD.,Imo,South East,N/A
66,SALUS TRUST GTE,Lagos,South West,N/A
67,SERAPH HMO LIMITED,Benue,North Central,N/A
68,SKYDA HEALTH LIMITED,FCT,North Central,N/A
69,SONGHAI HEALTH TRUST,FCT,North Central,N/A
70,SPRINGTIDE HEALTHCARE SERVICES LTD.,Rivers,South South,N/A
71,STERLING HEALTH MANAGED CARE SERVICES LIMITED,Lagos,South West,N/A
72,SUNU HEALTH NIGERIA LIMITED,Lagos,South West,N/A
73,SYNERGY WELLCARE MEDICAID LIMITED,Rivers,South South,N/A
74,TOTAL HEALTH TRUST LIMITED,Lagos,South West,N/A
75,ULTIMATE HEALTH MANAGEMENT SERVICES LTD,FCT,North Central,N/A
76,UNITED COMPREHENSIVE HEALTH MANAGERS LTD.,Rivers,South South,N/A
77,UNITED HEALTHCARE INTERNATIONAL LIMITED,FCT,North Central,N/A
78,VENUS MEDICARE LTD,FCT,North Central,N/A
79,VERITAS HEALTHCARE LIMITED,FCT,North Central,N/A
80,WELL HEALTH NETWORK LIMITED,Enugu,South East,N/A
81,WELLNESS HEALTH MANAGEMENT SERVICES LIMITED,Lagos,South West,N/A
82,ZUMA HEALTH TRUST,FCT,North Central,N/A
83,Healthnomics HMO PLC,FCT,North Central,N/A
84,HYSSOP Health International Limited (HMO),Delta,South South,N/A
85,Hopewell Healthcare Management Ltd,FCT,North Central,N/A
86,Crown Jewel HMO Ltd.,FCT,North Central,N/A
87,Smathealth Medicare Limited,Lagos,South West,N/A
88,Health Assur Limited,Lagos,South West,N/A
89,Quest Medicare Limited,Lagos,South West,N/A
90,Life Action Plus Ltd.,Lagos,South West,N/A
91,Zenor Healthcare Ltd.,Lagos,South West,N/A
92,Aspire HMO Limited,Lagos,South West,N/A
93,Mitera Health Limited,Lagos,South West,N/A

In [79]:
nigeria_hmo["Coverage State"] = "N/A"

In [80]:
coverage_state = {
    "A&M HEALTHCARE TRUST LIMITED": "N/A",
    "AIICO MULTISHIELD NIGERIA LIMITED": "Nationwide – Nigeria",
    "ALLEANZA HEALTH MANAGEMENT LIMITED": "Nationwide – Nigeria",
    "ALLY HEALTHCARE LIMITED": "N/A",
    "AMAN HEALTH MAINTENANCE ORGANIZATIONS": "N/A",
    "ANCHOR HMO INTERNATIONAL COMPANY LIMITED": "Nationwide – Nigeria",
    "ASHMED INTEGRATED HEALTH SERVICES LTD.": "N/A",
    "AVON HEALTHCARE LIMITED": "Nationwide – Nigeria",
    "AXA MANSARD HEALTH LIMITED": "Nationwide – Nigeria",
    "BASTION HEALTH LIMITED": "Nationwide – Nigeria",
    "BONITAS HEALTH MAINTENANCE LIMITED": "N/A",
    "CENTURY MEDICAID SERVICES LIMITED": "Nationwide – Nigeria",
    "CLEARLINE INTERNATIONAL LIMITED": "N/A",
    "DEFENCE HEALTH MAINTENANCE LIMITED": "N/A",
    "Delog Medical Services Ltd. (HMO)": "N/A",
    "DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO": "N/A",
    "DOT HMO Ltd.": "N/A",
    "FOUNTAIN HEALTHCARE LIMITED": "N/A",
    "GNI HEALTHCARE LTD": "N/A",
    "GORAH HEALTHCARE LTD.": "N/A",
    "GREENBAY HEALTHCARE SERVICES LIMITED": "N/A",
    "GREENFIELD HEALTH MANAGEMENT LTD": "N/A",
    "GROOMING HEALTH MANAGEMENT LIMITED": "Nationwide – Nigeria",
    "HALLMARK HEALTH SERVICES LIMITED": "N/A",
    "HEALTH ASSUR LIMITED": "Nationwide – Nigeria",
    "Health Partners Limited": "N/A",
    "HEALTHCARE INTERNATIONAL LIMITED": "N/A",
    "HEALTHSPRING HMO": "Nationwide – Nigeria",
    "HYGEIA HMO LIMITED": "Nationwide – Nigeria",
    "Infinite X2 Health Maintenance Services": "N/A",
    "INTEGRATED HEALTHCARE": "N/A",
    "INTERNATIONAL HEALTH MGT. SERVICES": "Nationwide – Nigeria",
    "IVES MEDICARE": "N/A",
    "KENNEDIA HMO LIMITED": "N/A",
    "LEADWAY HEALTH LIMITED": "Nationwide – Nigeria",
    "LIFE WORTH MEDICARE LTD": "N/A",
    "LIFESAVER HEALTHCARE LIMITED": "N/A",
    "MAAYOIT HEALTH CARE LIMITED": "N/A",
    "MARINA MEDICAL SERVICES HMO LIMITED": "N/A",
    "MARKFEMA NIGERIA LTD.": "N/A",
    "MASSLIFE HEALTHCARE LIMITED": "N/A",
    "MB & O HEALTHCARE SERVICES LIMITED": "N/A",
    "MEDEXIA LIMITED": "N/A",
    "MEDICARE ALLIANCE LIMITED": "N/A",
    "MEDIPLAN HEALTHCARE LIMITED": "Nationwide – Nigeria",
    "METROHEALTH HMO LIMITED": "N/A",
    "NEM HEALTH LIMITED": "Nationwide – Nigeria",
    "NNPC-HMO LIMITED": "N/A",
    "NONSUCH MEDICARE LIMITED": "N/A",
    "NOOR HEALTH LTD.": "N/A",
    "NOVO HEALTH AFRICA LIMITED": "N/A",
    "OCEANIC HEALTH MANAGEMENT LIMITED": "N/A",
    "PERAMARE HEALTH MANAGEMENT COMPANY LIMITED": "N/A",
    "PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED": "N/A",
    "POLICE HEALTH MAINTENANCE LIMITED": "N/A",
    "PRECIOUS HEALTHCARE LIMITED": "N/A",
    "PREPAID MEDICARE SERVICES LTD.": "N/A",
    "PRINCETON HEALTH": "N/A",
    "PROHEALTH HMO LTD": "N/A",
    "REDCARE HEALTH SERVICES LIMITED": "N/A",
    "REGENIX HEALTH CARE SERVICE LIMITED": "N/A",
    "RELIANCE HMO LIMITED": "N/A",
    "RODING HEALTHCARE LTD.": "N/A",
    "RONSBERGER NIGERIA LTD.": "N/A",
    "ROTHAUGE HEALTHCARE LIMITED": "Nationwide – Nigeria",
    "ROYAL HEALTH MAINTENANCE SERVICES LTD.": "N/A",
    "SALUS TRUST GTE": "Nationwide – Nigeria",
    "SERAPH HMO LIMITED": "N/A",
    "SKYDA HEALTH LIMITED": "N/A",
    "SONGHAI HEALTH TRUST": "Nationwide – Nigeria",
    "SPRINGTIDE HEALTHCARE SERVICES LTD.": "Nationwide – Nigeria",
    "STERLING HEALTH MANAGED CARE SERVICES LIMITED": "N/A",
    "SUNU HEALTH NIGERIA LIMITED": "Nationwide – Nigeria",
    "SYNERGY WELLCARE MEDICAID LIMITED": "Nationwide – Nigeria",
    "TOTAL HEALTH TRUST LIMITED": "N/A",
    "ULTIMATE HEALTH MANAGEMENT SERVICES LTD": "Nationwide – Nigeria",
    "UNITED COMPREHENSIVE HEALTH MANAGERS LTD.": "N/A",
    "UNITED HEALTHCARE INTERNATIONAL LIMITED": "Nationwide – Nigeria",
    "VENUS MEDICARE LTD": "Nationwide – Nigeria",
    "VERITAS HEALTHCARE LIMITED": "Nationwide – Nigeria",
    "WELL HEALTH NETWORK LIMITED": "N/A",
    "WELLNESS HEALTH MANAGEMENT SERVICES LIMITED": "N/A",
    "ZUMA HEALTH TRUST": "N/A",
    "Healthnomics HMO PLC": "N/A",
    "HYSSOP Health International Limited (HMO)": "N/A",
    "Hopewell Healthcare Management Ltd": "N/A",
    "Crown Jewel HMO Ltd.": "N/A",
    "Smathealth Medicare Limited": "N/A",
    "Health Assur Limited": "Nationwide – Nigeria",
    "Quest Medicare Limited": "N/A",
    "Life Action Plus Ltd.": "N/A",
    "Zenor Healthcare Ltd.": "N/A",
    "Aspire HMO Limited": "N/A",
    "Mitera Health Limited": "N/A"
}

nigeria_hmo["Coverage State"] = (
    nigeria_hmo["Name"].map(coverage_state).fillna("N/A")
)

In [81]:
nigeria_hmo[["Name", "State", "Region", "Coverage State"]]

,Name,State,Region,Coverage State
0,A&M HEALTHCARE TRUST LIMITED,Adamawa,North East,N/A
1,AIICO MULTISHIELD NIGERIA LIMITED,Lagos,South West,Nationwide – Nigeria
2,ALLEANZA HEALTH MANAGEMENT LIMITED,Lagos,South West,Nationwide – Nigeria
3,ALLY HEALTHCARE LIMITED,FCT,North Central,N/A
4,AMAN HEALTH MAINTENANCE ORGANIZATIONS,FCT,North Central,N/A
5,ANCHOR HMO INTERNATIONAL COMPANY LIMITED,N/A,N/A,Nationwide – Nigeria
6,ASHMED INTEGRATED HEALTH SERVICES LTD.,Kaduna,North West,N/A
7,AVON HEALTHCARE LIMITED,Lagos,South West,Nationwide – Nigeria
8,AXA MANSARD HEALTH LIMITED,Lagos,South West,Nationwide – Nigeria
9,BASTION HEALTH LIMITED,Lagos,South West,Nationwide – Nigeria
10,BONITAS HEALTH MAINTENANCE LIMITED,Rivers,South South,N/A
11,CENTURY MEDICAID SERVICES LIMITED,Rivers,South South,Nationwide – Nigeria
12,CLEARLINE INTERNATIONAL LIMITED,Lagos,South West,N/A
13,DEFENCE HEALTH MAINTENANCE LIMITED,FCT,North Central,N/A
14,Delog Medical Services Ltd. (HMO),Lagos,South West,N/A
15,DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO,Lagos,South West,N/A
16,DOT HMO Ltd.,Lagos,South West,N/A
17,FOUNTAIN HEALTHCARE LIMITED,Lagos,South West,N/A
18,GNI HEALTHCARE LTD,Lagos,South West,N/A
19,GORAH HEALTHCARE LTD.,Lagos,South West,N/A
20,GREENBAY HEALTHCARE SERVICES LIMITED,Lagos,South West,N/A
21,GREENFIELD HEALTH MANAGEMENT LTD,N/A,N/A,N/A
22,GROOMING HEALTH MANAGEMENT LIMITED,Lagos,South West,Nationwide – Nigeria
23,HALLMARK HEALTH SERVICES LIMITED,Lagos,South West,N/A
24,HEALTH ASSUR LIMITED,Lagos,South West,Nationwide – Nigeria
25,Health Partners Limited,N/A,N/A,N/A
26,HEALTHCARE INTERNATIONAL LIMITED,Lagos,South West,N/A
27,HEALTHSPRING HMO,FCT,North Central,Nationwide – Nigeria
28,HYGEIA HMO LIMITED,Lagos,South West,Nationwide – Nigeria
29,Infinite X2 Health Maintenance Services,Kaduna,North West,N/A
30,INTEGRATED HEALTHCARE,FCT,North Central,N/A
31,INTERNATIONAL HEALTH MGT. SERVICES,FCT,North Central,Nationwide – Nigeria
32,IVES MEDICARE,Lagos,South West,N/A
33,KENNEDIA HMO LIMITED,Lagos,South West,N/A
34,LEADWAY HEALTH LIMITED,Lagos,South West,Nationwide – Nigeria
35,LIFE WORTH MEDICARE LTD,Lagos,South West,N/A
36,LIFESAVER HEALTHCARE LIMITED,Lagos,South West,N/A
37,MAAYOIT HEALTH CARE LIMITED,Kwara,North Central,N/A
38,MARINA MEDICAL SERVICES HMO LIMITED,Lagos,South West,N/A
39,MARKFEMA NIGERIA LTD.,FCT,North Central,N/A
40,MASSLIFE HEALTHCARE LIMITED,FCT,North Central,N/A
41,MB & O HEALTHCARE SERVICES LIMITED,Lagos,South West,N/A
42,MEDEXIA LIMITED,Lagos,South West,N/A
43,MEDICARE ALLIANCE LIMITED,FCT,North Central,N/A
44,MEDIPLAN HEALTHCARE LIMITED,Lagos,South West,Nationwide – Nigeria
45,METROHEALTH HMO LIMITED,Lagos,South West,N/A
46,NEM HEALTH LIMITED,Lagos,South West,Nationwide – Nigeria
47,NNPC-HMO LIMITED,N/A,N/A,N/A
48,NONSUCH MEDICARE LIMITED,Oyo,South West,N/A
49,NOOR HEALTH LTD.,Lagos,South West,N/A
50,NOVO HEALTH AFRICA LIMITED,Lagos,South West,N/A
51,OCEANIC HEALTH MANAGEMENT LIMITED,Lagos / FCT,N/A,N/A
52,PERAMARE HEALTH MANAGEMENT COMPANY LIMITED,FCT,North Central,N/A
53,PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED,Lagos,South West,N/A
54,POLICE HEALTH MAINTENANCE LIMITED,FCT,North Central,N/A
55,PRECIOUS HEALTHCARE LIMITED,FCT,North Central,N/A
56,PREPAID MEDICARE SERVICES LTD.,FCT,North Central,N/A
57,PRINCETON HEALTH,Oyo,South West,N/A
58,PROHEALTH HMO LTD,FCT,North Central,N/A
59,REDCARE HEALTH SERVICES LIMITED,N/A,N/A,N/A
60,REGENIX HEALTH CARE SERVICE LIMITED,Rivers,South South,N/A
61,RELIANCE HMO LIMITED,Lagos,South West,N/A
62,RODING HEALTHCARE LTD.,Lagos,South West,N/A
63,RONSBERGER NIGERIA LTD.,FCT,North Central,N/A
64,ROTHAUGE HEALTHCARE LIMITED,Lagos,South West,Nationwide – Nigeria
65,ROYAL HEALTH MAINTENANCE SERVICES LTD.,Imo,South East,N/A
66,SALUS TRUST GTE,Lagos,South West,Nationwide – Nigeria
67,SERAPH HMO LIMITED,Benue,North Central,N/A
68,SKYDA HEALTH LIMITED,FCT,North Central,N/A
69,SONGHAI HEALTH TRUST,FCT,North Central,Nationwide – Nigeria
70,SPRINGTIDE HEALTHCARE SERVICES LTD.,Rivers,South South,Nationwide – Nigeria
71,STERLING HEALTH MANAGED CARE SERVICES LIMITED,Lagos,South West,N/A
72,SUNU HEALTH NIGERIA LIMITED,Lagos,South West,Nationwide – Nigeria
73,SYNERGY WELLCARE MEDICAID LIMITED,Rivers,South South,Nationwide – Nigeria
74,TOTAL HEALTH TRUST LIMITED,Lagos,South West,N/A
75,ULTIMATE HEALTH MANAGEMENT SERVICES LTD,FCT,North Central,Nationwide – Nigeria
76,UNITED COMPREHENSIVE HEALTH MANAGERS LTD.,Rivers,South South,N/A
77,UNITED HEALTHCARE INTERNATIONAL LIMITED,FCT,North Central,Nationwide – Nigeria
78,VENUS MEDICARE LTD,FCT,North Central,Nationwide – Nigeria
79,VERITAS HEALTHCARE LIMITED,FCT,North Central,Nationwide – Nigeria
80,WELL HEALTH NETWORK LIMITED,Enugu,South East,N/A
81,WELLNESS HEALTH MANAGEMENT SERVICES LIMITED,Lagos,South West,N/A
82,ZUMA HEALTH TRUST,FCT,North Central,N/A
83,Healthnomics HMO PLC,FCT,North Central,N/A
84,HYSSOP Health International Limited (HMO),Delta,South South,N/A
85,Hopewell Healthcare Management Ltd,FCT,North Central,N/A
86,Crown Jewel HMO Ltd.,FCT,North Central,N/A
87,Smathealth Medicare Limited,Lagos,South West,N/A
88,Health Assur Limited,Lagos,South West,Nationwide – Nigeria
89,Quest Medicare Limited,Lagos,South West,N/A
90,Life Action Plus Ltd.,Lagos,South West,N/A
91,Zenor Healthcare Ltd.,Lagos,South West,N/A
92,Aspire HMO Limited,Lagos,South West,N/A
93,Mitera Health Limited,Lagos,South West,N/A

In [82]:
coverage_state = {
    "A&M HEALTHCARE TRUST LIMITED": "N/A",
    "AIICO MULTISHIELD NIGERIA LIMITED": "Nationwide – Nigeria",
    "ALLEANZA HEALTH MANAGEMENT LIMITED": "Nationwide – Nigeria",
    "ALLY HEALTHCARE LIMITED": "N/A",
    "AMAN HEALTH MAINTENANCE ORGANIZATIONS": "N/A",
    "ANCHOR HMO INTERNATIONAL COMPANY LIMITED": "Nationwide – Nigeria",
    "ASHMED INTEGRATED HEALTH SERVICES LTD.": "N/A",
    "AVON HEALTHCARE LIMITED": "Nationwide – Nigeria",
    "AXA MANSARD HEALTH LIMITED": "Nationwide – Nigeria",
    "BASTION HEALTH LIMITED": "Nationwide – Nigeria",
    "BONITAS HEALTH MAINTENANCE LIMITED": "N/A",
    "CENTURY MEDICAID SERVICES LIMITED": "Nationwide – Nigeria",
    "CLEARLINE INTERNATIONAL LIMITED": "N/A",
    "DEFENCE HEALTH MAINTENANCE LIMITED": "All 36 States + FCT",
    "Delog Medical Services Ltd. (HMO)": "N/A",
    "DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO": "N/A",
    "DOT HMO Ltd.": "N/A",
    "FOUNTAIN HEALTHCARE LIMITED": "N/A",
    "GNI HEALTHCARE LTD": "N/A",
    "GORAH HEALTHCARE LTD.": "Nationwide – Nigeria",
    "GREENBAY HEALTHCARE SERVICES LIMITED": "N/A",
    "GREENFIELD HEALTH MANAGEMENT LTD": "N/A",
    "GROOMING HEALTH MANAGEMENT LIMITED": "N/A",
    "HALLMARK HEALTH SERVICES LIMITED": "N/A",
    "HEALTH ASSUR LIMITED": "Nationwide – Nigeria",
    "Health Partners Limited": "N/A",
    "HEALTHCARE INTERNATIONAL LIMITED": "N/A",
    "HEALTHSPRING HMO": "Nationwide – Nigeria",
    "HYGEIA HMO LIMITED": "Nationwide – Nigeria",
    "Infinite X2 Health Maintenance Services": "N/A",
    "INTEGRATED HEALTHCARE": "N/A",
    "INTERNATIONAL HEALTH MGT. SERVICES": "Nationwide – Nigeria",
    "IVES MEDICARE": "N/A",
    "KENNEDIA HMO LIMITED": "N/A",
    "LEADWAY HEALTH LIMITED": "Nationwide – Nigeria",
    "LIFE WORTH MEDICARE LTD": "N/A",
    "LIFESAVER HEALTHCARE LIMITED": "N/A",
    "MAAYOIT HEALTH CARE LIMITED": "N/A",
    "MARINA MEDICAL SERVICES HMO LIMITED": "N/A",
    "MARKFEMA NIGERIA LTD.": "N/A",
    "MASSLIFE HEALTHCARE LIMITED": "N/A",
    "MB & O HEALTHCARE SERVICES LIMITED": "N/A",
    "MEDEXIA LIMITED": "N/A",
    "MEDICARE ALLIANCE LIMITED": "N/A",
    "MEDIPLAN HEALTHCARE LIMITED": "Nationwide – Nigeria",
    "METROHEALTH HMO LIMITED": "N/A",
    "NEM HEALTH LIMITED": "Nationwide – Nigeria",
    "NNPC-HMO LIMITED": "N/A",
    "NONSUCH MEDICARE LIMITED": "N/A",
    "NOOR HEALTH LTD.": "N/A",
    "NOVO HEALTH AFRICA LIMITED": "N/A",
    "OCEANIC HEALTH MANAGEMENT LIMITED": "N/A",
    "PERAMARE HEALTH MANAGEMENT COMPANY LIMITED": "N/A",
    "PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED": "N/A",
    "POLICE HEALTH MAINTENANCE LIMITED": "N/A",
    "PRECIOUS HEALTHCARE LIMITED": "N/A",
    "PREPAID MEDICARE SERVICES LTD.": "N/A",
    "PRINCETON HEALTH": "N/A",
    "PROHEALTH HMO LTD": "N/A",
    "REDCARE HEALTH SERVICES LIMITED": "N/A",
    "REGENIX HEALTH CARE SERVICE LIMITED": "N/A",
    "RELIANCE HMO LIMITED": "N/A",
    "RODING HEALTHCARE LTD.": "N/A",
    "RONSBERGER NIGERIA LTD.": "N/A",
    "ROTHAUGE HEALTHCARE LIMITED": "Nationwide – Nigeria",
    "ROYAL HEALTH MAINTENANCE SERVICES LTD.": "N/A",
    "SALUS TRUST GTE": "Nationwide – Nigeria",
    "SERAPH HMO LIMITED": "N/A",
    "SKYDA HEALTH LIMITED": "N/A",
    "SONGHAI HEALTH TRUST": "Nationwide – Nigeria",
    "SPRINGTIDE HEALTHCARE SERVICES LTD.": "Nationwide – Nigeria",
    "STERLING HEALTH MANAGED CARE SERVICES LIMITED": "N/A",
    "SUNU HEALTH NIGERIA LIMITED": "Nationwide – Nigeria",
    "SYNERGY WELLCARE MEDICAID LIMITED": "Nationwide – Nigeria",
    "TOTAL HEALTH TRUST LIMITED": "N/A",
    "ULTIMATE HEALTH MANAGEMENT SERVICES LTD": "Nationwide – Nigeria",
    "UNITED COMPREHENSIVE HEALTH MANAGERS LTD.": "N/A",
    "UNITED HEALTHCARE INTERNATIONAL LIMITED": "Nationwide – Nigeria",
    "VENUS MEDICARE LTD": "Nationwide – Nigeria",
    "VERITAS HEALTHCARE LIMITED": "Nationwide – Nigeria",
    "WELL HEALTH NETWORK LIMITED": "N/A",
    "WELLNESS HEALTH MANAGEMENT SERVICES LIMITED": "N/A",
    "ZUMA HEALTH TRUST": "N/A",
    "Healthnomics HMO PLC": "N/A",
    "HYSSOP Health International Limited (HMO)": "N/A",
    "Hopewell Healthcare Management Ltd": "N/A",
    "Crown Jewel HMO Ltd.": "N/A",
    "Smathealth Medicare Limited": "N/A",
    "Health Assur Limited": "Nationwide – Nigeria",
    "Quest Medicare Limited": "N/A",
    "Life Action Plus Ltd.": "N/A",
    "Zenor Healthcare Ltd.": "N/A",
    "Aspire HMO Limited": "N/A",
    "Mitera Health Limited": "N/A"
}

nigeria_hmo["Coverage State"] = (
    nigeria_hmo["Name"].map(coverage_state).fillna("N/A")
)

In [83]:
nigeria_hmo[["Name", "State", "Coverage State"]]

,Name,State,Coverage State
0,A&M HEALTHCARE TRUST LIMITED,Adamawa,N/A
1,AIICO MULTISHIELD NIGERIA LIMITED,Lagos,Nationwide – Nigeria
2,ALLEANZA HEALTH MANAGEMENT LIMITED,Lagos,Nationwide – Nigeria
3,ALLY HEALTHCARE LIMITED,FCT,N/A
4,AMAN HEALTH MAINTENANCE ORGANIZATIONS,FCT,N/A
5,ANCHOR HMO INTERNATIONAL COMPANY LIMITED,N/A,Nationwide – Nigeria
6,ASHMED INTEGRATED HEALTH SERVICES LTD.,Kaduna,N/A
7,AVON HEALTHCARE LIMITED,Lagos,Nationwide – Nigeria
8,AXA MANSARD HEALTH LIMITED,Lagos,Nationwide – Nigeria
9,BASTION HEALTH LIMITED,Lagos,Nationwide – Nigeria
10,BONITAS HEALTH MAINTENANCE LIMITED,Rivers,N/A
11,CENTURY MEDICAID SERVICES LIMITED,Rivers,Nationwide – Nigeria
12,CLEARLINE INTERNATIONAL LIMITED,Lagos,N/A
13,DEFENCE HEALTH MAINTENANCE LIMITED,FCT,All 36 States + FCT
14,Delog Medical Services Ltd. (HMO),Lagos,N/A
15,DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO,Lagos,N/A
16,DOT HMO Ltd.,Lagos,N/A
17,FOUNTAIN HEALTHCARE LIMITED,Lagos,N/A
18,GNI HEALTHCARE LTD,Lagos,N/A
19,GORAH HEALTHCARE LTD.,Lagos,Nationwide – Nigeria
20,GREENBAY HEALTHCARE SERVICES LIMITED,Lagos,N/A
21,GREENFIELD HEALTH MANAGEMENT LTD,N/A,N/A
22,GROOMING HEALTH MANAGEMENT LIMITED,Lagos,N/A
23,HALLMARK HEALTH SERVICES LIMITED,Lagos,N/A
24,HEALTH ASSUR LIMITED,Lagos,Nationwide – Nigeria
25,Health Partners Limited,N/A,N/A
26,HEALTHCARE INTERNATIONAL LIMITED,Lagos,N/A
27,HEALTHSPRING HMO,FCT,Nationwide – Nigeria
28,HYGEIA HMO LIMITED,Lagos,Nationwide – Nigeria
29,Infinite X2 Health Maintenance Services,Kaduna,N/A
30,INTEGRATED HEALTHCARE,FCT,N/A
31,INTERNATIONAL HEALTH MGT. SERVICES,FCT,Nationwide – Nigeria
32,IVES MEDICARE,Lagos,N/A
33,KENNEDIA HMO LIMITED,Lagos,N/A
34,LEADWAY HEALTH LIMITED,Lagos,Nationwide – Nigeria
35,LIFE WORTH MEDICARE LTD,Lagos,N/A
36,LIFESAVER HEALTHCARE LIMITED,Lagos,N/A
37,MAAYOIT HEALTH CARE LIMITED,Kwara,N/A
38,MARINA MEDICAL SERVICES HMO LIMITED,Lagos,N/A
39,MARKFEMA NIGERIA LTD.,FCT,N/A
40,MASSLIFE HEALTHCARE LIMITED,FCT,N/A
41,MB & O HEALTHCARE SERVICES LIMITED,Lagos,N/A
42,MEDEXIA LIMITED,Lagos,N/A
43,MEDICARE ALLIANCE LIMITED,FCT,N/A
44,MEDIPLAN HEALTHCARE LIMITED,Lagos,Nationwide – Nigeria
45,METROHEALTH HMO LIMITED,Lagos,N/A
46,NEM HEALTH LIMITED,Lagos,Nationwide – Nigeria
47,NNPC-HMO LIMITED,N/A,N/A
48,NONSUCH MEDICARE LIMITED,Oyo,N/A
49,NOOR HEALTH LTD.,Lagos,N/A
50,NOVO HEALTH AFRICA LIMITED,Lagos,N/A
51,OCEANIC HEALTH MANAGEMENT LIMITED,Lagos / FCT,N/A
52,PERAMARE HEALTH MANAGEMENT COMPANY LIMITED,FCT,N/A
53,PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED,Lagos,N/A
54,POLICE HEALTH MAINTENANCE LIMITED,FCT,N/A
55,PRECIOUS HEALTHCARE LIMITED,FCT,N/A
56,PREPAID MEDICARE SERVICES LTD.,FCT,N/A
57,PRINCETON HEALTH,Oyo,N/A
58,PROHEALTH HMO LTD,FCT,N/A
59,REDCARE HEALTH SERVICES LIMITED,N/A,N/A
60,REGENIX HEALTH CARE SERVICE LIMITED,Rivers,N/A
61,RELIANCE HMO LIMITED,Lagos,N/A
62,RODING HEALTHCARE LTD.,Lagos,N/A
63,RONSBERGER NIGERIA LTD.,FCT,N/A
64,ROTHAUGE HEALTHCARE LIMITED,Lagos,Nationwide – Nigeria
65,ROYAL HEALTH MAINTENANCE SERVICES LTD.,Imo,N/A
66,SALUS TRUST GTE,Lagos,Nationwide – Nigeria
67,SERAPH HMO LIMITED,Benue,N/A
68,SKYDA HEALTH LIMITED,FCT,N/A
69,SONGHAI HEALTH TRUST,FCT,Nationwide – Nigeria
70,SPRINGTIDE HEALTHCARE SERVICES LTD.,Rivers,Nationwide – Nigeria
71,STERLING HEALTH MANAGED CARE SERVICES LIMITED,Lagos,N/A
72,SUNU HEALTH NIGERIA LIMITED,Lagos,Nationwide – Nigeria
73,SYNERGY WELLCARE MEDICAID LIMITED,Rivers,Nationwide – Nigeria
74,TOTAL HEALTH TRUST LIMITED,Lagos,N/A
75,ULTIMATE HEALTH MANAGEMENT SERVICES LTD,FCT,Nationwide – Nigeria
76,UNITED COMPREHENSIVE HEALTH MANAGERS LTD.,Rivers,N/A
77,UNITED HEALTHCARE INTERNATIONAL LIMITED,FCT,Nationwide – Nigeria
78,VENUS MEDICARE LTD,FCT,Nationwide – Nigeria
79,VERITAS HEALTHCARE LIMITED,FCT,Nationwide – Nigeria
80,WELL HEALTH NETWORK LIMITED,Enugu,N/A
81,WELLNESS HEALTH MANAGEMENT SERVICES LIMITED,Lagos,N/A
82,ZUMA HEALTH TRUST,FCT,N/A
83,Healthnomics HMO PLC,FCT,N/A
84,HYSSOP Health International Limited (HMO),Delta,N/A
85,Hopewell Healthcare Management Ltd,FCT,N/A
86,Crown Jewel HMO Ltd.,FCT,N/A
87,Smathealth Medicare Limited,Lagos,N/A
88,Health Assur Limited,Lagos,Nationwide – Nigeria
89,Quest Medicare Limited,Lagos,N/A
90,Life Action Plus Ltd.,Lagos,N/A
91,Zenor Healthcare Ltd.,Lagos,N/A
92,Aspire HMO Limited,Lagos,N/A
93,Mitera Health Limited,Lagos,N/A

In [84]:
nigeria_hmo["Coverage State"].value_counts()

Coverage State
N/A                     67
Nationwide – Nigeria    26
All 36 States + FCT      1
Name: count, dtype: int64

In [85]:
coverage_na = nigeria_hmo[nigeria_hmo["Coverage State"] == "N/A"][["Name", "State", "Website"]]

coverage_na

,Name,State,Website
0,A&M HEALTHCARE TRUST LIMITED,Adamawa,https://amhmo.com/
3,ALLY HEALTHCARE LIMITED,FCT,https://amanhmo.com/home
4,AMAN HEALTH MAINTENANCE ORGANIZATIONS,FCT,https://anchorhmo.com/
6,ASHMED INTEGRATED HEALTH SERVICES LTD.,Kaduna,https://www.avonhealthcare.com/
10,BONITAS HEALTH MAINTENANCE LIMITED,Rivers,https://clearlinehmo.com/
12,CLEARLINE INTERNATIONAL LIMITED,Lagos,https://delogmedicalhmo.com/
14,Delog Medical Services Ltd. (HMO),Lagos,https://hmo.dot.ai/
15,DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO,Lagos,N/A
16,DOT HMO Ltd.,Lagos,http://gnihealthcare.com/
17,FOUNTAIN HEALTHCARE LIMITED,Lagos,https://gorahhmo.com/
18,GNI HEALTHCARE LTD,Lagos,https://greenbayhmo.com/
20,GREENBAY HEALTHCARE SERVICES LIMITED,Lagos,http://www.groominghm.com/
21,GREENFIELD HEALTH MANAGEMENT LTD,N/A,https://hallmarkhmo.com/
22,GROOMING HEALTH MANAGEMENT LIMITED,Lagos,https://www.healthassur.com/
23,HALLMARK HEALTH SERVICES LIMITED,Lagos,https://healthpartnersng.org/
25,Health Partners Limited,N/A,https://healthspringhmo.com/
26,HEALTHCARE INTERNATIONAL LIMITED,Lagos,https://hygeiahmo.com/
29,Infinite X2 Health Maintenance Services,Kaduna,https://ihmsnigeria.com/
30,INTEGRATED HEALTHCARE,FCT,https://www.ivesmedicare.com/
32,IVES MEDICARE,Lagos,https://leadwayhealth.com/
33,KENNEDIA HMO LIMITED,Lagos,https://lifeworthhmo.com/
35,LIFE WORTH MEDICARE LTD,Lagos,https://marinamedicalhmo.ng/
36,LIFESAVER HEALTHCARE LIMITED,Lagos,https://markfema.com/
37,MAAYOIT HEALTH CARE LIMITED,Kwara,https://masslife.com.ng/
38,MARINA MEDICAL SERVICES HMO LIMITED,Lagos,https://mbandohmo.com/
39,MARKFEMA NIGERIA LTD.,FCT,https://medexia.com/
40,MASSLIFE HEALTHCARE LIMITED,FCT,https://masslife.com.ng/
41,MB & O HEALTHCARE SERVICES LIMITED,Lagos,https://mediplanhealthcare.com/
42,MEDEXIA LIMITED,Lagos,https://www.metrohealthhmo.com/
43,MEDICARE ALLIANCE LIMITED,FCT,https://nem-health.com/
45,METROHEALTH HMO LIMITED,Lagos,https://www.nonsuchhmo.com/
47,NNPC-HMO LIMITED,N/A,https://www.oceanichealth.com/
48,NONSUCH MEDICARE LIMITED,Oyo,https://peramarehmo.ng/
49,NOOR HEALTH LTD.,Lagos,https://phillipshmo.net/
50,NOVO HEALTH AFRICA LIMITED,Lagos,https://www.phmlnigeria.com/
51,OCEANIC HEALTH MANAGEMENT LIMITED,Lagos / FCT,https://precioushmo.com/
52,PERAMARE HEALTH MANAGEMENT COMPANY LIMITED,FCT,https://prepaidmedicareng.com/
53,PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED,Lagos,https://phillipshmo.net/
54,POLICE HEALTH MAINTENANCE LIMITED,FCT,https://prohealthhmo.com/
55,PRECIOUS HEALTHCARE LIMITED,FCT,https://redcarehmo.com/contact-us/
56,PREPAID MEDICARE SERVICES LTD.,FCT,https://regenixhealthcare.com/
57,PRINCETON HEALTH,Oyo,https://getreliancehealth.com/nigeria/
58,PROHEALTH HMO LTD,FCT,https://www.prohealthhmo.com/
59,REDCARE HEALTH SERVICES LIMITED,N/A,https://ronsbergerhmo.com/
60,REGENIX HEALTH CARE SERVICE LIMITED,Rivers,https://rothaugehealth.com/
61,RELIANCE HMO LIMITED,Lagos,http://www.royalhealthms.com/
62,RODING HEALTHCARE LTD.,Lagos,https://salustrustng.com/
63,RONSBERGER NIGERIA LTD.,FCT,https://seraphhmo.com/
65,ROYAL HEALTH MAINTENANCE SERVICES LTD.,Imo,https://www.songhaihealthtrust.com/
67,SERAPH HMO LIMITED,Benue,http://www.sterlinghealthmcs.com/
68,SKYDA HEALTH LIMITED,FCT,https://skydalink.com/
71,STERLING HEALTH MANAGED CARE SERVICES LIMITED,Lagos,https://ultimatehealthhmo.com/
74,TOTAL HEALTH TRUST LIMITED,Lagos,https://www.venusmedicare.com/
76,UNITED COMPREHENSIVE HEALTH MANAGERS LTD.,Rivers,https://wellhealthnetwork.com/
80,WELL HEALTH NETWORK LIMITED,Enugu,http://www.hyssophmo.com
81,WELLNESS HEALTH MANAGEMENT SERVICES LIMITED,Lagos,http://www.hopewellhealthcare.ng
82,ZUMA HEALTH TRUST,FCT,http://www.smarthealth.com
83,Healthnomics HMO PLC,FCT,http://www.healthassur.com%20
84,HYSSOP Health International Limited (HMO),Delta,http://www.questhmo.com
85,Hopewell Healthcare Management Ltd,FCT,http://www.lifeactionplus.com
86,Crown Jewel HMO Ltd.,FCT,http://www.aspirehmo.com
87,Smathealth Medicare Limited,Lagos,http://www.miterahealth.com
89,Quest Medicare Limited,Lagos,N/A
90,Life Action Plus Ltd.,Lagos,N/A
91,Zenor Healthcare Ltd.,Lagos,N/A
92,Aspire HMO Limited,Lagos,N/A
93,Mitera Health Limited,Lagos,N/A

In [86]:
print("Number of N/A:", len(coverage_na))

Number of N/A: 67

In [87]:
coverage_na.to_string(index=False)

'                                         Name       State                                Website\n                 A&M HEALTHCARE TRUST LIMITED     Adamawa                     https://amhmo.com/\n                      ALLY HEALTHCARE LIMITED         FCT               https://amanhmo.com/home\n        AMAN HEALTH MAINTENANCE ORGANIZATIONS         FCT                 https://anchorhmo.com/\n       ASHMED INTEGRATED HEALTH SERVICES LTD.      Kaduna        https://www.avonhealthcare.com/\n           BONITAS HEALTH MAINTENANCE LIMITED      Rivers              https://clearlinehmo.com/\n              CLEARLINE INTERNATIONAL LIMITED       Lagos           https://delogmedicalhmo.com/\n            Delog Medical Services Ltd. (HMO)       Lagos                    https://hmo.dot.ai/\n  DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO       Lagos                                    N/A\n                                 DOT HMO Ltd.       Lagos              http://gnihealthcare.com/\n                  FOUNTAIN HEALTHCARE LIMITED       Lagos                  https://gorahhmo.com/\n                           GNI HEALTHCARE LTD       Lagos               https://greenbayhmo.com/\n         GREENBAY HEALTHCARE SERVICES LIMITED       Lagos             http://www.groominghm.com/\n             GREENFIELD HEALTH MANAGEMENT LTD         N/A               https://hallmarkhmo.com/\n           GROOMING HEALTH MANAGEMENT LIMITED       Lagos           https://www.healthassur.com/\n             HALLMARK HEALTH SERVICES LIMITED       Lagos          https://healthpartnersng.org/\n                      Health Partners Limited         N/A           https://healthspringhmo.com/\n             HEALTHCARE INTERNATIONAL LIMITED       Lagos                 https://hygeiahmo.com/\n      Infinite X2 Health Maintenance Services      Kaduna               https://ihmsnigeria.com/\n                        INTEGRATED HEALTHCARE         FCT          https://www.ivesmedicare.com/\n                                IVES MEDICARE       Lagos             https://leadwayhealth.com/\n                         KENNEDIA HMO LIMITED       Lagos              https://lifeworthhmo.com/\n                      LIFE WORTH MEDICARE LTD       Lagos           https://marinamedicalhmo.ng/\n                 LIFESAVER HEALTHCARE LIMITED       Lagos                  https://markfema.com/\n                  MAAYOIT HEALTH CARE LIMITED       Kwara               https://masslife.com.ng/\n          MARINA MEDICAL SERVICES HMO LIMITED       Lagos                 https://mbandohmo.com/\n                        MARKFEMA NIGERIA LTD.         FCT                   https://medexia.com/\n                  MASSLIFE HEALTHCARE LIMITED         FCT               https://masslife.com.ng/\n           MB & O HEALTHCARE SERVICES LIMITED       Lagos        https://mediplanhealthcare.com/\n                              MEDEXIA LIMITED       Lagos        https://www.metrohealthhmo.com/\n                    MEDICARE ALLIANCE LIMITED         FCT                https://nem-health.com/\n                      METROHEALTH HMO LIMITED       Lagos            https://www.nonsuchhmo.com/\n                             NNPC-HMO LIMITED         N/A         https://www.oceanichealth.com/\n                     NONSUCH MEDICARE LIMITED         Oyo                https://peramarehmo.ng/\n                             NOOR HEALTH LTD.       Lagos               https://phillipshmo.net/\n                   NOVO HEALTH AFRICA LIMITED       Lagos           https://www.phmlnigeria.com/\n            OCEANIC HEALTH MANAGEMENT LIMITED Lagos / FCT               https://precioushmo.com/\n   PERAMARE HEALTH MANAGEMENT COMPANY LIMITED         FCT         https://prepaidmedicareng.com/\n  PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED       Lagos               https://phillipshmo.net/\n            POLICE HEALTH MAINTENANCE LIMITED         FCT              https://prohealthhmo.com/\n                  PRECIOUS HEALTHCARE LIMITED         FCT     https://redcarehmo.com/contact-us/\n               PREPAID MEDICARE SERVICES LTD.         FCT         https://regenixhealthcare.com/\n                             PRINCETON HEALTH         Oyo https://getreliancehealth.com/nigeria/\n                            PROHEALTH HMO LTD         FCT          https://www.prohealthhmo.com/\n              REDCARE HEALTH SERVICES LIMITED         N/A             https://ronsbergerhmo.com/\n          REGENIX HEALTH CARE SERVICE LIMITED      Rivers            https://rothaugehealth.com/\n                         RELIANCE HMO LIMITED       Lagos          http://www.royalhealthms.com/\n                       RODING HEALTHCARE LTD.       Lagos              https://salustrustng.com/\n                      RONSBERGER NIGERIA LTD.         FCT                 https://seraphhmo.com/\n       ROYAL HEALTH MAINTENANCE SERVICES LTD.         Imo    https://www.songhaihealthtrust.com/\n                           SERAPH HMO LIMITED       Benue      http://www.sterlinghealthmcs.com/\n                         SKYDA HEALTH LIMITED         FCT                 https://skydalink.com/\nSTERLING HEALTH MANAGED CARE SERVICES LIMITED       Lagos         https://ultimatehealthhmo.com/\n                   TOTAL HEALTH TRUST LIMITED       Lagos         https://www.venusmedicare.com/\n    UNITED COMPREHENSIVE HEALTH MANAGERS LTD.      Rivers         https://wellhealthnetwork.com/\n                  WELL HEALTH NETWORK LIMITED       Enugu               http://www.hyssophmo.com\n  WELLNESS HEALTH MANAGEMENT SERVICES LIMITED       Lagos       http://www.hopewellhealthcare.ng\n                            ZUMA HEALTH TRUST         FCT             http://www.smarthealth.com\n                         Healthnomics HMO PLC         FCT          http://www.healthassur.com%20\n    HYSSOP Health International Limited (HMO)       Delta                http://www.questhmo.com\n           Hopewell Healthcare Management Ltd         FCT          http://www.lifeactionplus.com\n                         Crown Jewel HMO Ltd.         FCT               http://www.aspirehmo.com\n                  Smathealth Medicare Limited       Lagos            http://www.miterahealth.com\n                       Quest Medicare Limited       Lagos                                    N/A\n                        Life Action Plus Ltd.       Lagos                                    N/A\n                        Zenor Healthcare Ltd.       Lagos                                    N/A\n                           Aspire HMO Limited       Lagos                                    N/A\n                        Mitera Health Limited       Lagos                                    N/A'

In [88]:
coverage_na = nigeria_hmo[
    nigeria_hmo["Coverage State"] == "N/A"
][["Name", "State", "Website"]].copy()

coverage_na

,Name,State,Website
0,A&M HEALTHCARE TRUST LIMITED,Adamawa,https://amhmo.com/
3,ALLY HEALTHCARE LIMITED,FCT,https://amanhmo.com/home
4,AMAN HEALTH MAINTENANCE ORGANIZATIONS,FCT,https://anchorhmo.com/
6,ASHMED INTEGRATED HEALTH SERVICES LTD.,Kaduna,https://www.avonhealthcare.com/
10,BONITAS HEALTH MAINTENANCE LIMITED,Rivers,https://clearlinehmo.com/
12,CLEARLINE INTERNATIONAL LIMITED,Lagos,https://delogmedicalhmo.com/
14,Delog Medical Services Ltd. (HMO),Lagos,https://hmo.dot.ai/
15,DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO,Lagos,N/A
16,DOT HMO Ltd.,Lagos,http://gnihealthcare.com/
17,FOUNTAIN HEALTHCARE LIMITED,Lagos,https://gorahhmo.com/
18,GNI HEALTHCARE LTD,Lagos,https://greenbayhmo.com/
20,GREENBAY HEALTHCARE SERVICES LIMITED,Lagos,http://www.groominghm.com/
21,GREENFIELD HEALTH MANAGEMENT LTD,N/A,https://hallmarkhmo.com/
22,GROOMING HEALTH MANAGEMENT LIMITED,Lagos,https://www.healthassur.com/
23,HALLMARK HEALTH SERVICES LIMITED,Lagos,https://healthpartnersng.org/
25,Health Partners Limited,N/A,https://healthspringhmo.com/
26,HEALTHCARE INTERNATIONAL LIMITED,Lagos,https://hygeiahmo.com/
29,Infinite X2 Health Maintenance Services,Kaduna,https://ihmsnigeria.com/
30,INTEGRATED HEALTHCARE,FCT,https://www.ivesmedicare.com/
32,IVES MEDICARE,Lagos,https://leadwayhealth.com/
33,KENNEDIA HMO LIMITED,Lagos,https://lifeworthhmo.com/
35,LIFE WORTH MEDICARE LTD,Lagos,https://marinamedicalhmo.ng/
36,LIFESAVER HEALTHCARE LIMITED,Lagos,https://markfema.com/
37,MAAYOIT HEALTH CARE LIMITED,Kwara,https://masslife.com.ng/
38,MARINA MEDICAL SERVICES HMO LIMITED,Lagos,https://mbandohmo.com/
39,MARKFEMA NIGERIA LTD.,FCT,https://medexia.com/
40,MASSLIFE HEALTHCARE LIMITED,FCT,https://masslife.com.ng/
41,MB & O HEALTHCARE SERVICES LIMITED,Lagos,https://mediplanhealthcare.com/
42,MEDEXIA LIMITED,Lagos,https://www.metrohealthhmo.com/
43,MEDICARE ALLIANCE LIMITED,FCT,https://nem-health.com/
45,METROHEALTH HMO LIMITED,Lagos,https://www.nonsuchhmo.com/
47,NNPC-HMO LIMITED,N/A,https://www.oceanichealth.com/
48,NONSUCH MEDICARE LIMITED,Oyo,https://peramarehmo.ng/
49,NOOR HEALTH LTD.,Lagos,https://phillipshmo.net/
50,NOVO HEALTH AFRICA LIMITED,Lagos,https://www.phmlnigeria.com/
51,OCEANIC HEALTH MANAGEMENT LIMITED,Lagos / FCT,https://precioushmo.com/
52,PERAMARE HEALTH MANAGEMENT COMPANY LIMITED,FCT,https://prepaidmedicareng.com/
53,PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED,Lagos,https://phillipshmo.net/
54,POLICE HEALTH MAINTENANCE LIMITED,FCT,https://prohealthhmo.com/
55,PRECIOUS HEALTHCARE LIMITED,FCT,https://redcarehmo.com/contact-us/
56,PREPAID MEDICARE SERVICES LTD.,FCT,https://regenixhealthcare.com/
57,PRINCETON HEALTH,Oyo,https://getreliancehealth.com/nigeria/
58,PROHEALTH HMO LTD,FCT,https://www.prohealthhmo.com/
59,REDCARE HEALTH SERVICES LIMITED,N/A,https://ronsbergerhmo.com/
60,REGENIX HEALTH CARE SERVICE LIMITED,Rivers,https://rothaugehealth.com/
61,RELIANCE HMO LIMITED,Lagos,http://www.royalhealthms.com/
62,RODING HEALTHCARE LTD.,Lagos,https://salustrustng.com/
63,RONSBERGER NIGERIA LTD.,FCT,https://seraphhmo.com/
65,ROYAL HEALTH MAINTENANCE SERVICES LTD.,Imo,https://www.songhaihealthtrust.com/
67,SERAPH HMO LIMITED,Benue,http://www.sterlinghealthmcs.com/
68,SKYDA HEALTH LIMITED,FCT,https://skydalink.com/
71,STERLING HEALTH MANAGED CARE SERVICES LIMITED,Lagos,https://ultimatehealthhmo.com/
74,TOTAL HEALTH TRUST LIMITED,Lagos,https://www.venusmedicare.com/
76,UNITED COMPREHENSIVE HEALTH MANAGERS LTD.,Rivers,https://wellhealthnetwork.com/
80,WELL HEALTH NETWORK LIMITED,Enugu,http://www.hyssophmo.com
81,WELLNESS HEALTH MANAGEMENT SERVICES LIMITED,Lagos,http://www.hopewellhealthcare.ng
82,ZUMA HEALTH TRUST,FCT,http://www.smarthealth.com
83,Healthnomics HMO PLC,FCT,http://www.healthassur.com%20
84,HYSSOP Health International Limited (HMO),Delta,http://www.questhmo.com
85,Hopewell Healthcare Management Ltd,FCT,http://www.lifeactionplus.com
86,Crown Jewel HMO Ltd.,FCT,http://www.aspirehmo.com
87,Smathealth Medicare Limited,Lagos,http://www.miterahealth.com
89,Quest Medicare Limited,Lagos,N/A
90,Life Action Plus Ltd.,Lagos,N/A
91,Zenor Healthcare Ltd.,Lagos,N/A
92,Aspire HMO Limited,Lagos,N/A
93,Mitera Health Limited,Lagos,N/A

In [89]:
nigeria_hmo[["Name", "Website"]].to_string(index=False)

'                                         Name                                      Website\n                 A&M HEALTHCARE TRUST LIMITED                           https://amhmo.com/\n            AIICO MULTISHIELD NIGERIA LIMITED            https://www.aiicomultishield.com/\n           ALLEANZA HEALTH MANAGEMENT LIMITED https://alleanzahealth.com/individual-plans/\n                      ALLY HEALTHCARE LIMITED                     https://amanhmo.com/home\n        AMAN HEALTH MAINTENANCE ORGANIZATIONS                       https://anchorhmo.com/\n     ANCHOR HMO INTERNATIONAL COMPANY LIMITED  https://ashmedintegratedhealthservices.com/\n       ASHMED INTEGRATED HEALTH SERVICES LTD.              https://www.avonhealthcare.com/\n                      AVON HEALTHCARE LIMITED     https://www.axamansard.com/health/plans/\n                   AXA MANSARD HEALTH LIMITED                      https://bastionhmo.com/\n                       BASTION HEALTH LIMITED             https://www.centurymedicaid.org/\n           BONITAS HEALTH MAINTENANCE LIMITED                    https://clearlinehmo.com/\n            CENTURY MEDICAID SERVICES LIMITED                  https://www.dhmlnigeria.com\n              CLEARLINE INTERNATIONAL LIMITED                 https://delogmedicalhmo.com/\n           DEFENCE HEALTH MAINTENANCE LIMITED                          https://doheec.com/\n            Delog Medical Services Ltd. (HMO)                          https://hmo.dot.ai/\n  DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO                                          N/A\n                                 DOT HMO Ltd.                    http://gnihealthcare.com/\n                  FOUNTAIN HEALTHCARE LIMITED                        https://gorahhmo.com/\n                           GNI HEALTHCARE LTD                     https://greenbayhmo.com/\n                        GORAH HEALTHCARE LTD.               https://www.greenfieldhmo.com/\n         GREENBAY HEALTHCARE SERVICES LIMITED                   http://www.groominghm.com/\n             GREENFIELD HEALTH MANAGEMENT LTD                     https://hallmarkhmo.com/\n           GROOMING HEALTH MANAGEMENT LIMITED                 https://www.healthassur.com/\n             HALLMARK HEALTH SERVICES LIMITED                https://healthpartnersng.org/\n                         HEALTH ASSUR LIMITED                https://www.hcihealthcare.ng/\n                      Health Partners Limited                 https://healthspringhmo.com/\n             HEALTHCARE INTERNATIONAL LIMITED                       https://hygeiahmo.com/\n                             HEALTHSPRING HMO                 https://healthspringhmo.com/\n                           HYGEIA HMO LIMITED         https://integratedhealthcareltd.com/\n      Infinite X2 Health Maintenance Services                     https://ihmsnigeria.com/\n                        INTEGRATED HEALTHCARE                https://www.ivesmedicare.com/\n           INTERNATIONAL HEALTH MGT. SERVICES                     https://kennediahmo.com/\n                                IVES MEDICARE                   https://leadwayhealth.com/\n                         KENNEDIA HMO LIMITED                    https://lifeworthhmo.com/\n                       LEADWAY HEALTH LIMITED                   https://maayoithealth.org/\n                      LIFE WORTH MEDICARE LTD                 https://marinamedicalhmo.ng/\n                 LIFESAVER HEALTHCARE LIMITED                        https://markfema.com/\n                  MAAYOIT HEALTH CARE LIMITED                     https://masslife.com.ng/\n          MARINA MEDICAL SERVICES HMO LIMITED                       https://mbandohmo.com/\n                        MARKFEMA NIGERIA LTD.                         https://medexia.com/\n                  MASSLIFE HEALTHCARE LIMITED                     https://masslife.com.ng/\n           MB & O HEALTHCARE SERVICES LIMITED              https://mediplanhealthcare.com/\n                              MEDEXIA LIMITED              https://www.metrohealthhmo.com/\n                    MEDICARE ALLIANCE LIMITED                      https://nem-health.com/\n                  MEDIPLAN HEALTHCARE LIMITED              https://mediplanhealthcare.com/\n                      METROHEALTH HMO LIMITED                  https://www.nonsuchhmo.com/\n                           NEM HEALTH LIMITED            https://www.novohealthafrica.org/\n                             NNPC-HMO LIMITED               https://www.oceanichealth.com/\n                     NONSUCH MEDICARE LIMITED                      https://peramarehmo.ng/\n                             NOOR HEALTH LTD.                     https://phillipshmo.net/\n                   NOVO HEALTH AFRICA LIMITED                 https://www.phmlnigeria.com/\n            OCEANIC HEALTH MANAGEMENT LIMITED                     https://precioushmo.com/\n   PERAMARE HEALTH MANAGEMENT COMPANY LIMITED               https://prepaidmedicareng.com/\n  PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED                     https://phillipshmo.net/\n            POLICE HEALTH MAINTENANCE LIMITED                    https://prohealthhmo.com/\n                  PRECIOUS HEALTHCARE LIMITED           https://redcarehmo.com/contact-us/\n               PREPAID MEDICARE SERVICES LTD.               https://regenixhealthcare.com/\n                             PRINCETON HEALTH       https://getreliancehealth.com/nigeria/\n                            PROHEALTH HMO LTD                https://www.prohealthhmo.com/\n              REDCARE HEALTH SERVICES LIMITED                   https://ronsbergerhmo.com/\n          REGENIX HEALTH CARE SERVICE LIMITED                  https://rothaugehealth.com/\n                         RELIANCE HMO LIMITED                http://www.royalhealthms.com/\n                       RODING HEALTHCARE LTD.                    https://salustrustng.com/\n                      RONSBERGER NIGERIA LTD.                       https://seraphhmo.com/\n                  ROTHAUGE HEALTHCARE LIMITED                   https://www.skydalink.com/\n       ROYAL HEALTH MAINTENANCE SERVICES LTD.          https://www.songhaihealthtrust.com/\n                              SALUS TRUST GTE                   https://springtidehmo.com/\n                           SERAPH HMO LIMITED            http://www.sterlinghealthmcs.com/\n                         SKYDA HEALTH LIMITED                       https://skydalink.com/\n                         SONGHAI HEALTH TRUST                 https://synergywellcare.com/\n          SPRINGTIDE HEALTHCARE SERVICES LTD.                   https://springtidehmo.com/\nSTERLING HEALTH MANAGED CARE SERVICES LIMITED               https://ultimatehealthhmo.com/\n                  SUNU HEALTH NIGERIA LIMITED                        https://www.uchm.net/\n            SYNERGY WELLCARE MEDICAID LIMITED             https://unitedhealthcare-ng.com/\n                   TOTAL HEALTH TRUST LIMITED               https://www.venusmedicare.com/\n      ULTIMATE HEALTH MANAGEMENT SERVICES LTD            https://veritashealthcareltd.com/\n    UNITED COMPREHENSIVE HEALTH MANAGERS LTD.               https://wellhealthnetwork.com/\n      UNITED HEALTHCARE INTERNATIONAL LIMITED       https://www.wellnesshealthcare.com.ng/\n                           VENUS MEDICARE LTD                  https://zumahealthtrust.ng/\n                   VERITAS HEALTHCARE LIMITED            http://www.healthnomicshmoplc.org\n                  WELL HEALTH NETWORK LIMITED                     http://www.hyssophmo.com\n  WELLNESS HEALTH MANAGEMENT SERVICES LIMITED             http://www.hopewellhealthcare.ng\n                            ZUMA HEALTH TRUST                   http://www.smarthealth.com\n                         Healthnomics HMO PLC                http://www.healthassur.com%20\n    HYSSOP Health International Limited (HMO)                      http://www.questhmo.com\n           Hopewell Healthcare Management Ltd                http://www.lifeactionplus.com\n                         Crown Jewel HMO Ltd.                     http://www.aspirehmo.com\n                  Smathealth Medicare Limited                  http://www.miterahealth.com\n                         Health Assur Limited                                          N/A\n                       Quest Medicare Limited                                          N/A\n                        Life Action Plus Ltd.                                          N/A\n                        Zenor Healthcare Ltd.                                          N/A\n                           Aspire HMO Limited                                          N/A\n                        Mitera Health Limited                                          N/A'

In [90]:
nigeria_hmo[["S/NO.", "Name", "Website"]].head(20)

,S/NO.,Name,Website
0,1,A&M HEALTHCARE TRUST LIMITED,https://amhmo.com/
1,2,AIICO MULTISHIELD NIGERIA LIMITED,https://www.aiicomultishield.com/
2,3,ALLEANZA HEALTH MANAGEMENT LIMITED,https://alleanzahealth.com/individual-plans/
3,4,ALLY HEALTHCARE LIMITED,https://amanhmo.com/home
4,5,AMAN HEALTH MAINTENANCE ORGANIZATIONS,https://anchorhmo.com/
5,6,ANCHOR HMO INTERNATIONAL COMPANY LIMITED,https://ashmedintegratedhealthservices.com/
6,7,ASHMED INTEGRATED HEALTH SERVICES LTD.,https://www.avonhealthcare.com/
7,8,AVON HEALTHCARE LIMITED,https://www.axamansard.com/health/plans/
8,9,AXA MANSARD HEALTH LIMITED,https://bastionhmo.com/
9,10,BASTION HEALTH LIMITED,https://www.centurymedicaid.org/
10,11,BONITAS HEALTH MAINTENANCE LIMITED,https://clearlinehmo.com/
11,12,CENTURY MEDICAID SERVICES LIMITED,https://www.dhmlnigeria.com
12,13,CLEARLINE INTERNATIONAL LIMITED,https://delogmedicalhmo.com/
13,14,DEFENCE HEALTH MAINTENANCE LIMITED,https://doheec.com/
14,15,Delog Medical Services Ltd. (HMO),https://hmo.dot.ai/
15,16,DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO,N/A
16,17,DOT HMO Ltd.,http://gnihealthcare.com/
17,18,FOUNTAIN HEALTHCARE LIMITED,https://gorahhmo.com/
18,19,GNI HEALTHCARE LTD,https://greenbayhmo.com/
19,20,GORAH HEALTHCARE LTD.,https://www.greenfieldhmo.com/

In [93]:
nigeria_hmo[['Name', 'State', 'Region', 'Coverage State']]

,Name,State,Region,Coverage State
0,A&M HEALTHCARE TRUST LIMITED,Adamawa,North East,N/A
1,AIICO MULTISHIELD NIGERIA LIMITED,Lagos,South West,Nationwide – Nigeria
2,ALLEANZA HEALTH MANAGEMENT LIMITED,Lagos,South West,Nationwide – Nigeria
3,ALLY HEALTHCARE LIMITED,FCT,North Central,N/A
4,AMAN HEALTH MAINTENANCE ORGANIZATIONS,FCT,North Central,N/A
5,ANCHOR HMO INTERNATIONAL COMPANY LIMITED,N/A,N/A,Nationwide – Nigeria
6,ASHMED INTEGRATED HEALTH SERVICES LTD.,Kaduna,North West,N/A
7,AVON HEALTHCARE LIMITED,Lagos,South West,Nationwide – Nigeria
8,AXA MANSARD HEALTH LIMITED,Lagos,South West,Nationwide – Nigeria
9,BASTION HEALTH LIMITED,Lagos,South West,Nationwide – Nigeria
10,BONITAS HEALTH MAINTENANCE LIMITED,Rivers,South South,N/A
11,CENTURY MEDICAID SERVICES LIMITED,Rivers,South South,Nationwide – Nigeria
12,CLEARLINE INTERNATIONAL LIMITED,Lagos,South West,N/A
13,DEFENCE HEALTH MAINTENANCE LIMITED,FCT,North Central,All 36 States + FCT
14,Delog Medical Services Ltd. (HMO),Lagos,South West,N/A
15,DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO,Lagos,South West,N/A
16,DOT HMO Ltd.,Lagos,South West,N/A
17,FOUNTAIN HEALTHCARE LIMITED,Lagos,South West,N/A
18,GNI HEALTHCARE LTD,Lagos,South West,N/A
19,GORAH HEALTHCARE LTD.,Lagos,South West,Nationwide – Nigeria
20,GREENBAY HEALTHCARE SERVICES LIMITED,Lagos,South West,N/A
21,GREENFIELD HEALTH MANAGEMENT LTD,N/A,N/A,N/A
22,GROOMING HEALTH MANAGEMENT LIMITED,Lagos,South West,N/A
23,HALLMARK HEALTH SERVICES LIMITED,Lagos,South West,N/A
24,HEALTH ASSUR LIMITED,Lagos,South West,Nationwide – Nigeria
25,Health Partners Limited,N/A,N/A,N/A
26,HEALTHCARE INTERNATIONAL LIMITED,Lagos,South West,N/A
27,HEALTHSPRING HMO,FCT,North Central,Nationwide – Nigeria
28,HYGEIA HMO LIMITED,Lagos,South West,Nationwide – Nigeria
29,Infinite X2 Health Maintenance Services,Kaduna,North West,N/A
30,INTEGRATED HEALTHCARE,FCT,North Central,N/A
31,INTERNATIONAL HEALTH MGT. SERVICES,FCT,North Central,Nationwide – Nigeria
32,IVES MEDICARE,Lagos,South West,N/A
33,KENNEDIA HMO LIMITED,Lagos,South West,N/A
34,LEADWAY HEALTH LIMITED,Lagos,South West,Nationwide – Nigeria
35,LIFE WORTH MEDICARE LTD,Lagos,South West,N/A
36,LIFESAVER HEALTHCARE LIMITED,Lagos,South West,N/A
37,MAAYOIT HEALTH CARE LIMITED,Kwara,North Central,N/A
38,MARINA MEDICAL SERVICES HMO LIMITED,Lagos,South West,N/A
39,MARKFEMA NIGERIA LTD.,FCT,North Central,N/A
40,MASSLIFE HEALTHCARE LIMITED,FCT,North Central,N/A
41,MB & O HEALTHCARE SERVICES LIMITED,Lagos,South West,N/A
42,MEDEXIA LIMITED,Lagos,South West,N/A
43,MEDICARE ALLIANCE LIMITED,FCT,North Central,N/A
44,MEDIPLAN HEALTHCARE LIMITED,Lagos,South West,Nationwide – Nigeria
45,METROHEALTH HMO LIMITED,Lagos,South West,N/A
46,NEM HEALTH LIMITED,Lagos,South West,Nationwide – Nigeria
47,NNPC-HMO LIMITED,N/A,N/A,N/A
48,NONSUCH MEDICARE LIMITED,Oyo,South West,N/A
49,NOOR HEALTH LTD.,Lagos,South West,N/A
50,NOVO HEALTH AFRICA LIMITED,Lagos,South West,N/A
51,OCEANIC HEALTH MANAGEMENT LIMITED,Lagos / FCT,N/A,N/A
52,PERAMARE HEALTH MANAGEMENT COMPANY LIMITED,FCT,North Central,N/A
53,PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED,Lagos,South West,N/A
54,POLICE HEALTH MAINTENANCE LIMITED,FCT,North Central,N/A
55,PRECIOUS HEALTHCARE LIMITED,FCT,North Central,N/A
56,PREPAID MEDICARE SERVICES LTD.,FCT,North Central,N/A
57,PRINCETON HEALTH,Oyo,South West,N/A
58,PROHEALTH HMO LTD,FCT,North Central,N/A
59,REDCARE HEALTH SERVICES LIMITED,N/A,N/A,N/A
60,REGENIX HEALTH CARE SERVICE LIMITED,Rivers,South South,N/A
61,RELIANCE HMO LIMITED,Lagos,South West,N/A
62,RODING HEALTHCARE LTD.,Lagos,South West,N/A
63,RONSBERGER NIGERIA LTD.,FCT,North Central,N/A
64,ROTHAUGE HEALTHCARE LIMITED,Lagos,South West,Nationwide – Nigeria
65,ROYAL HEALTH MAINTENANCE SERVICES LTD.,Imo,South East,N/A
66,SALUS TRUST GTE,Lagos,South West,Nationwide – Nigeria
67,SERAPH HMO LIMITED,Benue,North Central,N/A
68,SKYDA HEALTH LIMITED,FCT,North Central,N/A
69,SONGHAI HEALTH TRUST,FCT,North Central,Nationwide – Nigeria
70,SPRINGTIDE HEALTHCARE SERVICES LTD.,Rivers,South South,Nationwide – Nigeria
71,STERLING HEALTH MANAGED CARE SERVICES LIMITED,Lagos,South West,N/A
72,SUNU HEALTH NIGERIA LIMITED,Lagos,South West,Nationwide – Nigeria
73,SYNERGY WELLCARE MEDICAID LIMITED,Rivers,South South,Nationwide – Nigeria
74,TOTAL HEALTH TRUST LIMITED,Lagos,South West,N/A
75,ULTIMATE HEALTH MANAGEMENT SERVICES LTD,FCT,North Central,Nationwide – Nigeria
76,UNITED COMPREHENSIVE HEALTH MANAGERS LTD.,Rivers,South South,N/A
77,UNITED HEALTHCARE INTERNATIONAL LIMITED,FCT,North Central,Nationwide – Nigeria
78,VENUS MEDICARE LTD,FCT,North Central,Nationwide – Nigeria
79,VERITAS HEALTHCARE LIMITED,FCT,North Central,Nationwide – Nigeria
80,WELL HEALTH NETWORK LIMITED,Enugu,South East,N/A
81,WELLNESS HEALTH MANAGEMENT SERVICES LIMITED,Lagos,South West,N/A
82,ZUMA HEALTH TRUST,FCT,North Central,N/A
83,Healthnomics HMO PLC,FCT,North Central,N/A
84,HYSSOP Health International Limited (HMO),Delta,South South,N/A
85,Hopewell Healthcare Management Ltd,FCT,North Central,N/A
86,Crown Jewel HMO Ltd.,FCT,North Central,N/A
87,Smathealth Medicare Limited,Lagos,South West,N/A
88,Health Assur Limited,Lagos,South West,Nationwide – Nigeria
89,Quest Medicare Limited,Lagos,South West,N/A
90,Life Action Plus Ltd.,Lagos,South West,N/A
91,Zenor Healthcare Ltd.,Lagos,South West,N/A
92,Aspire HMO Limited,Lagos,South West,N/A
93,Mitera Health Limited,Lagos,South West,N/A

In [95]:
nigeria_hmo['Coverage State'].value_counts(dropna=False)

Coverage State
N/A                     67
Nationwide – Nigeria    26
All 36 States + FCT      1
Name: count, dtype: int64

In [98]:
# ==========================================
# FINAL COVERAGE STATE CLEANUP
# ==========================================

coverage_map = {
    'A&M HEALTHCARE TRUST LIMITED': 'Adamawa',
    'AIICO MULTISHIELD NIGERIA LIMITED': 'Nationwide – Nigeria',
    'ALLEANZA HEALTH MANAGEMENT LIMITED': 'Nationwide – Nigeria',
    'ALLY HEALTHCARE LIMITED': 'FCT',
    'AMAN HEALTH MAINTENANCE ORGANIZATIONS': 'FCT',
    'ANCHOR HMO INTERNATIONAL COMPANY LIMITED': 'Nationwide – Nigeria',
    'ASHMED INTEGRATED HEALTH SERVICES LTD.': 'Kaduna',
    'AVON HEALTHCARE LIMITED': 'Nationwide – Nigeria',
    'AXA MANSARD HEALTH LIMITED': 'Nationwide – Nigeria',
    'BASTION HEALTH LIMITED': 'Lagos',
    'BONITAS HEALTH MAINTENANCE LIMITED': 'Rivers',
    'CENTURY MEDICAID SERVICES LIMITED': 'Rivers',
    'CLEARLINE INTERNATIONAL LIMITED': 'Nationwide – Nigeria',
    'DEFENCE HEALTH MAINTENANCE LIMITED': 'Nationwide – Nigeria',
    'Delog Medical Services Ltd. (HMO)': 'Lagos',
    'DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO': 'Lagos',
    'DOT HMO Ltd.': 'Nationwide – Nigeria',
    'FOUNTAIN HEALTHCARE LIMITED': 'Nationwide – Nigeria',
    'GNI HEALTHCARE LTD': 'Nationwide – Nigeria',
    'GORAH HEALTHCARE LTD.': 'Lagos',
    'GREENBAY HEALTHCARE SERVICES LIMITED': 'Nationwide – Nigeria',
    'GREENFIELD HEALTH MANAGEMENT LTD': 'Nationwide – Nigeria',
    'GROOMING HEALTH MANAGEMENT LIMITED': 'Lagos',
    'HALLMARK HEALTH SERVICES LIMITED': 'Lagos',
    'HEALTH ASSUR LIMITED': 'Nationwide – Nigeria',
    'Health Partners Limited': 'Nationwide – Nigeria',
    'HEALTHCARE INTERNATIONAL LIMITED': 'Nationwide – Nigeria',
    'HEALTHSPRING HMO': 'FCT',
    'HYGEIA HMO LIMITED': 'Nationwide – Nigeria',
    'Infinite X2 Health Maintenance Services': 'Kaduna',
    'INTEGRATED HEALTHCARE': 'Nationwide – Nigeria',
    'INTERNATIONAL HEALTH MGT. SERVICES': 'Nationwide – Nigeria',
    'IVES MEDICARE': 'Lagos',
    'KENNEDIA HMO LIMITED': 'Lagos',
    'LEADWAY HEALTH LIMITED': 'Nationwide – Nigeria',
    'LIFE WORTH MEDICARE LTD': 'Nationwide – Nigeria',
    'LIFESAVER HEALTHCARE LIMITED': 'Lagos',
    'MAAYOIT HEALTH CARE LIMITED': 'Kwara',
    'MARINA MEDICAL SERVICES HMO LIMITED': 'Lagos',
    'MARKFEMA NIGERIA LTD.': 'FCT',
    'MASSLIFE HEALTHCARE LIMITED': 'FCT',
    'MB & O HEALTHCARE SERVICES LIMITED': 'Lagos',
    'MEDEXIA LIMITED': 'Lagos',
    'MEDICARE ALLIANCE LIMITED': 'FCT',
    'MEDIPLAN HEALTHCARE LIMITED': 'Nationwide – Nigeria',
    'METROHEALTH HMO LIMITED': 'Nationwide – Nigeria',
    'NEM HEALTH LIMITED': 'Nationwide – Nigeria',
    'NNPC-HMO LIMITED': 'Nationwide – Nigeria',
    'NONSUCH MEDICARE LIMITED': 'Oyo',
    'NOOR HEALTH LTD.': 'Lagos',
    'NOVO HEALTH AFRICA LIMITED': 'Nationwide – Nigeria',
    'OCEANIC HEALTH MANAGEMENT LIMITED': 'Lagos / FCT',
    'PERAMARE HEALTH MANAGEMENT COMPANY LIMITED': 'FCT',
    'PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED': 'Lagos',
    'POLICE HEALTH MAINTENANCE LIMITED': 'Nationwide – Nigeria',
    'PRECIOUS HEALTHCARE LIMITED': 'FCT',
    'PREPAID MEDICARE SERVICES LTD.': 'Nationwide – Nigeria',
    'PRINCETON HEALTH': 'Oyo',
    'PROHEALTH HMO LTD': 'Nationwide – Nigeria',
    'REDCARE HEALTH SERVICES LIMITED': 'Nationwide – Nigeria',
    'REGENIX HEALTH CARE SERVICE LIMITED': 'Rivers',
    'RELIANCE HMO LIMITED': 'Nationwide – Nigeria',
    'RODING HEALTHCARE LTD.': 'Lagos',
    'RONSBERGER NIGERIA LTD.': 'FCT',
    'ROTHAUGE HEALTHCARE LIMITED': 'Lagos',
    'ROYAL HEALTH MAINTENANCE SERVICES LTD.': 'Imo',
    'SALUS TRUST GTE': 'Lagos',
    'SERAPH HMO LIMITED': 'Benue',
    'SKYDA HEALTH LIMITED': 'FCT',
    'SONGHAI HEALTH TRUST': 'FCT',
    'SPRINGTIDE HEALTHCARE SERVICES LTD.': 'Rivers',
    'STERLING HEALTH MANAGED CARE SERVICES LIMITED': 'Nationwide – Nigeria',
    'SUNU HEALTH NIGERIA LIMITED': 'Nationwide – Nigeria',
    'SYNERGY WELLCARE MEDICAID LIMITED': 'Rivers',
    'TOTAL HEALTH TRUST LIMITED': 'Nationwide – Nigeria',
    'ULTIMATE HEALTH MANAGEMENT SERVICES LTD': 'Nationwide – Nigeria',
    'UNITED COMPREHENSIVE HEALTH MANAGERS LTD.': 'Rivers',
    'UNITED HEALTHCARE INTERNATIONAL LIMITED': 'Nationwide – Nigeria',
    'VENUS MEDICARE LTD': 'FCT',
    'VERITAS HEALTHCARE LIMITED': 'FCT',
    'WELL HEALTH NETWORK LIMITED': 'Enugu',
    'WELLNESS HEALTH MANAGEMENT SERVICES LIMITED': 'Lagos',
    'ZUMA HEALTH TRUST': 'FCT',
    'Healthnomics HMO PLC': 'FCT',
    'HYSSOP Health International Limited (HMO)': 'Delta',
    'Hopewell Healthcare Management Ltd': 'FCT',
    'Crown Jewel HMO Ltd.': 'FCT',
    'Smathealth Medicare Limited': 'Lagos',
    'Quest Medicare Limited': 'Lagos',
    'Life Action Plus Ltd.': 'Lagos',
    'Zenor Healthcare Ltd.': 'Lagos',
    'Aspire HMO Limited': 'Lagos',
    'Mitera Health Limited': 'Lagos'
}

nigeria_hmo['Coverage State'] = nigeria_hmo['Name'].map(coverage_map)

print("Missing Coverage State:", nigeria_hmo['Coverage State'].isna().sum())

nigeria_hmo[['Name', 'State', 'Coverage State']]

Missing Coverage State: 1

,Name,State,Coverage State
0,A&M HEALTHCARE TRUST LIMITED,Adamawa,Adamawa
1,AIICO MULTISHIELD NIGERIA LIMITED,Lagos,Nationwide – Nigeria
2,ALLEANZA HEALTH MANAGEMENT LIMITED,Lagos,Nationwide – Nigeria
3,ALLY HEALTHCARE LIMITED,FCT,FCT
4,AMAN HEALTH MAINTENANCE ORGANIZATIONS,FCT,FCT
5,ANCHOR HMO INTERNATIONAL COMPANY LIMITED,N/A,Nationwide – Nigeria
6,ASHMED INTEGRATED HEALTH SERVICES LTD.,Kaduna,Kaduna
7,AVON HEALTHCARE LIMITED,Lagos,Nationwide – Nigeria
8,AXA MANSARD HEALTH LIMITED,Lagos,Nationwide – Nigeria
9,BASTION HEALTH LIMITED,Lagos,Lagos
10,BONITAS HEALTH MAINTENANCE LIMITED,Rivers,Rivers
11,CENTURY MEDICAID SERVICES LIMITED,Rivers,Rivers
12,CLEARLINE INTERNATIONAL LIMITED,Lagos,Nationwide – Nigeria
13,DEFENCE HEALTH MAINTENANCE LIMITED,FCT,Nationwide – Nigeria
14,Delog Medical Services Ltd. (HMO),Lagos,Lagos
15,DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO,Lagos,Lagos
16,DOT HMO Ltd.,Lagos,Nationwide – Nigeria
17,FOUNTAIN HEALTHCARE LIMITED,Lagos,Nationwide – Nigeria
18,GNI HEALTHCARE LTD,Lagos,Nationwide – Nigeria
19,GORAH HEALTHCARE LTD.,Lagos,Lagos
20,GREENBAY HEALTHCARE SERVICES LIMITED,Lagos,Nationwide – Nigeria
21,GREENFIELD HEALTH MANAGEMENT LTD,N/A,Nationwide – Nigeria
22,GROOMING HEALTH MANAGEMENT LIMITED,Lagos,Lagos
23,HALLMARK HEALTH SERVICES LIMITED,Lagos,Lagos
24,HEALTH ASSUR LIMITED,Lagos,Nationwide – Nigeria
25,Health Partners Limited,N/A,Nationwide – Nigeria
26,HEALTHCARE INTERNATIONAL LIMITED,Lagos,Nationwide – Nigeria
27,HEALTHSPRING HMO,FCT,FCT
28,HYGEIA HMO LIMITED,Lagos,Nationwide – Nigeria
29,Infinite X2 Health Maintenance Services,Kaduna,Kaduna
30,INTEGRATED HEALTHCARE,FCT,Nationwide – Nigeria
31,INTERNATIONAL HEALTH MGT. SERVICES,FCT,Nationwide – Nigeria
32,IVES MEDICARE,Lagos,Lagos
33,KENNEDIA HMO LIMITED,Lagos,Lagos
34,LEADWAY HEALTH LIMITED,Lagos,Nationwide – Nigeria
35,LIFE WORTH MEDICARE LTD,Lagos,Nationwide – Nigeria
36,LIFESAVER HEALTHCARE LIMITED,Lagos,Lagos
37,MAAYOIT HEALTH CARE LIMITED,Kwara,Kwara
38,MARINA MEDICAL SERVICES HMO LIMITED,Lagos,Lagos
39,MARKFEMA NIGERIA LTD.,FCT,FCT
40,MASSLIFE HEALTHCARE LIMITED,FCT,FCT
41,MB & O HEALTHCARE SERVICES LIMITED,Lagos,Lagos
42,MEDEXIA LIMITED,Lagos,Lagos
43,MEDICARE ALLIANCE LIMITED,FCT,FCT
44,MEDIPLAN HEALTHCARE LIMITED,Lagos,Nationwide – Nigeria
45,METROHEALTH HMO LIMITED,Lagos,Nationwide – Nigeria
46,NEM HEALTH LIMITED,Lagos,Nationwide – Nigeria
47,NNPC-HMO LIMITED,N/A,Nationwide – Nigeria
48,NONSUCH MEDICARE LIMITED,Oyo,Oyo
49,NOOR HEALTH LTD.,Lagos,Lagos
50,NOVO HEALTH AFRICA LIMITED,Lagos,Nationwide – Nigeria
51,OCEANIC HEALTH MANAGEMENT LIMITED,Lagos / FCT,Lagos / FCT
52,PERAMARE HEALTH MANAGEMENT COMPANY LIMITED,FCT,FCT
53,PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED,Lagos,Lagos
54,POLICE HEALTH MAINTENANCE LIMITED,FCT,Nationwide – Nigeria
55,PRECIOUS HEALTHCARE LIMITED,FCT,FCT
56,PREPAID MEDICARE SERVICES LTD.,FCT,Nationwide – Nigeria
57,PRINCETON HEALTH,Oyo,Oyo
58,PROHEALTH HMO LTD,FCT,Nationwide – Nigeria
59,REDCARE HEALTH SERVICES LIMITED,N/A,Nationwide – Nigeria
60,REGENIX HEALTH CARE SERVICE LIMITED,Rivers,Rivers
61,RELIANCE HMO LIMITED,Lagos,Nationwide – Nigeria
62,RODING HEALTHCARE LTD.,Lagos,Lagos
63,RONSBERGER NIGERIA LTD.,FCT,FCT
64,ROTHAUGE HEALTHCARE LIMITED,Lagos,Lagos
65,ROYAL HEALTH MAINTENANCE SERVICES LTD.,Imo,Imo
66,SALUS TRUST GTE,Lagos,Lagos
67,SERAPH HMO LIMITED,Benue,Benue
68,SKYDA HEALTH LIMITED,FCT,FCT
69,SONGHAI HEALTH TRUST,FCT,FCT
70,SPRINGTIDE HEALTHCARE SERVICES LTD.,Rivers,Rivers
71,STERLING HEALTH MANAGED CARE SERVICES LIMITED,Lagos,Nationwide – Nigeria
72,SUNU HEALTH NIGERIA LIMITED,Lagos,Nationwide – Nigeria
73,SYNERGY WELLCARE MEDICAID LIMITED,Rivers,Rivers
74,TOTAL HEALTH TRUST LIMITED,Lagos,Nationwide – Nigeria
75,ULTIMATE HEALTH MANAGEMENT SERVICES LTD,FCT,Nationwide – Nigeria
76,UNITED COMPREHENSIVE HEALTH MANAGERS LTD.,Rivers,Rivers
77,UNITED HEALTHCARE INTERNATIONAL LIMITED,FCT,Nationwide – Nigeria
78,VENUS MEDICARE LTD,FCT,FCT
79,VERITAS HEALTHCARE LIMITED,FCT,FCT
80,WELL HEALTH NETWORK LIMITED,Enugu,Enugu
81,WELLNESS HEALTH MANAGEMENT SERVICES LIMITED,Lagos,Lagos
82,ZUMA HEALTH TRUST,FCT,FCT
83,Healthnomics HMO PLC,FCT,FCT
84,HYSSOP Health International Limited (HMO),Delta,Delta
85,Hopewell Healthcare Management Ltd,FCT,FCT
86,Crown Jewel HMO Ltd.,FCT,FCT
87,Smathealth Medicare Limited,Lagos,Lagos
88,Health Assur Limited,Lagos,NaN
89,Quest Medicare Limited,Lagos,Lagos
90,Life Action Plus Ltd.,Lagos,Lagos
91,Zenor Healthcare Ltd.,Lagos,Lagos
92,Aspire HMO Limited,Lagos,Lagos
93,Mitera Health Limited,Lagos,Lagos

In [100]:
nigeria_hmo['Coverage State'].value_counts(dropna=False)

Coverage State
Nationwide – Nigeria    35
Lagos                   24
FCT                     17
Rivers                   6
Kaduna                   2
Oyo                      2
Adamawa                  1
Kwara                    1
Lagos / FCT              1
Imo                      1
Benue                    1
Enugu                    1
Delta                    1
NaN                      1
Name: count, dtype: int64

In [101]:
nigeria_hmo[nigeria_hmo['Coverage State'].isna()][['S/NO.', 'Name', 'State', 'Website']]

    S/NO.                  Name  State Website
88     89  Health Assur Limited  Lagos     N/A

In [104]:
nigeria_hmo.loc[nigeria_hmo['Name'] == 'Health Assur Limited', 'Coverage State'] = 'Lagos'

In [106]:
nigeria_hmo['Coverage State'].isna().sum()

np.int64(0)

In [108]:
nigeria_hmo[['Name', 'Website', 'Coverage Type']]

,Name,Website,Coverage Type
0,A&M HEALTHCARE TRUST LIMITED,https://amhmo.com/,N/A
1,AIICO MULTISHIELD NIGERIA LIMITED,https://www.aiicomultishield.com/,N/A
2,ALLEANZA HEALTH MANAGEMENT LIMITED,https://alleanzahealth.com/individual-plans/,N/A
3,ALLY HEALTHCARE LIMITED,https://amanhmo.com/home,N/A
4,AMAN HEALTH MAINTENANCE ORGANIZATIONS,https://anchorhmo.com/,N/A
5,ANCHOR HMO INTERNATIONAL COMPANY LIMITED,https://ashmedintegratedhealthservices.com/,N/A
6,ASHMED INTEGRATED HEALTH SERVICES LTD.,https://www.avonhealthcare.com/,N/A
7,AVON HEALTHCARE LIMITED,https://www.axamansard.com/health/plans/,N/A
8,AXA MANSARD HEALTH LIMITED,https://bastionhmo.com/,N/A
9,BASTION HEALTH LIMITED,https://www.centurymedicaid.org/,N/A
10,BONITAS HEALTH MAINTENANCE LIMITED,https://clearlinehmo.com/,N/A
11,CENTURY MEDICAID SERVICES LIMITED,https://www.dhmlnigeria.com,N/A
12,CLEARLINE INTERNATIONAL LIMITED,https://delogmedicalhmo.com/,N/A
13,DEFENCE HEALTH MAINTENANCE LIMITED,https://doheec.com/,N/A
14,Delog Medical Services Ltd. (HMO),https://hmo.dot.ai/,N/A
15,DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO,N/A,N/A
16,DOT HMO Ltd.,http://gnihealthcare.com/,N/A
17,FOUNTAIN HEALTHCARE LIMITED,https://gorahhmo.com/,N/A
18,GNI HEALTHCARE LTD,https://greenbayhmo.com/,N/A
19,GORAH HEALTHCARE LTD.,https://www.greenfieldhmo.com/,N/A
20,GREENBAY HEALTHCARE SERVICES LIMITED,http://www.groominghm.com/,N/A
21,GREENFIELD HEALTH MANAGEMENT LTD,https://hallmarkhmo.com/,N/A
22,GROOMING HEALTH MANAGEMENT LIMITED,https://www.healthassur.com/,N/A
23,HALLMARK HEALTH SERVICES LIMITED,https://healthpartnersng.org/,N/A
24,HEALTH ASSUR LIMITED,https://www.hcihealthcare.ng/,N/A
25,Health Partners Limited,https://healthspringhmo.com/,N/A
26,HEALTHCARE INTERNATIONAL LIMITED,https://hygeiahmo.com/,N/A
27,HEALTHSPRING HMO,https://healthspringhmo.com/,N/A
28,HYGEIA HMO LIMITED,https://integratedhealthcareltd.com/,N/A
29,Infinite X2 Health Maintenance Services,https://ihmsnigeria.com/,N/A
30,INTEGRATED HEALTHCARE,https://www.ivesmedicare.com/,N/A
31,INTERNATIONAL HEALTH MGT. SERVICES,https://kennediahmo.com/,N/A
32,IVES MEDICARE,https://leadwayhealth.com/,N/A
33,KENNEDIA HMO LIMITED,https://lifeworthhmo.com/,N/A
34,LEADWAY HEALTH LIMITED,https://maayoithealth.org/,N/A
35,LIFE WORTH MEDICARE LTD,https://marinamedicalhmo.ng/,N/A
36,LIFESAVER HEALTHCARE LIMITED,https://markfema.com/,N/A
37,MAAYOIT HEALTH CARE LIMITED,https://masslife.com.ng/,N/A
38,MARINA MEDICAL SERVICES HMO LIMITED,https://mbandohmo.com/,N/A
39,MARKFEMA NIGERIA LTD.,https://medexia.com/,N/A
40,MASSLIFE HEALTHCARE LIMITED,https://masslife.com.ng/,N/A
41,MB & O HEALTHCARE SERVICES LIMITED,https://mediplanhealthcare.com/,N/A
42,MEDEXIA LIMITED,https://www.metrohealthhmo.com/,N/A
43,MEDICARE ALLIANCE LIMITED,https://nem-health.com/,N/A
44,MEDIPLAN HEALTHCARE LIMITED,https://mediplanhealthcare.com/,N/A
45,METROHEALTH HMO LIMITED,https://www.nonsuchhmo.com/,N/A
46,NEM HEALTH LIMITED,https://www.novohealthafrica.org/,N/A
47,NNPC-HMO LIMITED,https://www.oceanichealth.com/,N/A
48,NONSUCH MEDICARE LIMITED,https://peramarehmo.ng/,N/A
49,NOOR HEALTH LTD.,https://phillipshmo.net/,N/A
50,NOVO HEALTH AFRICA LIMITED,https://www.phmlnigeria.com/,N/A
51,OCEANIC HEALTH MANAGEMENT LIMITED,https://precioushmo.com/,N/A
52,PERAMARE HEALTH MANAGEMENT COMPANY LIMITED,https://prepaidmedicareng.com/,N/A
53,PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED,https://phillipshmo.net/,N/A
54,POLICE HEALTH MAINTENANCE LIMITED,https://prohealthhmo.com/,N/A
55,PRECIOUS HEALTHCARE LIMITED,https://redcarehmo.com/contact-us/,N/A
56,PREPAID MEDICARE SERVICES LTD.,https://regenixhealthcare.com/,N/A
57,PRINCETON HEALTH,https://getreliancehealth.com/nigeria/,N/A
58,PROHEALTH HMO LTD,https://www.prohealthhmo.com/,N/A
59,REDCARE HEALTH SERVICES LIMITED,https://ronsbergerhmo.com/,N/A
60,REGENIX HEALTH CARE SERVICE LIMITED,https://rothaugehealth.com/,N/A
61,RELIANCE HMO LIMITED,http://www.royalhealthms.com/,N/A
62,RODING HEALTHCARE LTD.,https://salustrustng.com/,N/A
63,RONSBERGER NIGERIA LTD.,https://seraphhmo.com/,N/A
64,ROTHAUGE HEALTHCARE LIMITED,https://www.skydalink.com/,N/A
65,ROYAL HEALTH MAINTENANCE SERVICES LTD.,https://www.songhaihealthtrust.com/,N/A
66,SALUS TRUST GTE,https://springtidehmo.com/,N/A
67,SERAPH HMO LIMITED,http://www.sterlinghealthmcs.com/,N/A
68,SKYDA HEALTH LIMITED,https://skydalink.com/,N/A
69,SONGHAI HEALTH TRUST,https://synergywellcare.com/,N/A
70,SPRINGTIDE HEALTHCARE SERVICES LTD.,https://springtidehmo.com/,N/A
71,STERLING HEALTH MANAGED CARE SERVICES LIMITED,https://ultimatehealthhmo.com/,N/A
72,SUNU HEALTH NIGERIA LIMITED,https://www.uchm.net/,N/A
73,SYNERGY WELLCARE MEDICAID LIMITED,https://unitedhealthcare-ng.com/,N/A
74,TOTAL HEALTH TRUST LIMITED,https://www.venusmedicare.com/,N/A
75,ULTIMATE HEALTH MANAGEMENT SERVICES LTD,https://veritashealthcareltd.com/,N/A
76,UNITED COMPREHENSIVE HEALTH MANAGERS LTD.,https://wellhealthnetwork.com/,N/A
77,UNITED HEALTHCARE INTERNATIONAL LIMITED,https://www.wellnesshealthcare.com.ng/,N/A
78,VENUS MEDICARE LTD,https://zumahealthtrust.ng/,N/A
79,VERITAS HEALTHCARE LIMITED,http://www.healthnomicshmoplc.org,N/A
80,WELL HEALTH NETWORK LIMITED,http://www.hyssophmo.com,N/A
81,WELLNESS HEALTH MANAGEMENT SERVICES LIMITED,http://www.hopewellhealthcare.ng,N/A
82,ZUMA HEALTH TRUST,http://www.smarthealth.com,N/A
83,Healthnomics HMO PLC,http://www.healthassur.com%20,N/A
84,HYSSOP Health International Limited (HMO),http://www.questhmo.com,N/A
85,Hopewell Healthcare Management Ltd,http://www.lifeactionplus.com,N/A
86,Crown Jewel HMO Ltd.,http://www.aspirehmo.com,N/A
87,Smathealth Medicare Limited,http://www.miterahealth.com,N/A
88,Health Assur Limited,N/A,N/A
89,Quest Medicare Limited,N/A,N/A
90,Life Action Plus Ltd.,N/A,N/A
91,Zenor Healthcare Ltd.,N/A,N/A
92,Aspire HMO Limited,N/A,N/A
93,Mitera Health Limited,N/A,N/A

In [111]:

coverage_type = {

    "A&M HEALTHCARE TRUST LIMITED":
        "Individual / Family / Corporate",

    "AIICO MULTISHIELD NIGERIA LIMITED":
        "Individual / Family / Corporate / SME / Group / International",

    "ALLEANZA HEALTH MANAGEMENT LIMITED":
        "Individual / Family / Corporate / Elderly / SME",

    "ALLY HEALTHCARE LIMITED":
        "Individual / Corporate",

    "AMAN HEALTH MAINTENANCE ORGANIZATIONS":
        "Individual / Family / Corporate",

    "ANCHOR HMO INTERNATIONAL COMPANY LIMITED":
        "Individual / Corporate / SME",

    "ASHMED INTEGRATED HEALTH SERVICES LTD.":
        "Individual / Family / Corporate",

    "AVON HEALTHCARE LIMITED":
        "Individual / Family / Corporate",

    "AXA MANSARD HEALTH LIMITED":
        "Individual / Family / Corporate",

    "BASTION HEALTH LIMITED":
        "Individual / Family / Corporate",

    "BONITAS HEALTH MAINTENANCE LIMITED":
        "Individual / Family / Corporate",

    "CENTURY MEDICAID SERVICES LIMITED":
        "Individual / Family / Corporate / Community / Industrial / Educational",

    "CLEARLINE INTERNATIONAL LIMITED":
        "Individual / Family / Corporate",

    "DEFENCE HEALTH MAINTENANCE LIMITED":
        "Corporate / Group / Military",

    "Delog Medical Services Ltd. (HMO)":
        "Individual / Family / Corporate",

    "DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO":
        "Individual / Family / Corporate",

    "DOT HMO Ltd.":
        "Individual / Family / Corporate",

    "FOUNTAIN HEALTHCARE LIMITED":
        "Individual / Family / Corporate",

    "GNI HEALTHCARE LTD":
        "Individual / Family / Corporate",

    "GORAH HEALTHCARE LTD.":
        "Individual / Family / Corporate",

    "GREENBAY HEALTHCARE SERVICES LIMITED":
        "Individual / Family / Corporate",

    "GREENFIELD HEALTH MANAGEMENT LTD":
        "Individual / Family / Corporate",

    "GROOMING HEALTH MANAGEMENT LIMITED":
        "Individual / Corporate / SME",

    "HALLMARK HEALTH SERVICES LIMITED":
        "Retail / SME / Corporate / International",

    "HEALTH ASSUR LIMITED":
        "Individual / Family / Business / Corporate",

    "Health Partners Limited":
        "Retail / SME / Corporate",

    "HEALTHCARE INTERNATIONAL LIMITED":
        "Individual / Family / Corporate / International",

    "HEALTHSPRING HMO":
        "Individual / Family",

    "HYGEIA HMO LIMITED":
        "Individual / Family / Senior Citizens / Maternity / SME / Corporate",

    "Infinite X2 Health Maintenance Services":
        "Individual / Family / Corporate",

    "INTEGRATED HEALTHCARE":
        "Individual / Family / Corporate",

    "INTERNATIONAL HEALTH MGT. SERVICES":
        "Corporate / Group",

    "IVES MEDICARE":
        "Individual / Family / Corporate",

    "KENNEDIA HMO LIMITED":
        "SME / Corporate / Group",

    "LEADWAY HEALTH LIMITED":
        "Retail / SME / Corporate / International",

    "LIFE WORTH MEDICARE LTD":
        "Individual / Family / Corporate",

    "LIFESAVER HEALTHCARE LIMITED":
        "Individual / Family / Corporate",

    "MAAYOIT HEALTH CARE LIMITED":
        "Individual / Family / Corporate",

    "MARINA MEDICAL SERVICES HMO LIMITED":
        "Individual / Family / Corporate",

    "MARKFEMA NIGERIA LTD.":
        "Individual / Family / Corporate",

    "MASSLIFE HEALTHCARE LIMITED":
        "Individual / Family / Corporate",

    "MB & O HEALTHCARE SERVICES LIMITED":
        "Individual / Family / Corporate",

    "MEDEXIA LIMITED":
        "Individual / Family / Corporate",

    "MEDICARE ALLIANCE LIMITED":
        "Individual / Family / Corporate",

    "MEDIPLAN HEALTHCARE LIMITED":
        "Corporate / Individual / Family / Diaspora",

    "METROHEALTH HMO LIMITED":
        "Individual / Family / Corporate",

    "NEM HEALTH LIMITED":
        "Individual / Family / SME / Corporate / Senior Citizens / Diaspora",

    "NNPC-HMO LIMITED":
        "Corporate / Group",

    "NONSUCH MEDICARE LIMITED":
        "Corporate / TISHIP / Community / NHIA",

    "NOOR HEALTH LTD.":
        "Individual / Family / Corporate",

    "NOVO HEALTH AFRICA LIMITED":
        "Individual / Family / Corporate",

    "OCEANIC HEALTH MANAGEMENT LIMITED":
        "Individual / Family / Corporate",

    "PERAMARE HEALTH MANAGEMENT COMPANY LIMITED":
        "Individual / Family / Corporate",

    "PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED":
        "Individual / Family / Corporate",

    "POLICE HEALTH MAINTENANCE LIMITED":
        "Corporate / Group / Police",

    "PRECIOUS HEALTHCARE LIMITED":
        "Individual / Family / Corporate",

    "PREPAID MEDICARE SERVICES LTD.":
        "Individual / Family / Corporate",

    "PRINCETON HEALTH":
        "Individual / Family / Corporate",

    "PROHEALTH HMO LTD":
        "Individual / Family / Corporate / SME / Group / Social Health Insurance",

    "REDCARE HEALTH SERVICES LIMITED":
        "Individual / Family / Corporate",

    "REGENIX HEALTH CARE SERVICE LIMITED":
        "Individual / Family / Corporate",

    "RELIANCE HMO LIMITED":
        "Individual / Family / SME / Corporate",

    "RODING HEALTHCARE LTD.":
        "Individual / Family / Corporate",

    "RONSBERGER NIGERIA LTD.":
        "Individual / Family / Corporate",

    "ROTHAUGE HEALTHCARE LIMITED":
        "Individual / Family / Corporate",

    "ROYAL HEALTH MAINTENANCE SERVICES LTD.":
        "Individual / Family / Corporate",

    "SALUS TRUST GTE":
        "Individual / Family / Student / Corporate",

    "SERAPH HMO LIMITED":
        "Individual / Family / Corporate",

    "SKYDA HEALTH LIMITED":
        "Individual / Family / Corporate",

    "SONGHAI HEALTH TRUST":
        "Individual / Family / Corporate",

    "SPRINGTIDE HEALTHCARE SERVICES LTD.":
        "Individual / Corporate / International",

    "STERLING HEALTH MANAGED CARE SERVICES LIMITED":
        "Individual / Family / Corporate",

    "SUNU HEALTH NIGERIA LIMITED":
        "Individual / Family / Employee / Corporate",

    "SYNERGY WELLCARE MEDICAID LIMITED":
        "Individual / Family / Employee / Business",

    "TOTAL HEALTH TRUST LIMITED":
        "Individual / Family / Corporate",

    "ULTIMATE HEALTH MANAGEMENT SERVICES LTD":
        "Group / Individual / Family / SME / Corporate",

    "UNITED COMPREHENSIVE HEALTH MANAGERS LTD.":
        "Individual / Family / Corporate",

    "UNITED HEALTHCARE INTERNATIONAL LIMITED":
        "Retail / Individual / Family / Corporate / International / Travel",

    "VENUS MEDICARE LTD":
        "Individual / Small Employer / Corporate",

    "VERITAS HEALTHCARE LIMITED":
        "Retail / Individual / Family / Corporate / TISHIP",

    "WELL HEALTH NETWORK LIMITED":
        "Individual / Family / Corporate / Group / Institutional / Student",

    "WELLNESS HEALTH MANAGEMENT SERVICES LIMITED":
        "Individual / Family / Corporate",

    "ZUMA HEALTH TRUST":
        "Individual / Family / Corporate",

    "Healthnomics HMO PLC":
        "Individual / Family",

    "HYSSOP Health International Limited (HMO)":
        "Individual / Family / Corporate",

    "Hopewell Healthcare Management Ltd":
        "Individual / Family",

    "Crown Jewel HMO Ltd.":
        "Individual / Family / SME / Corporate",

    "Smathealth Medicare Limited":
        "Individual / Family / Corporate",

    "Quest Medicare Limited":
        "Individual / Family / Corporate",

    "Life Action Plus Ltd.":
        "Individual / Family / Retail / SME / Corporate / Retirement / Community",

    "Zenor Healthcare Ltd.":
        "Individual / Family / SME / Corporate",

    "Aspire HMO Limited":
        "Individual / Family / Corporate",

    "Mitera Health Limited":
        "Individual / Family / Corporate"
}


# Apply the mapping
nigeria_hmo["Coverage Type"] = nigeria_hmo["Name"].map(coverage_type)


# ============================================================
# CHECKS
# ============================================================

print("Total rows:", len(nigeria_hmo))
print("Missing Coverage Type:", nigeria_hmo["Coverage Type"].isna().sum())

# Display the completed column
display(
    nigeria_hmo[["Name", "Coverage Type"]]
)


# Check the unique categories used
print("\nCoverage Type counts:")
print(nigeria_hmo["Coverage Type"].value_counts())

Total rows: 94
Missing Coverage Type: 1

,Name,Coverage Type
0,A&M HEALTHCARE TRUST LIMITED,Individual / Family / Corporate
1,AIICO MULTISHIELD NIGERIA LIMITED,Individual / Family / Corporate / SME / Group / International
2,ALLEANZA HEALTH MANAGEMENT LIMITED,Individual / Family / Corporate / Elderly / SME
3,ALLY HEALTHCARE LIMITED,Individual / Corporate
4,AMAN HEALTH MAINTENANCE ORGANIZATIONS,Individual / Family / Corporate
5,ANCHOR HMO INTERNATIONAL COMPANY LIMITED,Individual / Corporate / SME
6,ASHMED INTEGRATED HEALTH SERVICES LTD.,Individual / Family / Corporate
7,AVON HEALTHCARE LIMITED,Individual / Family / Corporate
8,AXA MANSARD HEALTH LIMITED,Individual / Family / Corporate
9,BASTION HEALTH LIMITED,Individual / Family / Corporate
10,BONITAS HEALTH MAINTENANCE LIMITED,Individual / Family / Corporate
11,CENTURY MEDICAID SERVICES LIMITED,Individual / Family / Corporate / Community / Industrial / Educational
12,CLEARLINE INTERNATIONAL LIMITED,Individual / Family / Corporate
13,DEFENCE HEALTH MAINTENANCE LIMITED,Corporate / Group / Military
14,Delog Medical Services Ltd. (HMO),Individual / Family / Corporate
15,DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO,Individual / Family / Corporate
16,DOT HMO Ltd.,Individual / Family / Corporate
17,FOUNTAIN HEALTHCARE LIMITED,Individual / Family / Corporate
18,GNI HEALTHCARE LTD,Individual / Family / Corporate
19,GORAH HEALTHCARE LTD.,Individual / Family / Corporate
20,GREENBAY HEALTHCARE SERVICES LIMITED,Individual / Family / Corporate
21,GREENFIELD HEALTH MANAGEMENT LTD,Individual / Family / Corporate
22,GROOMING HEALTH MANAGEMENT LIMITED,Individual / Corporate / SME
23,HALLMARK HEALTH SERVICES LIMITED,Retail / SME / Corporate / International
24,HEALTH ASSUR LIMITED,Individual / Family / Business / Corporate
25,Health Partners Limited,Retail / SME / Corporate
26,HEALTHCARE INTERNATIONAL LIMITED,Individual / Family / Corporate / International
27,HEALTHSPRING HMO,Individual / Family
28,HYGEIA HMO LIMITED,Individual / Family / Senior Citizens / Maternity / SME / Corporate
29,Infinite X2 Health Maintenance Services,Individual / Family / Corporate
30,INTEGRATED HEALTHCARE,Individual / Family / Corporate
31,INTERNATIONAL HEALTH MGT. SERVICES,Corporate / Group
32,IVES MEDICARE,Individual / Family / Corporate
33,KENNEDIA HMO LIMITED,SME / Corporate / Group
34,LEADWAY HEALTH LIMITED,Retail / SME / Corporate / International
35,LIFE WORTH MEDICARE LTD,Individual / Family / Corporate
36,LIFESAVER HEALTHCARE LIMITED,Individual / Family / Corporate
37,MAAYOIT HEALTH CARE LIMITED,Individual / Family / Corporate
38,MARINA MEDICAL SERVICES HMO LIMITED,Individual / Family / Corporate
39,MARKFEMA NIGERIA LTD.,Individual / Family / Corporate
40,MASSLIFE HEALTHCARE LIMITED,Individual / Family / Corporate
41,MB & O HEALTHCARE SERVICES LIMITED,Individual / Family / Corporate
42,MEDEXIA LIMITED,Individual / Family / Corporate
43,MEDICARE ALLIANCE LIMITED,Individual / Family / Corporate
44,MEDIPLAN HEALTHCARE LIMITED,Corporate / Individual / Family / Diaspora
45,METROHEALTH HMO LIMITED,Individual / Family / Corporate
46,NEM HEALTH LIMITED,Individual / Family / SME / Corporate / Senior Citizens / Diaspora
47,NNPC-HMO LIMITED,Corporate / Group
48,NONSUCH MEDICARE LIMITED,Corporate / TISHIP / Community / NHIA
49,NOOR HEALTH LTD.,Individual / Family / Corporate
50,NOVO HEALTH AFRICA LIMITED,Individual / Family / Corporate
51,OCEANIC HEALTH MANAGEMENT LIMITED,Individual / Family / Corporate
52,PERAMARE HEALTH MANAGEMENT COMPANY LIMITED,Individual / Family / Corporate
53,PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED,Individual / Family / Corporate
54,POLICE HEALTH MAINTENANCE LIMITED,Corporate / Group / Police
55,PRECIOUS HEALTHCARE LIMITED,Individual / Family / Corporate
56,PREPAID MEDICARE SERVICES LTD.,Individual / Family / Corporate
57,PRINCETON HEALTH,Individual / Family / Corporate
58,PROHEALTH HMO LTD,Individual / Family / Corporate / SME / Group / Social Health Insurance
59,REDCARE HEALTH SERVICES LIMITED,Individual / Family / Corporate
60,REGENIX HEALTH CARE SERVICE LIMITED,Individual / Family / Corporate
61,RELIANCE HMO LIMITED,Individual / Family / SME / Corporate
62,RODING HEALTHCARE LTD.,Individual / Family / Corporate
63,RONSBERGER NIGERIA LTD.,Individual / Family / Corporate
64,ROTHAUGE HEALTHCARE LIMITED,Individual / Family / Corporate
65,ROYAL HEALTH MAINTENANCE SERVICES LTD.,Individual / Family / Corporate
66,SALUS TRUST GTE,Individual / Family / Student / Corporate
67,SERAPH HMO LIMITED,Individual / Family / Corporate
68,SKYDA HEALTH LIMITED,Individual / Family / Corporate
69,SONGHAI HEALTH TRUST,Individual / Family / Corporate
70,SPRINGTIDE HEALTHCARE SERVICES LTD.,Individual / Corporate / International
71,STERLING HEALTH MANAGED CARE SERVICES LIMITED,Individual / Family / Corporate
72,SUNU HEALTH NIGERIA LIMITED,Individual / Family / Employee / Corporate
73,SYNERGY WELLCARE MEDICAID LIMITED,Individual / Family / Employee / Business
74,TOTAL HEALTH TRUST LIMITED,Individual / Family / Corporate
75,ULTIMATE HEALTH MANAGEMENT SERVICES LTD,Group / Individual / Family / SME / Corporate
76,UNITED COMPREHENSIVE HEALTH MANAGERS LTD.,Individual / Family / Corporate
77,UNITED HEALTHCARE INTERNATIONAL LIMITED,Retail / Individual / Family / Corporate / International / Travel
78,VENUS MEDICARE LTD,Individual / Small Employer / Corporate
79,VERITAS HEALTHCARE LIMITED,Retail / Individual / Family / Corporate / TISHIP
80,WELL HEALTH NETWORK LIMITED,Individual / Family / Corporate / Group / Institutional / Student
81,WELLNESS HEALTH MANAGEMENT SERVICES LIMITED,Individual / Family / Corporate
82,ZUMA HEALTH TRUST,Individual / Family / Corporate
83,Healthnomics HMO PLC,Individual / Family
84,HYSSOP Health International Limited (HMO),Individual / Family / Corporate
85,Hopewell Healthcare Management Ltd,Individual / Family
86,Crown Jewel HMO Ltd.,Individual / Family / SME / Corporate
87,Smathealth Medicare Limited,Individual / Family / Corporate
88,Health Assur Limited,NaN
89,Quest Medicare Limited,Individual / Family / Corporate
90,Life Action Plus Ltd.,Individual / Family / Retail / SME / Corporate / Retirement / Community
91,Zenor Healthcare Ltd.,Individual / Family / SME / Corporate
92,Aspire HMO Limited,Individual / Family / Corporate
93,Mitera Health Limited,Individual / Family / Corporate

Coverage Type counts:
Coverage Type
Individual / Family / Corporate                                            56
Individual / Family / SME / Corporate                                       3
Individual / Family                                                         3
Individual / Corporate / SME                                                2
Corporate / Group                                                           2
Retail / SME / Corporate / International                                    2
Individual / Family / Employee / Corporate                                  1
Individual / Family / Student / Corporate                                   1
Individual / Corporate / International                                      1
Group / Individual / Family / SME / Corporate                               1
Individual / Family / Employee / Business                                   1
Corporate / Group / Police                                                  1
Retail / Individual / Family / Corporate / International / Travel           1
Individual / Small Employer / Corporate                                     1
Retail / Individual / Family / Corporate / TISHIP                           1
Individual / Family / Corporate / Group / Institutional / Student           1
Individual / Family / Corporate / SME / Group / Social Health Insurance     1
Corporate / Individual / Family / Diaspora                                  1
Corporate / TISHIP / Community / NHIA                                       1
Individual / Family / SME / Corporate / Senior Citizens / Diaspora          1
Individual / Family / Corporate / SME / Group / International               1
SME / Corporate / Group                                                     1
Individual / Family / Senior Citizens / Maternity / SME / Corporate         1
Individual / Family / Corporate / International                             1
Retail / SME / Corporate                                                    1
Individual / Family / Business / Corporate                                  1
Corporate / Group / Military                                                1
Individual / Family / Corporate / Community / Industrial / Educational      1
Individual / Corporate                                                      1
Individual / Family / Corporate / Elderly / SME                             1
Individual / Family / Retail / SME / Corporate / Retirement / Community     1
Name: count, dtype: int64

In [112]:

services = {

"A&M HEALTHCARE TRUST LIMITED":
"Outpatient care; Specialist consultation; Inpatient care; Diagnostic services; Prescription medicines; Emergency care; Maternity care",

"AIICO MULTISHIELD NIGERIA LIMITED":
"Medical consultation; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Hospital care; Emergency care; Maternity care",

"ALLEANZA HEALTH MANAGEMENT LIMITED":
"Medical consultation; Hospital admission; Surgery; Maternity care; Emergency care; Pharmacy services; Provider network access",

"ALLY HEALTHCARE LIMITED":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"AMAN HEALTH MAINTENANCE ORGANIZATIONS":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"ANCHOR HMO INTERNATIONAL COMPANY LIMITED":
"Corporate health plans; Retail health plans; Third-party administration; Customized health plans; Emergency support; Claims management",

"ASHMED INTEGRATED HEALTH SERVICES LTD.":
"Managed healthcare; Health insurance; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"AVON HEALTHCARE LIMITED":
"Health insurance; Outpatient care; Inpatient care; Specialist consultation; Diagnostic services; Prescription medicines; Emergency care; Maternity care; Dental care; Optical care",

"AXA MANSARD HEALTH LIMITED":
"Outpatient care; Inpatient care; Surgical services; Routine immunization; Emergency evacuation; Dental care; Eye care; Physiotherapy; Telemedicine; Pharmacy services; Hospital cash",

"BASTION HEALTH LIMITED":
"Health insurance; Outpatient care; Inpatient care; Specialist care; Hospital services; Emergency care; Provider network access; Corporate and individual health plans",

"BONITAS HEALTH MAINTENANCE LIMITED":
"Health insurance; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care",

"CENTURY MEDICAID SERVICES LIMITED":
"Managed healthcare; Health insurance; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"CLEARLINE INTERNATIONAL LIMITED":
"Outpatient care; General and specialist consultation; Teleconsultation; Prescription medicines; Diagnostic and laboratory services; Hospital care; Emergency care",

"DEFENCE HEALTH MAINTENANCE LIMITED":
"Military and defence health insurance; Primary healthcare; Secondary healthcare; Tertiary healthcare; Clinical services; Pharmacy services; Nursing care; Allied medical services; Public health services",

"Delog Medical Services Ltd. (HMO)":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"DOT HMO Ltd.":
"Clinic visits; Diagnostic services; Prescription medicines; Specialist care; Telemedicine; Wellness and preventive care; Emergency support",

"FOUNTAIN HEALTHCARE LIMITED":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care",

"GNI HEALTHCARE LTD":
"Medical consultation; Specialist care; Laboratory and diagnostic services; Prescription medicines; Maternity care; Eye care; Dental care; Immunization; Hospital admission; Surgery; HIV care; Ambulance services",

"GORAH HEALTHCARE LTD.":
"Preventive healthcare; Wellness care; Emergency services; Specialist consultation; Maternity care; Hospital and clinic access",

"GREENBAY HEALTHCARE SERVICES LIMITED":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"GREENFIELD HEALTH MANAGEMENT LTD":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"GROOMING HEALTH MANAGEMENT LIMITED":
"Routine checkups; Specialist consultation; Emergency care; Outpatient care; Inpatient care; Health insurance; Corporate and individual health plans",

"HALLMARK HEALTH SERVICES LIMITED":
"General consultation; Specialist consultation; Diagnostic investigations; Physiotherapy; Renal dialysis; Surgical care; Telemedicine; Gym access; Mortuary cover; Hospital care",

"HEALTH ASSUR LIMITED":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care",

"Health Partners Limited":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"HEALTHCARE INTERNATIONAL LIMITED":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care",

"HEALTHSPRING HMO":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"HYGEIA HMO LIMITED":
"Outpatient care; Inpatient care; Optical care; Dental care; Chronic disease management; Telemedicine; Physiotherapy; ENT services; Wellness and preventive care; Maternal and child care",

"Infinite X2 Health Maintenance Services":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"INTEGRATED HEALTHCARE":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"INTERNATIONAL HEALTH MGT. SERVICES":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"IVES MEDICARE":
"Health insurance; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care",

"KENNEDIA HMO LIMITED":
"Managed healthcare; Medical consultation; Doctor consultation; Hospital appointments; Provider network access; Health insurance plans; Telemedicine",

"LEADWAY HEALTH LIMITED":
"Outpatient care; Inpatient care; Optical care; Dental care; Telemedicine; Emergency services; Mental health care; Chronic disease management; Pharmacy services; Home vaccination; Fitness and nutrition services",

"LIFE WORTH MEDICARE LTD":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care",

"LIFESAVER HEALTHCARE LIMITED":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"MAAYOIT HEALTH CARE LIMITED":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care",

"MARINA MEDICAL SERVICES HMO LIMITED":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"MARKFEMA NIGERIA LTD.":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"MASSLIFE HEALTHCARE LIMITED":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care",

"MB & O HEALTHCARE SERVICES LIMITED":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"MEDEXIA LIMITED":
"Prepaid health plans; Third-party administration; Clinic management; Health audit; Health, safety and environment consultancy; Medical expense administration",

"MEDICARE ALLIANCE LIMITED":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"MEDIPLAN HEALTHCARE LIMITED":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care",

"METROHEALTH HMO LIMITED":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"NEM HEALTH LIMITED":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"NNPC-HMO LIMITED":
"Employee health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"NONSUCH MEDICARE LIMITED":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care",

"NOOR HEALTH LTD.":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"NOVO HEALTH AFRICA LIMITED":
"Quality healthcare; Health insurance plans; Community health project management; Healthcare financing and administration; Health system support; Retail health plans; Geriatric care; Corporate health plans",

"OCEANIC HEALTH MANAGEMENT LIMITED":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"PERAMARE HEALTH MANAGEMENT COMPANY LIMITED":
"Emergency care; Outpatient care; Diagnostic services; Prescription medicines; Physiotherapy; Advanced investigations; Inpatient care; Surgery; Maternity care; Dental care; Eye care; Child welfare; Immunization; Mental health therapy; Annual medical checks; Home healthcare; Gym and spa access; Teleconsultation",

"PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED":
"Health insurance; Outpatient care; Inpatient care; Specialist care; Surgical care; Pre-employment screening; Annual medical checkups; Hospital provider network",

"POLICE HEALTH MAINTENANCE LIMITED":
"Police personnel health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"PRECIOUS HEALTHCARE LIMITED":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"PREPAID MEDICARE SERVICES LTD.":
"Prepaid health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"PRINCETON HEALTH":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"PROHEALTH HMO LTD":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care",

"REDCARE HEALTH SERVICES LIMITED":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"REGENIX HEALTH CARE SERVICE LIMITED":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"RELIANCE HMO LIMITED":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Telemedicine",

"RODING HEALTHCARE LTD.":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"RONSBERGER NIGERIA LTD.":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"ROTHAUGE HEALTHCARE LIMITED":
"Specialist consultation; Outpatient services; Hospital admission; Prescription drugs; Immunization; Laboratory investigations; Physiotherapy; Dental care; Optical care; Surgical procedures; Maternity care; ICU services; Preventive wellness; Employment screening; Third-party administration; Healthcare consulting",

"ROYAL HEALTH MAINTENANCE SERVICES LTD.":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"SALUS TRUST GTE":
"Health insurance; Routine consultation; Specialist treatment; Health screening; Diagnostic testing; Pharmacy services; Chronic illness management; Wellness programmes; Fitness and nutrition guidance; Counselling; Preventive care; Health education",

"SERAPH HMO LIMITED":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"SKYDA HEALTH LIMITED":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"SONGHAI HEALTH TRUST":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"SPRINGTIDE HEALTHCARE SERVICES LTD.":
"Outpatient care; General consultation; Specialist consultation; Inpatient care; Hospital access; Prescription medicines; Chronic disease management; Diagnostic services; Laboratory services; Radiology; Eye care; Dental care; Wellness programmes; Preventive care; Telemedicine; Health coaching",

"STERLING HEALTH MANAGED CARE SERVICES LIMITED":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"SUNU HEALTH NIGERIA LIMITED":
"Managed healthcare; Health insurance; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Telemedicine; Overseas referral services",

"SYNERGY WELLCARE MEDICAID LIMITED":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"TOTAL HEALTH TRUST LIMITED":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care",

"ULTIMATE HEALTH MANAGEMENT SERVICES LTD":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"UNITED COMPREHENSIVE HEALTH MANAGERS LTD.":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"UNITED HEALTHCARE INTERNATIONAL LIMITED":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"VENUS MEDICARE LTD":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"VERITAS HEALTHCARE LIMITED":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"WELL HEALTH NETWORK LIMITED":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"WELLNESS HEALTH MANAGEMENT SERVICES LIMITED":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Wellness and preventive care",

"ZUMA HEALTH TRUST":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"Healthnomics HMO PLC":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"HYSSOP Health International Limited (HMO)":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"Hopewell Healthcare Management Ltd":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"Crown Jewel HMO Ltd.":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"Smathealth Medicare Limited":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"Quest Medicare Limited":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"Life Action Plus Ltd.":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"Zenor Healthcare Ltd.":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"Aspire HMO Limited":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care",

"Mitera Health Limited":
"Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care"
}


nigeria_hmo["Services Rendered"] = nigeria_hmo["Name"].map(services)

print("Missing Services:", nigeria_hmo["Services Rendered"].isna().sum())

nigeria_hmo[["Name", "Services Rendered"]]

Missing Services: 1

,Name,Services Rendered
0,A&M HEALTHCARE TRUST LIMITED,Outpatient care; Specialist consultation; Inpatient care; Diagnostic services; Prescription medicines; Emergency care; Maternity care
1,AIICO MULTISHIELD NIGERIA LIMITED,Medical consultation; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Hospital care; Emergency care; Maternity care
2,ALLEANZA HEALTH MANAGEMENT LIMITED,Medical consultation; Hospital admission; Surgery; Maternity care; Emergency care; Pharmacy services; Provider network access
3,ALLY HEALTHCARE LIMITED,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
4,AMAN HEALTH MAINTENANCE ORGANIZATIONS,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
5,ANCHOR HMO INTERNATIONAL COMPANY LIMITED,Corporate health plans; Retail health plans; Third-party administration; Customized health plans; Emergency support; Claims management
6,ASHMED INTEGRATED HEALTH SERVICES LTD.,Managed healthcare; Health insurance; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
7,AVON HEALTHCARE LIMITED,Health insurance; Outpatient care; Inpatient care; Specialist consultation; Diagnostic services; Prescription medicines; Emergency care; Maternity care; Dental care; Optical care
8,AXA MANSARD HEALTH LIMITED,Outpatient care; Inpatient care; Surgical services; Routine immunization; Emergency evacuation; Dental care; Eye care; Physiotherapy; Telemedicine; Pharmacy services; Hospital cash
9,BASTION HEALTH LIMITED,Health insurance; Outpatient care; Inpatient care; Specialist care; Hospital services; Emergency care; Provider network access; Corporate and individual health plans
10,BONITAS HEALTH MAINTENANCE LIMITED,Health insurance; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care
11,CENTURY MEDICAID SERVICES LIMITED,Managed healthcare; Health insurance; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
12,CLEARLINE INTERNATIONAL LIMITED,Outpatient care; General and specialist consultation; Teleconsultation; Prescription medicines; Diagnostic and laboratory services; Hospital care; Emergency care
13,DEFENCE HEALTH MAINTENANCE LIMITED,Military and defence health insurance; Primary healthcare; Secondary healthcare; Tertiary healthcare; Clinical services; Pharmacy services; Nursing care; Allied medical services; Public health services
14,Delog Medical Services Ltd. (HMO),Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
15,DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
16,DOT HMO Ltd.,Clinic visits; Diagnostic services; Prescription medicines; Specialist care; Telemedicine; Wellness and preventive care; Emergency support
17,FOUNTAIN HEALTHCARE LIMITED,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care
18,GNI HEALTHCARE LTD,Medical consultation; Specialist care; Laboratory and diagnostic services; Prescription medicines; Maternity care; Eye care; Dental care; Immunization; Hospital admission; Surgery; HIV care; Ambulance services
19,GORAH HEALTHCARE LTD.,Preventive healthcare; Wellness care; Emergency services; Specialist consultation; Maternity care; Hospital and clinic access
20,GREENBAY HEALTHCARE SERVICES LIMITED,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
21,GREENFIELD HEALTH MANAGEMENT LTD,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
22,GROOMING HEALTH MANAGEMENT LIMITED,Routine checkups; Specialist consultation; Emergency care; Outpatient care; Inpatient care; Health insurance; Corporate and individual health plans
23,HALLMARK HEALTH SERVICES LIMITED,General consultation; Specialist consultation; Diagnostic investigations; Physiotherapy; Renal dialysis; Surgical care; Telemedicine; Gym access; Mortuary cover; Hospital care
24,HEALTH ASSUR LIMITED,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care
25,Health Partners Limited,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
26,HEALTHCARE INTERNATIONAL LIMITED,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care
27,HEALTHSPRING HMO,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
28,HYGEIA HMO LIMITED,Outpatient care; Inpatient care; Optical care; Dental care; Chronic disease management; Telemedicine; Physiotherapy; ENT services; Wellness and preventive care; Maternal and child care
29,Infinite X2 Health Maintenance Services,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
30,INTEGRATED HEALTHCARE,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
31,INTERNATIONAL HEALTH MGT. SERVICES,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
32,IVES MEDICARE,Health insurance; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care
33,KENNEDIA HMO LIMITED,Managed healthcare; Medical consultation; Doctor consultation; Hospital appointments; Provider network access; Health insurance plans; Telemedicine
34,LEADWAY HEALTH LIMITED,Outpatient care; Inpatient care; Optical care; Dental care; Telemedicine; Emergency services; Mental health care; Chronic disease management; Pharmacy services; Home vaccination; Fitness and nutrition services
35,LIFE WORTH MEDICARE LTD,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care
36,LIFESAVER HEALTHCARE LIMITED,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
37,MAAYOIT HEALTH CARE LIMITED,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care
38,MARINA MEDICAL SERVICES HMO LIMITED,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
39,MARKFEMA NIGERIA LTD.,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
40,MASSLIFE HEALTHCARE LIMITED,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care
41,MB & O HEALTHCARE SERVICES LIMITED,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
42,MEDEXIA LIMITED,"Prepaid health plans; Third-party administration; Clinic management; Health audit; Health, safety and environment consultancy; Medical expense administration"
43,MEDICARE ALLIANCE LIMITED,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
44,MEDIPLAN HEALTHCARE LIMITED,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care
45,METROHEALTH HMO LIMITED,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
46,NEM HEALTH LIMITED,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
47,NNPC-HMO LIMITED,Employee health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
48,NONSUCH MEDICARE LIMITED,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care
49,NOOR HEALTH LTD.,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
50,NOVO HEALTH AFRICA LIMITED,Quality healthcare; Health insurance plans; Community health project management; Healthcare financing and administration; Health system support; Retail health plans; Geriatric care; Corporate health plans
51,OCEANIC HEALTH MANAGEMENT LIMITED,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
52,PERAMARE HEALTH MANAGEMENT COMPANY LIMITED,Emergency care; Outpatient care; Diagnostic services; Prescription medicines; Physiotherapy; Advanced investigations; Inpatient care; Surgery; Maternity care; Dental care; Eye care; Child welfare; Immunization; Mental health therapy; Annual medical checks; Home healthcare; Gym and spa access; Teleconsultation
53,PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED,Health insurance; Outpatient care; Inpatient care; Specialist care; Surgical care; Pre-employment screening; Annual medical checkups; Hospital provider network
54,POLICE HEALTH MAINTENANCE LIMITED,Police personnel health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
55,PRECIOUS HEALTHCARE LIMITED,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
56,PREPAID MEDICARE SERVICES LTD.,Prepaid health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
57,PRINCETON HEALTH,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
58,PROHEALTH HMO LTD,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care
59,REDCARE HEALTH SERVICES LIMITED,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
60,REGENIX HEALTH CARE SERVICE LIMITED,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
61,RELIANCE HMO LIMITED,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Telemedicine
62,RODING HEALTHCARE LTD.,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
63,RONSBERGER NIGERIA LTD.,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
64,ROTHAUGE HEALTHCARE LIMITED,Specialist consultation; Outpatient services; Hospital admission; Prescription drugs; Immunization; Laboratory investigations; Physiotherapy; Dental care; Optical care; Surgical procedures; Maternity care; ICU services; Preventive wellness; Employment screening; Third-party administration; Healthcare consulting
65,ROYAL HEALTH MAINTENANCE SERVICES LTD.,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
66,SALUS TRUST GTE,Health insurance; Routine consultation; Specialist treatment; Health screening; Diagnostic testing; Pharmacy services; Chronic illness management; Wellness programmes; Fitness and nutrition guidance; Counselling; Preventive care; Health education
67,SERAPH HMO LIMITED,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
68,SKYDA HEALTH LIMITED,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
69,SONGHAI HEALTH TRUST,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
70,SPRINGTIDE HEALTHCARE SERVICES LTD.,Outpatient care; General consultation; Specialist consultation; Inpatient care; Hospital access; Prescription medicines; Chronic disease management; Diagnostic services; Laboratory services; Radiology; Eye care; Dental care; Wellness programmes; Preventive care; Telemedicine; Health coaching
71,STERLING HEALTH MANAGED CARE SERVICES LIMITED,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
72,SUNU HEALTH NIGERIA LIMITED,Managed healthcare; Health insurance; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Telemedicine; Overseas referral services
73,SYNERGY WELLCARE MEDICAID LIMITED,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
74,TOTAL HEALTH TRUST LIMITED,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care
75,ULTIMATE HEALTH MANAGEMENT SERVICES LTD,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
76,UNITED COMPREHENSIVE HEALTH MANAGERS LTD.,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
77,UNITED HEALTHCARE INTERNATIONAL LIMITED,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
78,VENUS MEDICARE LTD,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
79,VERITAS HEALTHCARE LIMITED,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
80,WELL HEALTH NETWORK LIMITED,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
81,WELLNESS HEALTH MANAGEMENT SERVICES LIMITED,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Wellness and preventive care
82,ZUMA HEALTH TRUST,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
83,Healthnomics HMO PLC,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
84,HYSSOP Health International Limited (HMO),Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
85,Hopewell Healthcare Management Ltd,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
86,Crown Jewel HMO Ltd.,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
87,Smathealth Medicare Limited,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
88,Health Assur Limited,NaN
89,Quest Medicare Limited,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
90,Life Action Plus Ltd.,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
91,Zenor Healthcare Ltd.,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
92,Aspire HMO Limited,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care
93,Mitera Health Limited,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care

In [114]:
nigeria_hmo[nigeria_hmo["Services Rendered"].isna()][["S/NO.", "Name", "Website"]]

    S/NO.                  Name Website
88     89  Health Assur Limited     N/A

In [118]:
nigeria_hmo = nigeria_hmo.drop(index=88).reset_index(drop=True)

print("Number of rows:", len(nigeria_hmo))
print(nigeria_hmo[nigeria_hmo["Name"].str.strip().str.lower() == "health assur limited"])

Number of rows: 91
    S/NO.                  Name  HMO ID                        Website  \
24     25  HEALTH ASSUR LIMITED      87  https://www.hcihealthcare.ng/

                                          Address                 Email  \
24  NO.1 RAMAT CRESCENT OGUDU GRA, KOSOFE, LAGOS.  info@healthassur.com

                                                 Contact Number  Country  \
24  01-3422321, 08026547348, 0700 HEALTH ASSUR (07004325427787)  Nigeria

   Source                    Source URL  State      Region  \
24   NHIA  https://www.nhia.gov.ng/hmo/  Lagos  South West

          Coverage State                               Coverage Type  \
24  Nationwide – Nigeria  Individual / Family / Business / Corporate

                                                                                                                                                      Services Rendered  \
24  Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care

   Target Customers
24              N/A

In [119]:
print("Missing Services:", nigeria_hmo["Services Rendered"].isna().sum())
print("Missing Coverage Type:", nigeria_hmo["Coverage Type"].isna().sum())

Missing Services: 0
Missing Coverage Type: 0

In [120]:
target_customers = {

"A&M HEALTHCARE TRUST LIMITED":
"Individuals; Families; Corporate Organisations",

"AIICO MULTISHIELD NIGERIA LIMITED":
"Individuals; Families; SMEs; Corporate Organisations; Associations; Large Groups",

"ALLEANZA HEALTH MANAGEMENT LIMITED":
"Individuals; Families; Elderly/Senior Citizens; SMEs; Corporate Organisations",

"ALLY HEALTHCARE LIMITED":
"Individuals; Families; Corporate Organisations",

"AMAN HEALTH MAINTENANCE ORGANIZATIONS":
"Individuals; Families; Corporate Organisations",

"ANCHOR HMO INTERNATIONAL COMPANY LIMITED":
"Individuals; Families; SMEs; Small and Large Employers; Corporate Organisations",

"ASHMED INTEGRATED HEALTH SERVICES LTD.":
"Individuals; Families; Corporate Organisations",

"AVON HEALTHCARE LIMITED":
"Individuals; Couples; Families; Businesses; Corporate Organisations",

"AXA MANSARD HEALTH LIMITED":
"Individuals; Families; Employees; Groups; Corporate Organisations",

"BASTION HEALTH LIMITED":
"Individuals; Families; Senior Citizens; SMEs; Corporate Organisations",

"BONITAS HEALTH MAINTENANCE LIMITED":
"Individuals; Families; SMEs; Corporate Organisations",

"CENTURY MEDICAID SERVICES LIMITED":
"Individuals; Families; Corporate Organisations; Employees; Students; Educational Institutions; Industry Groups",

"CLEARLINE INTERNATIONAL LIMITED":
"Individuals; Families; SMEs; Corporate Organisations",

"DEFENCE HEALTH MAINTENANCE LIMITED":
"Defence Personnel; Defence Employees; Dependants",

"Delog Medical Services Ltd. (HMO)":
"Individuals; Families; SMEs; Corporate Organisations",

"DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO":
"Individuals; Families; SMEs; Corporate Organisations",

"DOT HMO Ltd.":
"Individuals; Families; SMEs; Teams",

"FOUNTAIN HEALTHCARE LIMITED":
"Individuals; Families; SMEs; Corporate Organisations",

"GNI HEALTHCARE LTD":
"Individuals; Families; Employees; Corporate Organisations",

"GORAH HEALTHCARE LTD.":
"Individuals; Families; Students; Senior Citizens; Corporate Organisations; International Clients",

"GREENBAY HEALTHCARE SERVICES LIMITED":
"Individuals; Families; Employers; Businesses; Corporate Organisations",

"GREENFIELD HEALTH MANAGEMENT LTD":
"Individuals; Families; SMEs; Corporate Organisations",

"GROOMING HEALTH MANAGEMENT LIMITED":
"Individuals; Families; Employees; Corporate Organisations",

"HALLMARK HEALTH SERVICES LIMITED":
"Individuals; Families; Employees; Corporate Organisations",

"HEALTH ASSUR LIMITED":
"Individuals; Families; Employees; SMEs; Corporate Organisations",

"Health Partners Limited":
"Individuals; Families; SMEs; Corporate Organisations",

"HEALTHCARE INTERNATIONAL LIMITED":
"Individuals; Families; SMEs; Corporate Organisations",

"HEALTHSPRING HMO":
"Individuals; Families",

"HYGEIA HMO LIMITED":
"Individuals; Families; Senior Citizens; SMEs; Corporate Organisations",

"Infinite X2 Health Maintenance Services":
"Individuals; Families; Corporate Organisations",

"INTEGRATED HEALTHCARE":
"Individuals; Families; Corporate Organisations",

"INTERNATIONAL HEALTH MGT. SERVICES":
"Individuals; Families; Corporate Organisations",

"IVES MEDICARE":
"Individuals; Families; Corporate Organisations",

"KENNEDIA HMO LIMITED":
"SMEs; Corporate Organisations; Large Corporates",

"LEADWAY HEALTH LIMITED":
"Individuals; Families; Senior Citizens; SMEs; Small and Large Companies; International Clients",

"LIFE WORTH MEDICARE LTD":
"Individuals; Families; SMEs; Corporate Organisations",

"LIFESAVER HEALTHCARE LIMITED":
"Individuals; Families; SMEs; Corporate Organisations",

"MAAYOIT HEALTH CARE LIMITED":
"Individuals; Families; SMEs; Corporate Organisations",

"MARINA MEDICAL SERVICES HMO LIMITED":
"Individuals; Families; SMEs; Corporate Organisations",

"MARKFEMA NIGERIA LTD.":
"Individuals; Families; Organisations; Companies; Government Bodies",

"MASSLIFE HEALTHCARE LIMITED":
"Individuals; Families; SMEs; Corporate Organisations; Senior Citizens; Tertiary Students; MSMEs",

"MB & O HEALTHCARE SERVICES LIMITED":
"Individuals; Families; SMEs; Corporate Organisations",

"MEDEXIA LIMITED":
"Healthcare Organisations; Healthcare Providers; Corporate Organisations",

"MEDICARE ALLIANCE LIMITED":
"Individuals; Families; SMEs; Corporate Organisations",

"MEDIPLAN HEALTHCARE LIMITED":
"Individuals; Families; SMEs; Corporate Organisations",

"METROHEALTH HMO LIMITED":
"Individuals; Families; SMEs; Corporate Organisations",

"NEM HEALTH LIMITED":
"Individuals; Families; SMEs; Corporate Organisations",

"NNPC-HMO LIMITED":
"NNPC Employees; NNPC Dependants; Employees of Participating Organisations",

"NONSUCH MEDICARE LIMITED":
"Individuals; Families; SMEs; Corporate Organisations",

"NOOR HEALTH LTD.":
"Individuals; Families; SMEs; Corporate Organisations",

"NOVO HEALTH AFRICA LIMITED":
"Individuals; Families; Employers; Corporate Organisations; Government Organisations; Communities",

"OCEANIC HEALTH MANAGEMENT LIMITED":
"Individuals; Families; SMEs; Corporate Organisations",

"PERAMARE HEALTH MANAGEMENT COMPANY LIMITED":
"Individuals; Families; SMEs; Corporate Organisations",

"PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED":
"Individuals; Families; Employees; Corporate Organisations",

"POLICE HEALTH MAINTENANCE LIMITED":
"Police Personnel; Police Employees; Dependants",

"PRECIOUS HEALTHCARE LIMITED":
"Individuals; Families; SMEs; Corporate Organisations",

"PREPAID MEDICARE SERVICES LTD.":
"Individuals; Families; SMEs; Corporate Organisations",

"PRINCETON HEALTH":
"Individuals; Families; SMEs; Corporate Organisations",

"PROHEALTH HMO LTD":
"Individuals; Families; SMEs; Corporate Organisations",

"REDCARE HEALTH SERVICES LIMITED":
"Individuals; Families; SMEs; Corporate Organisations",

"REGENIX HEALTH CARE SERVICE LIMITED":
"Individuals; Families; SMEs; Corporate Organisations",

"RELIANCE HMO LIMITED":
"Individuals; Families; SMEs; Corporate Organisations",

"RODING HEALTHCARE LTD.":
"Individuals; Families; SMEs; Corporate Organisations",

"RONSBERGER NIGERIA LTD.":
"Individuals; Families; SMEs; Corporate Organisations",

"ROTHAUGE HEALTHCARE LIMITED":
"Individuals; Families; Employees; Employers; Corporate Organisations",

"ROYAL HEALTH MAINTENANCE SERVICES LTD.":
"Individuals; Families; SMEs; Corporate Organisations",

"SALUS TRUST GTE":
"Individuals; Families; Employees; Corporate Organisations",

"SERAPH HMO LIMITED":
"Individuals; Families; SMEs; Corporate Organisations",

"SKYDA HEALTH LIMITED":
"Individuals; Families; SMEs; Corporate Organisations",

"SONGHAI HEALTH TRUST":
"Individuals; Families; SMEs; Corporate Organisations",

"SPRINGTIDE HEALTHCARE SERVICES LTD.":
"Individuals; Families; Employees; Corporate Organisations",

"STERLING HEALTH MANAGED CARE SERVICES LIMITED":
"Individuals; Families; SMEs; Corporate Organisations",

"SUNU HEALTH NIGERIA LIMITED":
"Individuals; Families; SMEs; Corporate Organisations; Employees",

"SYNERGY WELLCARE MEDICAID LIMITED":
"Individuals; Families; SMEs; Corporate Organisations",

"TOTAL HEALTH TRUST LIMITED":
"Individuals; Families; SMEs; Corporate Organisations",

"ULTIMATE HEALTH MANAGEMENT SERVICES LTD":
"Individuals; Families; SMEs; Corporate Organisations",

"UNITED COMPREHENSIVE HEALTH MANAGERS LTD.":
"Individuals; Families; SMEs; Corporate Organisations",

"UNITED HEALTHCARE INTERNATIONAL LIMITED":
"Individuals; Families; SMEs; Corporate Organisations",

"VENUS MEDICARE LTD":
"Individuals; Families; SMEs; Corporate Organisations",

"VERITAS HEALTHCARE LIMITED":
"Individuals; Families; SMEs; Corporate Organisations",

"WELL HEALTH NETWORK LIMITED":
"Individuals; Families; SMEs; Corporate Organisations",

"WELLNESS HEALTH MANAGEMENT SERVICES LIMITED":
"Individuals; Families; SMEs; Corporate Organisations",

"ZUMA HEALTH TRUST":
"Individuals; Families; SMEs; Corporate Organisations",

"Healthnomics HMO PLC":
"Individuals; Families; SMEs; Corporate Organisations",

"HYSSOP Health International Limited (HMO)":
"Individuals; Families; SMEs; Corporate Organisations",

"Hopewell Healthcare Management Ltd":
"Individuals; Families; SMEs; Corporate Organisations",

"Crown Jewel HMO Ltd.":
"Individuals; Families; SMEs; Corporate Organisations",

"Smathealth Medicare Limited":
"Individuals; Families; SMEs; Corporate Organisations",

"Quest Medicare Limited":
"Individuals; Families; SMEs; Corporate Organisations",

"Life Action Plus Ltd.":
"Individuals; Families; SMEs; Corporate Organisations",

"Zenor Healthcare Ltd.":
"Individuals; Families; SMEs; Corporate Organisations",

"Aspire HMO Limited":
"Individuals; Families; SMEs; Corporate Organisations",

"Mitera Health Limited":
"Individuals; Families; SMEs; Corporate Organisations"
}


nigeria_hmo["Target Customers"] = nigeria_hmo["Name"].map(target_customers)


print("Missing Target Customers:",
      nigeria_hmo["Target Customers"].isna().sum())

print("\nNumber of rows:",
      len(nigeria_hmo))

nigeria_hmo[["Name", "Target Customers"]]

Missing Target Customers: 0

Number of rows: 91

,Name,Target Customers
0,A&M HEALTHCARE TRUST LIMITED,Individuals; Families; Corporate Organisations
1,AIICO MULTISHIELD NIGERIA LIMITED,Individuals; Families; SMEs; Corporate Organisations; Associations; Large Groups
2,ALLEANZA HEALTH MANAGEMENT LIMITED,Individuals; Families; Elderly/Senior Citizens; SMEs; Corporate Organisations
3,ALLY HEALTHCARE LIMITED,Individuals; Families; Corporate Organisations
4,AMAN HEALTH MAINTENANCE ORGANIZATIONS,Individuals; Families; Corporate Organisations
5,ANCHOR HMO INTERNATIONAL COMPANY LIMITED,Individuals; Families; SMEs; Small and Large Employers; Corporate Organisations
6,ASHMED INTEGRATED HEALTH SERVICES LTD.,Individuals; Families; Corporate Organisations
7,AVON HEALTHCARE LIMITED,Individuals; Couples; Families; Businesses; Corporate Organisations
8,AXA MANSARD HEALTH LIMITED,Individuals; Families; Employees; Groups; Corporate Organisations
9,BASTION HEALTH LIMITED,Individuals; Families; Senior Citizens; SMEs; Corporate Organisations
10,BONITAS HEALTH MAINTENANCE LIMITED,Individuals; Families; SMEs; Corporate Organisations
11,CENTURY MEDICAID SERVICES LIMITED,Individuals; Families; Corporate Organisations; Employees; Students; Educational Institutions; Industry Groups
12,CLEARLINE INTERNATIONAL LIMITED,Individuals; Families; SMEs; Corporate Organisations
13,DEFENCE HEALTH MAINTENANCE LIMITED,Defence Personnel; Defence Employees; Dependants
14,Delog Medical Services Ltd. (HMO),Individuals; Families; SMEs; Corporate Organisations
15,DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO,Individuals; Families; SMEs; Corporate Organisations
16,DOT HMO Ltd.,Individuals; Families; SMEs; Teams
17,FOUNTAIN HEALTHCARE LIMITED,Individuals; Families; SMEs; Corporate Organisations
18,GNI HEALTHCARE LTD,Individuals; Families; Employees; Corporate Organisations
19,GORAH HEALTHCARE LTD.,Individuals; Families; Students; Senior Citizens; Corporate Organisations; International Clients
20,GREENBAY HEALTHCARE SERVICES LIMITED,Individuals; Families; Employers; Businesses; Corporate Organisations
21,GREENFIELD HEALTH MANAGEMENT LTD,Individuals; Families; SMEs; Corporate Organisations
22,GROOMING HEALTH MANAGEMENT LIMITED,Individuals; Families; Employees; Corporate Organisations
23,HALLMARK HEALTH SERVICES LIMITED,Individuals; Families; Employees; Corporate Organisations
24,HEALTH ASSUR LIMITED,Individuals; Families; Employees; SMEs; Corporate Organisations
25,Health Partners Limited,Individuals; Families; SMEs; Corporate Organisations
26,HEALTHCARE INTERNATIONAL LIMITED,Individuals; Families; SMEs; Corporate Organisations
27,HEALTHSPRING HMO,Individuals; Families
28,HYGEIA HMO LIMITED,Individuals; Families; Senior Citizens; SMEs; Corporate Organisations
29,Infinite X2 Health Maintenance Services,Individuals; Families; Corporate Organisations
30,INTEGRATED HEALTHCARE,Individuals; Families; Corporate Organisations
31,INTERNATIONAL HEALTH MGT. SERVICES,Individuals; Families; Corporate Organisations
32,IVES MEDICARE,Individuals; Families; Corporate Organisations
33,KENNEDIA HMO LIMITED,SMEs; Corporate Organisations; Large Corporates
34,LEADWAY HEALTH LIMITED,Individuals; Families; Senior Citizens; SMEs; Small and Large Companies; International Clients
35,LIFE WORTH MEDICARE LTD,Individuals; Families; SMEs; Corporate Organisations
36,LIFESAVER HEALTHCARE LIMITED,Individuals; Families; SMEs; Corporate Organisations
37,MAAYOIT HEALTH CARE LIMITED,Individuals; Families; SMEs; Corporate Organisations
38,MARINA MEDICAL SERVICES HMO LIMITED,Individuals; Families; SMEs; Corporate Organisations
39,MARKFEMA NIGERIA LTD.,Individuals; Families; Organisations; Companies; Government Bodies
40,MASSLIFE HEALTHCARE LIMITED,Individuals; Families; SMEs; Corporate Organisations; Senior Citizens; Tertiary Students; MSMEs
41,MB & O HEALTHCARE SERVICES LIMITED,Individuals; Families; SMEs; Corporate Organisations
42,MEDEXIA LIMITED,Healthcare Organisations; Healthcare Providers; Corporate Organisations
43,MEDICARE ALLIANCE LIMITED,Individuals; Families; SMEs; Corporate Organisations
44,MEDIPLAN HEALTHCARE LIMITED,Individuals; Families; SMEs; Corporate Organisations
45,METROHEALTH HMO LIMITED,Individuals; Families; SMEs; Corporate Organisations
46,NEM HEALTH LIMITED,Individuals; Families; SMEs; Corporate Organisations
47,NNPC-HMO LIMITED,NNPC Employees; NNPC Dependants; Employees of Participating Organisations
48,NONSUCH MEDICARE LIMITED,Individuals; Families; SMEs; Corporate Organisations
49,NOOR HEALTH LTD.,Individuals; Families; SMEs; Corporate Organisations
50,NOVO HEALTH AFRICA LIMITED,Individuals; Families; Employers; Corporate Organisations; Government Organisations; Communities
51,OCEANIC HEALTH MANAGEMENT LIMITED,Individuals; Families; SMEs; Corporate Organisations
52,PERAMARE HEALTH MANAGEMENT COMPANY LIMITED,Individuals; Families; SMEs; Corporate Organisations
53,PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED,Individuals; Families; Employees; Corporate Organisations
54,POLICE HEALTH MAINTENANCE LIMITED,Police Personnel; Police Employees; Dependants
55,PRECIOUS HEALTHCARE LIMITED,Individuals; Families; SMEs; Corporate Organisations
56,PREPAID MEDICARE SERVICES LTD.,Individuals; Families; SMEs; Corporate Organisations
57,PRINCETON HEALTH,Individuals; Families; SMEs; Corporate Organisations
58,PROHEALTH HMO LTD,Individuals; Families; SMEs; Corporate Organisations
59,REDCARE HEALTH SERVICES LIMITED,Individuals; Families; SMEs; Corporate Organisations
60,REGENIX HEALTH CARE SERVICE LIMITED,Individuals; Families; SMEs; Corporate Organisations
61,RELIANCE HMO LIMITED,Individuals; Families; SMEs; Corporate Organisations
62,RODING HEALTHCARE LTD.,Individuals; Families; SMEs; Corporate Organisations
63,RONSBERGER NIGERIA LTD.,Individuals; Families; SMEs; Corporate Organisations
64,ROTHAUGE HEALTHCARE LIMITED,Individuals; Families; Employees; Employers; Corporate Organisations
65,ROYAL HEALTH MAINTENANCE SERVICES LTD.,Individuals; Families; SMEs; Corporate Organisations
66,SALUS TRUST GTE,Individuals; Families; Employees; Corporate Organisations
67,SERAPH HMO LIMITED,Individuals; Families; SMEs; Corporate Organisations
68,SKYDA HEALTH LIMITED,Individuals; Families; SMEs; Corporate Organisations
69,SONGHAI HEALTH TRUST,Individuals; Families; SMEs; Corporate Organisations
70,SPRINGTIDE HEALTHCARE SERVICES LTD.,Individuals; Families; Employees; Corporate Organisations
71,STERLING HEALTH MANAGED CARE SERVICES LIMITED,Individuals; Families; SMEs; Corporate Organisations
72,SUNU HEALTH NIGERIA LIMITED,Individuals; Families; SMEs; Corporate Organisations; Employees
73,SYNERGY WELLCARE MEDICAID LIMITED,Individuals; Families; SMEs; Corporate Organisations
74,TOTAL HEALTH TRUST LIMITED,Individuals; Families; SMEs; Corporate Organisations
75,ULTIMATE HEALTH MANAGEMENT SERVICES LTD,Individuals; Families; SMEs; Corporate Organisations
76,UNITED COMPREHENSIVE HEALTH MANAGERS LTD.,Individuals; Families; SMEs; Corporate Organisations
77,UNITED HEALTHCARE INTERNATIONAL LIMITED,Individuals; Families; SMEs; Corporate Organisations
78,VENUS MEDICARE LTD,Individuals; Families; SMEs; Corporate Organisations
79,VERITAS HEALTHCARE LIMITED,Individuals; Families; SMEs; Corporate Organisations
80,WELL HEALTH NETWORK LIMITED,Individuals; Families; SMEs; Corporate Organisations
81,WELLNESS HEALTH MANAGEMENT SERVICES LIMITED,Individuals; Families; SMEs; Corporate Organisations
82,ZUMA HEALTH TRUST,Individuals; Families; SMEs; Corporate Organisations
83,Healthnomics HMO PLC,Individuals; Families; SMEs; Corporate Organisations
84,HYSSOP Health International Limited (HMO),Individuals; Families; SMEs; Corporate Organisations
85,Hopewell Healthcare Management Ltd,Individuals; Families; SMEs; Corporate Organisations
86,Crown Jewel HMO Ltd.,Individuals; Families; SMEs; Corporate Organisations
87,Smathealth Medicare Limited,Individuals; Families; SMEs; Corporate Organisations
88,Zenor Healthcare Ltd.,Individuals; Families; SMEs; Corporate Organisations
89,Aspire HMO Limited,Individuals; Families; SMEs; Corporate Organisations
90,Mitera Health Limited,Individuals; Families; SMEs; Corporate Organisations

In [121]:
combined_df = pd.concat(
    [nigeria_hmo, england_wales_df],
    ignore_index=True
)

combined_df

,S/NO.,Name,HMO ID,Website,Address,Email,Contact Number,Country,Source,Source URL,State,Region,Coverage State,Coverage Type,Services Rendered,Target Customers
0,1.0,A&M HEALTHCARE TRUST LIMITED,102.0,https://amhmo.com/,"Plot U Bekaji Road, Opposite Bekaji Jumma'at Mosque, Jimeta, Yola, Adamawa State",info@amhmo.com,"08033646497, 09162788582, 08024143666",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Adamawa,North East,Adamawa,Individual / Family / Corporate,Outpatient care; Specialist consultation; Inpatient care; Diagnostic services; Prescription medicines; Emergency care; Maternity care,Individuals; Families; Corporate Organisations
1,2.0,AIICO MULTISHIELD NIGERIA LIMITED,6.0,https://www.aiicomultishield.com/,"322, IKORODU ROAD, ANTHONY",info@aiicomultishield.com loshunniyi@aiicomultishield.com,07026744353 08056744353,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Nationwide – Nigeria,Individual / Family / Corporate / SME / Group / International,Medical consultation; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Hospital care; Emergency care; Maternity care,Individuals; Families; SMEs; Corporate Organisations; Associations; Large Groups
2,3.0,ALLEANZA HEALTH MANAGEMENT LIMITED,111.0,https://alleanzahealth.com/individual-plans/,"? 83B, Basheer Shittu Avenue, Magodo Estate, Phase 2, Shangisha, Lagos",info@alleanzahealth.com,07036592835,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Nationwide – Nigeria,Individual / Family / Corporate / Elderly / SME,Medical consultation; Hospital admission; Surgery; Maternity care; Emergency care; Pharmacy services; Provider network access,Individuals; Families; Elderly/Senior Citizens; SMEs; Corporate Organisations
3,4.0,ALLY HEALTHCARE LIMITED,119.0,https://amanhmo.com/home,"Suit C4 Plot 1196 Ndjamena Crescent, Wuse II, Abuja",allyhealthcarelimited@gmail.com,08148808171,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,FCT,North Central,FCT,Individual / Corporate,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care,Individuals; Families; Corporate Organisations
4,5.0,AMAN HEALTH MAINTENANCE ORGANIZATIONS,121.0,https://anchorhmo.com/,"? 1, M. M. Alkali Street, Off 442 Crescent, Citec Vilas Gwarinpa, Abuja",info@amanhmo.com,08100588906,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,FCT,North Central,FCT,Individual / Family / Corporate,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care,Individuals; Families; Corporate Organisations
5,6.0,ANCHOR HMO INTERNATIONAL COMPANY LIMITED,76.0,https://ashmedintegratedhealthservices.com/,GOLDCREST MALL BUILDING,info@anchorhmo.com,"08031230306, 07058890062, 07080601192",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,N/A,N/A,Nationwide – Nigeria,Individual / Corporate / SME,Corporate health plans; Retail health plans; Third-party administration; Customized health plans; Emergency support; Claims management,Individuals; Families; SMEs; Small and Large Employers; Corporate Organisations
6,7.0,ASHMED INTEGRATED HEALTH SERVICES LTD.,89.0,https://www.avonhealthcare.com/,"RE 013 ZUNGERU CLOSE BY BIMA ROAD NITEL QUARTERS, KADUNA",info@ashmedintegratedhealthservices.com,07036035182,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Kaduna,North West,Kaduna,Individual / Family / Corporate,Managed healthcare; Health insurance; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care,Individuals; Families; Corporate Organisations
7,8.0,AVON HEALTHCARE LIMITED,63.0,https://www.axamansard.com/health/plans/,"22B, GLOVER ROAD",info@avonhealthcare.com,"08102659972, 07002779800",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Nationwide – Nigeria,Individual / Family / Corporate,Health insurance; Outpatient care; Inpatient care; Specialist consultation; Diagnostic services; Prescription medicines; Emergency care; Maternity care; Dental care; Optical care,Individuals; Couples; Families; Businesses; Corporate Organisations
8,9.0,AXA MANSARD HEALTH LIMITED,59.0,https://bastionhmo.com/,"177, IKORODU ROAD, ONIPANU, LAGOS",healthcare@axamansard.com,0700AXAMANSARD,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Nationwide – Nigeria,Individual / Family / Corporate,Outpatient care; Inpatient care; Surgical services; Routine immunization; Emergency evacuation; Dental care; Eye care; Physiotherapy; Telemedicine; Pharmacy services; Hospital cash,Individuals; Families; Employees; Groups; Corporate Organisations
9,10.0,BASTION HEALTH LIMITED,97.0,https://www.centurymedicaid.org/,"UBN HOUSE NO 1 ADEOLA ODEKU STREET, VICTORIA ISLAND, LAGOS, ETI OSA, LAGOS, Nigeria",Naomiduku@bastionhmo.com,0802BASTI0NHM0 08002278466,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Lagos,Individual / Family / Corporate,Health insurance; Outpatient care; Inpatient care; Specialist care; Hospital services; Emergency care; Provider network access; Corporate and individual health plans,Individuals; Families; Senior Citizens; SMEs; Corporate Organisations
10,11.0,BONITAS HEALTH MAINTENANCE LIMITED,120.0,https://clearlinehmo.com/,"No. 7 Birabi Street, GRA phase 1, Port Harcourt, Rivers State",info@bonitashmo.org,09164113000,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Rivers,South South,Rivers,Individual / Family / Corporate,Health insurance; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care,Individuals; Families; SMEs; Corporate Organisations
11,12.0,CENTURY MEDICAID SERVICES LIMITED,99.0,https://www.dhmlnigeria.com,"36 OKOROJI STREET, D/LINE, PORT HARCOURT, PORT HARCOURT CITY LGA, RIVERS STATE, Nigeria","info@centurymedicaid.org, centurymedicaid@yahoo.com","08090235044, 09087000193, 09087000192",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Rivers,South South,Rivers,Individual / Family / Corporate / Community / Industrial / Educational,Managed healthcare; Health insurance; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care,Individuals; Families; Corporate Organisations; Employees; Students; Educational Institutions; Industry Groups
12,13.0,CLEARLINE INTERNATIONAL LIMITED,3.0,https://delogmedicalhmo.com/,"290, IKORODU ROAD, ANTHONY, LAGOS",info@clearlinehmo.net clearline_int@yahoo.com,"08076490111, 08076490101, 014482520",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Nationwide – Nigeria,Individual / Family / Corporate,Outpatient care; General and specialist consultation; Teleconsultation; Prescription medicines; Diagnostic and laboratory services; Hospital care; Emergency care,Individuals; Families; SMEs; Corporate Organisations
13,14.0,DEFENCE HEALTH MAINTENANCE LIMITED,22.0,https://doheec.com/,"2 HAMINA CLOSE, ABUJA",info@dhmlnigeria.com,"07037921025, 08069305886",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,FCT,North Central,Nationwide – Nigeria,Corporate / Group / Military,Military and defence health insurance; Primary healthcare; Secondary healthcare; Tertiary healthcare; Clinical services; Pharmacy services; Nursing care; Allied medical services; Public health services,Defence Personnel; Defence Employees; Dependants
14,15.0,Delog Medical Services Ltd. (HMO),117.0,https://hmo.dot.ai/,"? 369, Borno Way, Alagomeji, Yaba, Lagos",info@delogmedicalhmo.com,08128300972,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Lagos,Individual / Family / Corporate,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care,Individuals; Families; SMEs; Corporate Organisations
15,16.0,DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO,115.0,N/A,"2nd Floor, 34/36, Association Avenue, Ilupeju, Lagos",info@doheec.com,"09069431050, 09078945165",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Lagos,Individual / Family / Corporate,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care,Individuals; Families; SMEs; Corporate Organisations
16,17.0,DOT HMO Ltd.,100.0,http://gnihealthcare.com/,"MJS House, 366 Murtala Mohammed Way (Opposite Polaris Bank), Yaba, Lagos",support@dot.aihelp@dot.ai,07000368466 (calls) 08170369507 (WhatsApp 0nly),Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Nationwide – Nigeria,Individual / Family / Corporate,Clinic visits; Diagnostic services; Prescription medicines; Specialist care; Telemedicine; Wellness and preventive care; Emergency support,Individuals; Families; SMEs; Teams
17,18.0,FOUNTAIN HEALTHCARE LIMITED,94.0,https://gorahhmo.com/,"ALL SEASON PLACE, NO 74 ISHERI- OGUNNUSI ROAD, OJUDU-OMOLE, IKEJA LAGOS",info@fountainhealthcareng.com,"0700F0UNTAIN, 08077705100, 08077705200",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Nationwide – Nigeria,Individual / Family / Corporate,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care,Individuals; Families; SMEs; Corporate Organisations
18,19.0,GNI HEALTHCARE LTD,60.0,https://greenbayhmo.com/,"28, AFOLABI AINA STREET, OFF AWOLOWO WAY, IKEJA LAGOS",gnihealthcare@greatnigeriaplc.com,"08057752870, 08163290105 07043051516, 07046251142",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Nationwide – Nigeria,Individual / Family / Corporate,Medical consultation; Specialist care; Laboratory and diagnostic services; Prescription medicines; Maternity care; Eye care; Dental care; Immunization; Hospital admission; Surgery; HIV care; Ambulance services,Individuals; Families; Employees; Corporate Organisations
19,20.0,GORAH HEALTHCARE LTD.,112.0,https://www.greenfieldhmo.com/,"? 322A, Ikorodu Road, Ikeja, Lagos",info@gorahhmo.com,"08132783427, 07031870956",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Lagos,Individual / Family / Corporate,Preventive healthcare; Wellness care; Emergency services; Specialist consultation; Maternity care; Hospital and clinic access,Individuals; Families; Students; Senior Citizens; Corporate Organisations; International Clients
20,21.0,GREENBAY HEALTHCARE SERVICES LIMITED,43.0,http://www.groominghm.com/,"9, ODUNUGA STREET, OFF OPEBI LINK ROAD,",info@greenbayhmo.com,070047336229,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Nationwide – Nigeria,Individual / Family / Corporate,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care,Individuals; Families; Employers; Businesses; Corporate Organisations
21,22.0,GREENFIELD HEALTH MANAGEMENT LTD,78.0,https://hallmarkhmo.com/,"PLOT 14, MARKET GARDEN POCKET LAYOUT, BY ISIADINSO CLOSE, G",info@greenfieldhmo.com hodaccounts@greenfieldhmo.com ezealaelizabeth@greenfieldhmo.com,"09091910003, 09091909993",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,N/A,N/A,Nationwide – Nigeria,Individual / Family / Corporate,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care,Individuals; Families; SMEs; Corporate Organisations
22,23.0,GROOMING HEALTH MANAGEMENT LIMITED,108.0,https://www.healthassur.com/,"No. 3, Tina Chris Street, Ejigbo, Lagos State",info@groominghm.com,"07080631850, 09087966270",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Lagos,Individual / Corporate / SME,Routine checkups; Specialist consultation; Emergency care; Outpatient care; Inpatient care; Health insurance; Corporate and individual health plans,Individuals; Families; Employees; Corporate Organisations
23,24.0,HALLMARK HEALTH SERVICES LIMITED,96.0,https://healthpartnersng.org/,"264 Ikorodu Road, Obanikoro, Lagos, Somolu Local Government Area, Lagos, Nigeria",info@hallmarkhmo.com,"08170920155, 09087792936, 08090918940",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Lagos,Retail / SME / Corporate / International,General consultation; Specialist consultation; Diagnostic investigations; Physiotherapy; Renal dialysis; Surgical care; Telemedicine; Gym access; Mortuary cover; Hospital care,Individuals; Families; Employees; Corporate Organisations
24,25.0,HEALTH ASSUR LIMITED,87.0,https://www.hcihealthcare.ng/,"NO.1 RAMAT CRESCENT OGUDU GRA, KOSOFE, LAGOS.",info@healthassur.com,"01-3422321, 08026547348, 0700 HEALTH ASSUR (07004325427787)",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Nationwide – Nigeria,Individual / Family / Business / Corporate,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care,Individuals; Families; Employees; SMEs; Corporate Organisations
25,26.0,Health Partners Limited,35.0,https://healthspringhmo.com/,NaN,hmo@healthpartnersng.org,"08077140844, 08077140855, 08077140688",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,N/A,N/A,Nationwide – Nigeria,Retail / SME / Corporate,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care,Individuals; Families; SMEs; Corporate Organisations
26,27.0,HEALTHCARE INTERNATIONAL LIMITED,4.0,https://hygeiahmo.com/,"308A, MURITALA MOHAMMED WAY, YABA",info@healthcare-ng.com,"08052099069 (Abuja) 08052099099 (Lagos) 014489820, 08052099094",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Nationwide – Nigeria,Individual / Family / Corporate / International,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care,Individuals; Families; SMEs; Corporate Organisations
27,28.0,HEALTHSPRING HMO,122.0,https://healthspringhmo.com/,"? 1, Julius Nyerere Crescent, Asokoro, Abuja",info@healthspringhmo.com,"07047000591, 07047000590",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,FCT,North Central,FCT,Individual / Family,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care,Individuals; Families
28,29.0,HYGEIA HMO LIMITED,1.0,https://integratedhealthcareltd.com/,"2ND FLOOR, BANK OF INDUSTRY BUILDING, 21/22 MARINA","hycare@hygeiahmo.com, nhisdesk@hygeiahmo.com","070049434266, 014488300",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Nationwide – Nigeria,Individual / Family / Senior Citizens / Maternity / SME / Corporate,Outpatient care; Inpatient care; Optical care; Dental care; Chronic disease management; Telemedicine; Physiotherapy; ENT services; Wellness and preventive care; Maternal and child care,Individuals; Families; Senior Citizens; SMEs; Corporate Organisations
29,30.0,Infinite X2 Health Maintenance Services,113.0,https://ihmsnigeria.com/,"No. 13, Lafia Road, Adjacent Kaduna Golf Course, Kaduna State","Infinitex2health@gmail.com, info@infinitex2health.net",07066026262,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Kaduna,North West,Kaduna,Individual / Family / Corporate,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care,Individuals; Families; Corporate Organisations
30,31.0,INTEGRATED HEALTHCARE,14.0,https://www.ivesmedicare.com/,"19, JOS STREET, AREA 3 GARKI-ABUJA",info@integratedhealthcareltd.com,"08051322662, 08146120236, 08097236759, 09020008294 SMS (and WhatsApp only: 08063206121) Lagos: 08159391310 Awka: 08159391321 Uyo: 08159391334 Kano: 08159391333: Yola: 08159391308 Jos: 08159391311 Ibadan: 08159391324 Minna: 08159391306",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,FCT,North Central,Nationwide – Nigeria,Individual / Family / Corporate,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care,Individuals; Families; Corporate Organisations
31,32.0,INTERNATIONAL HEALTH MGT. SERVICES,11.0,https://kennediahmo.com/,"IGI HOUSE, 3 GWAMI ST, WUSE ZONE 4,",info@ihmsnigeria.com,"08085861299, 07041446622, 07004467466",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,FCT,North Central,Nationwide – Nigeria,Corporate / Group,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care,Individuals; Families; Corporate Organisations
32,33.0,IVES MEDICARE,69.0,https://leadwayhealth.com/,"4 MOJIDI STREET, OFF TOYIN STREET",info@ivesmedicare.com,"08032639058, 09085187582, 08092165592",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Lagos,Individual / Family / Corporate,Health insurance; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care,Individuals; Families; Corporate Organisations
33,34.0,KENNEDIA HMO LIMITED,109.0,https://lifeworthhmo.com/,"14B, Kingsley Emu Street, Lagos, Off Chris Onanuga, Lekki Phase 1",info@kennediahmo.com,"070030306060, 017002018, 09120351385",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Lagos,SME / Corporate / Group,Managed healthcare; Medical consultation; Doctor consultation; Hospital appointments; Provider network access; Health insurance plans; Telemedicine,SMEs; Corporate Organisations; Large Corporates
34,35.0,LEADWAY HEALTH LIMITED,90.0,https://maayoithealth.org/,"121/123, FUNSHO WILLIAMS AVENUE, IPONRI, SURULERE, LAGOS.",healthcare@leadway.com,"012801051, 08139862271",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Nationwide – Nigeria,Retail / SME / Corporate / International,Outpatient care; Inpatient care; Optical care; Dental care; Telemedicine; Emergency services; Mental health care; Chronic disease management; Pharmacy services; Home vaccination; Fitness and nutrition services,Individuals; Families; Senior Citizens; SMEs; Small and Large Companies; International Clients
35,36.0,LIFE WORTH MEDICARE LTD,79.0,https://marinamedicalhmo.ng/,"13A, BISHOP COKER ROUND ABOUT, ILUPEJU, LAGOS",info@lifeworthhmo.com,08091111760,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Nationwide – Nigeria,Individual / Family / Corporate,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care,Individuals; Families; SMEs; Corporate Organisations
36,37.0,LIFESAVER HEALTHCARE LIMITED,118.0,https://markfema.com/,"20B, Olutoye Crescent, Afra Estate, Off Adeniyi Jones Avenue, Ikeja, Lagos State",mb@lifesaverhealthcarehmo.com,09123973551,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Lagos,Individual / Family / Corporate,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care,Individuals; Families; SMEs; Corporate Organisations
37,38.0,MAAYOIT HEALTH CARE LIMITED,98.0,https://masslife.com.ng/,"MHL BUILDING OPPOSITE GSS, OLD JEBBA ROAD, ILORIN, KWARA STATE, P.O. BOX 5504, ILORIN, KWARA STATE, ILORIN, ILORIN WEST, KWARA, Nigeria",info@mayooithealth.org,"08058026841, 08174627100",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Kwara,North Central,Kwara,Individual / Family / Corporate,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care,Individuals; Families; SMEs; Corporate Organisations

In [123]:
%whos DataFrame

Variable           Type         Data/Info
-----------------------------------------
combined_df        DataFrame    Shape: (117, 16)
coverage_na        DataFrame    Shape: (67, 3)
england_df         DataFrame    Shape: (14, 13)
england_wales_df   DataFrame    Shape: (26, 13)
health_df          DataFrame    Shape: (14, 13)
nigeria_df         DataFrame    Shape: (0, 13)
nigeria_hmo        DataFrame    Shape: (91, 16)
wales_df           DataFrame    Shape: (12, 13)
website_df         DataFrame    Shape: (94, 2)

In [124]:
df = combined_df.copy()

print("========================================")
print("DATASET OVERVIEW")
print("========================================")
print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))
print()

print("COLUMNS:")
print(df.columns.tolist())
print()

print("========================================")
print("MISSING VALUES (NaN)")
print("========================================")
print(df.isna().sum())
print()

print("========================================")
print("N/A VALUES")
print("========================================")
na_counts = (df.astype(str).apply(
    lambda col: col.str.strip().str.upper().eq("N/A")
)).sum()

print(na_counts)
print()

print("========================================")
print("DUPLICATE ORGANISATION NAMES")
print("========================================")

duplicates = df[df["Name"].duplicated(keep=False)].sort_values("Name")

if len(duplicates) == 0:
    print("No duplicate organisation names found.")
else:
    print(duplicates[["Name", "Country", "Website"]].to_string(index=False))

print()

print("========================================")
print("DUPLICATE WEBSITES")
print("========================================")

website_duplicates = df[
    df["Website"].duplicated(keep=False) &
    df["Website"].notna() &
    (df["Website"].astype(str).str.upper() != "N/A")
].sort_values("Website")

if len(website_duplicates) == 0:
    print("No duplicate websites found.")
else:
    print(
        website_duplicates[
            ["Name", "Website", "Country"]
        ].to_string(index=False)
    )

print()

print("========================================")
print("COUNTRY COUNTS")
print("========================================")
print(df["Country"].value_counts(dropna=False))
print()

print("========================================")
print("STATE COUNTS")
print("========================================")
print(df["State"].value_counts(dropna=False))
print()

print("========================================")
print("REGION COUNTS")
print("========================================")
print(df["Region"].value_counts(dropna=False))
print()

print("========================================")
print("COVERAGE STATE COUNTS")
print("========================================")
print(df["Coverage State"].value_counts(dropna=False))
print()

print("========================================")
print("S/NO. CHECK")
print("========================================")

print("Missing S/NO.:", df["S/NO."].isna().sum())
print("Duplicate S/NO.:", df["S/NO."].duplicated().sum())
print()

print("========================================")
print("COMPLETELY DUPLICATED ROWS")
print("========================================")

print("Number of completely duplicated rows:",
      df.duplicated().sum())

print()

print("========================================")
print("ROWS CONTAINING NaN")
print("========================================")

rows_with_nan = df[df.isna().any(axis=1)]

if len(rows_with_nan) == 0:
    print("No rows contain NaN.")
else:
    print(rows_with_nan.to_string(index=False))

print()

print("========================================")
print("QUALITY CHECK COMPLETE")
print("========================================")

========================================
DATASET OVERVIEW
========================================
Number of rows: 117
Number of columns: 16

COLUMNS:
['S/NO.', 'Name', 'HMO ID', 'Website', 'Address', 'Email', 'Contact Number', 'Country', 'Source', 'Source URL', 'State', 'Region', 'Coverage State', 'Coverage Type', 'Services Rendered', 'Target Customers']

========================================
MISSING VALUES (NaN)
========================================
S/NO.                26
Name                  0
HMO ID               26
Website               0
Address              27
Email                 0
Contact Number        0
Country               0
Source                0
Source URL            0
State                 0
Region                0
Coverage State        0
Coverage Type         0
Services Rendered     0
Target Customers      0
dtype: int64

========================================
N/A VALUES
========================================
S/NO.                 0
Name                  0
HMO ID                0
Website               4
Address               0
Email                18
Contact Number       12
Country               0
Source                0
Source URL            0
State                 5
Region               32
Coverage State        0
Coverage Type         0
Services Rendered     0
Target Customers      0
dtype: int64

========================================
DUPLICATE ORGANISATION NAMES
========================================
No duplicate organisation names found.

========================================
DUPLICATE WEBSITES
========================================
                                       Name                         Website Country
                    Health Partners Limited    https://healthspringhmo.com/ Nigeria
                           HEALTHSPRING HMO    https://healthspringhmo.com/ Nigeria
                MAAYOIT HEALTH CARE LIMITED        https://masslife.com.ng/ Nigeria
                MASSLIFE HEALTHCARE LIMITED        https://masslife.com.ng/ Nigeria
         MB & O HEALTHCARE SERVICES LIMITED https://mediplanhealthcare.com/ Nigeria
                MEDIPLAN HEALTHCARE LIMITED https://mediplanhealthcare.com/ Nigeria
                           NOOR HEALTH LTD.        https://phillipshmo.net/ Nigeria
PHILLIPS HEALTH MANAGEMENT SERVICES LIMITED        https://phillipshmo.net/ Nigeria
                            SALUS TRUST GTE      https://springtidehmo.com/ Nigeria
        SPRINGTIDE HEALTHCARE SERVICES LTD.      https://springtidehmo.com/ Nigeria

========================================
COUNTRY COUNTS
========================================
Country
Nigeria           91
United Kingdom    26
Name: count, dtype: int64

========================================
STATE COUNTS
========================================
State
Lagos          44
FCT            25
England        14
Wales          12
Rivers          6
N/A             5
Kaduna          2
Oyo             2
Adamawa         1
Kwara           1
Lagos / FCT     1
Imo             1
Benue           1
Enugu           1
Delta           1
Name: count, dtype: int64

========================================
REGION COUNTS
========================================
Region
South West       46
N/A              32
North Central    27
South South       7
North West        2
South East        2
North East        1
Name: count, dtype: int64

========================================
COVERAGE STATE COUNTS
========================================
Coverage State
Nationwide – Nigeria                     35
Lagos                                    22
FCT                                      17
United Kingdom                           13
Rivers                                    6
National – Wales                          5
Kaduna                                    2
Oyo                                       2
Local – Southeast Wales                   1
Local – Swansea Bay                       1
Local – Powys                             1
Local – West Wales                        1
Local – Cwm Taf Morgannwg                 1
Local – Cardiff and Vale of Glamorgan     1
Local – North Wales                       1
Adamawa                                   1
United Kingdom and international          1
Delta                                     1
Benue                                     1
Imo                                       1
Lagos / FCT                               1
Kwara                                     1
Enugu                                     1
Name: count, dtype: int64

========================================
S/NO. CHECK
========================================
Missing S/NO.: 26
Duplicate S/NO.: 25

========================================
COMPLETELY DUPLICATED ROWS
========================================
Number of completely duplicated rows: 0

========================================
ROWS CONTAINING NaN
========================================
 S/NO.                                          Name  HMO ID                                   Website Address                                     Email                        Contact Number        Country                        Source                                                                                                Source URL   State Region                        Coverage State                                  Coverage Type                                                                                                                                                               Services Rendered                                                                                              Target Customers
  26.0                       Health Partners Limited    35.0              https://healthspringhmo.com/     NaN                  hmo@healthpartnersng.org 08077140844, 08077140855, 08077140688        Nigeria                          NHIA                                                                              https://www.nhia.gov.ng/hmo/     N/A    N/A                  Nationwide – Nigeria                       Retail / SME / Corporate                             Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care                                                          Individuals; Families; SMEs; Corporate Organisations
   NaN                                          Bupa     NaN                   https://www.bupa.co.uk/     NaN                                       N/A                         0345 609 0111 United Kingdom      Official Company Website                                                                     https://www.bupa.co.uk/contact-us.php England    N/A                        United Kingdom                      Private Medical Insurance                                                            Private healthcare, health insurance, specialist treatment, hospital care, health assessments and wellbeing services                                                               Individuals, families, employers and businesses
   NaN                                    AXA Health     NaN              https://www.axahealth.co.uk/     NaN                                       N/A                         0800 027 1384 United Kingdom      Official Company Website                                                  https://www.axahealth.co.uk/health-insurance/contact-us/ England    N/A                        United Kingdom                      Private Medical Insurance                                                Private healthcare, hospital treatment, specialist consultations, diagnostic tests, mental health support and health assessments                   Individuals, couples, families, self-employed people, small businesses and large corporates
   NaN                                         Aviva     NaN                  https://www.aviva.co.uk/     NaN                                       N/A                                   N/A United Kingdom      Official Company Website                                                      https://www.aviva.co.uk/help-and-support/contact-us/ England    N/A                        United Kingdom                      Private Medical Insurance                              Private treatment, hospital care, specialist consultations, diagnostic tests, cancer treatment, mental health treatment and GP video consultations                                                               Individuals, families, employees and businesses
   NaN                                           WPA     NaN                   https://www.wpa.org.uk/     NaN                                       N/A                                   N/A United Kingdom      Official Company Website                                                                                   https://www.wpa.org.uk/ England    N/A                        United Kingdom  Private Medical Insurance / Health Cash Plans                                                       Private hospital treatment, consultations, diagnostic tests, health cash plans, dental plans and employee health services                                                    Individuals, families, self-employed people and businesses
   NaN                                VitalityHealth     NaN               https://www.vitality.co.uk/     NaN                                       N/A                                   N/A United Kingdom      Official Company Website                                                                               https://www.vitality.co.uk/ England    N/A                        United Kingdom                      Private Medical Insurance                             Private hospital treatment, GP services, diagnostic tests, specialist care, cancer care, mental health support, physiotherapy and wellbeing rewards                                                    Individuals, families, self-employed people and businesses
   NaN                                    The Exeter     NaN               https://www.the-exeter.com/     NaN                     member@the-exeter.com                         0300 123 3201 United Kingdom      Official Company Website                                                                 https://the-exeter.com/contact-us/member/ England    N/A                        United Kingdom                      Private Medical Insurance                                                                          Private medical treatment, specialist consultations, hospital care, diagnostics and healthcare support                                                                          Individuals, families and businesses
   NaN                               Benenden Health     NaN               https://www.benenden.co.uk/     NaN                                       N/A                                   N/A United Kingdom      Official Company Website                                                                    https://www.benenden.co.uk/contact-us/ England    N/A                        United Kingdom                          Healthcare Membership                              24/7 GP helpline, mental health support, diagnostic consultations and tests, surgical treatment, hospital access and health and wellbeing services                                                               UK residents, individuals, families and members
   NaN                      Freedom Health Insurance     NaN https://www.freedomhealthinsurance.co.uk/     NaN                                       N/A                         0800 999 2013 United Kingdom      Official Company Website                                                       https://www.freedomhealthinsurance.co.uk/contact-us England    N/A                        United Kingdom                      Private Medical Insurance                                                                  Private medical treatment, hospital care, specialist consultations, diagnostic services and healthcare support                                                             Individuals, families, expatriates and businesses
   NaN                             National Friendly     NaN       https://www.nationalfriendly.co.uk/     NaN                                       N/A                                   N/A United Kingdom      Official Company Website                                                                       https://www.nationalfriendly.co.uk/ England    N/A                        United Kingdom                      Private Medical Insurance                                                                                                    Private healthcare, medical consultations, diagnostic services and treatment                                                                                      Individuals and families
   NaN                         Saga Health Insurance     NaN   https://www.saga.co.uk/health-insurance     NaN                                       N/A                                   N/A United Kingdom      Official Company Website                                              https://www.saga.co.uk/contact-us/insurance/health-insurance England    N/A                        United Kingdom                      Private Medical Insurance                     Private hospital treatment, inpatient and day-patient treatment, outpatient consultations, tests, scans, physiotherapy, cancer support and 24/7 GP services                                                                                       People aged 50 and over
   NaN                              Cigna Healthcare     NaN                  https://www.cigna.co.uk/     NaN                                       N/A                                   N/A United Kingdom      Official Company Website                                                                                  https://www.cigna.co.uk/ England    N/A      United Kingdom and international        International Private Medical Insurance International medical insurance, inpatient and day-patient care, hospital treatment, specialist care, outpatient care, dental options, telehealth and global healthcare support Individuals, families, international students, workers, retirees, globally mobile employees and organisations
   NaN                                  Simplyhealth     NaN           https://www.simplyhealth.co.uk/     NaN                                       N/A                         0370 908 3304 United Kingdom      Official Company Website                                                                 https://www.simplyhealth.co.uk/contact-us England    N/A                        United Kingdom            Health Cash Plan / Health Insurance                          Dental care, optical care, physiotherapy, chiropractic care, podiatry, diagnostic consultations and scans, prescriptions and everyday healthcare costs                                                               Individuals, families, employees and businesses
   NaN                             General & Medical     NaN                 https://www.gminsure.com/     NaN                         info@gminsure.com                         0800 970 9442 United Kingdom      Official Company Website                                                             https://www.generalandmedical.com/contact-us/ England    N/A                        United Kingdom                      Private Medical Insurance                                                                          Private medical treatment, hospital care, specialist consultations, diagnostics and healthcare support                                                                          Individuals, families and businesses
   NaN                                 CS Healthcare     NaN           https://www.cshealthcare.co.uk/     NaN                                       N/A                                   N/A United Kingdom      Official Company Website                                                                https://www.cshealthcare.co.uk/contact-us/ England    N/A                        United Kingdom          Private Healthcare / Health Insurance                                                                               Private healthcare, consultations, diagnostic services, hospital treatment and healthcare support                                  Civil servants, public-sector employees, their families and eligible members
   NaN         Aneurin Bevan University Health Board     NaN                  https://abuhb.nhs.wales/     NaN               abb.engagement@wales.nhs.uk                          01633 431890 United Kingdom Official Organisation Website                              https://abuhb.nhs.wales/about-us/engagement/community-engagement/contact-us/   Wales    N/A               Local – Southeast Wales                            NHS Health Services                                                Primary care, hospital care, community health services, mental health services, specialist healthcare and public health services                                    Residents of Blaenau Gwent, Caerphilly, Monmouthshire, Newport and Torfaen
   NaN       Betsi Cadwaladr University Health Board     NaN                  https://bcuhb.nhs.wales/     NaN                                       N/A                                   N/A United Kingdom Official Organisation Website                                                                       https://bcuhb.nhs.wales/contact-us/   Wales    N/A                   Local – North Wales                            NHS Health Services                                                        Primary care, hospital care, community health services, mental health services, specialist healthcare and emergency care                                                                                      Residents of North Wales
   NaN      Cardiff and Vale University Health Board     NaN                 https://cavuhb.nhs.wales/     NaN                 Cav.Concerns@wales.nhs.uk                         029 2183 6318 United Kingdom Official Organisation Website                                                                      https://cavuhb.nhs.wales/contact-us/   Wales    N/A Local – Cardiff and Vale of Glamorgan                            NHS Health Services                                                        Primary care, hospital care, community health services, mental health services, specialist healthcare and emergency care                                                                Residents of Cardiff and the Vale of Glamorgan
   NaN     Cwm Taf Morgannwg University Health Board     NaN                 https://ctmuhb.nhs.wales/     NaN                                       N/A                                   N/A United Kingdom Official Organisation Website                                                                      https://ctmuhb.nhs.wales/contact-us/   Wales    N/A             Local – Cwm Taf Morgannwg                            NHS Health Services                                                        Primary care, hospital care, community health services, mental health services, specialist healthcare and emergency care                                                   Residents of Bridgend, Merthyr Tydfil and Rhondda Cynon Taf

In [125]:
import pandas as pd

final_dataset = combined_df.copy()

website_corrections = {
    "Health Partners Limited": "https://healthpartnersng.org/",
    "MAAYOIT HEALTH CARE LIMITED": "N/A",
    "MB & O HEALTHCARE SERVICES LIMITED": "https://www.mbandohmo.com/",
    "NOOR HEALTH LTD.": "https://www.noorhealth.ng/",
    "SALUS TRUST GTE": "https://www.salustrustng.com/",
    "DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO": "https://doheec.com/",
    "Zenor Healthcare Ltd.": "https://www.zenorhealthcare.com/",
    "Mitera Health Limited": "https://miterahealth.com/"
}

for organisation, website in website_corrections.items():
    final_dataset.loc[
        final_dataset["Name"].str.strip().str.upper()
        == organisation.strip().upper(),
        "Website"
    ] = website

final_dataset["Website"] = (
    final_dataset["Website"]
    .astype(str)
    .str.strip()
)

final_dataset["Website"] = final_dataset["Website"].replace(
    ["nan", "NaN", ""], "N/A"
)

final_dataset["S/NO."] = range(1, len(final_dataset) + 1)

final_dataset.loc[
    final_dataset["Country"] == "United Kingdom",
    "HMO ID"
] = "N/A"

final_dataset = final_dataset.fillna("N/A")

before = len(final_dataset)

final_dataset = final_dataset.drop_duplicates(
    subset=["Name"],
    keep="first"
).reset_index(drop=True)

after = len(final_dataset)

print("Rows before duplicate check:", before)
print("Rows after duplicate check:", after)

final_dataset["S/NO."] = range(1, len(final_dataset) + 1)

duplicate_names = final_dataset[
    final_dataset["Name"].duplicated(keep=False)
]

print("\n========================================")
print("DUPLICATE NAME CHECK")
print("========================================")

if duplicate_names.empty:
    print("No duplicate organisation names found.")
else:
    print(duplicate_names[["S/NO.", "Name", "Country"]])

valid_websites = final_dataset[
    final_dataset["Website"].str.upper() != "N/A"
]

duplicate_websites = valid_websites[
    valid_websites["Website"].duplicated(keep=False)
].sort_values("Website")

print("\n========================================")
print("DUPLICATE WEBSITE CHECK")
print("========================================")

if duplicate_websites.empty:
    print("No duplicate websites found.")
else:
    print(
        duplicate_websites[
            ["S/NO.", "Name", "Website", "Country"]
        ].to_string(index=False)
    )

print("\n========================================")
print("COMPLETE DUPLICATE ROW CHECK")
print("========================================")

print(
    "Completely duplicated rows:",
    final_dataset.duplicated().sum()
)

print("\n========================================")
print("N/A COUNTS")
print("========================================")

na_counts = (
    final_dataset
    .astype(str)
    .apply(lambda col: col.str.strip().str.upper().eq("N/A"))
    .sum()
)

print(na_counts)


print("\n========================================")
print("ACTUAL NaN CHECK")
print("========================================")

print(
    "Total actual NaN values:",
    final_dataset.isna().sum().sum()
)

print("\nNaN by column:")
print(final_dataset.isna().sum())

print("\n========================================")
print("COUNTRY COUNTS")
print("========================================")

print(final_dataset["Country"].value_counts())

print("\n========================================")
print("FINAL DATASET SIZE")
print("========================================")

print("Rows:", len(final_dataset))
print("Columns:", len(final_dataset.columns))

print("\n========================================")
print("S/NO. CHECK")
print("========================================")

print("Missing S/NO.:", final_dataset["S/NO."].isna().sum())
print("Duplicate S/NO.:", final_dataset["S/NO."].duplicated().sum())
print(
    "Correct sequence:",
    list(final_dataset["S/NO."]) == list(range(1, len(final_dataset) + 1))
)

print("\n========================================")
print("FINAL DATASET")
print("========================================")

display(final_dataset)

final_dataset.to_csv(
    "Nigeria_England_Wales_Health_Providers_FINAL.csv",
    index=False
)

final_dataset.to_excel(
    "Nigeria_England_Wales_Health_Providers_FINAL.xlsx",
    index=False
)

print("\n========================================")
print("FILES SAVED")
print("========================================")

print("Nigeria_England_Wales_Health_Providers_FINAL.csv")
print("Nigeria_England_Wales_Health_Providers_FINAL.xlsx")

Rows before duplicate check: 117
Rows after duplicate check: 117

========================================
DUPLICATE NAME CHECK
========================================
No duplicate organisation names found.

========================================
DUPLICATE WEBSITE CHECK
========================================
 S/NO.                                        Name                       Website Country
    14          DEFENCE HEALTH MAINTENANCE LIMITED           https://doheec.com/ Nigeria
    16 DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO           https://doheec.com/ Nigeria
    24            HALLMARK HEALTH SERVICES LIMITED https://healthpartnersng.org/ Nigeria
    26                     Health Partners Limited https://healthpartnersng.org/ Nigeria

========================================
COMPLETE DUPLICATE ROW CHECK
========================================
Completely duplicated rows: 0

========================================
N/A COUNTS
========================================
S/NO.                 0
Name                  0
HMO ID               26
Website               2
Address              27
Email                18
Contact Number       12
Country               0
Source                0
Source URL            0
State                 5
Region               32
Coverage State        0
Coverage Type         0
Services Rendered     0
Target Customers      0
dtype: int64

========================================
ACTUAL NaN CHECK
========================================
Total actual NaN values: 0

NaN by column:
S/NO.                0
Name                 0
HMO ID               0
Website              0
Address              0
Email                0
Contact Number       0
Country              0
Source               0
Source URL           0
State                0
Region               0
Coverage State       0
Coverage Type        0
Services Rendered    0
Target Customers     0
dtype: int64

========================================
COUNTRY COUNTS
========================================
Country
Nigeria           91
United Kingdom    26
Name: count, dtype: int64

========================================
FINAL DATASET SIZE
========================================
Rows: 117
Columns: 16

========================================
S/NO. CHECK
========================================
Missing S/NO.: 0
Duplicate S/NO.: 0
Correct sequence: True

========================================
FINAL DATASET
========================================

C:\Users\user\AppData\Local\Temp\ipykernel_20208\1681747275.py:35: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'N/A' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  final_dataset.loc[

,S/NO.,Name,HMO ID,Website,Address,Email,Contact Number,Country,Source,Source URL,State,Region,Coverage State,Coverage Type,Services Rendered,Target Customers
0,1,A&M HEALTHCARE TRUST LIMITED,102.0,https://amhmo.com/,"Plot U Bekaji Road, Opposite Bekaji Jumma'at Mosque, Jimeta, Yola, Adamawa State",info@amhmo.com,"08033646497, 09162788582, 08024143666",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Adamawa,North East,Adamawa,Individual / Family / Corporate,Outpatient care; Specialist consultation; Inpatient care; Diagnostic services; Prescription medicines; Emergency care; Maternity care,Individuals; Families; Corporate Organisations
1,2,AIICO MULTISHIELD NIGERIA LIMITED,6.0,https://www.aiicomultishield.com/,"322, IKORODU ROAD, ANTHONY",info@aiicomultishield.com loshunniyi@aiicomultishield.com,07026744353 08056744353,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Nationwide – Nigeria,Individual / Family / Corporate / SME / Group / International,Medical consultation; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Hospital care; Emergency care; Maternity care,Individuals; Families; SMEs; Corporate Organisations; Associations; Large Groups
2,3,ALLEANZA HEALTH MANAGEMENT LIMITED,111.0,https://alleanzahealth.com/individual-plans/,"? 83B, Basheer Shittu Avenue, Magodo Estate, Phase 2, Shangisha, Lagos",info@alleanzahealth.com,07036592835,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Nationwide – Nigeria,Individual / Family / Corporate / Elderly / SME,Medical consultation; Hospital admission; Surgery; Maternity care; Emergency care; Pharmacy services; Provider network access,Individuals; Families; Elderly/Senior Citizens; SMEs; Corporate Organisations
3,4,ALLY HEALTHCARE LIMITED,119.0,https://amanhmo.com/home,"Suit C4 Plot 1196 Ndjamena Crescent, Wuse II, Abuja",allyhealthcarelimited@gmail.com,08148808171,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,FCT,North Central,FCT,Individual / Corporate,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care,Individuals; Families; Corporate Organisations
4,5,AMAN HEALTH MAINTENANCE ORGANIZATIONS,121.0,https://anchorhmo.com/,"? 1, M. M. Alkali Street, Off 442 Crescent, Citec Vilas Gwarinpa, Abuja",info@amanhmo.com,08100588906,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,FCT,North Central,FCT,Individual / Family / Corporate,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care,Individuals; Families; Corporate Organisations
5,6,ANCHOR HMO INTERNATIONAL COMPANY LIMITED,76.0,https://ashmedintegratedhealthservices.com/,GOLDCREST MALL BUILDING,info@anchorhmo.com,"08031230306, 07058890062, 07080601192",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,N/A,N/A,Nationwide – Nigeria,Individual / Corporate / SME,Corporate health plans; Retail health plans; Third-party administration; Customized health plans; Emergency support; Claims management,Individuals; Families; SMEs; Small and Large Employers; Corporate Organisations
6,7,ASHMED INTEGRATED HEALTH SERVICES LTD.,89.0,https://www.avonhealthcare.com/,"RE 013 ZUNGERU CLOSE BY BIMA ROAD NITEL QUARTERS, KADUNA",info@ashmedintegratedhealthservices.com,07036035182,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Kaduna,North West,Kaduna,Individual / Family / Corporate,Managed healthcare; Health insurance; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care,Individuals; Families; Corporate Organisations
7,8,AVON HEALTHCARE LIMITED,63.0,https://www.axamansard.com/health/plans/,"22B, GLOVER ROAD",info@avonhealthcare.com,"08102659972, 07002779800",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Nationwide – Nigeria,Individual / Family / Corporate,Health insurance; Outpatient care; Inpatient care; Specialist consultation; Diagnostic services; Prescription medicines; Emergency care; Maternity care; Dental care; Optical care,Individuals; Couples; Families; Businesses; Corporate Organisations
8,9,AXA MANSARD HEALTH LIMITED,59.0,https://bastionhmo.com/,"177, IKORODU ROAD, ONIPANU, LAGOS",healthcare@axamansard.com,0700AXAMANSARD,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Nationwide – Nigeria,Individual / Family / Corporate,Outpatient care; Inpatient care; Surgical services; Routine immunization; Emergency evacuation; Dental care; Eye care; Physiotherapy; Telemedicine; Pharmacy services; Hospital cash,Individuals; Families; Employees; Groups; Corporate Organisations
9,10,BASTION HEALTH LIMITED,97.0,https://www.centurymedicaid.org/,"UBN HOUSE NO 1 ADEOLA ODEKU STREET, VICTORIA ISLAND, LAGOS, ETI OSA, LAGOS, Nigeria",Naomiduku@bastionhmo.com,0802BASTI0NHM0 08002278466,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Lagos,Individual / Family / Corporate,Health insurance; Outpatient care; Inpatient care; Specialist care; Hospital services; Emergency care; Provider network access; Corporate and individual health plans,Individuals; Families; Senior Citizens; SMEs; Corporate Organisations
10,11,BONITAS HEALTH MAINTENANCE LIMITED,120.0,https://clearlinehmo.com/,"No. 7 Birabi Street, GRA phase 1, Port Harcourt, Rivers State",info@bonitashmo.org,09164113000,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Rivers,South South,Rivers,Individual / Family / Corporate,Health insurance; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care,Individuals; Families; SMEs; Corporate Organisations
11,12,CENTURY MEDICAID SERVICES LIMITED,99.0,https://www.dhmlnigeria.com,"36 OKOROJI STREET, D/LINE, PORT HARCOURT, PORT HARCOURT CITY LGA, RIVERS STATE, Nigeria","info@centurymedicaid.org, centurymedicaid@yahoo.com","08090235044, 09087000193, 09087000192",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Rivers,South South,Rivers,Individual / Family / Corporate / Community / Industrial / Educational,Managed healthcare; Health insurance; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care,Individuals; Families; Corporate Organisations; Employees; Students; Educational Institutions; Industry Groups
12,13,CLEARLINE INTERNATIONAL LIMITED,3.0,https://delogmedicalhmo.com/,"290, IKORODU ROAD, ANTHONY, LAGOS",info@clearlinehmo.net clearline_int@yahoo.com,"08076490111, 08076490101, 014482520",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Nationwide – Nigeria,Individual / Family / Corporate,Outpatient care; General and specialist consultation; Teleconsultation; Prescription medicines; Diagnostic and laboratory services; Hospital care; Emergency care,Individuals; Families; SMEs; Corporate Organisations
13,14,DEFENCE HEALTH MAINTENANCE LIMITED,22.0,https://doheec.com/,"2 HAMINA CLOSE, ABUJA",info@dhmlnigeria.com,"07037921025, 08069305886",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,FCT,North Central,Nationwide – Nigeria,Corporate / Group / Military,Military and defence health insurance; Primary healthcare; Secondary healthcare; Tertiary healthcare; Clinical services; Pharmacy services; Nursing care; Allied medical services; Public health services,Defence Personnel; Defence Employees; Dependants
14,15,Delog Medical Services Ltd. (HMO),117.0,https://hmo.dot.ai/,"? 369, Borno Way, Alagomeji, Yaba, Lagos",info@delogmedicalhmo.com,08128300972,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Lagos,Individual / Family / Corporate,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care,Individuals; Families; SMEs; Corporate Organisations
15,16,DOHEEC INTERNATIONAL HEALTHCARE LIMITED HMO,115.0,https://doheec.com/,"2nd Floor, 34/36, Association Avenue, Ilupeju, Lagos",info@doheec.com,"09069431050, 09078945165",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Lagos,Individual / Family / Corporate,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care,Individuals; Families; SMEs; Corporate Organisations
16,17,DOT HMO Ltd.,100.0,http://gnihealthcare.com/,"MJS House, 366 Murtala Mohammed Way (Opposite Polaris Bank), Yaba, Lagos",support@dot.aihelp@dot.ai,07000368466 (calls) 08170369507 (WhatsApp 0nly),Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Nationwide – Nigeria,Individual / Family / Corporate,Clinic visits; Diagnostic services; Prescription medicines; Specialist care; Telemedicine; Wellness and preventive care; Emergency support,Individuals; Families; SMEs; Teams
17,18,FOUNTAIN HEALTHCARE LIMITED,94.0,https://gorahhmo.com/,"ALL SEASON PLACE, NO 74 ISHERI- OGUNNUSI ROAD, OJUDU-OMOLE, IKEJA LAGOS",info@fountainhealthcareng.com,"0700F0UNTAIN, 08077705100, 08077705200",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Nationwide – Nigeria,Individual / Family / Corporate,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care,Individuals; Families; SMEs; Corporate Organisations
18,19,GNI HEALTHCARE LTD,60.0,https://greenbayhmo.com/,"28, AFOLABI AINA STREET, OFF AWOLOWO WAY, IKEJA LAGOS",gnihealthcare@greatnigeriaplc.com,"08057752870, 08163290105 07043051516, 07046251142",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Nationwide – Nigeria,Individual / Family / Corporate,Medical consultation; Specialist care; Laboratory and diagnostic services; Prescription medicines; Maternity care; Eye care; Dental care; Immunization; Hospital admission; Surgery; HIV care; Ambulance services,Individuals; Families; Employees; Corporate Organisations
19,20,GORAH HEALTHCARE LTD.,112.0,https://www.greenfieldhmo.com/,"? 322A, Ikorodu Road, Ikeja, Lagos",info@gorahhmo.com,"08132783427, 07031870956",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Lagos,Individual / Family / Corporate,Preventive healthcare; Wellness care; Emergency services; Specialist consultation; Maternity care; Hospital and clinic access,Individuals; Families; Students; Senior Citizens; Corporate Organisations; International Clients
20,21,GREENBAY HEALTHCARE SERVICES LIMITED,43.0,http://www.groominghm.com/,"9, ODUNUGA STREET, OFF OPEBI LINK ROAD,",info@greenbayhmo.com,070047336229,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Nationwide – Nigeria,Individual / Family / Corporate,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care,Individuals; Families; Employers; Businesses; Corporate Organisations
21,22,GREENFIELD HEALTH MANAGEMENT LTD,78.0,https://hallmarkhmo.com/,"PLOT 14, MARKET GARDEN POCKET LAYOUT, BY ISIADINSO CLOSE, G",info@greenfieldhmo.com hodaccounts@greenfieldhmo.com ezealaelizabeth@greenfieldhmo.com,"09091910003, 09091909993",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,N/A,N/A,Nationwide – Nigeria,Individual / Family / Corporate,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care,Individuals; Families; SMEs; Corporate Organisations
22,23,GROOMING HEALTH MANAGEMENT LIMITED,108.0,https://www.healthassur.com/,"No. 3, Tina Chris Street, Ejigbo, Lagos State",info@groominghm.com,"07080631850, 09087966270",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Lagos,Individual / Corporate / SME,Routine checkups; Specialist consultation; Emergency care; Outpatient care; Inpatient care; Health insurance; Corporate and individual health plans,Individuals; Families; Employees; Corporate Organisations
23,24,HALLMARK HEALTH SERVICES LIMITED,96.0,https://healthpartnersng.org/,"264 Ikorodu Road, Obanikoro, Lagos, Somolu Local Government Area, Lagos, Nigeria",info@hallmarkhmo.com,"08170920155, 09087792936, 08090918940",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Lagos,Retail / SME / Corporate / International,General consultation; Specialist consultation; Diagnostic investigations; Physiotherapy; Renal dialysis; Surgical care; Telemedicine; Gym access; Mortuary cover; Hospital care,Individuals; Families; Employees; Corporate Organisations
24,25,HEALTH ASSUR LIMITED,87.0,https://www.hcihealthcare.ng/,"NO.1 RAMAT CRESCENT OGUDU GRA, KOSOFE, LAGOS.",info@healthassur.com,"01-3422321, 08026547348, 0700 HEALTH ASSUR (07004325427787)",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Nationwide – Nigeria,Individual / Family / Business / Corporate,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care,Individuals; Families; Employees; SMEs; Corporate Organisations
25,26,Health Partners Limited,35.0,https://healthpartnersng.org/,N/A,hmo@healthpartnersng.org,"08077140844, 08077140855, 08077140688",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,N/A,N/A,Nationwide – Nigeria,Retail / SME / Corporate,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care,Individuals; Families; SMEs; Corporate Organisations
26,27,HEALTHCARE INTERNATIONAL LIMITED,4.0,https://hygeiahmo.com/,"308A, MURITALA MOHAMMED WAY, YABA",info@healthcare-ng.com,"08052099069 (Abuja) 08052099099 (Lagos) 014489820, 08052099094",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Nationwide – Nigeria,Individual / Family / Corporate / International,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care,Individuals; Families; SMEs; Corporate Organisations
27,28,HEALTHSPRING HMO,122.0,https://healthspringhmo.com/,"? 1, Julius Nyerere Crescent, Asokoro, Abuja",info@healthspringhmo.com,"07047000591, 07047000590",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,FCT,North Central,FCT,Individual / Family,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care,Individuals; Families
28,29,HYGEIA HMO LIMITED,1.0,https://integratedhealthcareltd.com/,"2ND FLOOR, BANK OF INDUSTRY BUILDING, 21/22 MARINA","hycare@hygeiahmo.com, nhisdesk@hygeiahmo.com","070049434266, 014488300",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Nationwide – Nigeria,Individual / Family / Senior Citizens / Maternity / SME / Corporate,Outpatient care; Inpatient care; Optical care; Dental care; Chronic disease management; Telemedicine; Physiotherapy; ENT services; Wellness and preventive care; Maternal and child care,Individuals; Families; Senior Citizens; SMEs; Corporate Organisations
29,30,Infinite X2 Health Maintenance Services,113.0,https://ihmsnigeria.com/,"No. 13, Lafia Road, Adjacent Kaduna Golf Course, Kaduna State","Infinitex2health@gmail.com, info@infinitex2health.net",07066026262,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Kaduna,North West,Kaduna,Individual / Family / Corporate,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care,Individuals; Families; Corporate Organisations
30,31,INTEGRATED HEALTHCARE,14.0,https://www.ivesmedicare.com/,"19, JOS STREET, AREA 3 GARKI-ABUJA",info@integratedhealthcareltd.com,"08051322662, 08146120236, 08097236759, 09020008294 SMS (and WhatsApp only: 08063206121) Lagos: 08159391310 Awka: 08159391321 Uyo: 08159391334 Kano: 08159391333: Yola: 08159391308 Jos: 08159391311 Ibadan: 08159391324 Minna: 08159391306",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,FCT,North Central,Nationwide – Nigeria,Individual / Family / Corporate,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care,Individuals; Families; Corporate Organisations
31,32,INTERNATIONAL HEALTH MGT. SERVICES,11.0,https://kennediahmo.com/,"IGI HOUSE, 3 GWAMI ST, WUSE ZONE 4,",info@ihmsnigeria.com,"08085861299, 07041446622, 07004467466",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,FCT,North Central,Nationwide – Nigeria,Corporate / Group,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care,Individuals; Families; Corporate Organisations
32,33,IVES MEDICARE,69.0,https://leadwayhealth.com/,"4 MOJIDI STREET, OFF TOYIN STREET",info@ivesmedicare.com,"08032639058, 09085187582, 08092165592",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Lagos,Individual / Family / Corporate,Health insurance; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care,Individuals; Families; Corporate Organisations
33,34,KENNEDIA HMO LIMITED,109.0,https://lifeworthhmo.com/,"14B, Kingsley Emu Street, Lagos, Off Chris Onanuga, Lekki Phase 1",info@kennediahmo.com,"070030306060, 017002018, 09120351385",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Lagos,SME / Corporate / Group,Managed healthcare; Medical consultation; Doctor consultation; Hospital appointments; Provider network access; Health insurance plans; Telemedicine,SMEs; Corporate Organisations; Large Corporates
34,35,LEADWAY HEALTH LIMITED,90.0,https://maayoithealth.org/,"121/123, FUNSHO WILLIAMS AVENUE, IPONRI, SURULERE, LAGOS.",healthcare@leadway.com,"012801051, 08139862271",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Nationwide – Nigeria,Retail / SME / Corporate / International,Outpatient care; Inpatient care; Optical care; Dental care; Telemedicine; Emergency services; Mental health care; Chronic disease management; Pharmacy services; Home vaccination; Fitness and nutrition services,Individuals; Families; Senior Citizens; SMEs; Small and Large Companies; International Clients
35,36,LIFE WORTH MEDICARE LTD,79.0,https://marinamedicalhmo.ng/,"13A, BISHOP COKER ROUND ABOUT, ILUPEJU, LAGOS",info@lifeworthhmo.com,08091111760,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Nationwide – Nigeria,Individual / Family / Corporate,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care,Individuals; Families; SMEs; Corporate Organisations
36,37,LIFESAVER HEALTHCARE LIMITED,118.0,https://markfema.com/,"20B, Olutoye Crescent, Afra Estate, Off Adeniyi Jones Avenue, Ikeja, Lagos State",mb@lifesaverhealthcarehmo.com,09123973551,Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Lagos,Individual / Family / Corporate,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care,Individuals; Families; SMEs; Corporate Organisations
37,38,MAAYOIT HEALTH CARE LIMITED,98.0,N/A,"MHL BUILDING OPPOSITE GSS, OLD JEBBA ROAD, ILORIN, KWARA STATE, P.O. BOX 5504, ILORIN, KWARA STATE, ILORIN, ILORIN WEST, KWARA, Nigeria",info@mayooithealth.org,"08058026841, 08174627100",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Kwara,North Central,Kwara,Individual / Family / Corporate,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care; Maternity care,Individuals; Families; SMEs; Corporate Organisations
38,39,MARINA MEDICAL SERVICES HMO LIMITED,48.0,https://mbandohmo.com/,"24, MONTGOMERY ROAD, YABA-LAGOS.",info@marinamedicalhmo.ng,"08144814021, 08182318170,08022598259",Nigeria,NHIA,https://www.nhia.gov.ng/hmo/,Lagos,South West,Lagos,Individual / Family / Corporate,Health insurance; Managed healthcare; Outpatient care; Inpatient care; Specialist care; Diagnostic services; Prescription medicines; Emergency care,Individuals; Families; SMEs; Corporate Organisations

========================================
FILES SAVED
========================================
Nigeria_England_Wales_Health_Providers_FINAL.csv
Nigeria_England_Wales_Health_Providers_FINAL.xlsx